apiVersion: v1
kind: Secret
metadata:
  name: goose-indexer-secrets
  namespace: ai
stringData:
  #ENC[AES256_GCM,data:pNWWsai7OGsJc5Yzcu6DewDETPWh2kBzWNnLtUXeM/TumJYDGBdmDvWsybMfodAME+6ZBzlFJ1nN++JZGgbKozFlC7W+4unN5A==,iv:s++ox3Ws3xdvnHNMU+njiCI/soeWiLwVRJLzoYPkuZU=,tag:KH4wmqkBZWoC+gY6Mxfs6w==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:w9N2P1+otZncmygt6F8CLx5NR0/wVTzUjioF4sX99FW4hpH6EAi+LgGSM+SB2eJhELQK/vmWQOnCL1QYMDPs+goe1g==,iv:Mkbl4G5flmRmH1ErZlV2IOHqqyNjbu5JQBKPvUZxcyk=,tag:Fho+v9GxIG9CyDKplzV2RQ==,type:str]
  #ENC[AES256_GCM,data:FugqtzFWcJAPpVocjW/NcTDCRv3H792z/ws2GNZP0KshImjqGMGCsyMfIPRq8nW0bUg6GTU=,iv:+E395vSP/FuO9c0cMhanOD3EILdUPF44SVE5CI/ckI0=,tag:iuFyv3OhUlD6VphwjgTY1Q==,type:comment]
  GITHUB_TOKEN: ENC[AES256_GCM,data:9qFsH6Jgokcq4kGS0WzZZ+7Pzf3HZRP8ocV0FSGVzmA3hXzqhkaS4dqD+BzG9NLIgXFwamkj2RRbeo3VVCrRezvR3sjcd4qgFNXHW/AMohblgOIhVM2gvSVS4n+K,iv:PUefcqW59riGBiozevWJQ4o1xy7pa8a0sw8WQ1KxdqI=,tag:pNahZEZ//1d8sQM8+UzgsA==,type:str]
  #ENC[AES256_GCM,data:wP3hx9Tl5KjuQ7htDMpQrt/h4FAZteMm1FvM6OFbRcjg,iv:aU630Kokhk7XZpgtzfMrEhRC9xTtGI9A7vZDFJuYB/E=,tag:JAEwssci3ZEuFyEiAEeL3Q==,type:comment]
  PGHOST: ENC[AES256_GCM,data:VhMPEbluutP47qJhT7Uda4yqf1+THs8xYatBp3YO1UP4563aReWt,iv:t6owL0Lj6NeQLHV1Bss8VExBUQFyF2MGKl9fwR01wlk=,tag:aFBaGMzcy67M1HhIszEOOg==,type:str]
  PGPORT: ENC[AES256_GCM,data:I7uE7Q==,iv:MBg6rZt4rYNWndcpNPpU38Xb4pQ/8CfOA9yHFtb+lJo=,tag:2gF8o1NuvR8/18R90rkK5w==,type:str]
  PGDATABASE: ENC[AES256_GCM,data:pU85NGkYC0Q=,iv:aqgayytnJeZAIUk6XsjjPYcR0wXMv70G4ToeNBxb0Pc=,tag:sPv/w+QMdDlzJ6DlWrYFdw==,type:str]
  PGUSER: ENC[AES256_GCM,data:b/p8I+fHXEg=,iv:jasSnP8ALkqdbWSXc0RVCYu67I9yh/V0G0gfMnMtPMM=,tag:Za/RIbCiCZr+ae1DmyXKqQ==,type:str]
  PGPASSWORD: ENC[AES256_GCM,data:4IIh2pOLN/tTUusE11UH1vUxsy+XgOcz5/8Mb3XStbcSRfmNQ0TwvxO7NZFA/jJNcrDNalDDF+0N612e/Nusqw==,iv:KShKWQKUug6NSa0i5waDEg6b0Z0NAYFYMfs1VZtDZ3U=,tag:OFoIpf0O3zCYoqXw4RJgyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc1FhWFBrby9sSTVSdW5p
        QW16dEM1bG8xekZNRjBqU1Bwajd5cndtNkZZCjdHVDAvSXQ3Q3NvNmFkSTY1S0JB
        UlJic0xBKzhQalRIdmFvME1UVDZkUEEKLS0tIHp3ZDZSa3oyb3FTdmdtb0tuaUVF
        b09NRnhXbGd2QStoamRCUnNmeTFFa2sK5rvenehDQcQpYa+VCG8JkQxDheUeZsVB
        jW65nnBW6SAtTWr+l7BJSYiOUQ4z5SGUV4Z2K0EkqRKp8SddfyhaVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T16:58:01Z"
  mac: ENC[AES256_GCM,data:z4kGq21NtVF1b0YtB+ni3auJqRZdnJF5K1JflAY1qwRs0bO6V0e1XW99H0bILszgS+fl/uvzh0h5S9D3Ia+UyPnaJT32tOiiamSIaTaxyG5VWilOeV1ToRZdra/0eYZzrvVXsnCvbtTKnz3J3ZoAabe7GapiSBgFXbwnSAJ5gMg=,iv:UzauEAzirRaoOSJadZ8tsXA+R2NBZcjJaVA/oLDran4=,tag:MRTfPBihL11hJnFKee0j0Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
