apiVersion: v1
kind: Secret
metadata:
  name: anythingllm-secret
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:riOxXxORyejvkKzqC0T7WwV+DBrNFJ6D1DGtVjrH0LxP64JAfIloYixjkslwwyKJHDUwHnBnkl8UVjEw9muSgA==,iv:/r01n+G+QxSGgtUK1j4UlXjfCdwwI+ooV5SE//ALY2s=,tag:ZPlOVrAAEuqMf6RZd2waug==,type:str]
  #ENC[AES256_GCM,data:OR+41m+6kXEZ9eLTkNFFgwuIqd9I3V9p3ziXF1LKxVYx1LN7RbjhGy+GX4hAo00=,iv:nDddrmH8ocf1FoJVWfu5vJC2TfE8f2rqZPHGtw87QpY=,tag:B/+HG68VScsob5GQAIVYag==,type:comment]
  #ENC[AES256_GCM,data:Uo1quqFMIh8V+Xoi5EjCvsEVsoOX+lZdTx0kKHttwFpovyHEq7fN1UAPtg55r/7tGV6V9jIEK8JY+VoyCL/6UV13+p5+LXI=,iv:DygszZegzcd2QkRGAAHSn08YichLqHoVDLChutHqLME=,tag:Ww5tcTzRzG5REF9Q9V8XTQ==,type:comment]
  #ENC[AES256_GCM,data:iOBth60LD/0b7pNGuGVTB/x5gUFr5imTjRy4YWbNIWfFNtJJVI1mwdU/FFMw2rPmzxCCb0Ch9KYax8vKpg3VlUIidY7fUYydgw==,iv:5gGx1Pv6M2VFGVQEcSwJRknwrMjSo2dLR6/73gWBnvI=,tag:SjyOITPwGNwtlF/ihppMNg==,type:comment]
  LITELLM_VIRTUAL_KEY: ENC[AES256_GCM,data:Jwsi3vbxtAzsOw7M9R+RSp716Knur6xZRw==,iv:tm50/Dt/PMALSTDOT0ZS86Mor3I4cnU20HAi9ZyK6VA=,tag:+KssWbhOUhpwrnFxhHtEqw==,type:str]
  #ENC[AES256_GCM,data:VUYGQo011Ld7ISOCS1mU4sW1iPff1Cx7JCB6bv7haa92695gqtN2VFAfelQSBa1QYFK4nG0xrS24nYQ+/mWssz0mHc7D63U5SQ==,iv:EwTqWetVEoMNiCq6ky2QyEk3ZtVpLsKCw6/0ijr2XOw=,tag:cpWffekvG5lfLklmEre6bw==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:crL4p50CM+TgqRr4jpAyb1X0IDZwDGE2l/VBJXHBQeArDeLVdW1q,iv:VuOHPrE6Cs4T8pWXvrKdY50YifICsDD357efrDRqFMw=,tag:1CWohBQdjfUlzA3++tW/8w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:pzelfUUUYBKRj+k=,iv:qY1ShTe6nKGkDsFZ2KKsGo4ULTzOSlwZBkMs0Bt4sts=,tag:aUn1HxYbRHnXk3GBlzPOOQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:cZ0aDRkkTbynoxc=,iv:iLC1OHQaCDb7L2JpcYfYymoVk7BJ4z950ADBmM5GnKU=,tag:ptdHWNhyhWtxe64ZT17FsA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:O9WDrYBifssVwy4zTsSn6JHsUGY1oBFFhOCy9P/BSUjMoaZcPgEIJ3CAn5DR91gm,iv:BIAdVclrwIZ7ei8SGMrAFnquwIldtnZe0sZdezusrKo=,tag:5agN4UkfINIt0NYJ51ztfw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:NZvzy12yIn8=,iv:uoQ42oMB2yx6ho9e6HOmz0q5J6GenRqhCIQb0A9xUCY=,tag:InL3Xfn+CxbDE0GQKkYkGQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:HFhsWPrhOlAZ2jcVGxM=,iv:zsENceO1mMh/Di5i9W3rYrO3LOTGVw4qW+Y6nYZYh2s=,tag:lkjKE7oCKgRwbZixs8jAyw==,type:str]
  #ENC[AES256_GCM,data:ZTsoQIdpwMhB38lCmE4OA4SEKYa3w6nzUvDJSMwppHGsTaA3FJfZVTfvZUTm8vdUqf9Zw1379s1w,iv:z5XFvqxn0o5HoPQd+7AxRbi/+oWVb3yWa2yxvGHZX88=,tag:X5cOCgJceof5RlJ7kBoSwA==,type:comment]
  #ENC[AES256_GCM,data:FVCqGWUr6104+RtDNvXDixfxtN9MtjNIKebh5bZzhhXS/nmZ8i1YJGNiKMj7wWtc2yVCYHKUog==,iv:HrAakDkd1FjdYhaPr1XTaPvXG5GH7pXT4Bz6S//iIvQ=,tag:4EEL9kMEphAw6sJYC+/c2g==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:TJ1IlxJbmEjNuga8wWer3zgCtgK2k1y3QlXozwXcYaDiIC3B9ikmh6j8hkDtJjXFc+XqZDJ38C/oTcow4e06UdfXixW6LZZJiWvmVVJ2CqnsquCzZiZ/AqvmdJ0xAu5kgfOePuzsTenc2YEQvdZcDNbrjxkF3RIorH4AWyhwSq2eLg==,iv:2YxrUkDAAhXO0a64YpoiJgTVTLuNVsqiq7bcUQdQofc=,tag:VbE6lNg7YqIGVbaZc4bPnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU1pGbnBCOW1GZ09WZ083
        cXpZa0l6cFB5NGp5TEtKQmFMNjZYK3dtOEdJCkx4VmlvZkcxUUJUNTU2Y284N0hl
        akpUTnd6Tm4zN0dTU3BDUEFtY0FKeHMKLS0tIGI0Ym5DclI5T0dTRXZjRmJwWnRM
        UktjNlZ6ZFduYWJhb1FadmYzNnlEQkEK7DB7uM6p1d9XpJ9/v9odCpiUaGwy0FXT
        GAc9TxAxq7vY6MQq1kM9RdjOYTn/T9TB8fKbBDtYrsG7T6kMvUaaRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T16:50:49Z"
  mac: ENC[AES256_GCM,data:ndvqJByci4rjHYfrc5+Wjw/5EnhZZA6EtZOHoIiQLAy6VqAcvrx5nQdnBtYYnyDDPU16nVrgAiBqffpVVPTWvvlxRYbw7KkOpw+WKf2rcgDUh6EuiZdpg2UNfl9qO87RsW75+ox91g2G59jp0Rr3gefABGK18cpp8g2ZNH7MmM4=,iv:5T1dn20Ya2geW1Qnk8dplO7e17OaJFLBbObvCINYe9E=,tag:4G8SJE/Nz/YKSEjR5lPMXA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
