---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: parseable
spec:
  interval: 30m
  chart:
    spec:
      chart: parseable
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: parseable
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    parseable:
      # Override image to use Docker Hub with latest stable version
      image:
        repository: parseable/parseable
        tag: v2.5.1
        pullPolicy: IfNotPresent
      # Disable high availability for standalone mode
      highAvailability:
        enabled: false
      # Store type must be a string: "s3-store"
      store: s3-store
      # Persistence configuration for staging directory
      persistence:
        staging:
          enabled: true
          storageClass: "openebs-hostpath"
          accessMode: ReadWriteOnce
          size: 50Gi
        ingestor:
          enabled: false
        data:
          enabled: false
        querier:
          enabled: true
          storageClass: "openebs-hostpath"
          accessMode: ReadWriteOnce
          size: 50Gi
      # S3 configuration via secret with P_ prefix environment variables
      s3ModeSecret:
        enabled: true
        secrets:
          - name: parseable-env-secret
            prefix: P_
            keys:
              - addr
              - username
              - password
              - staging.dir
              - fs.dir
              - s3.url
              - s3.access.key
              - s3.secret.key
              - s3.bucket
              - s3.region

      # Explicitly disable other storage modes
      gcsModeSecret:
        enabled: false
      blobModeSecret:
        enabled: false
      localModeSecret:
        enabled: false
      resources:
        limits:
          memory: 4Gi
          cpu: 4
        requests:
          cpu: 500m
          memory: 1Gi
      service:
        type: ClusterIP
        port: 80
      metrics:
        serviceMonitor:
          enabled: true
