apiVersion: v1
kind: Secret
metadata:
  name: parseable-env-secret
  namespace: monitoring
type: Opaque
stringData:
  #ENC[AES256_GCM,data:StPpPxcN9Zk3Z36klf0oR98AYY6HKcGFKpH7cfAV5Q==,iv:0aEFzicHh319mmtVXVPcqwG++T5N2IVvE0+gEpYY41Q=,tag:W3pw8tDa5aZaknZt0pMT+Q==,type:comment]
  addr: ENC[AES256_GCM,data:dFI3MSSZEOE5t8fi,iv:pi/ztNw+d5QlU0osoU5PsNdpZJZENPPJ3COgztco8g0=,tag:TAcoifKSTmEHh3vsOvLhKg==,type:str]
  username: ENC[AES256_GCM,data:NIar2KA=,iv:186oMLWCwohRb3XwkD0OnPY30qWbivmHggwNCvEqOro=,tag:lPXYtoQpZGuN7tCdyrSy9A==,type:str]
  password: ENC[AES256_GCM,data:sdoJbyzrJ0odMFU+vxBhHnvtRYq7nxg=,iv:Xtf0sD0RoC/gkJrzirjzGMmmGTvAXnVVilFdZJqZ2pY=,tag:9a9Jb2HAMTdRpJHrjMmqHw==,type:str]
  #ENC[AES256_GCM,data:TA3SfKUKSyiqJiX793wyM6Y7qTit68G0U8/FNNtIdMw6Upg=,iv:w5jyEsa1y/9n9W+72MxNuAJpBid588gahyCnhbecAvs=,tag:f3d8J3NkyorYt+/Y8e2Q8A==,type:comment]
  staging.dir: ENC[AES256_GCM,data:VyyGBNSWM7Rw,iv:QuewqGlbpbP+IKOA/kcL6imSE9V0iTFm0fNOJdjFtIM=,tag:45dlp0VMJ6cT75UCkcMUKg==,type:str]
  fs.dir: ENC[AES256_GCM,data:L57pAnyK,iv:PHik60hfqZdbqLnHA2vQ8Ww7WlI8/AhZPtyg2WsjgNU=,tag:UuFfMCjh6eE3IbZQisxFcg==,type:str]
  #ENC[AES256_GCM,data:8qVtmtlakd2X6s2SkzZSbjU=,iv:L+HWayrdND1ppFOTdfSX63ZXtnmRBtEmWYyDBfs1QPo=,tag:0gJK6jmSwJLGoRcZo7rEqQ==,type:comment]
  s3.url: ENC[AES256_GCM,data:y62H7McshzhSlTlmgvPGKuyW,iv:EN3JfEUYIqc3VUlknANT/VwH0sWMOYGCF/8kr0IXZlY=,tag:G569ExUCbga6BfEXBf6a2Q==,type:str]
  s3.access.key: ENC[AES256_GCM,data:/R7H6LxHupG9fOdcGg==,iv:BZlF133a62UBuciqr9NTAyl2L5eFzAagiaLrq9NRpQo=,tag:CUekf965pvbx86S9vNCMtw==,type:str]
  s3.secret.key: ENC[AES256_GCM,data:r/+Naamm3kuaG1trZ87S3Q==,iv:xsSONz6fhZ8ABl3hpfDqwWWjspK0tqY2CuR6R3xBHcE=,tag:PSBh/wfjXu/1w5U06b7MDg==,type:str]
  s3.bucket: ENC[AES256_GCM,data:fnCNZZowMXWxPbh7KMs=,iv:8kLPUsbmct21Bdxq+yCJscWRqAxGtq+2PLLExkd9riU=,tag:WrFdcEHpkOul8oHa5XFqpw==,type:str]
  s3.region: ENC[AES256_GCM,data:tj9GRoI=,iv:FK1VLOqYSsNmVvTvq042IK+p41Fha4mzHOGQCyZXPck=,tag:ppeeFw6Oa8M5zTbYdZwJCA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL0tqNUZuQ0pIelBhNGNT
        UzlxZmdKaEVUUHg1YzRyV3hKeW4wS1ZMMFZzCnVHYm5va3I1YTIzcWk5ZnEvMUhk
        em9rSnEraW5pWW9TRnFvMGpKcm9YdWMKLS0tIGFLcDZwOVI3SkRoSDlGNHlxanpk
        SmJ3V29OM000NWdXb084a0grK3Z2YTAKLtUPII5dzsk1JeuMVVfMqGdJf7BBD3DQ
        R7sj61L/eT3UOdvpq8WcyAk4AE4abB0F69pUdy3zKh4qT4DRmTgtmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:7Pggim8OZSkxbcksHUpzEQMFYyml6CWXJmwS32bW8MdNKYH3SQ5ap+LTcF9EZengpDAvYGft+uehrYy4AykZ3VoR2jABAnC1MXXZO2SdHcdZs15yJejxq75wftqo5abBTs4UxRC9idarX6nbx+r8yTCDAlsRPlTv2VYrkNnQOtM=,iv:kCoPy4AUMvz7u2D29j+0kbB4fp121atuEWoEzWUtv3U=,tag:EyEmnUqK3Fvwu+8JWbgnzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
