---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parseable
  namespace: monitoring
  labels:
    app.kubernetes.io/name: parseable
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: parseable
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: http
