apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
type: Opaque
stringData:
  RUNNER_TOKEN: ENC[AES256_GCM,data:8oKo9YtJHx837nlasPsMSJTVnjQqJk6/1OssOBy2nkfEPHkQ2+1Q2w==,iv:S025GenkR65gcn+R3KLymQ47MilkNrMg9k/t+dtXxFY=,tag:ltA7EJEn5C4XTJHKp85Mgw==,type:str]
  FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:/HykE20BlDBm9KydbmK+uy3Hof0=,iv:2byY+33MPRohrR/7qrXlizqQEkPGrIDyqJOoW6X2NlI=,tag:XVoxNZkaiFx2AtHvePJhMQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNk9YclpWVlMrWTFuVUhJ
        OVJlc2V4dXRRUDBHTmlHOVVnb3ZQbTFROXpNCnk4cms1eFcyZnZGNDM1YnpkV0Fy
        TStYMGcyWlZpSHg5VVVpWndRWWtuLzAKLS0tIG1YbHRZeVR2U0drckZ3S0hZNFRk
        dHd4WmpqczZNM1E1UkFNUTJwS0grTW8KIJpSMSTdEfR3KfILjFd6gCpAHwgzwRXP
        LaQ/6JTSJxk5GGAWE3FIiRuM3jLSgYvufQ2GpGUY2IVG+FZ99Giazw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:yClaja+3VXKK/aETsZGQaaBzbQuCBcnmj7wSqlerHrFbH4JuFCCvotItw8obK5qZe0ajByCeJu5qLNjBelaPfib8cBnmgFGBY/cRqbu5jID1vzLUzGT1Kce+Y6Wx7fEaREYxFxMc/1WuWOtZwWY9mdUkfmPewfNHQP0iTxcUXB8=,iv:scHqA32E9Y4rmr8hDNljY6wjnxFxgerZ9prhbaU9jsM=,tag:/1s6C21BhyU4pR/fY7r7eQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
