apiVersion: v1
kind: Secret
metadata:
  name: mem0-secrets
type: Opaque
stringData:
  ADMIN_API_KEY: ENC[AES256_GCM,data:IL6LpDZI3mB0M1VOz+BZfkdPr/yxXsNDHXa3q3cYf1WfDhukcTGH4BA3bUWdDXAKpGgatZjDK5tBvOKUWmIZ4w==,iv:PeGUOmjhe8ODEL3J0jr3VkEW7Oferh/oGEM7yxSBkc8=,tag:vnD4R43OS2ffKiQOBBXUAQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:/b2h3865tPp6RY9GDbvw5e0UKjm2LT95steMVHgFYlYT+zKUCvbb2jJx4Nacy6N9+ID/22Q1FFQNJ0/GBBcwXw==,iv:GxZFiusHLkmZGpeL6VZsIwmsivNfNhVPSy27LGl9bA4=,tag:mDY1lddcitG39UiJuhbBzA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:uGfZzbyHB9w3XvcLA1LtAAikkW5t9xniIGyxxqkklJqRiaL89SJY,iv:i3akz3nXNKHBsiyCwgYapO4G4GOp9yZOQMv+WEM2T6c=,tag:OReVvgGe8KkCa1k8os4upw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5Ma78A==,iv:Al/yikSZxFmbtau1mJ3wVTbHxh33d9EuGodIPVE6a04=,tag:9H/CMICRepOw2zNUfVbBkg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:qwLmDg==,iv:rhXXL1t4vsbSgk9Bu2e62BzOOPNU6sfQweaZhGQcERo=,tag:+i8+IKu10bY0wRBtVAV8CA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6jHu5NT9PisycP3opSaJcI4UUw+x8tZfCCChUhX2TRs=,iv:PmPXfO3aaPi5fX2SCdrO2oPuitSTrVDyBal45w8UXOE=,tag:+fcEdMy3/anqySdVqCtRog==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hnLEm2naBCY=,iv:NbpGa/NeztMSZrrw/a0ks89zfTDPppQ3q9lh+tSgR+c=,tag:HJlAH/zVpVqelevoNsjKMA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:7Qt4XIDTWV7lAl5aqsE=,iv:MIAPe/+G9IPi2BsKqJQWoyflPbexQh+OZzJBtVJqRPE=,tag:0aIwiSJajaujvbD5+MGJcA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:NnmUDgoHr4g+inWhZoaZKkWZr/c/70CvdERuZoHZyMM9GwQU8eDS,iv:Q9/BTm4fXgpzS69CxvQegprXxqLjph7a7nxM/LJ6J6I=,tag:yrbSM9SPTkm48/mEDE4GIw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:deW1EA==,iv:bDHQwYxVgwD+XlJGPwK6UgzPg1seBS2QUJPqjkRooZo=,tag:n9txhPWLZFS5VSPpLXzu7w==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:FN4gfg==,iv:4jsrhbJzEE0XX8tg1jtxXBf9kgVD3XEDK1iM5OyD95I=,tag:clnposwvLtDAC7ZZqsyuGw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:Saq9HQ==,iv:2CwRSrkifDcnGcV+4wYeuZ0cVBEs8obTBLj2C9jyB24=,tag:pHFg0FB62+0N71FlGJGAQw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:2AztEO6jEMxkGEY7tdyM2uAemaDs+gz4wPnPxFKEtwg=,iv:GJtViWgh+FmCGDcBCiuIE184o2WOILHEpiNvHbNzaY8=,tag:IvqSMDB905y0rKLfW8j4nw==,type:str]
  POSTGRES_COLLECTION_NAME: ENC[AES256_GCM,data:gvakE2VE8++SEIYk,iv:zBeyjB+forkSVlBxFYx5Pe0Mv7S8W4eJVbKHLnuKJ48=,tag:XiBUAJRBHWHZOA4pMs+kUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUkVwVDUrN2tBSERDQ3Nt
        MzU0Z0VEY01DYk04RmVvWjhSc1MvR0N4ZVR3CkFuRVFEV2tGMEFYejZSWWFlV1lF
        eXhoUzZXUHZiTmRYSktaUlNtRzVOYWMKLS0tIEhSVm9MZmtnNllvd2ZiMVFBbm50
        R0NncDJHWUd6L055ZGJTU0JkbUk3cU0Kz949jtbtlFg2ZhO9ljliSmCHg0DC6zHH
        dtI2QtMcZOf69fdI6fxogZV14917QsFIhiYNq6ScyUrkeGWM+spQyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T18:57:04Z"
  mac: ENC[AES256_GCM,data:vDC7Cn6s5hivAr4DJ+xdwix6Sf0dgITVv2N6Do+AYJ6m2OIi8qAikcGK/AAS2oLBhJvZlNtnwlJa+41F/wMvVIipjL6tRLM/chFvr2DtTGGmAyLNQ4tXH84MmZZcqYj1jxkCj5IHV8+KFG4bKdf3HoHkh2lVPFIHjADepDWC2kY=,iv:CyXYz74hERkqie5smQMKV3sWMp3cDkY8SV1eqRaSrtk=,tag:dgNzuiRUjSJJVQFREJgFJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
