apiVersion: v1
kind: Secret
metadata:
  name: mem0-secrets
type: Opaque
stringData:
  MEM0_API_KEY: ENC[AES256_GCM,data:irYLhMN4aJ31qfYzIco4u9h3t8X6jbza0s9MG4Bn0BCXluV2SpIE/IvmPz1/tpWCSH2U4265xsjwi3DUDcsFdg==,iv:1yJSQrSdO0kG6m6nxKD5XxfHrjiT7Qy2/d6VnHyEiEI=,tag:trmpoeOk8T3hj2s+g4lDKQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:NudLFdA73lX+cdDG+c/XhXfkzeqhcW/ECkfokkI4S1oY2xt0ismwllB06eLqYbZR1M3ZrUKtwzJFIHA5n8Qi+A==,iv:suqIIoKwjycfDvREbfovTTR945/i1cGUz1N1POPDD1A=,tag:tAvnFvWAYGHkqd1/jbfX1w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Yl4gsHr7NLC59740JkiTQUOvnKYAtUXUFbOkmZ7FTdMT9ZgejFvF,iv:wheeQoL5M9LaFi8p27a9v5swWfWjYKjMRwwbzoIvJhs=,tag:90XLFxf4rkOBjwrkd+xC/A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ciIRDQ==,iv:YichZvzejGiJW+iK1kpBPYg6GsDrmx3g2u705d4DN3o=,tag:/k5EJ71h45wnyeggsXfmpw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:vHZwRA==,iv:IjN2efpMnWxJ2QSsT6WGoI+h89Z8co45OmV9Isv6P74=,tag:HvjzrukhaOfwQnwdj/nSlA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:BZP3zOe9fPSBMqyl6Oj6ei5Ygh1cbaSr+3kAqHQbjlk=,iv:LQk2gBAyJDrP0BthUD/8ms2Khf86wRUUbPklbdkCRlA=,tag:UZAlrlXuGfVQS5qyXQ72+A==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:M9d5wskiudI=,iv:APF2sYpR37UpiUNguja5IUkw4W0573FX3MXprvcRD0k=,tag:x4yUqmbkh6Qg8Y71eoVDMg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pU3Hoxaq9ofiVEUOXBs=,iv:Yh5BzJ3tPFZzhNu1IFRAVAq6wlm+SogNRiKAWBhxWrg=,tag:I/M0ZkyKxL4OPKcySj38cA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:G7ztkVB8mpcDgtzjPxMZhLTOuDl7kLzsHHl4cFbawEWYXO2m7OEC,iv:h1oWgNQArStzSxmZGj+vtUvywJl9tNY2N+41psZAz8c=,tag:ByP4J855dom51/A7anTAYw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:Jc6Muw==,iv:LryZuIiWpKzH3xPTT3PrGe05Vva4HCp7zH6//uIcJWA=,tag:aM28CPAqVxXwp5Kw6HWJgA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:ko/lEg==,iv:+6F8m4hKY4aifzrRxHKYZC5xM5BOxATFLmfhVFp76MA=,tag:HVd+g5/yRqSfh9Qxu9eJlg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:q5T2lw==,iv:ErzuNhtGiW3/2mCenx+cl7BDaBRBOEhAL2pmMSgF7vg=,tag:7wmaLTjGSD9ehcZS0Wsz4g==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:JIetMU5FBnt8kwICulO6eRBIU1Bt20d77pVEM4T1AAE=,iv:LqNMU3WjltOq5MyNjre4tY2BYH+l+zZn4wSsoleAwpg=,tag:hAk+w4pGHnpmP2Tvkg+PXA==,type:str]
  POSTGRES_COLLECTION_NAME: ENC[AES256_GCM,data:T0gzoFeA2NIqO69N,iv:KFrAb+brWHnQ38Ytn2f3ZnvBocG3R3+tQGB7ciqMico=,tag:dlKZaNtdvCfJXT3KPGd6gA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSnBhd0Y4VzBvYjdnaEM1
        Q2pkVXpTRUNva1N1aUpPcDFERlFEeXNoUDNFCjRPVGhxN0JwQjlzaDFaZ3JOQkY2
        T2lkU3hESkcxQlhMR3c3MFRuZ1ViMzgKLS0tIHpBSzhJcisraXQ4a3VsUk9oQWR3
        TDRQcjRhdWlZZ0prQ3JlcmZwOTRNcmcKwd4G658REWbbuEupb2xkUCw3SACQmE7k
        lPH8tbblglY5Pq8UIG7EqKBQOZ48Pk6TU0cDUKR90JV9LJ5phpq2Xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T19:04:21Z"
  mac: ENC[AES256_GCM,data:QHdl6LQlwKio61ah614tIOK8TK8pb9S+2LdjeUay02IdxIstjONsLsyP+J7fPU7QBIOCxZEKMUh1+W6JAAH6LVo2IP7wEX2NWK0rOX7WkWbmsFL6DO9eMEE+R2/Gboy07kE8fLnH84CAMeEJyDe8iH0QGj11jnjrsQCqWgzMkXc=,iv:FqxqadA8VBeKBnNQeV/daLNESTkvBkE4Z+/PD5ppvfA=,tag:rmTSjPh4I1gp0iIKeUqFSw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
