apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:xWEYwMb/3hRtAQUb7K16tcIN6In74Ci5RXb2QKSCvE4Jz3TghoT0EjHlE8Z3bLUeRA9N7OWeYM7288yZ91SFrg==,iv:EfV4GZKqPtiE/EAA0oUH5Wi6N2oZFS91xfVkyWDDTPI=,tag:KvMYyKiafrKftsFz99S8wA==,type:str]
  SALT: ENC[AES256_GCM,data:/1lfExwjR9CMhfx2MZAzdYAH6QXJ3JFKHsDSarHLd5/j9KNcm9nUlO54wlfY7+PH/jcvPMxtlQs/yLTwhc6HOQ==,iv:z/KeYQCLQw7EDIjzd5it8Ex99+yRhbAtd6hrCjhUKWg=,tag:xll5IYuxD0Rj/PHV0F4tzg==,type:str]
  CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:Rur0GiTkWbij3JyL3PE858WKZ/hdKaujfTc9dY2R8CE=,iv:xa3NJPinImtprbZuW9DUjHvky7Zv/fW8xrScUAZivhg=,tag:l6rpSljVIjn4R0rbdhSbPQ==,type:str]
  LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:vN5hDh4IY4cyXEm2RYEMvg5CxeBKoPfbuU5KJFSc+M8EDNWs9Es=,iv:Nns7mFLfyXwQOwyMJR2/6Qr86w5aKNANpvpC/w+n3xE=,tag:MeQ+6KqMtNIZH+9y1be8og==,type:str]
  LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:3uMkoGI8ABtSzTCeFODrai3AKSpBmZdMSvBw9wSmdBI2Y/mjP4XEwaAOzMulTI9Hrx6lLc+S,iv:SegN7kRsKr6N3LrVfssJAS6xCYi1e+uU7q6djdNMOlo=,tag:FXWOx081Ze1AbT4umvGO3Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:uqOb01ummjVN6O/SWgY8lkx4W/xv1WQuAjg0ZGCa1Z2DrHVbE5aA,iv:iz6oG4NzGRQ43RdYXgX0iGQG+Mo5Pj9wSE0zsuZOeTQ=,tag:v53RqaAO5z988qP5PeOfKA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WGs3fXfUc6M=,iv:nm9qd16EXDJftWIgzY7Obg6ro0Wx7REdmD3V00Ury7k=,tag:UtM5DlXZotyXTrDTiKLVtQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wJrYH+gN5e0=,iv:3SfubLX8wZlPvTZgSeTRuIsM2w8MGBvXGELC/6+e4e8=,tag:8qzzOOXVytWzs/FJxDuOyA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ktbXIRoAUMS1fS8JVF5+2SbEZWPjGntKqrWU0X8NRJk=,iv:IyOnfNj3yYaUrTH68tSLSjjWHO6FTRp4IDpVXrJ2kP0=,tag:P1cPCZtO8SQyMR1wswDwnA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Gtg5cS19mdo=,iv:ZUZEqfHrOksGqFkjey9AEFUNOud8XgZ8umXjGrdFy2w=,tag:1R1Qwe+ClJnaKv7iTdT5TA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:hlRngBL52nS2RChpFVA=,iv:Tl1r2s49aiISIILlKKe5n9kCNYJJbt0kbt+p/RNxMq4=,tag:2oURg5aMf8KAWkzrUhPQEA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:9G6bo/uRH7744ycYc7i4vNBwAB8j7tWI3HMXwzqTk2sC3rfSYB1hfTcCeEduBhLmAs9BgWp/Mi9cqkLczLkfR0/NXqK8jvw3p1oK0fqLUP2D5l7cDx9QKj7drhLMS7QLg91UC2EmxQREIj6n,iv:m4s0OO0lPHfr7Zz4Zr8AjICAJG67DFLfx4DkIwlgLI8=,tag:gYDb0khQ4Y3JnyXwdzKg8w==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:B6NpmkC3G0RdFw0MZXxmS/Xq01VzG3yDyj5qQlJXFJcb7y8dJkyLAiFiFWd/HCf0l+V4P9k4P+oU0xaBepasmrwt0v52oaKYESlR6kKKAvimszQdvZvBJsTV,iv:JvhfHSpNlWa7VVx1vVcAGwTuglrYTo0bCGeyNePv4GY=,tag:R0YKDIPpRaXt+l5ShOY8nA==,type:str]
  AUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:jm4ksnoTUlVLLNC4eXsV8zFPPBetAH087fzCWTnwGD0IopG/IxgTNQ==,iv:1SqKQXpNExGHuKO0CMEPo8Cn2hCEEqthj6nzRnN1g4g=,tag:KKtnjHcHpfrWoxmFPdGtfw==,type:str]
  AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:QmCC5H1s/otFjzK8UL3g3kBRfe+irtjQ+fvANRKZCJKCdXJnvoEO0yBmNSlxiukyX8NB/JJ8PBYWKQpK/bNykeFpQN165Ys3hkuj36LtmkGrlMTcP6XIPzUfu+6XR9U/XM+DqSHsZaXP844iU4/v5kblKFLq6zrM5bQTK0CKn4E=,iv:BVLEHiZDgMn1R99wQVTT1vt2xV6bg1ci/aBYa4eNBl4=,tag:BoY7odmBsr+W/nyxaV5pzA==,type:str]
  LANGFUSE_INIT_USER_PASSWORD: ENC[AES256_GCM,data:vTAZS5FtGeKPjX2BGol2l83yjs7BP50U4z5JQeSkyDy9oFnIsvwvlg==,iv:LnG3XnC10Z6iPrZLWghJ4djb+sOW0BEJrAYDhPgCYYU=,tag:u87RJdS4uVoYREZ1uuaAXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUDRnb2lKbmgrWXcvVDF6
        V2JKOXIvdlZyc2RHTHd2WFBSZlh2YkxFOGljCnkwODJ4SFc0clhjdjVpYjc2RnBl
        bTNSaXNyMGtkN1FiZVgrKzVPVFN2SmsKLS0tIHI3T1dTamNUa1BzckxDbjRtQnlu
        bXppcHI4eVpmOWZDUkJCek9ubGc5TTAKkd1ScvkGDQGFPPolJfWZNlu918dNQBNc
        23Jcya5Tmz070alT9sby92fX/L5fVJNQocunuWRssY7TTXOkgYBL3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T16:28:06Z"
  mac: ENC[AES256_GCM,data:tEMS0Hqtuxctqw4cUUW17VvBTUgA2heqMIrdlAMTWQviEevlWouCXB3/hail+frM7pXgSi1AlsiVbqPNPBPqVFAgy7+PSWc8cigVJDyQCNrMBIfGsMPb29EVJrshEqlhkE3F1pCha1apY2czYG0jLDUnSxGaZl5I4cVKu6Xj6EE=,iv:JYl1DuwVPo+jXWubIWatiPhDM7JIAPVkQDAnDx6bFpo=,tag:5AfZ/84bZQkkmUXyZ9MhHg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
