---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-operator
  namespace: toolhive-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://netdata.github.io/helmchart/
      chart: netdata
      version: 3.7.141
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 5m
  values: {}
