apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:M3IDOEOkhnJ5MmxyQfCGEc6mqDtATuICY08ULhdizGXb7pAmMlwuDXPqVe1/lFMVsHJQguoxrhCzFFdA+R6SvhRrasDDMwrJqrEZzfOmJ/1u02H32EBbAA==,iv:X4bfINk3Hx2jlbfusF4j+zGSLIR6lSs13i3FwH1AaZ0=,tag:PTlqSTf/u4blFv5prLi5mQ==,type:str]
  registrationToken: ENC[AES256_GCM,data:Eg4LeDzGkqhlJePRhdfgljq6mOOBd81C6ci6LqDy+1gZx7Q7VkL76idxYFI=,iv:vUak/HOA2ADAtuqBjpiWloC8FZ5rzTIC/idJesK3bFI=,tag:/UAxYNQcftYir9n8EnXYsg==,type:str]
  enroll-key: ENC[AES256_GCM,data:PYwDgJ8ZcR85KzzKSI2oX9j9pHckPXat7g==,iv:Z1N6eAKa9dGRobUJqQWw8av912iFPiNfWrjUn1Z/CWk=,tag:AfFpQug6FvA4L3kAmMaPdQ==,type:str]
  #ENC[AES256_GCM,data:X5is6SoPallHuVnduwltDWE2mU+50nVzx0u4SrxSLBUcxn0JhY/hQN1clrvXDFGnozTkWfK7y2bhF+mYbvzQt1UX8ik=,iv:ntNzEiASWQifjqjyIjh9ExXVZ0h80WrBd2cC8IB5jDI=,tag:eibccEVwyGHJE4wmgFm35w==,type:comment]
  #ENC[AES256_GCM,data:vns1gH042bwmNGoWNft+vR4vTlEz/pE1F/EPMnEc0Djol+CjtPlTmje8qbD3GpqV83p1lkT6Cdi0THJ9RLfYoRumr6Znn9Y=,iv:hLA4e+yJKdi65u1GLHWzqPN1aCNOAyqu+b8Mg751B2E=,tag:AFzdF0THJYp1sE8adgQK/g==,type:comment]
  #ENC[AES256_GCM,data:PWCppXGYNgkT6rhBwGemCMsF4mcrMg4NEmAUi/3YgEtFSK8kx1Mvjl5vZ6zGaYFv+Nr2e5k/ioFL/2WgApj0hvjmjvoXqwYJpXo=,iv:OKTjCiD8V7jvPQtJXZPV6Zzy+kq5TDJwi5tfuBmttfs=,tag:sk3WG9RcCVqo9xSPLsAHZg==,type:comment]
  #ENC[AES256_GCM,data:2znnYS+dC9VptZ4BnzPAc+nVh8lKcUaz9/uc5GG8oTpjOtlUpc2aeShAsFoeG5eVHZJWmuV0MS/dkow=,iv:O4eg+osrCpZ0gbtNSwaqNWgMg+6K+6/DrhYQrg/PLU8=,tag:L2Pe/NQbSYh+JA0WdVaLqA==,type:comment]
  CROWDSEC_DB_PASSWORD: ENC[AES256_GCM,data:bMsS29FWF1RHdcxVNESIGLdZxdCNudVa0uTonqXf7YX1vTzvitNaq9M9Jqx0NN3ou0RURJrqQKooGeKa6SGnWQ==,iv:eV/TN9yxzRAV3d3/O1ilHz4Vi74U7IYRg+cByNu5BKw=,tag:UQ1SXgiUSQaxvrhmIq4bfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFpWcGlKTlFXN3NzS0pP
        Qkh2bTVUTUlyS1hmM282M1JFVDRmNWRFaEVBCkpwMW5ZMG8zRFBJZG0xa3I0N3VQ
        RzJKK0Qyd2FMWk9ueFIvM2wrSGd5UzQKLS0tIENRR3BXOGxlWmhmZm91amtrR3F3
        STZxM3BNN1dmV2Y3TGVucC9NK3JxTzAK+erX+Tvdzj0ki/QqTGK+89RT23287Vjl
        JMEQP3y4NDPS67gWPPxlkGVcNbH/vHFPkYVQd8aPNaJjYrZG6cn1gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T14:30:59Z"
  mac: ENC[AES256_GCM,data:4b+76LWfSAuxVi9YjzgGdNa9Co7eUMhVLKowVWSU/4Ul2WLc+WL5yIjGGtBsnYk5wkW3qwB8q4dZ0MywGVZouMtT14uHaMBlvMQJdL4vL4hizYXJF4ja6bz6VLLZhmA+gsSPAak7qWrhWcnWDpHjpnmSOKer92zVN/enDSGak+s=,iv:3Gnjs0WrsB13VB3nGmyJsqpwtg7cfAQXbfL1ja0wLO8=,tag:nmfjFc16QQBsjg/vYlDdRg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:X9bB4i5RwpioaZ8CtQOdScht8TW/i8/L4Pl83/TczB1oaLOPB+ii6N0XVqaotc8F+RpP6FRw4D6GDMBKryDnoQ==,iv:UkcC3Pjhlxn9aURcjh8MLE4ma1cZuw4kNUZ2gpENke8=,tag:DAZQiCXuEaddHKwwDeJRjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFpWcGlKTlFXN3NzS0pP
        Qkh2bTVUTUlyS1hmM282M1JFVDRmNWRFaEVBCkpwMW5ZMG8zRFBJZG0xa3I0N3VQ
        RzJKK0Qyd2FMWk9ueFIvM2wrSGd5UzQKLS0tIENRR3BXOGxlWmhmZm91amtrR3F3
        STZxM3BNN1dmV2Y3TGVucC9NK3JxTzAK+erX+Tvdzj0ki/QqTGK+89RT23287Vjl
        JMEQP3y4NDPS67gWPPxlkGVcNbH/vHFPkYVQd8aPNaJjYrZG6cn1gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T14:30:59Z"
  mac: ENC[AES256_GCM,data:4b+76LWfSAuxVi9YjzgGdNa9Co7eUMhVLKowVWSU/4Ul2WLc+WL5yIjGGtBsnYk5wkW3qwB8q4dZ0MywGVZouMtT14uHaMBlvMQJdL4vL4hizYXJF4ja6bz6VLLZhmA+gsSPAak7qWrhWcnWDpHjpnmSOKer92zVN/enDSGak+s=,iv:3Gnjs0WrsB13VB3nGmyJsqpwtg7cfAQXbfL1ja0wLO8=,tag:nmfjFc16QQBsjg/vYlDdRg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-initdb-secrets
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:gA3S8R+p8mhWW47nqeX23AzOUOC0fAcCOdhW1H95fxn6JxhRVNHpT9yYcNkPlkW/TMpDavmFsgVhus+uUw9pAVUKx/W1hqk=,iv:diX1K1LncGnPsHDrULieztH/NfFvH7X2CTNu6xAca+A=,tag:FU1LCIKwuwMe/IeTi3DJ+w==,type:comment]
  #ENC[AES256_GCM,data:3ngndTk+EHgaN418l51G4mllhizsKjfUZKSMygqQx2+ptQGbKKQhRcTw5AJ2+av02OsZyap61+nBxAVQ5wfnmjS/DLYu,iv:dDY3mqdtNPm3ZOGCJG+8X7Jf3PddcLrOJFeJ15VOOaY=,tag:iRi4qcf2vgYU71c+AG4TvQ==,type:comment]
  #ENC[AES256_GCM,data:8NHYUDU0LlGlR7QU7dDj1aXhFSSlgZQfQ/yhBax7sSOc2IU+UJzD8p/gPEER9HQTilQcnd8YhqE/AeG5tHsT7Y+D,iv:E7aDaMtW7N+FDYvHH4sTT/P62mOs1aJDHKpIjKXzYds=,tag:212BZyvMJwFH2g1ee50b0A==,type:comment]
  #ENC[AES256_GCM,data:0FLfYYKLlwHzItPbabeq1poYZktuHG93JFk5Xe+/IvP082TZV0MkZs/UAnZex7MXDap50XN/ZEljoL20BuYRhTLhgQ5WL4bjWw==,iv:TiAgpyy8XcOO6UEJErKPyOFfDn+8PAGH83XOkV3Mf/U=,tag:WaK9acLghQEVtexne1Em0A==,type:comment]
  #ENC[AES256_GCM,data:wx1di4WijxCab0JSCOB/huiyp0D/pBRqsvPHhCCrLsLHr0gfXAZ2jpIKUPSz9bxR0iPUOvsBzF3jtne5SuHVU8dLaPJ0KccSJlA=,iv:sy012zys8Vrr6d2sN2+ktT+AoKUEv5oaHYCZTabGQsg=,tag:tpYoRwFAB/XB0UHmECQBRw==,type:comment]
  #ENC[AES256_GCM,data:fKs9ifE9sigDQ+1jV5t+FZ64DalyAKXFQNM=,iv:RivqekB86AnDDeK7GI9tPMW108o01/pqBqflc631s00=,tag:QRUjCPERzScZuxc1sSpAKw==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GknCgTZ7sENtynxULK7v2GomWDEC4jTQ3SjMXanQ+TkL/JqYj3Aj,iv:4K7hvdeuYs8VVqdCQXS4gWJMC6QdR4Fxwwo0cEFJ6Pc=,tag:AfaLLW9oNlm7TPzEN0fGQw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WDD1w5Z0kA4=,iv:ePAd4ABdv7HQPygw1IpEo+kFQiZyi7Bjy/pZvhGXx54=,tag:gGWDdbhEpm6JDzPLTl2/wg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:w7kuVcs8mYM=,iv:pId5aveLSmf4ZPjA+SZW8TsiFYLwXTQ0PAjbEdSp4QI=,tag:t0qZ01rVNhm3f7/bg+BXeA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:42vI7a/CzXU3VimmGDTgKuQppViqjjtQYHknAnGIL+EVZLzu/AIL9+B59i3wqKTgM8WQwTZhIviI6uD71Ny4nw==,iv:cjMU9NVFIopnYP0ET3d7RWjDYgo+tm8nr1hUg5JTO+Y=,tag:dSk4ckisRNTpHDSCH1ng9w==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:XDffpB5um88=,iv:ZPib2SQQc3mggGsPFzxJIo/NMepf6yGaB+O1iot6qJA=,tag:VVTwcP5yYHyDWLVhQjUpdA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:AmsnmUcSOw8XWujGXUU=,iv:Y98LlCaIzE+DkJR+ANLKbtitj286aUrfWSV7QpChw/I=,tag:mOD6Q3JL0HX/ALiQNRK9Ow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFpWcGlKTlFXN3NzS0pP
        Qkh2bTVUTUlyS1hmM282M1JFVDRmNWRFaEVBCkpwMW5ZMG8zRFBJZG0xa3I0N3VQ
        RzJKK0Qyd2FMWk9ueFIvM2wrSGd5UzQKLS0tIENRR3BXOGxlWmhmZm91amtrR3F3
        STZxM3BNN1dmV2Y3TGVucC9NK3JxTzAK+erX+Tvdzj0ki/QqTGK+89RT23287Vjl
        JMEQP3y4NDPS67gWPPxlkGVcNbH/vHFPkYVQd8aPNaJjYrZG6cn1gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T14:30:59Z"
  mac: ENC[AES256_GCM,data:4b+76LWfSAuxVi9YjzgGdNa9Co7eUMhVLKowVWSU/4Ul2WLc+WL5yIjGGtBsnYk5wkW3qwB8q4dZ0MywGVZouMtT14uHaMBlvMQJdL4vL4hizYXJF4ja6bz6VLLZhmA+gsSPAak7qWrhWcnWDpHjpnmSOKer92zVN/enDSGak+s=,iv:3Gnjs0WrsB13VB3nGmyJsqpwtg7cfAQXbfL1ja0wLO8=,tag:nmfjFc16QQBsjg/vYlDdRg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
