apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  namespace: security
type: Opaque
stringData:
  csLapiSecret: ENC[AES256_GCM,data:B1hBa9lHc4FBFKmwCf3vodts1BwP4tJxWUwPvztC8xEqmfzd2oEGdDyAHAgx21cRXCAPe9Az+WiRkK4B15twezUTiPDEHIyO5udYPxAWri1Su63bNdsflw==,iv:RAV5w8qGjpY/JD2I59KxDiQTZbTXzeeA1DwWrA1vF5E=,tag:qc9zfeftJscdM0FerdzxEQ==,type:str]
  registrationToken: ENC[AES256_GCM,data:tzSoBgDYQAV7ST3NXqoW2olRPvKl6pIib7DrZRGLs81dkugYvoUdzSNtYy8=,iv:jA2Bx6Iq21ByeDBoYK1fTLK8VkHRkfHRzAPZDEyTj+E=,tag:OsBaHWoilAeA3w6DJoTC6g==,type:str]
  enroll-key: ENC[AES256_GCM,data:EQQbHbhpbUp+1/PUnlAp4WEt6yGLGntpwQ==,iv:HfdfpUzq+EZGRTl7fgpBAozsPdxDo4I0mnWt3oruS4k=,tag:SErHGs5zBgcLEdTEl+dvZw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNlh0Y2pCOE5VL2NUUnZx
        alBOdVVBYVkvdlo2Z2pUYXlENldIT1dUeFU0CjlPS0w5eFlJaVl3QjQzOWxNTzNU
        cTl4cEYweE1UajhwQi9xaklwZFFYSlUKLS0tIDRiWU5ZdTdRbVpQckk0QmhoSnMv
        dC80U25YRmRSa20yYkxGS0xZZjVpTm8KoxHUKtjjNT9Hg5H6N1s828/FolbCFGlT
        ab19i9Vfu27lviN5E08urPsbMk54vQr+2fP8j9iZHFAdCVF3dsrPUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:bLrjjt8iJP0RArAZUmnNmIL3DCHFruiHUG+tI/MPONFsRO/Yfgv+QHBfE6EZcGNv+LwC69UjhMx8qbyBpg7RfQ6e8KExnmOF7jEOmOvbQMRLpL67otL7TUYjJi5cSgmlBF4MXlL3APTxqsDoOPDdKH0xGbKukhc8o9IBeLBzeiU=,iv:EAht4zQAsSCFvHlYTjTEsciBrXQe9JA+Qv3uOlH9FwE=,tag:qNX0arkc67Dgfd2BJIvbow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: ENC[AES256_GCM,data:W8Y4m8zMO6LoECUsEbU76dyqOiB4V7gW0USOYWLASOJU2AIIiHaGM9oHqs+zb74fFdZKYyF6xFXvrKFMT/VRHA==,iv:SiTiwcdkqXb16dIPst8fG91P6m4lwdkrxbzT8bs/EiI=,tag:Rbax6CjS7HcTLva82YLEpg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNlh0Y2pCOE5VL2NUUnZx
        alBOdVVBYVkvdlo2Z2pUYXlENldIT1dUeFU0CjlPS0w5eFlJaVl3QjQzOWxNTzNU
        cTl4cEYweE1UajhwQi9xaklwZFFYSlUKLS0tIDRiWU5ZdTdRbVpQckk0QmhoSnMv
        dC80U25YRmRSa20yYkxGS0xZZjVpTm8KoxHUKtjjNT9Hg5H6N1s828/FolbCFGlT
        ab19i9Vfu27lviN5E08urPsbMk54vQr+2fP8j9iZHFAdCVF3dsrPUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:bLrjjt8iJP0RArAZUmnNmIL3DCHFruiHUG+tI/MPONFsRO/Yfgv+QHBfE6EZcGNv+LwC69UjhMx8qbyBpg7RfQ6e8KExnmOF7jEOmOvbQMRLpL67otL7TUYjJi5cSgmlBF4MXlL3APTxqsDoOPDdKH0xGbKukhc8o9IBeLBzeiU=,iv:EAht4zQAsSCFvHlYTjTEsciBrXQe9JA+Qv3uOlH9FwE=,tag:qNX0arkc67Dgfd2BJIvbow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
