---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector
spec:
  hostname: home-kubernetes-connector
  exitNode: true
  proxyClass: kernel-org-tun
  subnetRouter:
    advertiseRoutes:
      - "10.42.0.0/16" # pods
      - "10.43.0.0/16" # services/lbs
