apiVersion: v1
kind: Secret
metadata:
  name: talos-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  AWS_REGION: ENC[AES256_GCM,data:T05cqwo=,iv:IAqFleblJmgLY+l4IaRW7V2NV28g6N8EkGMLq8b2Pik=,tag:ccyWCYsEhWhUIMLYoE4wGA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:259a4QQ=,iv:osS7/VJEhmlEhGtaAUvNc8uKIBxHxgOnoZAOuoQcZb0=,tag:V2aZot8AWVxGi+lx7tFuBg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CS0/FFxvkW8=,iv:so2GkJP1G75Vui912+1m+Fa3aZEMDyG45DsakNTdFW0=,tag:lzh2w5zHtHjx1m+p41JoGA==,type:str]
  CUSTOM_S3_ENDPOINT: ENC[AES256_GCM,data:WXADHRPoYDbeQ8w/slYOBX3L,iv:M0DfcsjXujk70tuvpJmKjJ2AVj6Z/tzKSnkD+rDkNpM=,tag:qOYgFd0jcO8kwrx8961/sw==,type:str]
  BUCKET: ENC[AES256_GCM,data:m0IOlaPR3p/zsP7kkQ==,iv:zcTQpM2GQ/uDMmfDrCS0/TdnZ1tYoTeXyH0vqGOjwNk=,tag:w+cswN8zeXnbmBWsPlr5Gg==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:0ynPv34=,iv:UENY2Qm303FnOUWo19o3NjRN90tt67XKELZdChsePoI=,tag:0HWWY8mBJ3mQABMM4u0BoA==,type:str]
  S3_PREFIX: ENC[AES256_GCM,data:VomezNpcsw==,iv:R+IsLv1QaaeBetKCUPmrymq51hHR++gZ9t5dzN9yHf0=,tag:lRqDglHP5L2iqrFWFRs2kQ==,type:str]
  AGE_X25519_PUBLIC_KEY: ENC[AES256_GCM,data:XWFabJpJHm1A4bvRVMaXfhAEbcl89jIqzlXUFdyRIvggVT2WX0TZHDTkZx1oubjmaRisq1BnDvVAQdWSODU=,iv:4QW/EcgRhIzZ+RLAK4jKL6IMEo0JNE7YoFjcLZxvgi8=,tag:ye2gikNhpR2WtkfcMVWGYQ==,type:str]
  ENABLE_COMPRESSION: ENC[AES256_GCM,data:IDHj9A==,iv:GIsvczBBdISo6DS2S2amqx6jWrsgfL1xI6fHobfBsY4=,tag:/Mzx/FhS+mD/52ZL6ziYnw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYWs2K3R0Zml6SkFweEZr
        WEg2Z2RYbjc2UWxGaTBZYlN6OGRlK0ovR2ljCm1tM0doK2Q5RHA0T0FMMGVwTTJa
        YUZIU1FXa2l0ZXJDTTBJcklNdVRrbE0KLS0tIGx2YTU0UjJmcWJkK2NaZTM2WmdD
        Rm5WQWt4cXdIbVlzclI5Vmd0a3MvR2cKvEpUBQaF/wSKD54sdsy+dXj/QaJkasG9
        6Go9fragFTlZulnRTdmHiia5gppLMkWPuAc70N8yX3WxW+BeJena3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:4zKhSe8v44T1zdDyzBITNe7JPmm/n/Qp4us9JtT0vnatlk1Fk0nKKrrrPxpUcunDmJ4qkiNKXdHppECo8e1QBfonnSdgELopt+SZIqKsvNH4/SymRuIvIK2skg3OY7Yd72NxsqRyjX+tS18YEorIVpQNeSoepDMqA8FF4aTZdXg=,iv:aJvY3ZVlMIEM7L15/ktIPRgj17vizFpKS+fdwz1tTlw=,tag:qYEBW9WmoViGFMfmc3O5BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup-secrets
  annotations:
    kubernetes.io/service-account.name: talos-backup-secrets
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYWs2K3R0Zml6SkFweEZr
        WEg2Z2RYbjc2UWxGaTBZYlN6OGRlK0ovR2ljCm1tM0doK2Q5RHA0T0FMMGVwTTJa
        YUZIU1FXa2l0ZXJDTTBJcklNdVRrbE0KLS0tIGx2YTU0UjJmcWJkK2NaZTM2WmdD
        Rm5WQWt4cXdIbVlzclI5Vmd0a3MvR2cKvEpUBQaF/wSKD54sdsy+dXj/QaJkasG9
        6Go9fragFTlZulnRTdmHiia5gppLMkWPuAc70N8yX3WxW+BeJena3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:4zKhSe8v44T1zdDyzBITNe7JPmm/n/Qp4us9JtT0vnatlk1Fk0nKKrrrPxpUcunDmJ4qkiNKXdHppECo8e1QBfonnSdgELopt+SZIqKsvNH4/SymRuIvIK2skg3OY7Yd72NxsqRyjX+tS18YEorIVpQNeSoepDMqA8FF4aTZdXg=,iv:aJvY3ZVlMIEM7L15/ktIPRgj17vizFpKS+fdwz1tTlw=,tag:qYEBW9WmoViGFMfmc3O5BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
