apiVersion: v1
kind: Secret
metadata:
  name: talos-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  AWS_REGION: ENC[AES256_GCM,data:UR0Hh08=,iv:gAlJXCTvGqWsTPmDboTXaVjtHLbu+MVRRzXBPjuO+OI=,tag:XJLrro12jqr6fi4uUoakAw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eNT138Y=,iv:cQJvsB6AuQT6AKLCyO0HvcKGkUoY9BFxx79gEk2z+Dw=,tag:UlFEqbSzWr2pTDicLqSFuA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ObG61RuAxkk=,iv:uubNAGAIc2wR9Dr/27rNM4F9yoZVLgvDTq34TSRj3Xc=,tag:Rd8snKo/yBI0p+F/Zi/2Kw==,type:str]
  CUSTOM_S3_ENDPOINT: ENC[AES256_GCM,data:/cEx6OCMZ+TmixzS5E54MIbK,iv:YZpGMiv8Seb2IdOon/AnV9XpPpxEdsts55ryNrOzHGw=,tag:J/kbDhex+y6qIW6PsdXsLQ==,type:str]
  BUCKET: ENC[AES256_GCM,data:uv/RXsU=,iv:/DquSzWDmeogcG7M07Brwg2Q+vuqWnFwcxQVlVR4Bww=,tag:yOQrS4hi3TEK13s3aHVN7g==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:bwQ+oyU=,iv:Tyc0WnJxWNd/WUc/oVYTWgOZpZrwJgvb4L7MBcbGblw=,tag:FbkTRW2TPVX5phUaeCiDDQ==,type:str]
  S3_PREFIX: ENC[AES256_GCM,data:fqvp4WGYHw==,iv:CBKZ/oWMEEt5X4xAn2ptoETNbTTJ6c8gkYTm/FtLF5Y=,tag:QoqTuh4zJOGlelYrs9AlJg==,type:str]
  AGE_X25519_PUBLIC_KEY: ENC[AES256_GCM,data:jDy5L3UeDnRKTFtb4s2gEeyLsrEzVu7KSLbGBRuX2J18R67Io4NYZgQOIozX2x2J/wDb/tfvugC1gsWBGig=,iv:ZNmaWFQn3KKKBtL0s5vwsYOtj9hud2fPBF03R917FkI=,tag:iKBOKeMBpAXiAdo5cKBSxQ==,type:str]
  ENABLE_COMPRESSION: ENC[AES256_GCM,data:AP9Q6Q==,iv:C/oHLSgf2hmAUiHd2tlTrRjmfhCToAw9UDjcWBYB7I4=,tag:iW7rURw9SbK8PPRp5xK4SA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTlHbUdsVGNxUnFtWjBj
        dzJvREtlQTF6dzRqQ3N0QURpTmdmSVdXTldRCnlZdzlyUkNRbTdpTzNsSkg0dTg1
        TU1lY2FXMlYrdm9GSmlDZHo2cEVJWVUKLS0tIGNSbkczcWNjczRGQ0ZqR2Q4bTNN
        QWJWNGF0aW5IVDczMHErWFVsTjFHeGsKeqlCGNCm0/UKIlZ5fRyEWCjDOR4RH0xI
        mCz7pYuJsGWVRBa9UqOk7RgB5oQTmF12LauIP4nGBuhLNYjAYstVnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T17:39:58Z"
  mac: ENC[AES256_GCM,data:zUKJhbaOJ51FL9gztXsYDNLtFoGBxCKb1lb9vjhbwzwV0lYtd8jmBe3KOkXuSSHZEPJOaTdt99SHoODAs1gHuuZucFtIL6eHikNOapY8iLKF5dXAdWsPvJfPbeGE3qB33QlCeRUIkHI1LqVUkJTPi31FBEy6HwwRCbRR9wF3arI=,iv:3R2zIHDv+QecduPogdQTNghA0PeOh/f/n7WPtGmRExg=,tag:1w2MdFgfTBmxJibwh3KR+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: talos-backup-secrets
  annotations:
    kubernetes.io/service-account.name: talos-backup-secrets
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTlHbUdsVGNxUnFtWjBj
        dzJvREtlQTF6dzRqQ3N0QURpTmdmSVdXTldRCnlZdzlyUkNRbTdpTzNsSkg0dTg1
        TU1lY2FXMlYrdm9GSmlDZHo2cEVJWVUKLS0tIGNSbkczcWNjczRGQ0ZqR2Q4bTNN
        QWJWNGF0aW5IVDczMHErWFVsTjFHeGsKeqlCGNCm0/UKIlZ5fRyEWCjDOR4RH0xI
        mCz7pYuJsGWVRBa9UqOk7RgB5oQTmF12LauIP4nGBuhLNYjAYstVnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T17:39:58Z"
  mac: ENC[AES256_GCM,data:zUKJhbaOJ51FL9gztXsYDNLtFoGBxCKb1lb9vjhbwzwV0lYtd8jmBe3KOkXuSSHZEPJOaTdt99SHoODAs1gHuuZucFtIL6eHikNOapY8iLKF5dXAdWsPvJfPbeGE3qB33QlCeRUIkHI1LqVUkJTPi31FBEy6HwwRCbRR9wF3arI=,iv:3R2zIHDv+QecduPogdQTNghA0PeOh/f/n7WPtGmRExg=,tag:1w2MdFgfTBmxJibwh3KR+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
