# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TRXEh8ADUTCku0ZMSY0bG340bPWzYzPAIAkkdN05O/nPB5m1OqK52w==,iv:Ml9ez5sVdUm7SKhqjgcENbsqQKy0HMa5/RNNH8eQiH4=,tag:hW5EtB+KLXiQPlkyldchsA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTEthRTcydzFhY09qUUwr
        QVIzQmdDSDZ2Ui9TdlI2clJVRERoSU83T1ZJCjFBNmJSTzlpYjRkMEMvODEvZ28y
        MEVQTzVQUmdPMFFCVytzYnhEN3lBNk0KLS0tIHI4TDJsOWg2YTZKUy85bkQvb29J
        OFRsZFdpMExTYitTeDM3SlRoaFZwSzgKQjzkOciYdhjuAbmG5GwAADQUPW29291Y
        vl6AqS/9whQeAKLikXnAowsfFXbGiHFV+cw1PFf4tI3cx/+Ecze0Ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-01T20:53:04Z"
  mac: ENC[AES256_GCM,data:DkNN34PR+nCpob4V47Bc8fmsWS98sybSyBitZYP4eSrtnBQZ0ni+sWofcmicX5aXuiHCmBBRp8vjMl0iwj5BwJQAdhI9nBIQz0xlQm8JRzVzEQZMApXIfxZjCkAfAG75Nwrd0A4iqoKrr+HETyOR3kshr6nPnOsRoS2TeyTRREk=,iv:qeD7hIVCQVfGBPKS4VLqj/4bXT8CUK5vDcedFbEZaPc=,tag:Jv4o7ETR0TWU3AIjWtcaLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
