apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  password: ENC[AES256_GCM,data:jjfHGfDZq3e6wcoCxOI=,iv:UEg83rv/8uTIrcF6OtVCsBm2G8MUOHo+FgAeN+2yzK8=,tag:1nHxG+eHyJOzpOwmvZ9Nrg==,type:str]
  username: ENC[AES256_GCM,data:bIjh4157FtE=,iv:KK2O6yXmVxINhY7d6ykg/Uv9iDT+2ShbM3Dx46WId9k=,tag:HX9nUOPuI7MJkAcMVdGzwA==,type:str]
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:AlqEKumiVp392MdX5w==,iv:JteNEk0kJQh9QxWyuIRmBS1mg48g2pdT0+rp04/gc/0=,tag:OLknOidzImg0ceL428q8Gw==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NfGqdIWT3TdOLUUEQ38FQg==,iv:25NSLobW0tw+0R9ymq5aRwnkP3RQWNepARkeCAqhxPI=,tag:LY+tunMvpcKhiCHT4r9F7g==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL2pUVkhoUXM0bVU3eHpC
        R01SZ2srRFZsMHdmS3VrODc1bEdUZjNhY0FrCjlNOUc5NXNjTU95WkYxUHExc3Jz
        L054N214dG51dEVPSUtWNFI5bSthSnMKLS0tIFJSQyszdHJ3dVpwNHAvZStScjVv
        U21YUzQwbXJPUVJTQjNtRnZZN0JJaFEKoAQZg/vcCeCWWY07eam6r+LBb+/AVg5e
        0FTERFN6ai79mu9YLWA6wZ//Fsa8FBZrOQPDhk67jsz5P4Pi9CkGFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:6UduMz4n+89tvxVyJPOd8IfSzyDAdeJhsFN4NFNdep0VOx+z1G4gMEAUIoF8r7izixiA+/+um9dD4/ZXHgNCM8T4tBpj/G/cmG8FN6fYW4ZdmnrBazEdLoDitqPgxNT9dTa22q1Wo/wfcX9FpO0SLYuoG06NiDldeqaClbrVy7o=,iv:RhGnjAd7D1pb9Ha/Z8la/FA7kekkf/NeKN96Y6hwp1w=,tag:LkCffgt9Uu59VokzyLhYDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
