# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PH9xFZ/Yz4ZA4OQ1ub28W+7wXwtazJ56W0xsgB0XVYGc38RSVnCRMg==,iv:n/3zzT75WNSdS1kus17aKV3bB+tKZFPPk2xvcj8RGqM=,tag:zpkZAV7yXcU5l1eWPd28IA==,type:str]
  CF_ZONE_ID: ENC[AES256_GCM,data:ptGSEPXiY4FWBT9lO58irXa9UsJQBR1ZXMIKiD5FKWQ=,iv:FrtUURfr2u8VXPKhlqzLVA0J4rxapNUCfaCK6xwsZdE=,tag:jvWJZ0/cGgWSWMAU/yMa9w==,type:str]
  CF_API_TOKEN: ENC[AES256_GCM,data:sAHuksUJuIrDN0jtRWKUVjXtpN1InDr/I2ou4cgPR/y2jV4YDGdNSA==,iv:erDqCBBQhXYvH1ut1Ddhwj2JgcxRdhBqZAY2uEm26e0=,tag:u6MChZbtp+DKv4xwPN3SJA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb1d0em1FUk54c0M3TC9X
        U2JXSVU5YzVnNlZjUkRTeWNlYUNHRjN6aG1nCm1PN2RFa2ZXYUJFUGxXU0lqa0x1
        NVlFN0gwNUFhdnYwQXA0MXZwWnh1WEkKLS0tICtsczVubEl4L1I2V2pVZEJTYjNE
        eUtDbVpJQnRtTVQzQnlaVTUyNUFyaXcKCYn1nP0wyk/2ASap/m2sIsPLwImjdQgb
        8CW8aQqi6OUshopCa6c2xwzCn7aro8uaXOu2F4ugkWzapDJE7YGM9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:eCZvj61aFD69vBlCC8td5NduMQDDd94iwMALcJXn20GV1PKJqE7Tr6omxcJomYD00Ye7PLEeG9APB8RmYzlRq9lx9y0lVpb7CTYHA0QE1Rgeemofl59eQ4KZ/WQsSn30USWuZAL58G7L0W29JvJEqAbhIXWY2yA7BfY31C/E+XY=,iv:Hr29uspFUKwKEBhDiwAaYuUd0A9ONAwj/rTT3yndIeY=,tag:JlD0WQB/NIasoCKPzq2mbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
