apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secrets
stringData:
  UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:lN5E6ReTdbtyGY0EoF4MDcb3VcU=,iv:mse3lXMy32qcUT69pcAbvovdfc9lu+gTpF4r4H0QHgI=,tag:d1PrXT5GuXbwtnpmIZ5z6w==,type:str]
  UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:kPK4JwkAPIeXQd8=,iv:WCpQFD/TMiSKWTE5H9lwUHJQycQ57vGziG3l/qJ6+GM=,tag:gdknAjtAK4mdfdshPH1sZw==,type:str]
  UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:diXDqqsltrab46MsJv5SXyaXhUnViR4jYuFqQBCk1rhOrdrsNXQNtFaW3DIKyg==,iv:s0aK6XLKGpOAc+IP2GDWTawJmQtWQaJRnewe0cuWY5k=,tag:EHLxnvt6vmnj/RAlJPsWTw==,type:str]
  UP_UNIFI_DEFAULT_SAVE_IDS: ENC[AES256_GCM,data:uLwzqw==,iv:Ofyw7iAxZ3TPBVzBuMrBa8X92y0Hc6w+1JtZWkfHOmU=,tag:J+CpHnPgevHjfeDuICGrpQ==,type:str]
  UP_UNIFI_DEFAULT_SAVE_EVENTS: ENC[AES256_GCM,data:Z18bSA==,iv:NNU+MdKzBBxOaDQaMFKfIS2zb8i6G+Z6wcBSEqQSuh0=,tag:aeYRq2OmsOUSsPtT77Xs0A==,type:str]
  UP_UNIFI_DEFAULT_SAVE_ALARMS: ENC[AES256_GCM,data:bgPprQ==,iv:H0HOuaWxipUskpU/X+RNea/5zHslWXR2HzNUV8RJXKo=,tag:mQ614+lYAuB6AKzDMMG6lQ==,type:str]
  UP_UNIFI_DEFAULT_SAVE_ANOMALIES: ENC[AES256_GCM,data:to3rjg==,iv:zccp3rxjuiz5CLgyyQaBB1WqPkwKqE2jzuX7Xeg7q4A=,tag:rsYj8EkrVbJQOLQZnWN9lg==,type:str]
  UP_UNIFI_DEFAULT_SAVE_DPI: ENC[AES256_GCM,data:tWOwMg==,iv:N6mS4iKX1gbaFHt2EazWNuj0YigIle/TOG/NFZVf5ZY=,tag:rq16quuHRhrBvzrjqomLwQ==,type:str]
  UP_UNIFI_DEFAULT_SAVE_SITES: ENC[AES256_GCM,data:SvE5Ww==,iv:vwgZ2eFJ9LuIua26LZ4FyanB4zNVb68CL0fBjoc2AuI=,tag:x8YI4W8maZvE3bGtxTY9qg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ3JwaHh5b3B2amttL2tK
        L1p1UnZsYkhzNlBiaUFLNjVTZExOMXFuSkY4CnM5UTMyQ2JTSmJReUZ6ZEQ3ZGcw
        WHhZRkpyWnhEWDExVGtUUjJrVDdZbjAKLS0tIE5nZlcyVUJ2eWRaTng0V09XNHpK
        WGhrUGZRVERodVUzeGVjcUw0aEFkbUEKqPKTOZF4etQzwmw2iuEuqiXYtBt7Y+qo
        5BtubzcPzsKzFjiYe/95PUMW5VI0c+h7cFdoTbd9j9GaxG0fML2ZgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:L4thY8OQYOAgvZ3G3ddmFWLu+TIURqCEFiNS+0xjHxoJ9NBT9UmV4/7hj2NpY2tkRWOQZ7URLJKI9jSLWdI4Pbv2hDSTg3VjEXunZYc7TvP8dfKJlMSfjf8rtCVbsmxg10VA6IQOcm6NUDNiQUORYZew7Zkwln7HQ/5CbWygL1I=,iv:pk5RFyNncOW+NxjmLtq3BBS4B/ChsfEL12IcriXhQPs=,tag:uVquvDwWsVATBYv33dWDNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
