# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-secret
  namespace: velero
type: Opaque
stringData:
  cloud: ENC[AES256_GCM,data:/LhzPYxeaowgsSXg2uJ1rZjBQv8KPyZghUnhQwEmBna8FDj82ikzlayd8dBEtBSrzHlUIkidZLDJpEZC6qNJFSQD4Q==,iv:FsSvkH0r6MrZJIw2oSkWBCuBkkaOwgb4MNw1tHPdrH8=,tag:cDV7mUK6BWiyWw1oz+H26Q==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNkFOK3FlNERJRXp1TWVP
        akNKMUE2Nkg0dVRyUFNqMVZnMC9keGw5VWxJCmN6SzBlaHEvZGxsdGM0TTgyMWVp
        MENNZC80Y0g2Y2FDRE9RWkpVNjNCamsKLS0tIGRsUFo4eVFFaW9EWmtuSlZiUVJW
        MTE5NVJBMlFweEFKOG5kNm9kSnpNZFUKmg6qysNFQRTAEqq3i3da8fz5r6vlSxXy
        ofX0jP6Vo1E16hr8kNu9D4M8O5znQfUe6jIKU8sQaoqi30UTH05SlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:ok3+HgzvTQESjlD+3Pedm7jTFlQQagpODINR66NkJukq4L2VOayCPxteE9KQMgdpUOXgh4xDJOIOhM+FHN50G5zl4VJco2XYgDVgTiXUp8K1mddwx5M3UIXGng8GyhEymF/wePTDE+W/88whsmdeVu1ern21pTwMo8tayYgp9u4=,iv:tAQD+iy0mGiLgzIlfKt1JU2+PVRHofvHFY7TbE/HxZA=,tag:v7aPP+1YSgLjU1tW8Z4cPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
