apiVersion: v1
kind: Secret
metadata:
  name: memos-secrets
stringData:
  MEMOS_DRIVER: ENC[AES256_GCM,data:KrpgCz1ua24=,iv:MOdo/i7+1oi40aqhXpgVfu1BACi8BQBMmdzPsmynH/U=,tag:AfvACWJC0cp7OxYSd48B/w==,type:str]
  MEMOS_DSN: ENC[AES256_GCM,data:fKq0biE8Jf6ZtJbejpDFsyq0PQFG4GcKryopP1EfTI7VPEfRbcjcvIyVyo/3hI4iktVVzwk+3IwJHppJHT+hZ8qMF2A554FPyun4DOUmXaGJeBNOn6oUKdInAutt2fiGVryu91Wx9U2AmIqCsEzp/zYswbJYvg==,iv:RHeDvolygKvbOV5p+wxTIKCa9TOjWLGNNclONwVJ6jQ=,tag:viN7oKT95sMEKxqccnsIsw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:fTifSgA=,iv:SAd3oY6i5RCRxyUm04vS0rN0elLyGNBcBX6DnfvzSm8=,tag:8De+yfks3ZbvaIgDnqXdrw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:93OM0t9cGG8DmecvP9Ymjr6EELZPiYb+HbGqE960dgBxov5tdHXYJp4=,iv:a+wYjcaF0BwPTzb1rxDXP/jpRdpgXUHmbjKHBZry5i0=,tag:wTf4Mum67cn+WP8bVbFRhQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:XO0QKf4=,iv:XBGrPJo6CnXFh3WDarAWXhh9O/FcZ8JAjSsueRWOESw=,tag:Ft8/GRSYJ5rezZTsIPn+hg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:jrYyBKhBIt8jkonFRp6HNdqhBpewdEnuwflHSu923iC21FQHlv8NYeXAAHk825cbohelbDeKa2c2uTvkVvKwzw==,iv:JP4ixXdIsKunOwA5VFy1Rp5VzLjxCT1y81VHpLBC6f0=,tag:TG85nYSorNT7HSXwXim1Og==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/Fo5uBQATqe8ADJwtYY=,iv:UTf5y0MdsjRehVHQ6uiIi7nqlp0VJHXwNe+n+7teIOI=,tag:R2iiOoXWHLU2grMp59BrPQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:HwT2xsuP9CU=,iv:ywFn0/u4MudFZzaizSIidiZW74Kv7IWTOztbB0dffpI=,tag:1C1opiIc1QQXHz3DnM4HPA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja2JTZ3pzTVIwMTBjZkxv
        RWxoSDlCQlByY290OGtWeXBqc2d3bmo3MEJjClhSZEdLTGh3TmRhU0JqL2x5NENo
        cFh2Qk43SVlybk9nM1BFOHRtQjJkUUEKLS0tIFQrako4bjZ5QnFBMjJzT1ZYdkhj
        YlV6S1ZGQkJIY04vK1FpYThuVmNLRUEK6PLS5WYHIa+rQ4JcV43yc2ziBcm6jq9b
        fEFFcalWoT0hyaL8F9wOyHwyvmDSYE4DLnc1ZiIXxMD7IwIPLGOegw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:p3AYMYCHcJKwzqLQYoelBKYgSWOsJj/vR3WhB9EiZTpxsw0838xnJ9nVSx1+1wCWgrG8xsYIODf4HUjuK5fp5/iF9SWdiIE9v1FLX598dJN/77CE3204p8PMkg0t+RbyoV6QeQFKjLV/dfZUJC26bX/18VUGzg83iLfsmib8yNo=,iv:LvR/dV+NPf4T57sgSgdpOjqmUkAElsxNEicnfA6Vl60=,tag:Ktb2naUvzrHAj79NCOc2pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
