# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  namespace: kube-system
stringData:
  client-info.yml: ENC[AES256_GCM,data:VCFBrx18O+4cvoNrcwlGvCqiMBo90S+bqHF8aliLOxIsuWz4g6c1LKunOwoZo7WG4+zU37ZCFcLOSFIhGkyoZw3YUZ0jBo2i4xuwIqUKM5yzVir2wvHNi7orEPLJ1KUJpoMFcEHngH2wvWBPexQ=,iv:vCvotaimWYQH7b5m1/cLNtdJEgbyUSStpJiu0IlXlOo=,tag:ylHpxQeHgCBiSFZAg/sTdg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzA2ZzNocnUxZGcrbWRC
        NUVBbE5TbzhRamRISzVCZncyc2h1dEIyTFZjClFtV28vRE9FbkFncm9XUkJZZjJv
        ZzNRSHh3SGpIdnRhbG5ackM2V01aL0kKLS0tIG1qVTF4TEp4V2JOSkVnbnFtcU1X
        amRIUndkY3QrZjdZWUQ4amRHQ0gwZDQKS+L3p3bEqQPl2dTdXm3kDsglBoQG5D1a
        nJNKLvpu2K5qY4hZT3kJSY5QOqQmsfnkj4KXoFiDVF39pHjoaoBBQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:63ebxuF0/p6iRODsOVVT5tGCj+7Q6xh48qOOde5kwqs0t1BIsob69fyNOtTPivqrtIiDAqjp2AucxelN6qqPdn4pfl2wlqYPpR3g6Qd3IBkk1saT2UZ+Er60ywXRSbQPRdIjJ7FFE8sS41CIgeYybPy99aO05RbDiFJqJjrneUI=,iv:FWBaekpif3GPsasp3Gpklzl+Az4wkpg+PA194J3inP8=,tag:qDxj7g8m5jfHCw0faAZMgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
