apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: toolhive-system
stringData:
  #ENC[AES256_GCM,data:AmqngUGLsdXkbe/10B4=,iv:uwn3et77XFwJN1k2KW9I889cWvxWxNpi6hkZOThQBwU=,tag:ufGt+YOf5HK8TYcMi5d1NQ==,type:comment]
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:8QH6b3tP0wjt/yEzW5Zgi92imRvYM74SM+1t0qYjO4H10dg3asqvtQ==,iv:M6Ald1FgVTEVs0yIEdDVQTWwLU3p+u3B2w0pBB2CQmI=,tag:a3lThPrENZxqrT/K42jHBg==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:w8HkuWNfKvcehJ0S0V7wt5OzhFj7ZwwjmCMhQNGJ3Kg0NmG2ZvNVVQ==,iv:3z3xjFtXurzCJ5aXSggz9r/ourSmW970ddxd5vvO8oM=,tag:KxRoHycOrLCpxVisL1/VCw==,type:str]
  #ENC[AES256_GCM,data:Yuv3bPpSq2eFSIjkfZ2QXEX6Y+GJWG2tm1Xl6jPI,iv:8j0XIK1qCB5sO/zJiR88tcrhrR4K9mTioDb/5Ckhyq0=,tag:kUmcdfzCYrYID699m7WOUQ==,type:comment]
  PAGERDUTY_API_TOKEN: ENC[AES256_GCM,data:b4QksPwwqZV9z63ALCeFvPQpzmIe3GQ8BoV5fq88AJJJCjVzQ7ijIdA5wAoF5C8=,iv:2R/R59Zft5cUfgOrfpQMtay43Hr5uIHWLioufY/CDSs=,tag:BpWZ9KFECOnZuhsKUwCYSQ==,type:str]
  DATADOG_API_KEY: ENC[AES256_GCM,data:2waDenYWZMB61eF0nnLQnFobIcI9UWfewoM/6jvZP4f2r1MlDTdfJt4Aug==,iv:MoUaZLdMKGlLxiJOmXwFHtrRLGBoFz8P97hpIJumMgk=,tag:UwdD88E1aIcs3eKEB9msTQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:buQ4VeoEN3nBa5aEKgb7qOgSkNM0glGvk9yZovLYJypNG98ZkMa1Ksk27hAeOOBlwQ==,iv:IQK9TtSvzjOfyfYIZQ/K83Du4OImgWJPQ8iISv7qyME=,tag:W7LbwV+L3VeKfDwNClYsGw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RQ+Q2Cs5k5gKFkauh37e3Jguh7u0o7riGBy2gtDfKwhPdlR6SzPXo6z3XrP6m59xCYbl1vU=,iv:wVxGPpBIhDYmRCSnRZGRs5wC4jKrwC3Sb0Hq8RN5G00=,tag:TGMitIyBO9VlrlJ9b35WSA==,type:str]
  #ENC[AES256_GCM,data:279+G/QS/UqkDoOZbI6fOrqKUX089SZu8WQq2nY=,iv:oEsQJOL8Uxuzw1ONc9KcUPBymGvRI/8Rvkkj7LBpQdE=,tag:j2L4OtJajqET1q2PSUGLyg==,type:comment]
  TAVILY_API_KEY: ENC[AES256_GCM,data:RNYQx46Sz2j4LTwOHurz+QuRXdkLvM5TUfBpHc2PipYYJNiOXjOWsgYH,iv:xljHEZBUTcRwLNH57Up+4ixxNIkN0vLFVlBbT0aDKcU=,tag:APvthOREVlCksCd46ghSrA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNjBzd0JwUlZRcC9vblNp
        aFBCVFFBT1FOMjZsRE16aC9EVUs4ellzSkRBCmpPS1FCWWxPLzJZK3poV2hyV2l3
        N1ByZ1BWY3lGYTd3QW1WV0lSdGVoSDgKLS0tIHRCWEtaeXQyTVk2bmZvRG1yOUxE
        TTRkcEFhSE1ZWjhZaW9DMUpuVnA5Y1EKZmMPL2MSSAj7cksW4cwxby22tpKKiJsy
        o7XAmRct92Y8maNwU4qoJWMENyh15emaOk1Y2TkuFivekqcYz/8XcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:inDTl9Pn0kv2ygSsvfwTh8zzagp6k+3dsbBA2iD3arWMzCcPHsoytgDuYdE5BMT6XyPV8YmEHJHMqU77zt1FXZg4qC30JVdB89J/6szqKzYe15v6ZH8VrHUxROCXxLWbeMee7hbmLngRppPtl9ufu4ac9ermpslg5TTct24Vu/4=,iv:/BKW1P2ZAydPh51HVdg/avLvTtKPducCwfcnFpsPKg8=,tag:FBrYaPENsJgWhihmXj302w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
