apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
stringData:
  #ENC[AES256_GCM,data:d1ite3N7B+WghJkCfthPHfNF6REZcIwh8RjChEpKYVYgN8+g0hj81aerveK75q/t5+iS,iv:WjNoenL62XzLtIjRQeS34uuiKsW8sTW3p0uL3XQ8n2s=,tag:bm3WpiA9Gvcw2mkIRBr3Jg==,type:comment]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:GcZeWK0KMblYmmIAgxsI1WDU6zqEFh9FaXjacz6K0mdQgvbhe4+E6KOHPYYtfPG60O602y+i8uSuW0hBuq2gZjM4BA==,iv:3QSjVvYsHKuRD7slADSbAzQWQt0vi5NoyvOBUYvJfPg=,tag:WSynlfBFIbCfB4qYWhnMKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0ExVXRXYk5ZcUY0WGNO
        NGxtQzd0MUlHSGpXVWlseFFieW1XWk55WlZNCnZ3T3pmcnMwdkU1ekhLNktzaTFw
        NlZWUTBzOVBtMlh1T2FacngwcHZTZnMKLS0tIDdQTWFqMllZWTBkdGFyYnZhMnRo
        bXJPRWI2Zll0RWZia05KbENTVENIa2cK45ZKoskJeMLxXPRzwUvIGM8BTu/k53J2
        2arLmq16UrYEndMSJYQgjWuIMu2rkg3oAziqOctwbYP4cSob+nXhxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T15:50:09Z"
  mac: ENC[AES256_GCM,data:ouTRQvjFWMo6a1NsTznnvzNNTkzHZWs1A3bGOaGw8fXcjzS8ObU+I2bxEhMmB0a30LWyos8gf0LBUyh7SLG3tUIRI3EoufKVoIGOYtXbzLQjHCWKlPkvqWHl7creUFEusjht7JEvBj2FBuRh3DMV6yUDeQOh2bWqLNNfa6npATA=,iv:/Dgx99WSQgcvzjGSaHUMBVJaa8219mrmN+nfRAOgr7k=,tag:5aa2KsGyHmGRYymkfIdjPw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
