apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
stringData:
  #ENC[AES256_GCM,data:RMmfiXDlNYj2r4KkrNEZvIuQRygGMzFlUD/Z45xQfeVfdjXtOhYjFnMyaIDR1NPLhzTS,iv:qyzweMJ2t4lEMA9q+16JZp9zoVs12RIHV/cb3I6d9OA=,tag:HYF6WwgNcfjD/Yrr8AdxaQ==,type:comment]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:tkblAQnUnchuOSRlbvo5jhM8BiInB1maUiAy9V9P7hhEPJYgNxGvAhlpV9qe2RRKeNdmTtmDL61cY04neoU06JXVQw==,iv:6zE8DnVjH3YRPSzYAQ7AfB2YYt53MWhvIv7EiBiDkIE=,tag:kmKyVaKvun3a6iatTt988w==,type:str]
  #ENC[AES256_GCM,data:MoEUrdZpzLr+jEdEnd8rO5K0oPKsEc6k0BpOz93epofv9wjJxgOn3N6irtJElETagf/PCH4V0EV0Nee4XRLQVCcrZFvb,iv:JgdbkxU0MyyTeNCoWkWPGou6ZbJyT5jXXazq+bpokCE=,tag:mkabhb6RIU+GrRlxDGZ14w==,type:comment]
  #ENC[AES256_GCM,data:+qzlY1X015sLGMbzbWOW54T4xBEjWTM4LSi7RjheZGhsZ5N89T6SWKjyVovEhVB2PC9Z,iv:ppEQJvUMypZu7mw3nm8MQ/+MS24nL/XgL72kDhfoTMg=,tag:EJzRad1vo4LAoOWK31TjKQ==,type:comment]
  #ENC[AES256_GCM,data:AoPdcc7gskmQjqD8RMV83KyTLDwC+V0uJyKweVT4f2OY1NJzrGfjUEVmq/b7aDpgiAs79CXz4aDuwOR/GDKt058+eLlcq16/I/5AvNuy4Q==,iv:3oG5Awz+ng/6csKl98SS4oXS14PM69vvX3qzEr5p1Pc=,tag:KKPkgAEMJNOgh4uJA5IHjw==,type:comment]
  #ENC[AES256_GCM,data:qJLllMfHPiaUPM4STLGsoWaPD6T0VYTK1yPShqbuZakSCLutqTmZ7bDm/GehjO1VD+NqohjYVZWF+5oVhYvyDUo=,iv:7qYIQIrbTr/qtnqZ0d+X88i5X+uJQ30nKrxvbk43a8U=,tag:2l78IOBKjIJfKI2EjrHdQw==,type:comment]
  #ENC[AES256_GCM,data:mhS2wxvVQbk5rgKCcC7y6KXClRB27r1McAWtHAQHFrLxYw==,iv:2TsssYbZX0FOYUAFl19aQqLv+S5eulyQyccV6jpGYuw=,tag:s6YU5jR35EmcVBzPHw84fQ==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:R0KK9GrDDJ6BlkaX+EwS+pHdC9Sjs9JsM1XU9y+/OV72645FOM2Wyqc9OKfDWBea3Fr1Y90LKm4gPUttnTKQETNGqlv6jI2dmmMSGb/GrfMgsQz7LmvIB+1aj+eH3UTLxldk0XZPbb1WSgExMN6oDh/Zr8EkYpmbr4k=,iv:5+sUnXtc+hw45nMkwsa0LTPOXGJsmdtnrGi6jg3Am74=,tag:JZxIr+IU82wsdCWGOFGmLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObm9vaWxQRHU0MFpvR1NE
        cWpPaDlMTmpKY0hIaFNJb3hDTlgrTi9HNjBNCjRDelluZTlFTGF2RmszaHhVUmtL
        Vm4rRnd3dUVKK3dOendvWGVqV1ZHSzAKLS0tIC8rY012SGtEMUhlRGNyZ2VFcTRH
        bGQ1WkFsdlNsTjZHZitJRE42ekVJREkK3/rmEBYatZ2ioAE321cgoBn6/IyyrzCx
        smPzTrwpsZOa22C4iRvfvSQiYIvGI3pdKLOtxVzQaGujAtDpMU8Cgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T16:49:32Z"
  mac: ENC[AES256_GCM,data:rKh6XgkrKzoHYunKn85odH2tiYnwWw0kt4o8y9N++0qmivqrLrWyUvFATzCX4fuoCDRCGpuHOnj/OPG/wlg2iZYxdiMJyVaoq66dINSQCnEiXZ/CF+SbQ4cps/K9pgONXXdLn4HzE5ntVjnpucr3b9ncZ648kcHtVRLJVNWzZ/U=,iv:Fx9KyQSatt8vCQm+3i5Y4WnheQCwKfL7EloUB2aDkwQ=,tag:XQHwWJ44BLPx0qaMXzPILg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
