apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
type: Opaque
stringData:
  #ENC[AES256_GCM,data:04Z/qqDCYhzv5EXZ3Uh6+BSTi0rKAnc=,iv:HGxikgEgAe0kNjzNox9ki9n2JgQtcCxHM/5tkajY+G0=,tag:SQnetxpplZ05izw+yG3T2w==,type:comment]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:swsNwi0yF266R5odAVFq0szMGkolG/3NyTPKtQ3M5j9S+BS1PSr9F42e9mnZ1Ns4yqg60F6IVAOt/nDZR6fwZ2PsyQ==,iv:pq1N+RnOPFEdADfaLKIC595lTulWhLercCCheTlgyCY=,tag:daoLFqli44jZF6doqCqeWg==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:qToQN/LpMwcpHNO8p8MrUoeBUVoYMQQvV+LlWR0KGK7k7ClkgOE/ss7hiPl087a7d3c1XST5FfZfDLWDYkUgcw==,iv:gbT45IGeomLHXWgeZp/4+ddEqhCbPMyNMz6Ykv78cdc=,tag:iqnWj7ZJ0uP0BB7mQjRP/w==,type:str]
  #ENC[AES256_GCM,data:DkHtJnuUKhq466U4Ev8HEq+Si6bJQw==,iv:/aImbByZ7oVix2jawbxR3Fg6ZqRZSz3HbQDf755UI+c=,tag:afByqJJFEKrDMWqJdn+9Lw==,type:comment]
  REDIS_URL: ENC[AES256_GCM,data:KExRviXFPurCVSYXyj3cakGrUKPD8e7mSD/jWCgEVTOBeBd5S/xEE2B0ReFXPg9JQm5F5PbR06ejVAf830J8fiJ2lHoHkP1zqK6wmeFQx7YIdnKfgJJmNg==,iv:Btx5Id6xbWxuiz415ae6+wClLiQnqkD423jefbpxH/0=,tag:hVuUnzoqGbEtiU0Jp4thfw==,type:str]
  #ENC[AES256_GCM,data:lq9AiLnSs9UrMnzIZzhhgBi8TSry+BEUIgIKcab12MQB8MC7qimCP5VdSZSaVv31m8I7FV75RbLD84aKAhEY9dwT,iv:X6hqZ+c8zw+q9cH0joz1ydc+KaToOkirFZMjVRvdTRw=,tag:3X+JzIW2+uYIOyx+OhCUIg==,type:comment]
  #ENC[AES256_GCM,data:N79EsEWr5pU+869UhYM0OAE+GwhK27XqdKSVX1incnhii/ioXFNG6GjuoPonwzhjpcI8DdJgZ8AoXfs=,iv:7rQkRrK9Axp64XL9PIoiCktysv43F0wrEn2nHQcM5SI=,tag:HG1kxirZEOSkUJH9SbIuDg==,type:comment]
  #ENC[AES256_GCM,data:vHPgX/2RCZ0nkkEt3/VhfAS6JV6aasCNoiTaL9qNaF/IW68LcF7fQyrRhtpv7n+OU/SbfLQG8wUmq81NYKe9CUzCZG8=,iv:opOQToP9IPh/JICa7t0mLISjVvNaFfgZPjXoWukb7BU=,tag:/TPRMcskUtVUn4mNdOJ1vg==,type:comment]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:S/oNitVWihCyZjpDHbsScWLLHuRigux2kZNJOc5bQQ6X7uUGdmzS0p0=,iv:F9gC86ehokrd6Go+F5SSWmQEpd4X4Hm6UJftiDs6qDQ=,tag:8r242cYUe2A5QPM/cJ+ylQ==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:BrbEcnCPb8jOlG0ggeh9q/oyjqlF2Tf2esjVak83lJYKTmNyO32vMRQ=,iv:nH1XOouFQT8f8s6k4G/2GsUqD1rabAWuAwnHxDrdW+8=,tag:rAzlEHk3Yib5augYZlRacg==,type:str]
  #ENC[AES256_GCM,data:X8C8hXE5PQS69lxGcr+yTmu+dbaYEbkXtM1jts/qr8prN25Xrtoh/JQuHDQ5AeNwHaoWIf57nueafEYLNiitIrxPyuDcWEU7kkJW,iv:/hwYfKwuMbSQiuh5KEyROQ82snr0S0uogz7lR2qMyM4=,tag:O5v74aPWG9XkY/A/cE2FAg==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cNuxhYM7eZBP7mv9tglnSyzufUdeKEPDeU8cJ5UMv9zidz3ce/476Sc=,iv:1d6KkJiBoSSaniWCzrqMU2VuNkKFquziTQs4MKIKHq4=,tag:wVRvy7OTlzPzbj1NyD23Mw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:p7Qpl1gs7w==,iv:3zyV5uSgrsVLobLsy7DtayGj6oeyAAYJdvt5v+lE4RY=,tag:tQFvewzibZW6fmuuyt4I9A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:OAfuYueZaA==,iv:Unq38DXaCjgyP/WMs4X+IsdUlbbv4ZtY2Dm2tdT+hsw=,tag:1NQkUOtHeNy91r3s37086A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ozjpVDg3PJzbtHTpoO+y1lOcpSvAJsQYz2w5SwzDt0WmkRC8IdiU4zBzRMAp65ChW3lsc7tbCCi/uOwOIJrPgw==,iv:6nFxuzWeSwj0FVLnmhBgHtLAGqP2jN6fplMJIwjQwVU=,tag:odlDZvmRZ0aFS5JOBbTKGw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ZtjlJ+20wJk=,iv:B3s2WrV2DtqTYagHcRE2Z/rxKMu+womYM34NHcWRjII=,tag:bdn+nzyuPok7bBsZBpfEng==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Vp9uL+I6wka1RG7HSYQ=,iv:7Hb0exhJ94JapMg/n+mAcCcZ5SDWVn54judgUNbDbes=,tag:Vsp9sBrJxWiFuBVaJAf57g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhakxDKzNiVGFyOXU1WTBr
        VkpOc1Ixc1FMb2ZhSkZmR3VrRmw4WnNFVVg0CjlCUmZ5T3EvQVBvTFptdjdUNi9D
        UlRsbXBLa1Z1M0JGMEU0eit5bjM4cEEKLS0tIEVHVGJQNGVDTGlmZVZzKzk3Y2xa
        bk9wczRSK2toWUxWcEliTktsbE9LY1UKJKaGGifv9HigpUUW6O6nphhHDsQYpi62
        JLB6hVDrHvPF/hHfb8PXIUPTDAqxnw8II9WRF45P79Rc44BPEL+EuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T16:09:07Z"
  mac: ENC[AES256_GCM,data:YdONxyGkkdUlZF8kheG5huElyIdANNuHwlTdK3mBUhy9uNzfeFX2FLG6ehVifAy8GP030sz35b6fhEVoggZ4tqP/DK8jIi+Su5bcar0Vzt0Nogd1gHEXgK0qc/gWRUx7zBqn8glhQgcX6ARWj9va2NYCqh9woDfaDXyR1Mxsuds=,iv:YLQzrYA0Nn8B+4+kBBioGZb7818WqEKPbgveok0vtNY=,tag:0q+Ztp3cTN69USQRHYXTdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
