apiVersion: v1
kind: Secret
metadata:
  name: omega-mcp-secrets
stringData:
  #ENC[AES256_GCM,data:pHqBoKVAbGRGHKp9lDVpzp4qnMBYac2+nAUmDPgJS3UCE1q6OhrUFSk0,iv:POHEI7wgj7MKxuUoFnCCU44bPzY7JWNSc+klJAa9VXo=,tag:YZjl9LvCW4rEN56Jbis9Zw==,type:comment]
  #ENC[AES256_GCM,data:h+GQFcxEqqo0MmZS8D6Cbxa/2EZ310LlHyaFKi9LC1M+376BmWgyStBmV0bVDOO44QpOjXs1x9nv06KXQ/y5DjITezE4NQ==,iv:3hQ/+XTo6iC03W7dA+4TI8ekH3Uats4485WO7yyifT4=,tag:F1iOhp/SV8YpM6dKwVBJFA==,type:comment]
  #ENC[AES256_GCM,data:jFldoUgCGRXbEcO0el0nAK/LTtIe8Kc8uRhfzofVz3DFzVBFCVG8B8oGMIdhPpF2VWIS8YT8TGURCwU/q0hmCcbvolaM8a6P,iv:FtyaILUGAJG4SQHo8mzIWv7qgFuKTq6Ur6nhmRIaRps=,tag:3X9j7zcyFJJNq/9i2E0kAA==,type:comment]
  #ENC[AES256_GCM,data:t1dSxPLPlnzliv9veyfC7T4NeDPP8A8hmL+2GCDbxqyNwQ6lCPb2IYfXTg==,iv:5gYQbRCWDbDmkEogwvjCtVN93FCWQvJMANjI+2Irq/E=,tag:JiSeHL45hI9qIGpRgGOaRg==,type:comment]
  #ENC[AES256_GCM,data:BtfHwFCFKyCVr+zhReL1N21recm5NxwMyon3sKN7sEqlqAmEiMJlrrmGFG8M,iv:vSWF3eb6aOwjyuEUs9g//gWHMpqgKZRq8i8sSawpBvI=,tag:86UKdOeHxFpjdS8NHVIypg==,type:comment]
  OMEGA_LICENSE_KEY: ENC[AES256_GCM,data:OpLSTcw4JdQMIQFdlCiVFcyGWgPfq4vQ66zNyr2K3v8O9FpqhBTyihrL3O+XXA==,iv:7Zq+GBSYSB/VkhogEM8u9fz18G2yBEpVXF4usrK59y4=,tag:S8iGEM7ZzeIAVGXJVNSE/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdnpQOThKVUVIWElZamdI
        YzlEMDB1cVd4ekFiTUFaMUZBL2VhV3FvVkJnCkNETGhyK29OeHNzVEhuV3JtOGRC
        Zk9RVHlHZWQ2SjV6M25EWlBqMXJoSEEKLS0tIHpyMzJaaG9ZWWtpRGZRVDQvOUdW
        QzFmVjkyOFVnRDkxNWdOMEV0VERYL0EKgRJNr/JRZUU2Urm1CUWuQLYxEFOyTHRY
        CnO9qxNofRX6RXTyJGlA2KNEXQNRL2NzDLl4oqgUahFSOzazkH/oFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T01:37:29Z"
  mac: ENC[AES256_GCM,data:44V2F76wmq37qGH3F/rXppWEeOfJ9nDVtvh/OL353b4U/XAgPFBhFh3oiSHTz9eH9N5+Q+ndivqDoaB7qfHpS+agzzziUZsbTxRVGw+XG9SuNTfO6eCUVf08PpMzRL7rbHGxFCMB64wBIKT79d5G8vA3Y3SDyhQmptjVDRg2/M8=,iv:n9HT+K8+rcbuBeUhDqsUJRVpu9T4w2UTB3ehBOLgS+E=,tag:uW7jYUQ91y991cz1iKNCIg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
