apiVersion: v1
kind: Secret
metadata:
  name: omega-mcp-secrets
stringData:
  #ENC[AES256_GCM,data:/97Azo0Cnskd7tnPf47BExU22mjUTZ0n84fNzgtUlDvFYsftv8F8TsXJ,iv:2YY5cHHI373Zo6AtcqSvj+Pua2imLhBXxQpqMkttyHo=,tag:GrTOUSL6FbMQWDOyuo4pGA==,type:comment]
  #ENC[AES256_GCM,data:JkU+WblMMfxc8FMD1Dz1Db3ueJfy/ssqDlAUMAAn7S1unvvWvLFP0P79AG0EBOoWp89FSuDtaMJIssGefhvr/hmD/YDrUQ==,iv:2soOemU9DcqchgtuPmF608odG8BR3PG0BWdoZcRfMa8=,tag:ITffxOgKV0Q9T0TO2XbyaQ==,type:comment]
  #ENC[AES256_GCM,data:Rg7VXeB7VfdXN9px7CXSFccJnaSExcWhIxwAPIei2Ihvw363cunvesJ0xbu9YEJi8H2jEo4orTJBAHuL76c3dUGln+1KlEqz,iv:GdldCSN+SUpymFXJwOpDhL6X5VrPdfu90FrzBmFaaDk=,tag:cBqCnDpkxuRYAYZyWTozCQ==,type:comment]
  #ENC[AES256_GCM,data:jKpqYAWTrMLVXvLrLWLR0hkOwtsjlrCkbTKCLt4a29B2HmGEaDxYov85Tw==,iv:RfNetgTd2wovlITKuYiYGhTKvfYXoBnV6mknR8z5hrM=,tag:n9SVsEpgWSx6LwBXSPUeWQ==,type:comment]
  #ENC[AES256_GCM,data:xgMmZXW2GxL0rljtsopGrpgj/MGKNAcamSF3J8uC4UD7IlAjtttrTn1pe+AG,iv:rkV5Laius0GuZxzEyWSZSVWnYzDDZx5FL+3iOHCHqeE=,tag:qfdE41+D3cjbisurPzebkA==,type:comment]
  OMEGA_LICENSE_KEY: ENC[AES256_GCM,data:F1yFOwZBR9Cb3/MuDZQi3M48Fak=,iv:ECDIk6r0dzSAssvZzHHaEdPZXQmxxWqgrtP0d2sRp6E=,tag:/gPO7UQzNS01/w498YNUWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WmJjZVF1SXFnZTdEdDgx
        Z2M3aUxiMkpsY2p1TnFENHA1anZNM1VENEdjCmFSbjNhRXFPY2FKQXVFR3hCYVRE
        T2xPb1I5UlJIT2tYR3VBdTMyOGdvazAKLS0tIHFDd0Z5ekgxQjd1NzhsTXpIeHZm
        eDVRb2hKU1RjVldvZE5SRFk2OE5zZUkKYSOGuzS9vFe8y04ofnXsgC3NPTEOoI35
        288pEzULjE4JINCnUGqYYFtfpSTAs2WX6/sUYW29Qukr2ppc16EVWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T01:27:40Z"
  mac: ENC[AES256_GCM,data:cvokwAaOau8z+lJeRtqJLUC7txMG7J/7QAm9v1Ka0D25iUkXlz9SzH7N6ERYfPbXhrCXAFhTTpo8f9AzsjWZBIerpOQqdfjJWW2Rh/ndXIv95eBMwz9zARqDHomzrfgkFx5/gEyTEyuTTHhRWafJfud9kKA9vAeNdjarv4hItpw=,iv:n2SKjCoix6apEVhdZ6v8oBvZzWRprBXeSevo6DoWDTk=,tag:u60fIPB/Koxk9MwWZuNlgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
