---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  discord:
    title: ":robot: Gatus"
    webhook-url: ${DISCORD_URL}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
# endpoints:
#   - name: self
#     group: internal
#     url: https://status.bth.wtf
#     interval: 1m
#     conditions:
#       - "[STATUS] == 404"
#     alerts:
#       - type: discord
