# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MeeuDcom50gFw3WOnT0Cg3uuhRMyACo8Axh5QP70K7IkRNh1YCE1Fw==,iv:cWl78g8cErkMc4jfrxIsJjHRhO/NXT/SpQbGVZIlR/o=,tag:pya/T6+i/H6+gb7yjKtjrw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRWFEYWNRMlAxb1FjYzB1
        ZWlwOVZiaHZCeU5XTTlLaFlJVHJHQ3BXSlJJCnZKcXZXWWNjbnBUSisvMFhBQXVY
        STJyY1RpbDdqNUkwYlBubTZoTkQzSVUKLS0tIFFXZVVtaFdsSGpmbWRPUFYxQ0Mz
        eTAvOEN6M21zL0haaWdlNFg4azdZd3cKN4RBNf6Ffhb8HLhg/pxN9moqpyHpvsjr
        L0bsZPUuCRHiM74sxVpRa5kMuZtcf6pKwUhAn084PtO5ZBnK6RUcHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:0yMBA3aTHoMrTOvuesgxUFzl6x1C073GQEYrZWDSq1NJreY9G+Apt+VEXXahSvqXFz94sFT5o/NgwWTJzdUO9mu0CknFwvrv0SUJvmoP9w6iGKw07UDOP+NBV+B17HJPCI3owWCH47jfd1wsMhH0P3tpahJvA4le9ReGHYe7WFA=,iv:eSDAZSHpoQQI6XdWjjfPUkZ7oEkzfs9IsCrMgAusyNg=,tag:xVqrtYLFiqjVOngPYQJVZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
