apiVersion: v1
kind: Secret
metadata:
  name: kelos-litellm-secret
type: Opaque
stringData:
  LITELLM_VIRTUAL_KEY: ENC[AES256_GCM,data:kFXlhJovaEUEtBzlSFE5UpouD5uoyZE7eA==,iv:9KHUbSlwAxLpZmEX2v8KJ0vDzHIC+2Q1J60vBsvfc90=,tag:qXJDdSYYKCaoWwDXkUaJLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc0pndDY1SUNvWEQzK1Rp
        VjRGWFp3NzhHeloyVGFJblVydDU4SXpQaFhrCkFiOXArQUdkV3JuMUk5b1o2c0li
        WXB2UlNCcG8vamJpQ2VTRVJmUDl1NE0KLS0tIDdqVDBuY1FCeEVuSnR3Z3RCbjg5
        MmZaaTMyU3I5cEZlWFRNZGdlQlovYVkKmKfg35WcWkghEHFpASyVU8e/VyoB2rQN
        uK+04cZKz8Q3xSLkl0IxKRuRydlwvaBkazOHystylRQ07Ey/wpVNdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T14:59:16Z"
  mac: ENC[AES256_GCM,data:TT3O7gcvVroIpu+1nOK08KY7s4+AZbsRZpNtK+qBkQfokFoQsjAiSsd+fgIlUSlyQ+8neHgC7RooCC4La+3UG1YihVi4B1Fkt2x+YHUbC63/dmXKLSt/ksS8DSwVCEZNENR827OzILh0xx6QiBxjRQJzDAyo7Ujsiwf8rcph5xY=,iv:+BtS5shAgwSy26JIwfKt1JIVMgZqpuuba00Rrg2m4zw=,tag:Q9p6RRbwgzfUdE7uPr4o5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: kelos-github-secret
type: Opaque
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:gyWkh4sBlA1vyuiYNDneyrOwGaJKn1qYT3riqltgm91v/ZfRpLqcn2qHIQxuHOvrayBRqtERXmQzZin+Do7vufN3A4rspBxEaFnUab20hdIZ+fHmCIF2w15OnD46,iv:61qcU3eSYmaflTDhBkfSK7HiCytTTY8SOnkOi7gboaE=,tag:T7W5FcGdmWCltsoOCwmbAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc0pndDY1SUNvWEQzK1Rp
        VjRGWFp3NzhHeloyVGFJblVydDU4SXpQaFhrCkFiOXArQUdkV3JuMUk5b1o2c0li
        WXB2UlNCcG8vamJpQ2VTRVJmUDl1NE0KLS0tIDdqVDBuY1FCeEVuSnR3Z3RCbjg5
        MmZaaTMyU3I5cEZlWFRNZGdlQlovYVkKmKfg35WcWkghEHFpASyVU8e/VyoB2rQN
        uK+04cZKz8Q3xSLkl0IxKRuRydlwvaBkazOHystylRQ07Ey/wpVNdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T14:59:16Z"
  mac: ENC[AES256_GCM,data:TT3O7gcvVroIpu+1nOK08KY7s4+AZbsRZpNtK+qBkQfokFoQsjAiSsd+fgIlUSlyQ+8neHgC7RooCC4La+3UG1YihVi4B1Fkt2x+YHUbC63/dmXKLSt/ksS8DSwVCEZNENR827OzILh0xx6QiBxjRQJzDAyo7Ujsiwf8rcph5xY=,iv:+BtS5shAgwSy26JIwfKt1JIVMgZqpuuba00Rrg2m4zw=,tag:Q9p6RRbwgzfUdE7uPr4o5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
