apiVersion: v1
kind: Secret
metadata:
  name: kelos-litellm-secret
type: Opaque
stringData:
  LITELLM_VIRTUAL_KEY: ENC[AES256_GCM,data:wdQ6KfMB1XlYMHbKvOlcIhrY0OUzgQiYVg==,iv:XJva+KxMzELKfauVedjD294716N1Ha3MSxRmQv3XkHY=,tag:vXOtqtcThKyuZZbk68SA8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjNVZm0vNitWQWlydFEz
        Y05RNW1DZ1VjdXg1Z0FDeHZMV2NsUUVHV3g4CkNiNDhKb2grRm5GSE8vNGFwdmZI
        RHNkYVJyRXBjMFZrbGVqMXVsaTU0Z1EKLS0tIDZVeExlUFdHaG15YUI2eG1OK0Rx
        czN6akI3TzRzcDd5dWlmOVk5R2Y4L28KJXsS2LGgV1hZrzIbathswsP26qZhfEzN
        7M/Eu4kbDMV45/b5aluhaR5e3aKfa2ffoEmPVWqP3A+jNOLcX3CmFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:36:42Z"
  mac: ENC[AES256_GCM,data:GyOOq3cD5NOyvjgTArE7djGYBTDh9MruGz/QspkPTKjQMyLZpVljM1Mn9JahfoZULQ1TT7eKLNcSvnQ4/Ypt+K46LRl4TUmiAHocd0DbRXA1BAyeqaZKYbDoUMWuij1lZJIhj9POUtLhJKZfntB9Kq6S8mZ0DGCnloBjTwZcId4=,iv:iGcOFo1nq7Wf6QAxTLRBZXgfUF4/EFdR+nlK+kBHyss=,tag:rSWbsw0bo97hliFhQ7kvJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: kelos-github-secret
type: Opaque
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:aZ9rMSAX6k/tPxEzrCB/QkNP0u/2IM0Tn9mvyjputc4DxfsbiB/AZYLmsRBewzczyuuWSL4+e4gVNGPWcL2FabE4P0w0PwuB9C2NzaRbj/IW37SQKstO3BBWFsKA,iv:fWwta39DPL5nBo47InIlrpdXe5EM5hV2pkUBhGDOzRQ=,tag:8ZxJ0g/5G1CTVJ3T9DEA+w==,type:str]
  GITHUB_APP_ID: ENC[AES256_GCM,data:V1JAqjgc,iv:+dRbifRZuNH8UErsNShM4/uawRQk+ZVFa/hyOgxZ3kU=,tag:iREBiDLH0qNXmrqZG3mXeg==,type:str]
  GITHUB_APP_INSTALLATION_ID: ENC[AES256_GCM,data:uEEJsgIJvKA=,iv:EGUqsz6MiucxEdkAgNEND6PTQ6BQUHRSEV6iCkOMvpM=,tag:QLUbuW5GsnHHohz5zxP2nQ==,type:str]
  GITHUB_APP_PRIVATE_KEY: ENC[AES256_GCM,data:AB8PmmlHu7wtBiL4NFHBRDtHQrltvAeBTNlAz1wLEI4TLwURjkugMwDDiKYSf4m23vDcovcnrkFsG8Z8+SVbXrz12NLmyV0ePfBnG1vxN2phHWrG8HzGqA2XBczjyrR4u3kLS1hIBLJt0fVyM8er6lFLwqR5z+sjxkkX+A/frkuiwiRUfdNKK2TMlFcud+30+4if6XirjzzckKgRHOCziilyWcwFeQWTkiuEw76Mjychn/WECrVzFAchFHv1fR5vuMJlPJPDvMLx4/6tGHaaOi9+iIO3cKI0NBaF56sjsDmiYrPo9yh2W6f9qEwfQ5V4bRhG4dUzRZ4jGkpWFzuQkEV1plBMEIrCmZUPxYGP+NGG3gIB/dMXIfWNvSIMMFxYPr9gijAgRAs/QT1q4sX8nSYP1LezhfpJgCGtfG6jQtBkYbGpJL3SNxI0+sw04EZkIoiVT+OXGvodlSMHd6O4Ns4fnTBq5ymGe+elAv2pu2dEBh4/HvFhdpwvBer1DvGcDxvz0Ar0W2xXeYv4skTy35tLNjLus2UpIyG7JFa1xfVnp36+RGCPZ3WQelhmFton7eyF6+xtpJvR1WaR5f02jDaevTpJozN1u+t67F5Xe1wUoNrOxc0vtOmbCoNXTnHFIO3FTQJBO34kwvvanss2F7pGhvxt87cazRWQbWsFfsDQXY8oy1L/QCjPjAcNqCfPCV3uby0VTXZFAKD+LfajARzb7sgIVJntoUVgL1VBTehjKV5gWwT8hwoOED413oP3CMwRyztcFPixEJ9gNmL+YKsl+JLQeuIGCe5p3pdbad1nsYPcFsTCuztNvck1H3VnBHybA4+YYTF7/02fxiqBEZQfEzDWKYoOl7SjtMlu+kzyYrpYS2Bg/to4ut/ehp3sth8YjrkbpPgQgpgWscFMcq9mpJ1enn3EmavbdxC413wJYI0MiWhb1kumhLBrhCKHh6aelBgCKCKk/A/2QwRBvCQRo/kOr1qT2JnDf0xMPWJ1cm/2ndQyk7409sOVB4etEttpsCue5aaA/LNsa367kxK/EdXc7VzgsC7ZUvG24EhwkyXwTtS5xRL6Jd5Y7okFBEx48rRI0Hs/skjBEin7Y3E0JOsV0Iq+im/aaRgoIO2CnIksqPInD7amTMX1rE9hN3MRIA9CRZQZulLq2s2ttw0zNSUaEmV3DEdmvIsLkdeerGuGIEw4k58ip1MpJXtr7dlP+mY2V9yjEiaiewOzX5M3l7AahpU0UD9BT3g4o08EjNfYBdNVuOG/02X0wjYxFHeQpAslMi9nmRK5/1M3xHzUELXfLxX3cJa66Vr2xTg5OglOQI8F/KgWZ/O61Udk+kwOdVvDvV6tIqy3JwWey8obhi2Ugu1UF3tHzp2IQQa92cqq4R+YsAPr739xZYuvMU1akm1dR0Hu+G3n2tRwPFIWeogcxPLoKQyjBH+ICk/UKoVVILiWbDspksNYwRkCWSsw/xjtz050GU8eHGYpFiNiM/089j2P5BfLZ1RvG86hPoGxHDUy3jS9xz5vefra3YvUHw8DHqM/x/BT+bI+V6aRfmqcFTOsT5eF/NVgJpj4/lhJiVery0x5ix/3NgQ3wn/X/sk+ViPEnAo9beUfx2YHps3crrYyq1X4CtlM98fi0TmaHkG4lWgw2/0IAIIok+cO2/WHxCcnuec453H2ZNRpRj9AkljXft4CDvpdo0ctGMiLeHc+ZhBNee8eFjzOVvYFeLMjeCrR10AvTVLUexmoXpcoADK1LqEClgCt4H1ybkxmBHW1F3lan3s2K3wu9qcor1rXkHGG5FjQ8vEs5qHB2rb2+Su4nKTS3zYc33AgYPpfRvbw5D7g6MWw/8b7T6ssDsRworfXt1AlrqGwBJqDkq/yd9xEWncRXcf2oclwTRif3z4K6mgNZKGINUmn0Y6wm9vWYamGnrGesISDCRlGyH2mX2oWu2a95qgmGquVTyIlYP6BZqsf7StVVTGCIjGzq2MyftveypdCEVD8puIy7fGYYWfr+enIymErQ7EI8w3c1+L2vI/zZ7IBNMNJoLQfTOMd0QGBZh8sJF5YtgeLsLerSPW/uzxPwpABZWRJ0GgVjxFIUO37KDIDlAf6+6cru8wnHbNnhWxPCtSTt9QxkLx0uB6xT+QJJBNzZPm4dGgsUE4e2Lee0fC/mX1zXhJHPqZn65pmyMDbWkyYbUqvb74u4O230FTtzJ9VnFJ1fg8lf2fgclh74g==,iv:SjL/65bS208HQ32XQijx9sP64SX8/g5Sw4Cz0ydQCpA=,tag:ta+C/TOHSR4kwjHomdemhg==,type:str]
  WEBHOOK_SECRET: ENC[AES256_GCM,data:/EnaIs9e8MKjnByAAxFfU6BIG3RdYvH1zghk5HpvQiPXewen1dSTdhd/ifOHGsWmL5eU8MkUkL35CiF/su/YIw==,iv:dZYGdVKueuL2//ubom6B+Ya2I2Em/OyL7LsQ7seCkTc=,tag:0ijx2kk690bnoGcIhRROjA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjNVZm0vNitWQWlydFEz
        Y05RNW1DZ1VjdXg1Z0FDeHZMV2NsUUVHV3g4CkNiNDhKb2grRm5GSE8vNGFwdmZI
        RHNkYVJyRXBjMFZrbGVqMXVsaTU0Z1EKLS0tIDZVeExlUFdHaG15YUI2eG1OK0Rx
        czN6akI3TzRzcDd5dWlmOVk5R2Y4L28KJXsS2LGgV1hZrzIbathswsP26qZhfEzN
        7M/Eu4kbDMV45/b5aluhaR5e3aKfa2ffoEmPVWqP3A+jNOLcX3CmFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:36:42Z"
  mac: ENC[AES256_GCM,data:GyOOq3cD5NOyvjgTArE7djGYBTDh9MruGz/QspkPTKjQMyLZpVljM1Mn9JahfoZULQ1TT7eKLNcSvnQ4/Ypt+K46LRl4TUmiAHocd0DbRXA1BAyeqaZKYbDoUMWuij1lZJIhj9POUtLhJKZfntB9Kq6S8mZ0DGCnloBjTwZcId4=,iv:iGcOFo1nq7Wf6QAxTLRBZXgfUF4/EFdR+nlK+kBHyss=,tag:rSWbsw0bo97hliFhQ7kvJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
