apiVersion: v1
kind: Secret
metadata:
  name: kelos-litellm-secret
type: Opaque
stringData:
  LITELLM_VIRTUAL_KEY: ENC[AES256_GCM,data:kFXlhJovaEUEtBzlSFE5UpouD5uoyZE7eA==,iv:9KHUbSlwAxLpZmEX2v8KJ0vDzHIC+2Q1J60vBsvfc90=,tag:qXJDdSYYKCaoWwDXkUaJLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc0pndDY1SUNvWEQzK1Rp
        VjRGWFp3NzhHeloyVGFJblVydDU4SXpQaFhrCkFiOXArQUdkV3JuMUk5b1o2c0li
        WXB2UlNCcG8vamJpQ2VTRVJmUDl1NE0KLS0tIDdqVDBuY1FCeEVuSnR3Z3RCbjg5
        MmZaaTMyU3I5cEZlWFRNZGdlQlovYVkKmKfg35WcWkghEHFpASyVU8e/VyoB2rQN
        uK+04cZKz8Q3xSLkl0IxKRuRydlwvaBkazOHystylRQ07Ey/wpVNdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T18:49:37Z"
  mac: ENC[AES256_GCM,data:jN9E3SLuMbuaecD7nxTEamVFnbCGL2NIAgiB3oYKXOSY4XBodprLhCqaKj9gTJWdYdSFAPRfQ0LYEVqNcEKWUbCiRVybW56dRYro3Knz+CtRy3yMfKDq9oEifS/XvRnR4prKZpHHLyZZChOJMgok0OC+aEYed0+jcKus79+6UPk=,iv:ZfkFPLFLAIk2/UGl50rJ7t8sVA+w1JGXPJV8S6gNk2E=,tag:4amfpj3dDXRcxNjHj4pscw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: kelos-github-secret
type: Opaque
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:NOqM9x5kWTdZGo5RG0/vdsX19N7H/58ZDK6Y0Oan,iv:myrw0Nw1dmL7QHgdId0XpZbGA4Aui/5lP0iN23Xt9f0=,tag:6czWhKC89arps/pk4jpGUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc0pndDY1SUNvWEQzK1Rp
        VjRGWFp3NzhHeloyVGFJblVydDU4SXpQaFhrCkFiOXArQUdkV3JuMUk5b1o2c0li
        WXB2UlNCcG8vamJpQ2VTRVJmUDl1NE0KLS0tIDdqVDBuY1FCeEVuSnR3Z3RCbjg5
        MmZaaTMyU3I5cEZlWFRNZGdlQlovYVkKmKfg35WcWkghEHFpASyVU8e/VyoB2rQN
        uK+04cZKz8Q3xSLkl0IxKRuRydlwvaBkazOHystylRQ07Ey/wpVNdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T18:49:37Z"
  mac: ENC[AES256_GCM,data:jN9E3SLuMbuaecD7nxTEamVFnbCGL2NIAgiB3oYKXOSY4XBodprLhCqaKj9gTJWdYdSFAPRfQ0LYEVqNcEKWUbCiRVybW56dRYro3Knz+CtRy3yMfKDq9oEifS/XvRnR4prKZpHHLyZZChOJMgok0OC+aEYed0+jcKus79+6UPk=,iv:ZfkFPLFLAIk2/UGl50rJ7t8sVA+w1JGXPJV8S6gNk2E=,tag:4amfpj3dDXRcxNjHj4pscw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
