---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./dragonflydb/ks.yaml
