---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name home-ops-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    githubConfigUrl: https://github.com/j0sh3rs/home-ops
    githubConfigSecret: home-ops-runner-secret
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-hostpath-fast
        resources:
          requests:
            storage: 10Gi
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    template:
      spec:
        serviceAccountName: *name
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
        containers:
          - name: runner
            # renovate: datasource=docker depName=ghcr.io/home-operations/actions-runner
            image: ghcr.io/home-operations/actions-runner:2.336.0
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
            volumeMounts:
              - name: talos
                mountPath: /var/run/secrets/talos.dev
                readOnly: true
        volumes:
          - name: talos
            secret:
              secretName: *name
