# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:IGLQD0/LolRpGZCBJWg3Ink/GFfrePf0ZakDCH6d8A4MBC1HX0DUir2d4vxmX1Xr391FniPwQ+ovyqvhyntuC2KRNznguoFe+I2pOIrGcKbtsjMSaOon7OBzveNRAw240NL5n0Hz01n0xHHekg2b4tvrgY9TtW3rMkW0RKXeeUmsTwsPk4YeYNIDQKnVMz15lqQHZ2rY/P11jXtww1TCfoh36DDtcQ8jbI+KRfTx10Msm2cvilAVqxm3gdX7P3yoK1jBzhO/LJnf/xDOi4tKMXVezwmDp38bh4f1CRzqBJk0UAHbg1PoJjOvJDQa,iv:nEacJ9AdyXuCEM7Omw/JHgoRtGodTe4U4pWHBYjQkkk=,tag:TVA0QCoXEur7aaiRCp7xng==,type:str]
  ACCOUNT_ID: ENC[AES256_GCM,data:GYTd4ARrSgZTYcgma1vcgv0OZnYPZM1gIZjzxSW1RCY=,iv:2hDUEiWtl7ou55Dnu3BG04XGlHtffN2BtfNR+7hDdOo=,tag:ZV9FxmU57y/pcTfgbGgWwA==,type:str]
  TUNNEL_NAME: ENC[AES256_GCM,data:+g1HJg==,iv:z+fMuev9e2BU9DB7e08Z0/giKsqIvFkxxhy5zyOtESU=,tag:c6tZtOgaN0UX1gflG5QtYQ==,type:str]
  TUNNEL_ID: ENC[AES256_GCM,data:d08gslmQKTKdhrJT0hbu0JDSSW3itqDNqbLAU9MFjoMCBsPq,iv:0anja/AIaS01X3+d2hGGO+50XXXticItAWiriSKiW5M=,tag:thTsbNL4STQ/EDm+jguhxA==,type:str]
  TUNNEL_SECRET: ENC[AES256_GCM,data:PI1xLTnNigEHAlTaP9pZSYUEEszrk+563OkWWDC2xYX0U/2cp/m2Iwqq1Q8=,iv:lCYDYgWg26WKn91mMy4yhp1FsV5Qd7+arOQK6nouSGE=,tag:fR0BfU1SNFSijR8XiUU8GQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUFV5aGhrWHd5OVRSYVl2
        bGxHMmx6a0xxV1ZabnNCaXJNQ0hEbnRQQXlnCnUraldwV2xLVUJQSkJEbXBUUGY5
        emRwTjN4alFqdFlIUlFxRVRrTllvaTAKLS0tIGtRSU5iSzFCVVJOakd1ZXlkQUJG
        VU1obm1iTk5weUxBdGw3bmRSSkRxZFkKWCOFDETTjF4zm2/Ve+Xfrbzbjfx44TLS
        d976ciTFd7QTIeF6yjvhtlaRQcfnyncGdL5kFyzuxS3BB1pGkIEnCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:tBI0c0k1VTZIlN/sXyIwueEuAkp97sZnsh4f/VrxP9rp6idAVMwdje9WnxEmO2d7Tn1wEwFZAc84VEBuSiBgvbI3ZqCODTTP/QtDHgP7HZ3XW6qHkdIKfARpGuOvz8q0p8BjjkgL4W7XGLGC4EN31gSSteeZpgxKKA2/6Ag5Fmo=,iv:smEwhL6UEtdzTBoP5Mdk1RJX+eEMzl5E7hYksQmCQ+U=,tag:HZhTPhs27vCMuJDNjXP8qw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
