# All keys are injected into BOTH hindsight pods via the chart's
# existingSecret envFrom. postgres-password must match
# kubernetes/apps/databases/cloudnative-pg/cluster/hindsight-role-secret.sops.yaml.
apiVersion: v1
kind: Secret
metadata:
  name: hindsight-secret
stringData:
  postgres-password: ENC[AES256_GCM,data:U2CxM2mS6V4t53qSRrUtyes9x+vId89sxQaut5E4Jey1vSkKLRLO3i7gpNKIuuAk,iv:8lmzk0nhChUPZIxFHyLghvKUUPyRoUbSZww2TbVz5vU=,tag:XPbL+V51aPf+PD76WoZlDQ==,type:str]
  HINDSIGHT_API_TENANT_USERS: ENC[AES256_GCM,data:sqG/qTfxqdQ1Q0JP4TBloO/5FOJ4dvbdQNs3lbfWMb12CozoEu1fp2A9eN164AD006FzWt5la3amS4bNV33ZVP73xm7Jmfwv1XEl4S29b7aL2AOOhGwNAH34atfj+1s8ZK3bg1U3sMEmlAxeWOEIZ74GjaotzCgixqUeb/bbqaQsCqYBeNNEXxz6F0A26+8OL1FMZFneFwU+/VubgAj7Y/5QPj0DOzAlk/r0eA7X8z6mmAGTssWgNvNk4gpPQx5plHUQ5wKoru/QFpF1QlViqYiUtQMa9I9EjUyZEErm96raYa0iZGcAVK3/UAEG5XhfqRCbIKt+CKmIT+V68r2+ekv4CWgnqSAX/PLosE2QSdYjs95A4+Anh7F1YYhUAsXpLe5cAf9lHQA3KajflOnfkRfYo2oU2Sgnk3h7yAvZyJbdyThghFP5Am0ifag=,iv:SxTpEvMKBiqhx10TG1QjZXONAZchdumZ2k5Fx0kQZwE=,tag:xrQ0KKD4q9NcgOkmCFdSIw==,type:str]
  HINDSIGHT_CP_DATAPLANE_API_KEY: ENC[AES256_GCM,data:C09pLIuYQ97O8Qk2k91l4/HOkemdvH1D3ITi2amZGhTR9EjqrxvNmiiMFQxu6cNYeLDLmuDnPeXWKwCxh1D5tA==,iv:y2DgGDXnXLSK8vl/k9JYaVNT2HRCkpcS29/RzFoPf+A=,tag:sR1kc0tiJCboTmwGPB08YA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQkxlbW81d3VVbzg0bzk0
        RDRzV21BbEtBZDl5Ni9zdDU1SGhzUTlnUmhJCm03VGNoM2h2SlV1NTNmdklvOVYy
        cFpuRjE3OWRRdDhuTk9xZ3prVmE2VUEKLS0tIGt5T3NIZVFjdXdpMTFCMGhkTERz
        Q1FGTEVxWXdlcCtudXUwalE5OFRWczAKeCwIgwz87jyckszlmtlZurpiCfvEQfXf
        5eaJNMLeAQAcykUeOPPouJg7L+GDvapMAiXviCsBTEf4smGftKSxZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T21:10:54Z"
  mac: ENC[AES256_GCM,data:5F89YLqIiyzImPH5ztj32YSj+SGFV3cW7IUgwh6LHIyy3DLJHdFQbqMUiA+Jz1Z0RhqBAWC6pL8EBwCsh8yRZyQeHY47wqh1K9aLuYwzTUbynihs2rvVSMaGS3efUlVEf1IOcgP7SSj+lZA9isBWJzNUO0wDT6wS8HSf7jpsjgA=,iv:rjFuMMXcv616FVtLqLbgUJMu77LfwXuIjtZ23q9kJbo=,tag:b+ackShzOv83vjYQ2UmDMg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
