apiVersion: v1
kind: Secret
metadata:
  name: memini-secret
stringData:
  #ENC[AES256_GCM,data:jO9XsmuUWxXzx0HtH0VkFYLlp2LbdTdIeBh6ZHWQP9O/nqiaBraJ5ufmABC++nYoaaTZuG+gl/buRyxqT3W7gaz6Xce6,iv:dGAum1WERTOcdIVEW2w8n+zeS5XmdTivpQqHciXWk+c=,tag:2H7m9dq0Rp7wJWi6nv5mzg==,type:comment]
  #ENC[AES256_GCM,data:zeTiKyPyEhD4FJZcVZPjISQN6Aa5e5wj/Ad3xRZ2k6Nj6mywPmYmfY3Uwww=,iv:NE89mK02IQ5BJ3oUxJ28BdvlsQBw1fdP6cQGg7mDsLk=,tag:w0r0/G5Z5zIuMWgze0/6Zg==,type:comment]
  MEMINI_API_KEY: ENC[AES256_GCM,data:KOWGL9Z3JBY=,iv:/jMpqEnenxaVYuSwyM2AmdvRK1kLx8rPWLFxGVjaltI=,tag:bdfYut2Cjkm3aQJiwKJVdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK2RYdjE0NklrcGdoL1lN
        U1B2bytMem5SNUMvaXpyRk04SEZ2QzJoaXlJClpFd3d1bHZzNXBxQVE2Ry9kSHNr
        a01ZaDN0MWtVRk9JUDk5VlVsSEE0QnMKLS0tIEtPejZZcXBGdEkrK21CcUlGZ0c5
        UGw5MDFjclQwQzNDc1hqNjRZYmhIa3cKxWhElidvEtY4ARjuFQ5/oaJ2M81vgx+d
        rjhSFx7hLZX9rB4E+EQ2SCoOlpiXPbKS0nDd9fSaSqYE5Ed3ehAJtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-14T23:44:02Z"
  mac: ENC[AES256_GCM,data:7EAt7NfXroXIAcGXlqv2mVD5F/4Skzxvsjj/cdhoC3M+Qg8qduiSxZAONLHYmTJ4p+013nIJpecrfSbky59SPZpt3YpQj/CVwBUcMWBlwEkY1GU2YmWcxG4eYrk0dOb03HNPpMKBkpHHZ6y3k4V05JqUC3D5t4e/peqaNT0WjJ0=,iv:PJdvxurH0/4iZ6rdD+WxEq60Dhv42mV7XCyhX2VJlGs=,tag:4dr2x+uO4z3h3qA1JrOY3A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
