apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
  namespace: services
stringData:
  passwd: ENC[AES256_GCM,data:PKFAaqYKUj16F1uX0iukqSdotFN382EAaeGHJjjN7dsVyX4FuIqvs9cr6euH5KuyeIcudiH4JS3r/+M5fnaKMFNDluwwucJIcu7qml8/kYh+9XzDNkH0jzitPlRUvIUnrSTFAO+1AwOv2rCGc6ELhIti0vsmy6zu3kf2Z+M62A==,iv:fVAaXhUxw/1kRCXnFTguXu/z/LfZ/CnCbW7bla7Td7s=,tag:UHSzJh9p51BNDUUxHHnVLw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc2pSRXBEMUZ0UXp4Qjll
        WnN6aWxxaHl3TEg3UWdQcENXL09qMFJnN0N3CnpGL21lc0hkcVR4aGFLWHl6eEll
        OWpoKzhkZU1OeGVqcFV6Wkx6VytHRDgKLS0tIHlEOWpxREVqUWt1U3lQUGNKd3A3
        L3hjenZOdEVuZUNENVA5SlNON3EvUEEKrbme0lJP7nLkOvALQKiKeSqHU8QG1k9+
        aIv1F+Yz29M6dlLFA++SMj4L7QfHDs+zbwk0EWkXl5pwEUr6N155gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T23:13:48Z"
  mac: ENC[AES256_GCM,data:9TKysrL13cqDjC4jiIbuLWkwCTpvtV59l9baa5CyMFHf8JDuo4pGK4kFjy4p19bt3KQzF+gedgJBBXMRSjhHMJz7ggHkmwOjv6gRNGxMfagbvdrczu91PxSQct2ey0yF6rewXd6FDg77CP0vIxohweoiXQdvmRf/Rja3M9wYMwc=,iv:T36FwSHZPfu6PRFmbxMJVH0NhnfRlqWydk/kVS74qz8=,tag:YB95Tb19y5YJ37dXJG7qhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
