---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonflydb
spec:
  interval: 30m
  chart:
    spec:
      # renovate: datasource=docker registryUrl=ghcr.io/dragonflydb/operator
      chart: dragonflydb
      version: v1.25.1
      sourceRef:
        kind: HelmRepository
        name: dragonflydb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    storage:
      enabled: true
      requests: 20Gi # Set as desired
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 2Gi
    extraArgs:
      - --dbfilename=dump.rdb
      - --snapshot_cron=* * * * * # cron format
      - --logtostderr
      - --memcached_port=11211
      - --default_lua_flags=allow-undeclared-keys
    tls:
      enabled: true
      createCerts: true
      issuer:
        name: letsencrypt-production
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      spec:
        - alert: DragonflyMissing
          expr: absent(dragonfly_uptime_in_seconds) == 1
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Dragonfly is missing
            description: "Dragonfly is missing"
