apiVersion: v1
kind: Secret
metadata:
  name: netdata-secrets
  namespace: monitoring
stringData:
  PARENT_CLAIMING_TOKEN: ENC[AES256_GCM,data:zrnlj4YFAabB1Lwd4KBEcT/YOvZE7BQZa1C2WwZMPzo6XLP0Db2leyYt/OcNUI8eXnL/Zuv2pS9GCO3kv7pPMfMRBMV+CLsSUlc14rTHIaavCt/vE8xAIwED9adYQOAJmOoA1afn4TKo9/0NuuaVtRPKusow9/s+LrjajDixqW/dds4CoSmt,iv:zxAIKkqVHLmXNn07h2jTUwp/8nQ1+YPnwxOaf+OrX54=,tag:N6pC315nDR+hCYTnVXB9dg==,type:str]
  PARENT_CLAIMING_ROOMS: ENC[AES256_GCM,data:O4MKOMrFei4Hck69vFX7wES9I8DCTwDVWN9AKk86LcZMF4ce,iv:jL2HQRZ5XbtZG36fpfrI5gDKKn+QBWpkZamoHBOZQb8=,tag:42I6JZJ6fqO1u+gQ7s4Rtg==,type:str]
  CHILD_CLAIMING_TOKEN: ENC[AES256_GCM,data:AivfG6O+75YYz11HOgdSjhpoNrJLS2NYzgdG3LSYb+ClVFoYlwUILeAhE9PqFRp1p1cbfm7IxRixbrGpvSUI0nulcC7jV4TyaHhBYWe+rSt41mcHcREjmmLEtWWkTZOzc4rzhfYt1gUtRy5/YKhvhbAgp24C4LoxABz84qiofuxnTgwGER3R,iv:vOUAsoHPCPcJ5VM0A2f3xBm502qELg47SiaSK1CCpSw=,tag:XYVB7x0dW6THhXSAWYgYnA==,type:str]
  CHILD_CLAIMING_ROOMS: ENC[AES256_GCM,data:hb4HP+WbIWyKgNAWMAmTRyyp1x0meBObghCJDkGl54wZBe+4,iv:TFLZRyRbeatyju5jKAbKLYhB/Ql9qbFBTZ+Ubj9+qIU=,tag:XfHB36mdu9JRGMiI77jThA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VjFiZlhlS0Q4YmxEVTFn
        ak5RcmJjaVQzQUNtNFlGbEsrcytuRnU3NVNvCjkrb0tMc3RHNGljUXJTUmZHak5m
        SHJSc1pPVWxKOUJOUHVpYUkzSzJXNVUKLS0tIHFObGhuYXY5TUd3cXA5dWxkZXIz
        K3Z0eWFlOWN5TS8vY3BuZkJ3cUxJWHMKKv2ZzD9glpiZQ69XNkEHF5hRPAzF4A2V
        Zy/L8Zv7pNOWWQqvNsKLiMWEsSJHAJ2wArtvEJG34ZZSq5bpidAMYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:EFm21QvZ7zLhhEJLD21CjaWvFzihRed7iV9mPNI8AQ3Y/DHQ9GX3lglrU7bmeBtwGXg+MmHluzDggDQ250oDQ2bat0rcFa58aJVERXbF8bAoGT2z3j21v5o2AShE0ZHyeEPoocgdVbz4vYllB4z8AWS/oS91UEynKChAvEpPADM=,iv:rnnE5cp8BZKM3JTcldwbRO8s53Ay8OZe8EUWXj/R4PI=,tag:+E3Jrb/46dKzYiNheV7wAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
