apiVersion: v1
kind: Secret
metadata:
  name: netdata-secrets
  namespace: monitoring
stringData:
  PARENT_CLAIMING_TOKEN: ENC[AES256_GCM,data:ajXmb+ppkpS0qDELfFdYP/ZNwgNG68rhVSrkrF2p2Nqy1tqpwLygXJZgwgLQX7HrroubsRtRWgC/2obVoQq5cWi4Tiytcy86rI2ByqJjoruERsrXe6szGy7xuEbGz0jUe1BpFzvq8WoPnNLjX7Bm09plJdIc4IC+GQnvcoJfkKvpTF3DDo2j,iv:omeAcNjwvWQV5DgYv1qrUnk+yRslOyeefIlhKHWu/wI=,tag:LdX+SKQISDW54/PvY1GKmg==,type:str]
  PARENT_CLAIMING_ROOMS: ENC[AES256_GCM,data:Et8D9IB90pZHrLVphj00t6jSVSDm3ONvASINrlMl/JS+8Jzt,iv:kZlb9tobueB6teXRSNkSXiNc3P45H18OFMFdT7zRicA=,tag:YZ7eMDpVe5XUZNlnj3d6og==,type:str]
  CHILD_CLAIMING_TOKEN: ENC[AES256_GCM,data:+ZPxvRbyz62f+pc1mocgy0v/orIaLSgNdbZzB5aVWnW541kV0j6rem94L7pkPWIOjMRTx+2991/Zr/Npfo2p5hItg2JexpHhZ+C7tFhBX4ssiFwE8etYs6KhzEMUPPDbCQ95tHUByIGV6NoO9latvqK28hOhBmt9iF1uRyFkxBa2PT4FskX5,iv:pj6EXIZfxM8U9HqQkgO5G/PkpYTyQe6PKktWgoCKgA4=,tag:LneDe166NNYFAe++0CXD/A==,type:str]
  CHILD_CLAIMING_ROOMS: ENC[AES256_GCM,data:z7mUYYlcSB7l4Nj3AxAM0QZlrlbL1L5zhSIlIh6jnqgtiBWI,iv:kBa67iCLEk2wpY0lJKWubOvTWo6qZRGt35WpraBxBm0=,tag:aZU9tkabjhw1zkqSx4Mx2A==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Zzu43ryD1FZsDW/xAhYlJ3N+GVeb7KxYOR2vhFyf1fFz45ldA0BoAyB7fnT0PFYszxDmNm+6jXltNMQA6mKETG0kN8tH9+SYVALNsk6ZfCZTYraKpJTgCegP3S8aT3zObrg5o7pjKHYabN0uQp/6yL3QdDIu/siF,iv:ZnzX2MSOhweDecNiQ/Xf4mRjGPtv+57lbb6UL/eeCRQ=,tag:ta5FmBagMVbFSzMhGLL9fw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUE5SUUFDVXhGQVdJSGFH
        bUJ5Y084MEZpUHgxdEZINm1zY1lwSUFtQUFnClJKL0JPaTdMUlZteWNjaTVWTlBw
        RnpublRSSlMxMFcxd0U4UFBCOHJMOUEKLS0tIG9wd0RoT3hNcUVHVGZLemJ1dTlD
        cE1UUHYydDNwZHBMQUxnMzZwcGFaSU0KifNkl7T4afWOymel20OkgP0KbeDmMlKo
        uwi2HjpsXO1ETE3MAEiGrRPLod1KN2yoKuUi6gc/v5mVMSjl2v8JzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T18:37:11Z"
  mac: ENC[AES256_GCM,data:Eb/ztu6vKPK7fk5X/QiYyMsIjcTMeipbQkF1QpJXNG4lOB3vW6MqPNeQQabZeQueGxz6BfVFBMEeMJ1mvaUDU5Z9nTgP8vbjR+bTydGqDq4LjvWdJlNTbMsGAWy2oSb8CDwvoVTdBLHlN+dTU7iycXYO+dchYPOfVhSqvgicFHc=,iv:iq3V/SdhfwqyO+7imKSZCuUhyQ0mrl0QnX+3HYKYT3k=,tag:jX+O2fevSbNwlNt3MY9A/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
