apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ShraGx8P4Ho/6g==,iv:GC44VPBv7nZpNOShLz9Ot/yFQG152dQM0EC+pjbeAsk=,tag:rX1qCi8zhpo5RQkhyQFumA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:UIM0+oLotCGS3wsgynyXkgfDmdieEmRk4qZcpgBOujkFtikWMlEk,iv:tWKDo1e2UmZ1oXXUZPb4p7OwD1zC1L0xSsMLBiMqZbg=,tag:91ONC/or4IcgPvH+EcUFOA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:2blyoXnorQ==,iv:j4S6fRh99uCkWcprKRJZqzN8ARH7wHJSJOIoFxlo+lQ=,tag:7oz79NN+Fvs/dlIYJAN63Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aWtFqr7dQh/aHaaEF+nEkxbarIuDpG4upqE+VSBamEOU6R24DFEc5r2zlFXVIIbUHbcdNU6pM84QnQ22+IRimw==,iv:G6wZVtBWXZUX22aW7YI3nH4zkuZJT4IF3kiWSzocZ74=,tag:ee1XR6rNDxpZ8pp8AcKwjQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pFRtI4ytAaM7G/Hjrjs=,iv:QIlZaiTEp3SXlCKSej5/Ti9E6j6lqqX89H3Y1n4nb0c=,tag:6b0ROUvK5P42Mipjb+vXAg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:uQcbvtbbnk4=,iv:feAqVNOqCB8blQCgK4EwiKBIrRVkogM7XMX5h4fZrfg=,tag:oD8vFPcVPg8XY1MTa0CUqQ==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:jmjg9yA=,iv:YoJS4IN3rrR4UlLy6Lu3PlvuAgzq1YGzD9DF6Jwoh5k=,tag:v7GIffBV0Ow+Lx2WM9aRCA==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:F9zNq12mtifBtjAFXh5P5vmPWeWr6ntoz6GpZpquavRb7UQih78BnN9nR8dFYp4PW5C1Zr+lZNgyO4ntJP3jt5XH7a4I19w+FtZP/rMRl7naQwkwCd334w==,iv:sSmb82UPSQyaxygALFAAS2Xg2gr5/i3ddURf5PBDr1Y=,tag:BjJ3z6mYdXFacmWK3drgnQ==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:kqAoUckz22YG9SziOPZYS1MXag==,iv:dWHrGzb+z2nGIxnGj2JsC8VEBJ2bqiHfr9udxTbFEZU=,tag:vRRMqH5RKXJN3VCAnc1aPA==,type:str]
  APP_URL: ENC[AES256_GCM,data:QhoLyUDVFvGKz9Q3rr72GTG7uA==,iv:QEl2OGrh2/LQwSmn+N4IDOFnf9RjSB3sruxC9gmsEJ4=,tag:4C8PQdcZw5gd7+zv7PVE0g==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:6+LB570ZOY/5MOHxiTlBKUGEGcJDBN0PLepG1dmSYejJJWmm7X1RIxqp4hYoirTdhJYP9m8ScM2tnAMejdFkNyaAiXc7ii34eXcf6DJKWLmfafUByF8MmevqBkOTtkpByukUQIejqbVJbREqMOuPkKBZQv3XYbRwWCCXLjBPQAAfyeZdB8ufL9K1gsfV,iv:1tw5EBrj76ulL/FotSToWfQEUPyM3rZOiZeGEo5YfBw=,tag:DvvtXYtaI0e4by5PLasyWQ==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:cvoj89od6avy8e+kYxJcCexKEnk9TI3jgLkxai9TA5Gf26SV12H6,iv:HuBQ6StFo8/tJ69CY2h2ypej9JIH6A4UfoG28X2TbPM=,tag:xsMzgeUPN7ZReFhQtVpGGg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:DVXv6A==,iv:WYyaC2Nhgi/AqxhAK9tesZ0dJUxacpMqLPg+1rnspoc=,tag:oyHU7WCyR91/9ja18L4KWw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:V3Go5b5USA==,iv:AzbHfKRAe2sFW9K7kzV9rGtFZW0clw8iL4XJEWiCKqI=,tag:4bZgrXm/YmJPxMZ0/0FH7Q==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:p5NsrQ2tT5/MOuM8MRMbT+k3YbR47hg1hMRRGeKUP/tQSsrhQP0yQJtH9EoOopeqcPukdwrV6VsNdjn8oS9vwA==,iv:OZtrs1cOSS+5xymrzlKVrtRlaiAyN0ZcKWdJTCBXm9A=,tag:ObSHJ95sHGTslY9mzzn1QA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:UbS/o5DrOxpGNA==,iv:f/wZ9R4BBHrkvC3NMsp5Kat2IHYZl6j2UFKcA/dPQdc=,tag:WIbqbvV1iR1ApRDGSZG8Vg==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:lSlaAm1RuxMAYw==,iv:dAVSXB3VPa/GNFFqhho50Wiat5cqpJ3DPRj9f1PmQv4=,tag:kl7aPyX8Jgd33gyMp5hvnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QkhIcXFFNmdaU3Q4d2NG
        OFRqZTF1dFhjZFhhUjZhdGl3anFtVkpFcEdJCm9xUCsxU0JjTWVTNk1rOW9tTnZT
        WFJVdWJCZkw2K1VkUEhPalRqa0xiSnMKLS0tIHR2SU5hZjNWUWhqU2VmNGp4VElt
        cnFhNUZsL2FROFZQbTYwSVlSaVdCTmsK2i2BIYWHDEdmQ6UasrKBPh48okMY6XJT
        Tj4xC48RLDAQDbKKcrleKbmakX83vq681M8MyKnocx5C3PSaGnxNPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T14:21:28Z"
  mac: ENC[AES256_GCM,data:uDZlWDoMBmeVMXzXgZ6rk3CTIBpFi4b+kpA/l922IoEUGEfRQ9o5OjQNcouIUyrDW3rlXP4Y0DVzXOB5DktnzL4wQNM+mt9eLGhLK9NEwa57N6RjJkmMVcOK3aMZVOQgMfmD12uXliYEcrbnmdBS1luSe7mWEGcFEnhKARK0ibA=,iv:IvwsHldTG2FyZRBYYw9t9tZh8LMzhsiD+DegNlkyCFM=,tag:2WLnMvU0mGy7Oou84ASQtQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
