apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WbvsDXjwWUCy4g==,iv:Mfs9qovX/BxZW/ZFSm4DO6QOI4rMUMfvbBrWSUa+NGY=,tag:mu0qLYpmRMuIHO5phTT7dw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:N+HI8X8hXwelWdTTG092FvKB0Q7x4kKs/kACF9CZ65Rptw/ll/n+4jw=,iv:RUXaS0/vDYSGpPPi/TvQt+tYGi5yCuvK8A7cjXt1xsM=,tag:44IbRzzn7Tpfef1PhzayDw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:tdSqnN4vTg==,iv:PCz5PPOSfMcS0fZb2AkTVhqOrGszH5OChiGPV6N83dw=,tag:wICoS4IUwA9FvUzeRsbXTw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IwC64hv1K+V/VgCWQ/IgFONuNsHpxFAE9tIPkHv4jSG//BTpzOdC+goDGRfxuCZD2KoHoDWxZIFiPxWsQWkpiA==,iv:DtvxPloZik9scrWewDNy8qyeitQQnQwwSPhQOiyiyKA=,tag:4ojs1qwFKjNCKphYCl6DjQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Grv+gMdtS9qChk1XYAw=,iv:IVNLGf5t+XyJnvamkRT5P+NEiO57BN9Yqgy2WL2R5NU=,tag:R5BxZtiKRI+y7r0vrimfbA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:e/D4RtN1Tmk=,iv:Ia0zSQ6SigZR+p/pPlgbtqyYr4y7gcKfw4pVml5XmvI=,tag:bcV58fDcS3dTsD7LwSgJeA==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:/aOjw4k=,iv:j8lhZzGFCKsMScQjSRaYU/9DPIRpwKx5+l/V60LKWdk=,tag:/HW0XolWy59tRUrlBmpIgg==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:pi2ZeveOCiSRGUgC5X7sCrzf9XX7z0/Q99nWv1hMXmeyImHUIMg6tSDv5L4FmTgsEJRvYzAtp233k5YZBSPqeruaAVvHujIHJXKGUoRKrn9AI8As9ya4PA==,iv:pNa+8YrVkdfRJvr399kTZGJ19jXieO64EXpxGP5z8Gc=,tag:m8+iOkB71W68yJbV3drg/Q==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:IVfNNumzccOBwxNuXapGW9vDxw==,iv:KfW3a+qc0vb+QUqiHFeVLzcHCzawwe2BFN/JSFntq6c=,tag:yJRsdJy66oP+ii+iodulwg==,type:str]
  APP_URL: ENC[AES256_GCM,data:zBPB0LgNXhn2Roq50CYxg6z7mQ==,iv:w1PBNIi1O/T3rs6KukUy4iGCuvIZkVtCCu6G+ZM79X0=,tag:Suhya4eW1dkHr/8zlr7ZCQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:xIRsb1WgAYoudCty/tr1hFRnD/pIBF0/jiabCxFbHe5ThrXecpLPALh3wte0DJqsboBnqc/BQ5Wgt1K464+X3+LDev+Z7lp1cdMlI0mZ5GfVsVm1Fl2m6oEoob4quTa8QMPEOvStalbRK7hLRcexdb3ZaFYY5pXSsFqemrAauQH4VYGsyDrVhzbZcIoNVXY=,iv:lljvFPybGHq+l//yVe8yki3L7Nh5AXCJXvI6kFG3NwE=,tag:L1xTmbSgWl1rxXwwtNnDTw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:GEkhx5QPoZIYmPbWXjXIdcLJEgb/IUhiwM6IAR7yCiayjGnJMAppKyA=,iv:wcQdgdrMNWw+l6zUtrEXAC8PYTb4qxjte4zKIas8QU8=,tag:oA/D+SvvBXtadkQVWxtRxw==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:ARSJfA==,iv:oAEXDOf2Ap024fFYvFcMcQpLHcGq/ZyJDAGf5zTJsLA=,tag:x6daRrmv/VDs5vFMaIzwdw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:0BtXSZn91Q==,iv:+GhwsrZ10CnXzT/M2xNdxkUCsycJZKBMeF0rlhRykVY=,tag:FNMIWs9+6FSBHY3GD7XCrQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:540yWwkahqIcPMA9S6dOI3WcxfkZU733YABVl0grlkGX8mR1jnZzHPKz7y0S/V2kQKOnSOpQ+ajQ3TVt4N9ODQ==,iv:iCWeY3Zst2PSa8LCh84Dax+8mvBQ12PweIrw2OjmDg8=,tag:nlvNdte8rXgDSm72iT7MYQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:qRxN62XiyLbf+w==,iv:A6PEseLllmEg80TtTIh03WLHUng+dzF50Bc/VSX5YRU=,tag:mHtlqr3cOWfHa9bdyKc9bg==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:gJMWaMZw6ornNQ==,iv:HZgI8S/2a9Zz5Lj/RMCS9KERSMwCT+kYvZJgEqh0tIM=,tag:lgHQ3Newg7td+4H+/GaZlQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYU5adk44YXlzU0prakE3
        ekU5NXI0bEZJNWM2aERTbnZiN0tGWmJnRUU4CmlpNUFJRnRvSGE5UjZHZGIvRndY
        bWwyNkNpVzNNbjFXK0tCNlFtcy96YVUKLS0tIE1Lcm5SdmpFWkRXWU1mUUxoeVZN
        NDhBYkpIakI4Sm9hT05rVVUwUWRJVjgKUz3PZ75i16AyFIdMogGE9hmKrzSwww6Q
        /vuQgUWIsyPra8P5sFqe+m3ptYCyuH8WrumE4x10ddY3qXhV8KanQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:uh44N75421GNQlHu63EHr6jpY+qgTi0h3U8HhFht6rqoObNS9P37OIJJcSIKhvrPd9DLDgcaXAv2/UHrHApNWfvUWjJfon5SoBOvelo6lSzA70knbmv+KHwNLbGhrhs6+kthJxBMw/9gNUvPZe0ntGOzqUZLMjwLUaUldSZRdMw=,iv:mP4mK8CvfuL/gAvzbye4tE6GvkrESMT8zUnL+WYr4vs=,tag:u5z+H4Cf4hXVuTQOb/bclA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
