apiVersion: v1
kind: Secret
metadata:
  name: metamcp-secrets
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SQ25lAEDY4Je8w==,iv:dPQ6o0QNhpzgtYWQ5YtjWc85LXp5SF8kRZqRIUZveH8=,tag:SRfra0jVDoiV2otQBymo/w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Us1184PtiQzejJhEn5yCE2bpniX29WhtyJJ5Yu17voGkkg0k/7DJlF0=,iv:wsvmNe7RYBYdOHkPuerGlBHfayHD6+W8552ekVhBmc8=,tag:c86vlpD7bU86kMWvNUnSEw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:+91xXZ2khA==,iv:nbYMVmSZa8uhCLrgoMMcAo9ckhgIQPHCaBfgtHnHTjc=,tag:WpBecxETbi6IKBKcd1RZfw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:He9zDy9MGEThdL2BQ9JH0QMAiGHtSDvfnlHsTAFwYezs2YEksLIYkISaAkjmrLJFG1bmFKtenaTqyUj474DenQ==,iv:gvJnRo2Kyz+VY0qrZ2tAGbt6da/QYBlMT4LGJtdc6/0=,tag:tWVjOEDiEHEVNjraZfnKqQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Nbzgb2KXe4UEoycXd7c=,iv:OC0Oa74mcOiY6twYYPn3yZLvnojx7fvVUZeMISoXqD8=,tag:1Vw/cUQ0FL3s2BAL9lQ8mA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:lYa+FPJdDwM=,iv:xTmn4mqbPKv35o1dpE/xo2yTP1lgc7j+twwQb7hu6GI=,tag:GuMSBSmWGgf1o9rKXPm24g==,type:str]
  TRANSFORM_LOCALHOST_TO_DOCKER_INTERNAL: ENC[AES256_GCM,data:SUqUA3Y=,iv:laznE3ZnEMPAd5BnccaouWHr3vICg1N7uvhFd6rHDF8=,tag:5wMppHOqf3PdCOB5QICwyQ==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:smnO1937q6j5ShMmj9fIJ4cfUAqLWLcVranukEBoDT/bdcMtsbzFHFBOFYRQYWyKf+R7riiJNKMxDvnlmQTghd0M2Ad3iME7l77h1yrkZe0MIEdnBGs6qQ==,iv:/RWoQ+3nuNrDR31LPo3ssueVGQZ3NwNxW+fao+3EdPg=,tag:BFU+y192jmmd9Lad9jtKdg==,type:str]
  NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:th4z8sm0oTqBNnMebDpvXWSuGw==,iv:1yMwOMcCx6Jc+kiefgxUg7XwnKvJv0gwiNa8bDf9Ewo=,tag:rNAnPry01d1jVGv58VsdSg==,type:str]
  APP_URL: ENC[AES256_GCM,data:fJMFjllKSLnzQc/06YZPfFB0+w==,iv:sn88L10LJxucLnsz/pF0YLGYZop/OnBTftAe4uoI2yM=,tag:ssV+Cnw89/b3RMX4jjaw3A==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:kpVGJaYzoE02wXQLKWddtnquLx4UPs7dnoyDXcy1Nym4YD7vnwJ33Nz5FjJNpbNw8pJY9m14mqAApbMZE54DRbYGVmij82gReAM4BWCWzhHq5cETUkkEqcKf/+ec5XtHAhaA+j1Woo7C2JEiY4MNgKQa9+C+nXwD2FOiUCxqrwaNrsVKPRwgjp7EluI3N6c=,iv:wGdue4HUQR50BjVVwkmhrHKMyrjy2N7UJ2qNi4sXwCU=,tag:HJ843lSzYxsbPNZRX1W34g==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:xdd9a36bhRJfhbztzPG9xkbVHRIAFnQ4qnRtJxjTVQcbn+0VUVk5XSQ=,iv:PhAGaMYjWFvEqu2Q3b3og6ruepEwje1Ki+jiGS1ECHA=,tag:Ff87I6zBebw/9U3Zu/koXg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:T7ujFQ==,iv:Gohgg13eWLGmibBB7QjaKBDN6Leo/NIrY6DWTSI/jiE=,tag:uIXR7HEs0Gi3WhcMK8Bl/A==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:FIvtNeOrrg==,iv:/ILq+oFxx3tIed7hXGNhYqRPBSQP6rbMYpYkrMdXuPg=,tag:+xEUWYL42RxJG5+iktvuPQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:woAOuDOxk4EC64JjOHPG4y8KmfeovQn/7KDCaz5s6S5N2bocCLVlxzu44K+QjIYkpJD6QtG4urozDAC5b+ApqQ==,iv:TFhYsjmjfZhLXD6oh1xkTa13dKYy6SOmT2NmBCDY3Cc=,tag:8Tw78B/QwC39OafDnhBaog==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:6amUc7b4EV8KaQ==,iv:qyZVVFB0497Bh30vGFa2TlcYe4xAnX03Q6I3ZUwdyb8=,tag:ECme48ZXBWO2eFhwel5KjQ==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:AcKCtaPx1+s1Ug==,iv:IwEIrwYTfKd+QKK49rCiAjQigHmsFCYt+ZQxJN2phmc=,tag:yUnpUbL9qtnE+1GJ0w5ocQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Wk15ZjlTMEFZeHhuSVVt
        M0toTTZCcDdsQ2twWjU2Wk1US29UMWlEd0FvCmhOZnpvQkdJSHVVVnM2cUpxbElq
        cE9LWlc3SjIydXcwdmczbFBuTGJPbTQKLS0tIDB4UWFPN0xla2tVZmZXWktKdFlw
        MUhWODlES29zanhNM04rcnoyQzlxWWcK0uIXgZmGR4sXTVaajYUr5zgJdq5AABuH
        9qu4e1GlwWtbl1Axa7Of4Xzo7xgd8YnBCsuDgsaRzRFIWllTyvZilA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-18T02:01:28Z"
  mac: ENC[AES256_GCM,data:5ET3QcVBWYh1I1EhODTTRW8jug0b8tUUIwlry5+tOwAUl/wUVuz+EarkMRHI8HLnsKdj0iAxlT+b7cuFMxYuisY4snn48Ar09NS4GDoZq1KH349R1xxNLekQznK0BB1ZYLO/pyysoroN4xuuzw4q8nhoJMm0nnogESbbpwF+vGo=,iv:M3xuQ0J7hN5dgmTejq/Te7hiI5mc7kSWffLL8OIxReE=,tag:JSFCh1p5poRI62uAyseczw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
