apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
stringData:
  AUTHENTIK_AUTHENTIK__DOMAIN: ENC[AES256_GCM,data:aPX+6GcPYQKtEUex,iv:aJll3XQCVC6v7Ot9iKq+SNJroghIDdEosHh2D2XBeO0=,tag:RL79ss36DSg1lRFgKU9bvg==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ZmWqVO2jkXk7w18e8saFNQDldKY0XzAKr0CKFJbMswsZAvNCZFzgF1FwIQ3UoVWHuVcK4ad0TYugpGH7gKFwZKzzC3U=,iv:u4GuLB6J+Q8kqa9+72QjWdXGcQlWvHdlFMZAwp+vhy4=,tag:aZyyS02mz7hhGfgO7N4Qmw==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ukhqz/HYxsYlLPJho1+bufrzWJZZ1TgVOqKMwZXYxPc=,iv:1dxgDdXK6hkAM3e4qtkl1ZAGc3BJX81TFlTu7bW3sDk=,tag:JFbdwv2bmn99d2YwjfB/yA==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:7GnNCvQ0WET9B8+YcgzVdTPp/+0zGRu6CaVIu3GYowho3zQZQpJbkJlTLNfUHCM3P1z4FsIFH9IgJGmwjOeFNQ==,iv:YPeKgjl0ekWBXC5DDAv2BFRSZpmEC9l+ZuoFZGAInlk=,tag:Nuxv8iDi3pYR2yv8knOVOA==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:+0aQ2fne/0VIYy0gthB48eOndGHdlDCNF9mN4Q02A59bnqNH40hGkyeCg50=,iv:fAYvvwbZPRWwQEHosCjkbTEtVpbvFUVQ3BWPwEl5r5g=,tag:AuiMI0OB5vvi35EbKczm8g==,type:str]
  #ENC[AES256_GCM,data:bVIzVoxg+glbhvTMz9qGRxWuwhgrAfoAudAJw5f0BhnZTYMPPYusGfbJVa92iPpvBpu9vXE8w8RRfXZrN+hVW8CeZq2JxlbsVw==,iv:at3ZK+v2zJ5bAsDvStD42hbg5Q0zYxRXAwMpslsayRU=,tag:6n9OEGoXh2Pl6PBfHLcHYg==,type:comment]
  AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:OMLwE6L9yMFMGI2RNPnzeDuTPtoFwjrGqu/7CFdmepnHd4fW9am4ARI=,iv:ueVvhdcQtJMXMeTpQwuT8Wsd/H92J1cBquFePPAWnrY=,tag:uCW6CBidyjLWIvdGK/OidA==,type:str]
  AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:Uvx+5Q0+uZlR,iv:FfA/eA65KYdDTsWqT9MhlclJiDuF1y4HIto0902eL+o=,tag:glZ5a+XZGISYHiqmZnw9PQ==,type:str]
  AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:Slgk7l9hO3VI,iv:8+qmiTi/NFwB0gdRloAqElu53tXk4ePyy+uNYxgt3sI=,tag:lHRrADHv6NBssr2p1kuHqg==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:XHoXAMV2kz4+nYTfCuUfF+DZC43948xtypxHTevjFHTPQd5wsyea6985vtk=,iv:yWgCBuxaBV5o/xLXRfveNVavcEyLB1f8yQN0BRW2VS4=,tag:xC0gqj0CZ0bWSxB7i7H/yA==,type:str]
  AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:9WA3iI9LCDU8lr+B/55A3QPwRLsHp9x7fJ0f4R5T8U4SSMzu8zjH,iv:Z/kkEz7LU8nQysbFxUT/NLoZ8sisPiZkhg4OMksdOCE=,tag:ymph7K3CsgocjFGRNCWoJg==,type:str]
  AUTHENTIK_REDIS__PORT: ENC[AES256_GCM,data:8HX6rA==,iv:S1twtnoYE0jIUXStDYon4jlT+LmpjNYri2xcWpFKPVE=,tag:eWNoZ53EZ/7XNI/2Oc7i+w==,type:str]
  AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:vAOQ5Z3lRXtAegUixoBBuHJEfSoYYB5c+5IYU/X6Lj4=,iv:yC6ruPhIa6k6MBXdQr3wLinaJ329qpuKl8GCRIp5PnM=,tag:Jh1pJWoZjkMjPfFNExId+g==,type:str]
  AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:cA==,iv:cQgilDJd9d4JwXRpcWMrSpcmvNOe0w/SXScbj9208qc=,tag:yngrRdiRkagbBQjEzjCBbw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8u6hDyUDR6eD,iv:zOgXlAtT+XsI9XwhThN2VbNsfoAe9byliNemyxMMVz8=,tag:ozv5lSy5SKEsYs+jTgpv4Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LW4h1nKYmnC6oUdAdomcVtZViecJ/7zJ7gbA3uUF6Ue0svIukmIW9Ws=,iv:yb+aSU+JFzOjMq+Rdw7J8FDZdjK3H68xsuUGefZq8Vg=,tag:2S7ey8X8YsbuYQVrV7FcoQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:unceei8ahDZE,iv:6Z52+oPl1Q1HYjoSuBHO70nAi7Vnu1WllevsKwngNuY=,tag:O5vvuGEwIMpfRvDX5ByUeQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4yuYuVut3HL/PJdk44HhPgH0Nt1QLGfGeEsaGiIQXVKoeVuRpgoRlfHzc+w=,iv:AvacpPnyWXww4rZJEijtHc64g1NWQ+r6HDla+O3/Bto=,tag:dWjBzKtPBKDChO0kbjuPog==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:mC2DnwPIbj8=,iv:aQyO8aqfvKuQxFU2ErHX4Q9/cgqy4R1OCf7Cj6Q7qhI=,tag:aoYAQTfDPj+Mf6jGH/UQvw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vkFlgCEFouTKUQiqavk=,iv:zGIeoBwBszVoVuwoGBqcoAQ1O35eWOFMpdQiD6guFh4=,tag:GwAnGGyHLup+0gAn2cqloA==,type:str]
  DRAGONFLYDB_PASSWORD: ENC[AES256_GCM,data:lcuwVYCOU4FZ9Px4WfFkAEYsb52rtF1ULAVdIRBVoGQ=,iv:j+KM4hxPyurNFnIzgZzd4pQtK2Skynsj+LPWdBgSAxg=,tag:IF98X/HSy312Mo2YO6qmeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWVRncEdBSFlHekQ5Vlkx
        VlhENUZtbFplNVJCcmRYR2t2YzFIckJrNGs4CndDMC9LNjZYNDdVbFlNS2ZVOXpn
        MlJSU2RpM1FQQlkvN1JMVFc3a1NTREUKLS0tIFpzeWtQUVo0N3JRYU5aOGI3OEk4
        cUQ0N3lBZ1libDNTQ2Nidm5HZFhUWlUKqwN3+ohy46zpzvxtCdMoEfe7bNY+BTwH
        UBlWwejmH8fh8Rhw32G4+j4DrHQx1mjwqQDnNrO6URkc/5MoHKHrZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:16:38Z"
  mac: ENC[AES256_GCM,data:bLkywVjNk9kdB/nQFKw1T6m7R5OCSYQPWnwYyMkNFxF+KGyyq9vtwvIYXeOZz2jRmjuq43qihP8GGAy3iMqHqsf4Wf2/ZERct4W7u6p1/AUVMu7PejXYJm7e5fonuo8Fe75EspkPuU6wp1Csx6zYqIYGQ50wNfpi4uH/NNtKzbI=,iv:IPc+hcmNmhFfkixLLmi4F+mAWbnEs3kVlCaDcXYCJX4=,tag:Gi8FgT7BLqu2kfZ6H2QBTg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
