apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
stringData:
  AUTHENTIK_AUTHENTIK__DOMAIN: ENC[AES256_GCM,data:1acnkSNNfyJ1exUU,iv:62v8lA2O5q1Q5gfffe1sHUY0mK5FUQ5lsHbYgoXp5xI=,tag:PUkSCir2i9mGoKrwkHjlMA==,type:str]
  AUTHENTIK_COOKIE_DOMAIN: ENC[AES256_GCM,data:uAnwD6tUjg==,iv:5TFCiK+kuUzbMtTLcu5r1xHPWPTRq9zacyyB4mZ8c7M=,tag:mkMgWvYuW8FWVvKxKaBEaA==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:xhcP0aEbgiw2BHzgUBXKOX7fJvWXz8rvx+IKi50uqnOibTCF8o7UGEAHHzup1g+f4rlF2swlFf99X/EzM5604b6uWgU=,iv:z8h1ISYpqmemPX/Myzk/GFo3m5aYOnsQ4UwGCC8HSb4=,tag:CAiiQHfir6l+RaF4VIdJoA==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:HPNjoZKf+pgYfOIkFMXKdyJ4WPNND+84/uTDaKADWdA=,iv:8hZbw0NPiqDs38XeL2XvQrr4s3mIka0DkqinHWz9OzM=,tag:HBj5xgBmkL6BOI/QTimDqw==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:hrWGdPmhKZkrZNS/SobbvVz5oxodAmbEIq7TnXUYWY6JBBVAHrz/vgxW0AxBNgBCORqKlscj7mfUEhsd+1kETw==,iv:VK+gUXfFEPKLzSzJcTA2uB74sy1rylPyLFjlL9CeUWA=,tag:AA155ycuIan33JroX8sJWg==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:af35W3e/nwxAOE68VvYXLJau3PoyaQXVlzzKg73Ws8WRa27oXZQIBOKUGqk=,iv:FgAsYu7Bl3TtPMCObGNXwOuQO32aBMjqcveQfWuvlfo=,tag:x2IKflK1RRXuDQRwtjETsQ==,type:str]
  #ENC[AES256_GCM,data:EAeFkAd9O0yeSu6CP/KQezyRndzNYXII/OEhcq6Iw7ob1cu1w3in5Smq0MJ/jTKkkdBpOsQ/SqicOTrpokmXEHAT0wfEM5E5rQ==,iv:1X8F9K60ZQmo8D9FcAMFwryXTUO13dEgNmB/vGTXdBI=,tag:ApioFzo65Jn8L9+z9RTGlQ==,type:comment]
  AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ge8oW6f7gMkMkXpT9Tbl25j+VmcXz4Znju5gdEESi7KuGnCOYX/+,iv:Cy+pbSrTFMLfSJpYlxLkPeD1ntGbVIs5k14tVN8XOEM=,tag:ZeKsNEAyK1BnKeogpPgGyA==,type:str]
  AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:6GurI7MZ7acO,iv:wv4F1InxXSP8l41ndA+f7o5w1+rfvdMi0uXosNfhzXY=,tag:FEiGGcoUfE1SrcExsSx6Tw==,type:str]
  AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:XEfOQZqpORuv,iv:7IkdXdAQr5MJWULgLT0l5kgfqe90EMtlg4fvk9plL7g=,tag:PJKPrxVwXZec9/jOBQGlmg==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Os9eY87xxzxn+42IvBzAcT6Am4anFRMDijZQEfjGut0eTsICaSivgw7JF6Y=,iv:x5jc0rcAPBnf2Ovxrj9ZVMRfJA778ShxnzkVmsVCZWo=,tag:CndW+8dDAA0hf2kP2OVoig==,type:str]
  AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:XkirqXsdqsHfZx/ZQWe1u/w6qzbBVjuZEEv8Ho/kM2WCFejPLUbT,iv:QnUtafjif4E5NFTzbZHZTujzmGxw9/6d6f6noNSO3F8=,tag:+b1pCxEBQx//U1GlFzE+ew==,type:str]
  AUTHENTIK_REDIS__PORT: ENC[AES256_GCM,data:RdQhSg==,iv:O5dTrCxnuvWX3RtsPAjwftsyswHfGlP8LnYZ/lDchLY=,tag:YG7KJATwouQDvs9N4puCNw==,type:str]
  AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:KUT5LChiI0MlMpgcaj+/7MrHv4nOyT6irz9+OCVVwmQ=,iv:5QJNSx5YnMjgSm3XO00cv0O2yCLexM9Lb30umQCOOL0=,tag:gJN6Hd3TZ6GsbuNPOWGykQ==,type:str]
  AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:Vg==,iv:TWAoiv+XY42wqDAzXxGoapMfMAVR+FndMDpjqjDhJls=,tag:XgCqk3Ivf/UqAmR3ThgqIg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5LiRh8Vr1HWk,iv:AjZLb7UGc1V+oDtP0J5Xv4kZwRRvUfjh0rzc2yvOI/M=,tag:hCWYIItvgpK27tKntuxUAQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:NexaGsWsu4/ysx69dWgelu1uE4rNu6CW7XGnAkgNTq5eUPqFJMGv,iv:NWzUkEfEOgrI1HakGoW+C/iPaqhEOsMYACccXqbwZk4=,tag:I8pNaKXqUqVXIp5nUPBifg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:D/xSsPJr7qXI,iv:c0PY1Av+cKesB7zwyjil78WrC2fGRiGwIQ5boYChUKI=,tag:WKuGHQWUlycC81GfoWuXhA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:362pd9CsYLvUncRbh0qupxP8A26Lqh9j2NGIRX9s3daLnH/aLeQ4K6e51uA=,iv:6v8/YyaoL7/7CdubviABPh5JuWOAE4w0meFBqlqU3U8=,tag:0xU+JBc0wxPoH5zsjtYsOw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:NhGHV9uhMbM=,iv:y+R7Hsmvld/39+Sw2cl8ZW8MNJsrshxR6fCqcsrLliI=,tag:fep2iVTHc5DYUZS+plyjtg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yszqT7dxdt4OPiHRkos=,iv:bh0AF3CEu65D+FiA7bJ6wI5PI+fW+dBEGSb/JbKAK9M=,tag:iAH6MbJ2Pb7LeikP2hcFuw==,type:str]
  DRAGONFLYDB_PASSWORD: ENC[AES256_GCM,data:KcO94SVFFl88Zn8YZYbFXe7U6qMyDEA79BOOYjoSr3Q=,iv:0MOF40EHPwW1Ky03wL3wG20SlIlyTwLtHLyUzImxrk8=,tag:91K8Gc59D3ynu+eRF9iKHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcU5jdkhKNGt5K1FYbERm
        VFgyWllWU0lkT2l0U3ZmdGNhOWw1dGxYSFMwCjVmNGxXMnRwdURZT1FERHF1bEhs
        Z0NXRzk2Smx5c1dHL3FBQzBUcEZRRXMKLS0tIHNkKzM2blZQdU52cFZ0cTdlQUsr
        UEplYjFhNHIwd0JmZWlid253MWlmaDQKt9f1dHh64AOCmEX2ICUcFICPhwkFm1OO
        InagLJmGjJlzz9Cy3/CLhs5ruRGJY+ITAl+R2/vhjPhT3B9jQRpmbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T14:21:27Z"
  mac: ENC[AES256_GCM,data:kksWV7xhKtwN+kyiEDocnJG4e0oK3pSiBRep4tDIKsO2HIF3Ufmqa/CVOEauAmnZQ2dPaDkzWUKD3xzIU+FuDgUd2TFmcb+bcwc1L27rDYjbamjFmkSN4E/Y1JCK58Bi88nRbVh04+9g0tbHcYJBPxe6SB1Nio1uz6j9Ik/MyMc=,iv:rG3THiCZlkRit3ubaXeuR8oca+jFmgzvc6haxTI6+vM=,tag:y7zmDPabtjOmnEknwsOJmg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
