apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:5fzBAhJI5tvW4vjpQH69WGuRG1jvJ9uXweLrovec0CMxOEvSxYSAMdNECCrsP5lldyvCxmQnv19FOqZxzWUz5ZuYExM=,iv:2nXdU/52If5Ez7zyTFXFtoExhWdkM/9CNyCbIj7eUCA=,tag:+vxTcTi5iq2wtasa+5d13Q==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Nds19wOEgOXJN5pcl88xLVCugj61xpBMJOWaykquyvM=,iv:OBRh+61+kYHojc+8nvNcRxx72Z7yCVMM+6a/CFsEnGI=,tag:g+XCI1EAwBAT75g97dlJyw==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:/1Sx2kffYbfMbA/Lq677cBmNb7Gvcj+0CRN9vQzIZgaOTmgk+Nl4AUhv5dU1kgQGjM9e2d3QHprIeGc/IsWdyw==,iv:PhEUyJKfUgSF2on5ewyBkP/40iVPL+6eFHafkTkv2bE=,tag:fg8KO+It+YZuIUstOYgwow==,type:str]
  AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:cGvrXpgA3gPkEQd3irqYCuDpYR+Q5JaqgHBGcnyFx+qVqrDJZ0XKzWcJsVo=,iv:JKj8N4g6mIPSn/8rb7p1m7KXHZE9W173bYpXdC+hUMw=,tag:0f3UP8DYvdS4pCLK5huMmA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:i461Ai0rTuwZ,iv:SXolHNMs4oh64WOyWkexljbrInCDgEfnoq6lr+vycRE=,tag:Y9wRMmMF/7xvg78sAtM50Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:a8NWrKDHnlhahp55OY8GTqnr6IDIrnuriIOHRCQydN+nKMNr+oP+PIA=,iv:Fx7n1trGOw1Ui7VXgF+10iyuT/hXcBd1GHcF5VqgvXo=,tag:hsTFBfSBnLqrQTuU2nNRGg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:E3AR5i2mLtIj,iv:5N6qxKmo+D7lTS0Nd6K73oUta5qmS9ENY+4lahGI94c=,tag:jNOQ9Kc2UziAptROui6/tw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:A5pgm9pmuiiDzwboNNdbjuOVvXIC80bn+dcpVYIXoYVTdW6ILrVHttZkHt8=,iv:sYDRn/Ph8rIqe33n2LNvHQhZM/hL7/Z8f/qa6f9spDg=,tag:v+F7cXiuLIfaD/14Kbshvw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:lO7i9MNq0Vc=,iv:ttpa9poaIi8O22fPbMDWMuZ+lhuLkLe99mRcNFA/LqA=,tag:VPYOUWZwQhN3cpA6AGcGgQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:KVLgJelo6jEJCOZp6m4=,iv:HjsuhpCh7iCADiD6Chvlrfc3LCkWQXJjuM1GXV1Oy60=,tag:o+xstyXIrsYv3sWvW2SPPw==,type:str]
  DRAGONFLYDB_PASSWORD: ENC[AES256_GCM,data:X/yl1ZBKROcv/USZgtTVuQ5MUwHNZHKeUBn5da2+/Zw=,iv:LqUYlXTUjBJjcQFAn/Ruuf7gDI8ZyE30ML9ALMpjvFQ=,tag:+tSVpz9tvxG7GUFHIJs02Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZzJyRTBPVDhnU3U4S1Uy
        ZjN2a2hRU1c0MmFJMENEOG0waUY0RStWV3dJClBpbnpyZVIyNnVWbS9zcndRKzlr
        T1BaUE9PRUZscnJLcjdSY2ZwRGF4Qm8KLS0tIGFUV3Z6T0lYZHZvL1FOaUV4aWJh
        d0IzOWlVbzBYREVsbUJPeVVsaHVmQmcK/YJgE5pSlJz6l2sPRxln1v4rh47FdUHh
        GVxWpU8LDvKmCKlb/2xzC93bkdOLHV77xK+2DYkH55aum3ahJq8xSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T17:54:09Z"
  mac: ENC[AES256_GCM,data:w0pNEV86KRXMFx7BY9NK9B1asQoOrcJVunNIuhkOaBVBf41IY3LrxXmEKpIIvyLbS9ISRTvy0auUzKvGeeQjOtZFsis+45afqkhY11g/Zpqd+OsR6NVkmQCHbtafSaRKoZoq9jxcRiy5hrlTh2bFzzTHN6OcxaX69Ic6IId7ras=,iv:mO9ZbAUFXz1mp2tCLc+a4ajISkmggRd21+6JR4fMASU=,tag:WKI9LNxGuh5m115AVRy8iQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
