---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./instance.yaml
  - ./prometheusrule.yaml
  - ./secret.sops.yaml
  - ./grafanadashboard.yaml
configMapGenerator:
  - name: dragonflydb-dashboard
    files:
      - dragonflydb-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
