apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-db-secret
  namespace: services
stringData:
  #ENC[AES256_GCM,data:PjVBIoLNZ58cik79x4E6u3GbNhGgUIllEf1o2SULVn9q+WDSOBDeE6u0io6n6uUTh5MXgZGOktxhQNnjYvrOEotdRx0=,iv:J/0+8qSTaWr2pE3gV+MoFIiW8bH/9f4BqrnxWWylQRE=,tag:xATaRrHtsLPsZKOOmXvTWQ==,type:comment]
  #ENC[AES256_GCM,data:4RCwLF4jiXkIDL16ZG8D4zEDYHGaf7xfm19R9kHrPmJHbyi/Y6+6cUoej+AD8zhRXrIAjt/NDc8/ww0FihE=,iv:AODlPUsW81+1xqpHLqIFi/tKSIuLxydDvbGPmU8Bkqw=,tag:YXpMxLLqfemIO1yrKCj3Mg==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:KS6tY8jiSIUa6Gf4Vg==,iv:8JFua477C4XMUtDhapcJqlqoZnR9WaI+KvIUfpx2+UA=,tag:pxRrf9yIkXCljKyJdD2H3A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:FqxQBvuUvtspdnaDkxNo424DlA4Zn8BEiJWsd/XxMqi3IfHVrC+5p2M=,iv:MIi6JYX591pbihKOijJBfC1OLK92tzuXAh/ELPGIaf0=,tag:c2vNhJ3j6vn3qtfDpHgAGw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Opwfm9BKf6L8ry01Ow==,iv:qB173KgsBiPGG+GdcBUMn+CHAf9cschdNyyuGLaozlg=,tag:9t51NKBbS5LRKvx35zm5wA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Y6cQ8qhCvMZLY+qbUjw2zbav9olXNknGFNOcFhIRwVQmI3j2Gn8JGUffE1XQ4UWIhwTa9n1YaTCkDMFl0z6RJg==,iv:z6Aw1NfVw1ZFUqgHAc5Ms7pI2QaytNAFWaZFBak4xmg=,tag:OM9fQbWiC39BXOGiGDIAGw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:kV40n1yytoo=,iv:9aEqPmn7Ce/4W7ZrVuKqC+TfbAh9V6GQdPgBwN5a1Cc=,tag:rMRamnntP7BO0Z5a/xG51A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5RaxKAUyFg6F5TeV1SE=,iv:Cxjtew7WT4lPE+pL2rr54ww6+ClazlODbR0E+lhpH/Y=,tag:RMT0EPPghQGvIt2cKFwQsQ==,type:str]
  #ENC[AES256_GCM,data:YOUQzMc23THn2IA8uHaxZ+appHkUrwn3VwdQUf8ihfIOcDNUuq55aD95sOu2etP+DHx4+xSTcY9yRsdu/HibT9r9XUz1,iv:yXOlaCdIpIXAx+mFHDCaGZ4s15B3/I3kMpsoIqZIlKs=,tag:dpyFhcntXW59MPgh8RdvbQ==,type:comment]
  #ENC[AES256_GCM,data:KtMZkVw5gdn9uIOXgMYR6hadEmmAisEIh5hYP5bxxHB5420vuSzm+UrJ3ae0ldTVEmPKylQnhz5UHpcMzc8cNyea,iv:w6IQLqj75nNGLxZYqbEU3FzDp+JnDIIklRuy0s++oZc=,tag:6otGM9xkxDyNWA/wOax3pw==,type:comment]
  RECORDER_DB_URL: ENC[AES256_GCM,data:86vOgzEPM1zjIH3fFmspbKAa56Qv118Y4iKGb+oLkL204GfUAuBJNqLOOF9L7xFsULsaZ9Y+Pt+mVsFEVztSfQLyx9A1SGn5EfaXtXw4S2VLZA3EUEGPINh/Eb4wAtEmcoap7fwIPENOOP3Ubg9iwSpk/OKovxktcoxfijzamw8n7x6v1SoznJqNn7JeTvCN+67zL943NFI=,iv:AOL6QGnzsnKTJqZDgaDZBTTeTu1K+dq2frGpY/y33Fo=,tag:f6mDiCSujbXByPsHqkHcsA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRlNkejFhMlQzTWxCTytl
        TWRvYXdXY3JsZzNxdHNMS1YyRjZBMUNDMlNrClhjeEc3WUdsU20vakgwejhRY1Rj
        QVNRWGI3TW5BN25sdWNGcndSMU9FOU0KLS0tIFlLZFowUVJxc0pwL21uRXIzaWsx
        czZiNXlncTdFQ0Y3WVJJbVUyVzlWZWMKq4nqlC0Ogc+pW7je9uBm7n6Jp8CqSNcp
        JhksJp+Rdd/vmSFhqnSbTKV0ca5aYZZWq+U6HnarfOac09eQ4wwOjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T23:00:35Z"
  mac: ENC[AES256_GCM,data:6OpApudjJB2cuIEhK9tVW+qefGIszWie5HT136kOFp1uOE02P26qO5A/PoQ/Z7DthNZ3IBhCTc3XVSdVtrODJAiZCvbR4WEBrTmT1wzeLGcHGMQ2jpaDbVSfUZ1+RsKQY58BkhmOlP6gJ4c7nkC5/DRXe8NgbRdAyJ1Zi24x4b0=,iv:YnOhKaYdBhvWCIMIMsQJrKR7RpEwlxGDCZmxFcwnxkk=,tag:plJKHvHPLNy1XlFEk421NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
