apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-db-secret
  namespace: services
stringData:
  #ENC[AES256_GCM,data:+mvMZPb0fZ5R8Xj/zHBbSE94qfb+B0CC/37AA8OW7xUdSwQRC7y5JlpCfm+M5roEEl5F9X9IdVJi0rP+b+FNzqB3qkY=,iv:O5l043Fkq1YqkDccDn/zX8x854yjWUbWtiX2WKOm1C0=,tag:3N9AjICCpun+m71vpwk8xA==,type:comment]
  #ENC[AES256_GCM,data:zattINyTnhRJjAcLFcLO3Bk38cpensfERUdNmZfQ5qx2V0U7MRR3oY5mm2f9UY+NKiW+qSlUOsmijfQUwKo=,iv:t9FuFaZ7hNkJd1AimplcRHgKk0LA93Sv3JWWucIUi08=,tag:iIbcR/AN1EE5dutnFNlFIw==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LvG9iXv/50mofYthZQ==,iv:esq7xKigRaYlFOmkLXxlvBnq+agnUvLqzrv9MgPoPr0=,tag:ErIWvdBe2cDax76JYHEsXA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:NbdnJiH2Wbu0wPX7a5jufAwoLjbvR0pYS3DQNBb3aSpP8Sm/iHK0,iv:7qiajn437OuXnLflpk7Xyng0NayeoSc16Rqo8cwu5Hs=,tag:XZaduqLNIJKggqjN3CJ9dQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:dXIzxRBxHb6zcAiKUg==,iv:KJYDlmSdEx9fJ6wKkAk5gNmACSrorqXcOW08z7qf9LM=,tag:I2up7uQt9RQqWRNRcLm0Pw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Byb609TtcQm2oO0HgT6vLluhdAtq5WvgeReNYRhz/xxEg/zdWgCz4sZHSdHecPezMYj7R7YQtJf0fKeHwgLESg==,iv:8c6lOgikiz3pHyuw0ht5kUHwTSq2ZWY5+Gp26DLZDZY=,tag:qLnBkfEzJROy1PjNGnl0IA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:DD0sajoNibQ=,iv:XRSWuGYVN8ciRuTbHIGHWYr9j0+v+bcRyvC5U981oEc=,tag:w1sVUffvqd3/gVF8B90n3Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TfuvOHSaayPo/ZsqNPE=,iv:tvjVW6TeB13fOT5MpuSOL/rPbbKsPYUgPWbrUP5tZUM=,tag:taHYpMgO2pxh6oYv8h4otA==,type:str]
  #ENC[AES256_GCM,data:7M5zMxQXM5o6tBw29RueaunfzD2dagslBAaQVtIX84lMXOE+KRknSiJSGGtKY5bu22oVHe80+LORJv8/iXC5grp0e56E,iv:bT+IBK30ZYxBZWYdf+IlCokX4u1BkVqfynLeq9E87AI=,tag:kEoANLX5NfAAKQIxrqTaRA==,type:comment]
  #ENC[AES256_GCM,data:JFECA6RiLp/a0A/GfOV3Do4LUEtqFCjYhlQ3ggvgTmtsfjkhNlsf8Tf94C5hip8MUix0EqjXhHCcwwHPHeRBhJOv,iv:AYzoOeJbCerWcvkSts+4mDb0xTGWJ8+vtGtog6olsog=,tag:enLbCKhWwUIzDF1SStSybw==,type:comment]
  RECORDER_DB_URL: ENC[AES256_GCM,data:UajwLoJcUvKNLG8Z92nRRXmCuzvUq40JCmHVBasf35tyWGxUhySX8FN5UvJOUtOLtSzt4bKFETjUmohggcD/w/cROMYacw7+UzK7blj/qhNnYH8FF8k6v74m0Q186hr8dqs/9F+CWYGYCGayts4rexWHInvxUELilCjdMSAhswjRxxx2mxNv0cM7FgSykZ19F55f0ASP,iv:vu8yFsIHbeb3IgPuIqnc+Ws2+JQyFF7EqvpJfdAZVWU=,tag:SSJAuqVHEe52QTL/120hcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1Z6Z3JYVTMvMzdPZ2xY
        UHJwZXdEU1pJZXloZzhVSzN6OUdqcW52OFdjClQrcGkwVWs5VWt0QzVPMVVSZGtu
        RkhRWWhVc2QzMzh6ZjRrb3hYWWp1ZDgKLS0tIHJWZTJxNlljOWYyTDZ4TERGNkFj
        K0pMa0dEeUpZNERKR0xKT3hDcC9mbkkKqNausJ74eN/up52Ue2dGp5bvZf8OL37y
        spK3mHxdlxJFUbIJdJr9r71NGt+UsZeZRrWptUc1zV9172gI0oGKUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T14:21:27Z"
  mac: ENC[AES256_GCM,data:F3b5009T4Wk+hTuevr3B0/z9Vo1Q3iNGphzoi6Gx03XWhc4Bzi0puS0IOYc2EqZsPdYXysUiljxF9GBOeHXxaUygySpQbUyZqsoMgO1TgduaAF9SQUYE27vNSQ/RRkT9o9c/t3z4u+mmHpVOZtAh7MqfIHB6Uyvp38CC4u2h6SU=,iv:tQ9i1TDZLb+XdDlMgn0pAXGt2CQjjeA/QfRcgeVWM0M=,tag:YlmVHA9tI4+hBjFxDs+KVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
