apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:dBDgsD3LraDj,iv:l1iFhSURSYW+s0HNgvF7jBOnrnFifHsdjnBiHGQjrxc=,tag:Xyd+uL5yTxIQAyPdz32QOQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdGpiOEpXTS9CTVhJVnlk
        TVJrUFdXRHdxKzNkazRCUkJGQ01Ga1VXL253CkVDWWpQQk4xMEhEZlljUHFZRnJ5
        WHdOcVgzNXFJbjB2Nmc5YTF4RURXTU0KLS0tIHRSTUtTemZNU202SnI0bXFGdUJj
        WHM3V0pQVVVSMXhvZkM5MncxWHlRa3MKauz8KeY9Gb1YOVeVBoRZnIk9+hV2nWEQ
        CnFsgjc6bcbGoqF1uLBUANTj1SzLm/dw9eRZuTaPwsts9+qDqujtGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:/26eCTkCt7OvCD7gdQydyx6Xi8ziV4caIWupZMtYmKkDEhg+3iGZsIf52SpA86tau8RI+3tQen3hkfvvRCSQK8wqMjQnYPUA7L5Xo99qbCWU9JlXIrIXhEOphUmaTtDM+HDsuo6hGC3bxM7XVdge+Bt7PZ4VKVpncEwJK4GWrhk=,iv:il2cBO2PTMVIwl02xbNnVcTGPZEYbLrpBETRfWx15ns=,tag:qPRBnHA34IbcJCZPow+kFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
