apiVersion: v1
kind: Secret
metadata:
  name: anythingllm-secret
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:CGxbapIGvOgQXpt0IWJaAvZm6P9yZxkKCT2eAhfrEammh2jOo72M/1cPJoAKmMnqZnXcMZJdyW3vxE3kOxdbvg==,iv:YgkTp/HnOiOfxlOdLJnkrSmATFMcoFkDMU0dkh6RH+c=,tag:Xayzmx26pGNKT/AD6t72Gg==,type:str]
  #ENC[AES256_GCM,data:G3zGX4X/NGjdyG3H7bZ57MzBxPnujRzlu2vS8wf9tW/FlusniTZyeP2lELkzE0o=,iv:5xPcVVsYfvqAnVrXOXOXX7dWllHqXhhighAbgCrMdd8=,tag:p1cwlJj8DFubD9/PJoh6eA==,type:comment]
  #ENC[AES256_GCM,data:aQnGdznQVzxv89MRHatnEjk428qjjnkBwmXC7inWbtfwn1E4YoXeoXmz/51k99P5iCFuhjPOhCVx1YhO2eEbv4AekD00+94=,iv:W5fo01eyTtfcWn6/U3wxm4IECgBOa0TneahI4iw08HY=,tag:Sa5jFOHRQvIa9swaEmubjw==,type:comment]
  #ENC[AES256_GCM,data:rOyZOmJgdlZjufpxc00zyuNVYjAF9NsOcz1MmZBjdstmF22YqMqwU9esPeVszlQbH3rQyfoJcQtHb+daF66O0tyR71ShcrQdzw==,iv:Hfdr+Ib6I1X4/oNpKjW17zAOCDY6IH4amM+m2fIzYdA=,tag:r4HyDOlEooU+0vB5G+/HbQ==,type:comment]
  LITELLM_VIRTUAL_KEY: ENC[AES256_GCM,data:YdiUK4ytgnc9L7aUr64NVHoJjifaSjAGuw==,iv:j+UELcp0RTzes4MGzaY3dDLBhzdRr9ts5kk9ll4xVVE=,tag:S0v718dufOIxWGU8yQ44bQ==,type:str]
  #ENC[AES256_GCM,data:XeTF85wwNW0qGFqXIJvH6IJWX5ML1FBuQ39Gq1zmePBMjUBCzYoj82ufuO6XXmnw+/DVO1T3ASZiB9ldn73OHJEftuGK3GYL3A==,iv:2m1OJr6QGso+OeNlpPlyZ6Tsic/6U0iIC33HaWe5l8s=,tag:h0viD4S/TzimiQ4oO2GMCg==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:yqidsSmVjA828dXFPSmfTvcROGG7zrgm2jQLoAMRk/Ejd5Y0GVRK,iv:Q5Yn7JZCCaIdkoPQ1sAEJEys1HgjMTI/jxY0f+5Btbg=,tag:gDAuZrcU77yDfWWLSTXy+w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DMqaoSUs1F1gIPI=,iv:EgFayAEs4p1e6EQxzKy4bpx3yoi5TagXKiqRAh3Euxk=,tag:PEKXPabYZ00z4XUc+ayJlg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VVqZ4ZcAbVTdM6k=,iv:8INPrD5ITZPXPswIzrLQ4n+jWXvjJ2+RsO/63Iu2/8A=,tag:dz17J8yJFEZNYUBFoDW5Tg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:AKC/RaJicLr5DPjdeVym606gTmYGMI3pCrGUR+hNVScfKFtIxhtBhHIUx8Sl/har,iv:fqe6Xnw0AX2UCsVdwZpUjXSeVDeX2sB8erNPesxVAaE=,tag:/DpPYrl8JALHfkQG1DV54Q==,type:str]
  VECTOR_DB_CONNECTION_STRING: ENC[AES256_GCM,data:BOv3Uo8LAGLgChkj7wd4PaeFC0s4Q3pqZ7Kg3nKdHq8A5naoorhraZiOOZnn3Luzqt3/byfK4LKZedt1lTMIPsxImisMuF8TF/aGsivcIeWhB1420fm4WTBHjGo7tT31TNyhGWoS+Rhp8xZlkS4/UGgibXlc69Zex3OkzVQ6klr0zA==,iv:LmmAbZwuOw4xVdtAwTal/nnLvLEPiqd7Mz32HrzxN/U=,tag:TWDopnyzC54e2PrKRN60dQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:umhjfBzUOwU=,iv:HuNDP6ZZQYm83xDXmBlP/6BdKi7rV0phpi2eUiuaaGQ=,tag:bARc8vwSUDnZZB77j3vuzg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TUUgo8gQdzYvQtOZljQ=,iv:SNwylS3JIulsvjiCLujQGXUt/cexhuRw9X8PqAKUptM=,tag:ajA9quUm6t4Miw3QxNKpWg==,type:str]
  #ENC[AES256_GCM,data:uQ+RIqgem7p4WDE4vR4whCV4eIyNK495NFBLNOosAP4uxJRLF8wIjMJfmWSvJSx4YIry1/1+/AL3,iv:Ue/IfYRz0+bEtz0gydnWTzLLGQrdXNU9kGAVg65iYpA=,tag:k5JLQIEIpeXuTdHaMqjFag==,type:comment]
  #ENC[AES256_GCM,data:K0NULF0vfUI/Vouhf3fMXfjYg+uy3gumi1RwBFM2XeW2uYFFuz5bnrM0wDw7zuYP/QFSSDhr2g==,iv:oC7SmvxQUotBGWbK1zO0VNV899dVJtSARHQ9589qowY=,tag:fLrJHfSxRTT7j6oHuyob4w==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:MIqyepHe3AzCxOcDCHmgfKGRJ/TH2BmiZxLsKQiNI7tHmmWWy/R7M6c7Gomu+7yzWA60I1swX85HPnAqDjs3oA6CekqKB7piBluFVxH+zuZCMupezJrnSfgKwC5rY8KsdeFkBiAKe0iIMsKvVz0XEvVUIzJLeiocrSxB8MMtAqiarA==,iv:Htrqis0l71SRWBJIr5gRTbxx5vPEnTXVvQjxPZ09FpE=,tag:fGgLiTwPeq/Ga64Axlx4NQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQck9WUmJpVDBVSlFLZmU5
        MUtNVWFpVTNKVGc1MkFlUFZ6MWZjUWRWZFhVCmNSaWhGVzFEdVdVNWNoSFlMRWdS
        U2V0V3NqbE00ajVUL0RnUDltekdvMVUKLS0tIE4zb2VqU2p0UjBWaHRFNjZmT1Za
        SzNMOUEzejBXUEllcFBPOThpQmxLM1UKtlWq/ZNvSI9VegzZ60azzU1ufwQpUs/k
        3BTQYfEp8QPPxLvNUY9wcpmWRobhlE+xcx53fMZzDUEYbc7eSP7PUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T18:34:58Z"
  mac: ENC[AES256_GCM,data:oC3CdKkkj1sAwIb6muphnjMZZkDg7F5RgzgB67s2oXha8eKOYhaksmk9yuE6qe7J3GVqFSwi5plSYlqif5n7dS41Tpmp/FeAiJRecUY+MekM++tIKzqxQXnOa/35Co0l1eN6xAbQDKcbNK9Z5aLirU9G/9nNnLPnBe6CaMCMHXE=,iv:PZ5bNyvJTT9LTbOPdIzZlCJv1hsuwwBgNat7AlnyXfc=,tag:jYumsoV1OAjA9j9YBFvTQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
