apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
stringData:
  GF_ANALYTICS_REPORTING_ENABLED: ENC[AES256_GCM,data:JET0Nnk=,iv:nchOCU2AairoS7pOHPKM4CNy4AdAJDdz8nfDZ5R5NB8=,tag:eLp7k7ec9LQlpeTuPvsZKg==,type:str]
  GF_DISABLE_SANITIZE_HTML: ENC[AES256_GCM,data:nwvATA==,iv:GqponzommVcP1WZNIS2pbNnHzt+f7sSTjci6cLcED40=,tag:YB3F9YIDOdXH+SV5bcH83g==,type:str]
  GF_PANELS_DISABLE_SANITIZE_HTML: ENC[AES256_GCM,data:AEB/ng==,iv:0cVFctZ1s/kyRF1QPxhJvGQL2OIik9a1pIVej+sv8bU=,tag:OorLp093jClyAPEZE6OzRw==,type:str]
  GF_SERVER_DOMAIN: ENC[AES256_GCM,data:fwDdmXZktQ1NiwDp+7y/,iv:aE8St8y2Hcx2WCipZJ1xgolTQ9jND4DvaQKmiNrzHyA=,tag:WqVg2Xqr4WYGlyI+xzkxEQ==,type:str]
  GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:n9f+4LFZi9KTDJAsus7CrVI7Pw==,iv:os/Bt3NoX+wMD9J7nQrh5Krglh2EL/GAMTDDW/p4NWw=,tag:ZeG2b+7eiqhwPyIIg12Z2A==,type:str]
  GF_SERVER_HTTP_PORT: ENC[AES256_GCM,data:gSo4Ig==,iv:X8TWKF6PaC0Gc5QH/C2jrbz/0qGRdJ2+b3jRY+0uwic=,tag:pv2JQuBhaHEDRNzgU4KFQQ==,type:str]
  GF_LOG_MODE: ENC[AES256_GCM,data:ThePaZxtXg==,iv:5As7SCaF2+MkhSE8pNpYspkjUN6O7BncILdQyIqsEjg=,tag:pA7be++SpMlTJKvYUCTNfg==,type:str]
  GF_SECURITY_CONTENT_SECURITY_POLICY: ENC[AES256_GCM,data:MJnujQ==,iv:jsCVS/oOLBdFmekFWXGGeTuEJ2nnqMtgHKIxeVt6K54=,tag:OrHZT1/OzHbXPq2BD9buZg==,type:str]
  #ENC[AES256_GCM,data:KCGUnToMqrkSoy11C0DXI4COUTpxIm9zIld2nEygM4XwBqT85XACWBCHXqteJXFeqtxNNsYUHFA4/ixDh2dbq/ywY0HAglqsE0Iy0alND2dJhcIVd6O/Gdlg8ZyoQefu8WneBFUD40fNgILB9O2hUkBbDepNYC17iZTd/5ISsTZJB+L3hcQommG4cPkJSzLXEsyiVBhIYjxp2Nr1/DNBYIpytD8+gzCJOZJchf0A9liagrXFIfwaSVYfNVje0qzXdXedwRj97h42Lr2fQA15gr8IogxaMRDOmnYufGCGifS2NdDiHxM6XWIrbzz9XQm6diecqc9KIvuw6Bix9L0XuHWFoyYKOF9SUc9cTrPqLDyFOjuWNSccY3+fvpJA+u2u8++nrtLWsNt25mju8Ry49prPeG5NmRIIO22PXE95n0kCK/PdOcaOfpLJRg8LqoLQvKW75lBOH+U=,iv:jntNyGAnwYFtrab1g6KCSmkVsTVTXWBtDGa5jlvB83w=,tag:SIKh79rrReU65Zg8wA1FEw==,type:comment]
  GF_SECURITY_COOKIE_SECURE: ENC[AES256_GCM,data:WwWZKA==,iv:ylZQRahwgi6qcP3PWtQkQGRBTZoJbY9QcZElD9O12YM=,tag:wLLUXkG3NkUXKUGIf8LV8A==,type:str]
  GF_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:dSg1GSxghpqCz9Jvlb9Bn544UCgOLHCN2MFS81FOcnhQe0SFkysVMw5uOhAQLQ==,iv:+W43uXxzxSGD+YFVyAy2TFyexOXraS7CUixZSDDQaf8=,tag:L75bOzugZKhLhpkUaDCK/w==,type:str]
  GF_SECURITY_X_XSS_PROTECTION: ENC[AES256_GCM,data:j+ua6w==,iv:8yZsTfP6BKn4VOJoWfk7ON56WwkQdV25L4QbmBMVe28=,tag:LHDq1lJ6ypAN9W6tycs8Pg==,type:str]
  GF_SECURITY_X_CONTENT_TYPE_OPTIONS: ENC[AES256_GCM,data:lD5QVA==,iv:YqWh5CgjvIvWn854Sb6T7JNjdSAyKD8OSmaxNhWX00o=,tag:EpS5tU30MMH2FrHlYx9Lsw==,type:str]
  GF_DATE_FORMATS_DEFAULT_TIMEZONE: ENC[AES256_GCM,data:rynZKZmlKUK6DyG5Gn6DRg==,iv:FnX0YejMMFRExd0/aoiUTPZqKrbnQODgUdKgyL21iLE=,tag:WJ05AYuppZmN3rZa7x8zTQ==,type:str]
  #ENC[AES256_GCM,data:83PGgOxKi/J0SUXRAc0NcJxB8JFUus2gqrbs,iv:+xArT3wfTSfIoFlpdITb1X01aY961QeQrXvpuMSq3og=,tag:2BGZupjuyvZZ5+hhEhMmVw==,type:comment]
  #ENC[AES256_GCM,data:9GJJKthUfUMwShQK7YKkpOEDNp+T6P9MOrxG70rsMHVw3oQWabsOCJI=,iv:ppAH4D+J6L29egoK7K+Eew9p8csr2rG2O1inFjO3SC0=,tag:syxjHQ6GPCp1SxWNkQpOaw==,type:comment]
  #ENC[AES256_GCM,data:r3UOIl5Nu6vB25ogTFr5xtzdTiMHQ4WBij8=,iv:rWj3iDbAeuNCZ1wq6LHEiWydFBiBN8mQvZMwMW0txKc=,tag:jc7HL2RiO0zmjxoPtQvnxg==,type:comment]
  #ENC[AES256_GCM,data:RoWe3NPNkel9OhC3l3obvANfyjsrDQAZKbVLZEE5sfJ5v4aKGFiFf7goJa9Dn1S6lT5H,iv:3sz1MR79Q7udeRNmf6SWvv69pwLJ7eNlLajU17UUdLA=,tag:TPIbHlMopzdZc3ya+EIwnQ==,type:comment]
  #ENC[AES256_GCM,data:+7sSwjbdY3QvkwKbz18Ba3dkFWi2nAArGOv0z8W6,iv:ik7vzSg5uww+KlDGz+hiXy5NWQJ/4YZfeaZzW38FoEc=,tag:GoT3IA/OE4GY/1n6DFaygg==,type:comment]
  #ENC[AES256_GCM,data:ZHM7EvouxANLaA7HtvvGeqTyzO2kqIiHuAU=,iv:Rz5ENabVewhWhHVPfhMeOnz0zt4MkpLkLmaHClizTEU=,tag:g+BlVEnAOGXKoVYP1iKAuA==,type:comment]
  #ENC[AES256_GCM,data:6l+buoeqC1elcRvcJdDz8pMYvdG9KVib,iv:sq3BXEVV2ky4xshML7dlixwbhVbaTySliYiJ8CT9VYg=,tag:l9vG4BmId88u8QAEwxxV1w==,type:comment]
  #ENC[AES256_GCM,data:Ur/tv2JO++L4lP+Hh45hIIjchFSk8mTAPCZX/AA/e0Q=,iv:y3soFlQwoA4OqVnev8ZfNoPslsvFj6XW22eMOkjhayY=,tag:CBScF8melCZwhhuiCrrUgQ==,type:comment]
  #ENC[AES256_GCM,data:IJorL3VgdFFmW7xzah9fW+MMN7Sz2/FU+Lkc,iv:Z39O8mXJac+bCS8LIDAsuiABzCvtZBEKnyZFUcrukqI=,tag:X8I3v/r0zjZuyTAHmNHmgw==,type:comment]
  #ENC[AES256_GCM,data:Q3EXAXLfGnlc557hNwd/XwqOdwOi2PMM43pRrOrcATGPIlZ5gEcElpc=,iv:FtziYK+BCyR37OfWXVmHT8P9FXJZa9XjQ1hgD4ByiEA=,tag:rLiNFhvWNhimM9DIlcdkFQ==,type:comment]
  #ENC[AES256_GCM,data:pqIbvooQMWNbK0JgrJNVY0h93CpzoHnj386r9+y58AGkGpo=,iv:dMKTpOyutskV9JY0VK2PKrM64nGe6jWdk6W3hbQ0YuM=,tag:hYIg0jvtSc3TRNum97qoOg==,type:comment]
  #ENC[AES256_GCM,data:Teso9pFKKXna97mcvbltObNoB3ZENidADUf5,iv:B2XmLA+zYhmBb0BGGRu13GFi0ZYhRPVVtM03UH7Rc5g=,tag:HZExs+TVnzgke6jkXOwy7w==,type:comment]
  #ENC[AES256_GCM,data:IQlQil/wI5sVN48z2MB6Pksa6uXsw/pw3Sl4ee2ovvMMRpaCyemDQIWp5A==,iv:7/F3vhNvSWkg8SCI/x0ggD73Q4rNWkxhZ7FjAL4zhb4=,tag:sN1VVjUk2fZqNNrxkrncbQ==,type:comment]
  GF_USERS_ALLOW_SIGN_UP: ENC[AES256_GCM,data:U3NGo0Y=,iv:atsk9g8WzCmDRB9QEbwYi5kxBXvRX/LRvV98E3TrNzg=,tag:h6McznwxyLi7JDKJEPGgbg==,type:str]
  GF_USERS_AUTO_ASSIGN_ORG: ENC[AES256_GCM,data:Uaf3+A==,iv:4ZHMXhcPbxUADh7YfFPnn5Rx3bwvH7FmN62PV37ZU0c=,tag:ANQnL4UDc+sob01sU7FK+w==,type:str]
  GF_USERS_AUTO_ASSIGN_ORG_ROLE: ENC[AES256_GCM,data:G09FaC0=,iv:1W6QvJLbiFNTYF2QJIjb/DCC41rW0vJcygb3BS1QvLc=,tag:GHzGF5QFfGNWrKUH2g7EfQ==,type:str]
  #ENC[AES256_GCM,data:ufmRgufiCbryRYst1VUOh3NlpArjDPJXPd7rwm2b,iv:qMuKlac3K/xybTebw78TapB7rULj7qcb/1UNlOLEFt8=,tag:pMiZMjrjQrKGEW7UNVcMtg==,type:comment]
  #ENC[AES256_GCM,data:omoMCEuBxd7nXoN/US+35YMwP2C4GXCEv/hNpv3SX7vpT5XSq51LJVn4FaNW,iv:OVFHTLZh1vsqlnPHFUZlbTT2dF9HN5/U1N7Ebu8uE9A=,tag:9HamSzBwvpaQGkB0dZjrOg==,type:comment]
  #ENC[AES256_GCM,data:SZwWGacn6EejIvnBsyzXRuYWduu28c3f6eyJGtfVF9t2NDK1nA==,iv:/q2hjb8jh3NedXvbZ7XqmPTsj51A2ksTj8u1gSFaxQ4=,tag:qeytzkEd5Wdn739aJAaIWQ==,type:comment]
  #ENC[AES256_GCM,data:+HcvRCc6l83NhA87o6OiCwllGokZ+zf38k5I4SFcn18OHUc=,iv:ULk6ayj6dV0ahvN0PzAvqa7Dd4X4HfuG+A8/li0mqHI=,tag:9iJ77HKXMgKqG0ISFtvNbw==,type:comment]
  GF_AUTH_ANONYMOUS_ENABLED: ENC[AES256_GCM,data:aFbm9g==,iv:hksmQ9jcvgpJh5XuBFVOjphuzaFPEgbsE2DbiTuQnIo=,tag:YZlLhAPYrH6qr6IcAdcpHw==,type:str]
  GF_AUTH_ANONYMOUS_ORG_ROLE: ENC[AES256_GCM,data:Xybq+XY=,iv:uLmGZcHyYimH2cS71hJpL6NJqw5pEg5TKDPfmUYnEpA=,tag:tpXhw8fm/ihbDnzqReLDyg==,type:str]
  GF_AUTH_ANONYMOUS_HIDE_VERSION: ENC[AES256_GCM,data:9WIIxA==,iv:pQN8OIcqbM+DNaHp2uyDKxg3YRWVS8tVrp/CEeOgm/0=,tag:ZCIQhA+4sJNFPUMX91m4IA==,type:str]
  GF_AUTH_BASIC_ENABLED: ENC[AES256_GCM,data:UN9fNU0=,iv:6Ri/074+UrGP6YpDOidaC7xrjtIlB8xsWcvudj0CHeI=,tag:3bITXMnGwA+nP1+lTmszyQ==,type:str]
  GF_AUTH_DISABLE_LOGIN_FORM: ENC[AES256_GCM,data:k32TMw==,iv:Dndw5UA7M1NNwzzVLUWz6iceTQR5e9yB2GhDn8NnB4U=,tag:6rqD3f9SViprBCKExN26vw==,type:str]
  #ENC[AES256_GCM,data:dw1KqB6f9IYZFg7dOfBMSLKsTGsrZVjW+sbCLhPJfz4DqX0mASYWBT5JHhUE6aNMpA==,iv:OuKDrQElcA47Y7tw1UDj4wKw3/O1yx2fVpr+jlT29iU=,tag:fqjaubeeWevqJDuHs45wtg==,type:comment]
  TZ: ENC[AES256_GCM,data:izjmjSNH4ZCEEt2zEIkAXw==,iv:U5UggAwvjCV/DUXOORyf0NJIV9b8NF1f2yKua4kmtWw=,tag:Ji+n6zZhDB/t2M0jUFQG+g==,type:str]
  GF_REMOTE_CACHING_TYPE: ENC[AES256_GCM,data:+LFbvak=,iv:K30XvAG9jltFlMPEPkGCB83pHuz1k6BmO029VZ524a4=,tag:KDpkRS+tIZe3TFa/hoR1yw==,type:str]
  GF_REMOTE_CACHING_CONNSTR: ENC[AES256_GCM,data:hyvkNws=,iv:BrR/4mF6YQ25rWSDNHxGiSG3LK9TMVFy12ueRF70Pws=,tag:h3nnVpntAYdhOfBZHfNnDA==,type:str]
  GF_REMOTE_CACHING_REDIS: ENC[AES256_GCM,data:NwxnhLmZb2cxIeWpWQPdpVuO0BHGGdYXZXIQdtvRosi1K6uL8vYjkHCk4nTCdzbGXNK2PSdAQu8vAfyH,iv:KTu7WeqBckDdpx0+m74UZ/DyiPX+6VD31EfH30pnr1A=,tag:lXOxLmASiyKLDXu0WkRhFw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK1daL2lnSnp1czMxVHpi
        S2xZaFBPTlVxUnI3SjFWSXcyZUhacHEvdVJBCnN2N1JCYWx1bzBJTktnR2dha3hL
        RXNRK0dFY05Vc1lpL0I0d0EzM05zeW8KLS0tIEljbmRqUGpLbWxMeVRoSmpaV0xj
        Y0FyQnhMbCtpK3Q0ZXZJU2FSMzNOSVUK6jY9YN8lPvENw2TDivbcYea5GudQzaoD
        lk6XJX3fKJ2GVXTz0eprZQwBHGZo/V45AEAJyi9mXpQkW7WywmxbnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:r7hQK+lxpUY1Cty7mTMWmAzP//0FEohkwqkoMrIW4SPtr0Ey5P4pYusenk2TpmYXfEPZrGgbZpJGWhIsk/aPYPHCA0kvvybxqyln2pdgYbwt4CZq+FrNRJe0UxrrNjxrTOzROeqbX3uKa28P6JCa849U10mTdEcL4zgyEjTCP9w=,iv:EYPwV2Br1VXeq8R5FGZ6izqo0WzF6Igv23uFmQzNeKo=,tag:L0bz6qC/Garw/bGgYfIrHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:PcPSK0mTTw==,iv:jMNmuLfkXSM8vUc8CM+kkZ8WocKFgNsFRaeuh++oz+k=,tag:ENc+uGC7H9En7YmIgF2vNA==,type:str]
  admin-password: ENC[AES256_GCM,data:5n7j49Veri0nuApDyWWAnQ==,iv:KEzMyHYHvDo6t4puNT3DY1sn90uPgdUqPETRSQf//iU=,tag:zt5xm4zwG0VTeHUrWq+5ug==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK1daL2lnSnp1czMxVHpi
        S2xZaFBPTlVxUnI3SjFWSXcyZUhacHEvdVJBCnN2N1JCYWx1bzBJTktnR2dha3hL
        RXNRK0dFY05Vc1lpL0I0d0EzM05zeW8KLS0tIEljbmRqUGpLbWxMeVRoSmpaV0xj
        Y0FyQnhMbCtpK3Q0ZXZJU2FSMzNOSVUK6jY9YN8lPvENw2TDivbcYea5GudQzaoD
        lk6XJX3fKJ2GVXTz0eprZQwBHGZo/V45AEAJyi9mXpQkW7WywmxbnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:r7hQK+lxpUY1Cty7mTMWmAzP//0FEohkwqkoMrIW4SPtr0Ey5P4pYusenk2TpmYXfEPZrGgbZpJGWhIsk/aPYPHCA0kvvybxqyln2pdgYbwt4CZq+FrNRJe0UxrrNjxrTOzROeqbX3uKa28P6JCa849U10mTdEcL4zgyEjTCP9w=,iv:EYPwV2Br1VXeq8R5FGZ6izqo0WzF6Igv23uFmQzNeKo=,tag:L0bz6qC/Garw/bGgYfIrHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
