---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oauth2-proxy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: oauth2proxy-secrets
      valuesKey: client-id
      targetPath: config.clientID
    - kind: Secret
      name: oauth2proxy-secrets
      valuesKey: client-secret
      targetPath: config.clientSecret
    - kind: Secret
      name: oauth2proxy-secrets
      valuesKey: cookie-secret
      targetPath: config.cookieSecret
  values:
    image:
      tag: v7.13.0
      pullPolicy: IfNotPresent
    replicaCount: 1
    service:
      type: ClusterIP
      portNumber: 80
    sessionStorage:
      type: redis
      redis:
        standalone:
          connectionUrl: "redis://dragonflydb.databases.svc.cluster.local:6379/5"
    extraArgs:
      provider: oidc
      cookie-secure: "true"
      cookie-httponly: "true"
      cookie-samesite: "lax"
      cookie-refresh: "1h"
      cookie-expire: "4h"
      set-xauthrequest: "true"
      set-authorization-header: "true"
      pass-access-token: "true"
      pass-authorization-header: "true"
      email-domain: "*"
      skip-provider-button: "true"
      reverse-proxy: "true"
      real-client-ip-header: "X-Forwarded-For"
      silence-ping-logging: "true"

    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 2000
      runAsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
    podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 2000
      runAsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 5
      periodSeconds: 10
    metrics:
      enabled: true
      port: 44180
      servicemonitor:
        enabled: true
    redis:
      enabled: false

    # Store sensitive values as secrets, not environment variables
    proxyVarsAsSecrets: true
