apiVersion: v1
kind: Secret
metadata:
  name: oauth2proxy-secrets
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:KdflxnMWwGOfj6feVvZcNepO3NOTFNN70Hi93ZZyUQ1Pryjm59svi+kQMWuD+J+srGB3msHcrPsxcO08qxhk1+KCdBU=,iv:v6NDBDM+vlL0sCtSROVw5dmzPpzFPdE1sIWH2ySjB+E=,tag:TEL41hQEJfbED+btZ3OnSQ==,type:comment]
  client-id: ENC[AES256_GCM,data:ztRGkwZWo5rHos6dw1uo5wWv/d4XXxFbz/kijA==,iv:rWol0qchmnW335IazFrXVobWSyOPEFamq3e4t4TrdP0=,tag:UNvHpQ1iiU7uG/Ve7lQLZw==,type:str]
  client-secret: ENC[AES256_GCM,data:0Gie32JI5AsgBDYtQ+MUdiuugmyoL/40skuuTqfsfTU=,iv:2ee8apyf25iMFXi3nq7maeOzjZzEJKuQlSQUfto7afY=,tag:z9bQwuKLqbMnVcthkvhDxQ==,type:str]
  #ENC[AES256_GCM,data:HCKbFvVrGh5fndZiVJ+zvCnsvv/dySnMOWir209u+GDYvKxU1pNNZL3DDNvSaDQJIXTsLU64GhtR/NmdplSo,iv:ekWI1A1RlVSFc8HHp2y3zL2In1Tzi3D0XI6FXuvn8PM=,tag:7yf30cDUfrkvSR6OK/4MBw==,type:comment]
  cookie-secret: ENC[AES256_GCM,data:IY1q7Q34jMPCoLg8KmSHThtg0f4Tn0wRx5vwhoh/u5K9G8KgItTOCYxD/Nc=,iv:I+lmbrkVWTSv5lPxdwc+tOrI1iEZvXlYpV3LToYYDWg=,tag:DpGBkC9JZ3+T2AmkI8Wmqg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U05lRkpQQm4zQjJ6SXVK
        cVlNUWd4S21QUmx2VWgrVExmWnVzcnArMXlRCld0dkhiSGhSN0IzVUJDaHpuWU5w
        ZDhRSmt3a3Z6MmhJRW95MkpndGRuY2sKLS0tIHVQY1dIYlFnSEFFa0J5VXk4d0VT
        T2RoN2FVVGV1V0x1Q2creEJzNGlhdmcKSaaQtBEWRJOLMAXsdEXlUrxIiUL91kAN
        0hLTu+8e+oOD6oftdMJe3cVHvPqcCUIQ5/bVyYBgYlQtzlfmzLBnNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:XDLQBfgzP/ACVZENfSlREKlmiL/Rnin63tdYIFV71L1EUxQEpmmCPZ1mJWwTCNgyaYtjnqtlh3qHIHCf+SlRf02fhKNzu8RVgeETEFdXxUKpIo09r4KOO+P9vqI1NQSrMP9xApE5IqQ6X3y+WWJDhbR4fuPz8HAlE/sdfBhiU3I=,iv:1NfX1WE3Hwts0hCp7Nl34/oRv937mSiDvO79M69JhMA=,tag:C8ahNQ6EoFAjRzjlt2WzRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
