apiVersion: v1
kind: Secret
metadata:
  name: oauth2proxy-secrets
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:HS8kyAAziHAWZHK46rCpPrrIJ9njVG2Uhyec0Czc9Jyi/xiS/c8JLnvfoxAs0ea2udJ9SxVmtIbMwdnGgL8to0RokaA=,iv:bINns7Zsi5s4Zf9FgZMzHcYcaOWc1ulJNee8m0Xek6s=,tag:Sn/+e79GGTN3R6JVj9gy9Q==,type:comment]
  client-id: ENC[AES256_GCM,data:BpdLCUCTUfc8KR+X6i+joneT9q7Pt8SH5gQy3A==,iv:wkygWbewYjkvi4GFfoMfKifjwPLrKh0C6uiLGGqcbgQ=,tag:t1+5uwzzLmUxjsS4n8L9/w==,type:str]
  client-secret: ENC[AES256_GCM,data:msLmo1+ONbyv2LEpurbF90Tm6Ti4f1DjoqNNyDKOijE=,iv:K0P2KtrCEtsS+faNiRlG2pJ7csCI2UHhy6GAV175NiA=,tag:X2YkhdZSWMCDM0FR0rBTpA==,type:str]
  #ENC[AES256_GCM,data:z3k8gIGXq45C3JgVE8khxTiXMMTopfregvPEZ6PvB90zzaux/Rb1kMLJHofqyHWVpM7WJTNgqy5kfPb1cLm0,iv:M8tBP6cH4CWbnKxC8JcUPm0g1pMvAUGUxjag97nc9FA=,tag:TU6z3/JqFJ2Gmi7y9/h3AA==,type:comment]
  cookie-secret: ENC[AES256_GCM,data:RWNKmCt9xJFh2ennJJVm8IUC/jTp6T3jGypQjk3i+7qPOzqsvn/MxBYnFk0=,iv:XnvhmHCUmGaP9ZpTiI3Dr6xcjG4NpzfGK87AZVNol/I=,tag:63DaJMPldDl+jaFzSEuUgA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR3BzVjZ3R1FnN0VRbG1W
        bCtKZHNnVG90Q0dXS044QlU5MWgzOXpIaFRBCklzL3pVYlcyM3hPcTFhWkRLWjRZ
        RWFoVXZBM0gwZktyTHkzbTc2b0N0TTAKLS0tIHVwdU80K1hacUI5VUZYaU1qQ0pi
        Qnh3ZlNaZ1FvTFV2VDMvUVZHall4MmsKU0VRKzXbtaqt0wfmxjM3cR8JQwQqO0BN
        HZuP87HvTv3T6OgJqgXiUvdxWxf9M+G/lxasF+03BWP8gg8NLItPzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T01:13:51Z"
  mac: ENC[AES256_GCM,data:fUBMr7iB/NkzGeMOsCe9V7S18oNJJVUhZUgzlIhmbKe/kPG4dX8LTVCz+/gm7WGHn7GAG+CAPzQ+Xingj83LRnKEZb0gfheGzCDcdK3XvvgBLBil52KQHykzeCI/C9ph4CYiSZiBK8cz9lAB7rBgs946p1pSABTlAoqqsVnmla8=,iv:JSiiqJuNTRU58qmI6Y/2z226V9sCTbZ1FuZooMphZFI=,tag:nJoKTu+o+QlJaeLqFX2Ulg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
