---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-barman-plugin
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
    tag: 0.6.0
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
