---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  chartRef:
    kind: OCIRepository
    name: mimir-single
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: mimir-secrets
      valuesKey: access-key
      targetPath: config.common.storage.s3.access_key_id
    - kind: Secret
      name: mimir-secrets
      valuesKey: secret-key
      targetPath: config.common.storage.s3.secret_access_key
  values:
    fullnameOverride: mimir
    nameOverride: mimir
    replicaCount: 2
    gateway:
      enabled: true
      parentRefs:
        - name: traefik-gateway
          namespace: network
      hostnames:
        - mimir.68cc.io
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2
    config:
      server:
        log_level: info
        http_listen_port: 8080
        grpc_listen_port: 9095
      common:
        storage:
          backend: s3
          s3:
            endpoint: s3.68cc.io
            region: us-east-1
            insecure: false
      blocks_storage:
        backend: s3
        s3:
          bucket_name: mimir-blocks
        tsdb:
          dir: /data/tsdb
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: mimir-alertmanager
      ruler_storage:
        backend: s3
        s3:
          bucket_name: mimir-ruler
    volumes:
      - name: data
        emptyDir: {}
    volumeMounts:
      - name: data
        mountPath: /data
