apiVersion: v1
kind: Secret
metadata:
  name: mimir-secrets
stringData:
  secret-key: ENC[AES256_GCM,data:Ime2Oxtq/8SpMZLIavgYRA==,iv:XWb7EFlymwSQPFPyWmUAe3Uip1yYrx6YqJs+HtPSqmo=,tag:YieNHKTyxpzO2TsRBbs2hw==,type:str]
  access-key: ENC[AES256_GCM,data:tsLqiryVnEoXHRBy2Q==,iv:ufTJkAMJSx7Z8mK2pKju34rFznntPpEoMCe1Mg0Lrhk=,tag:JuL6HerhtjpjBkllmIluDw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbU5SRm1Oa1ZrZEd0M1ph
        UlpjemRJNjlTdTJ1VUl2aUhZM0hZdUFPVTI0CmdPMnNxSmowNUhPQVg0YWNHV3pY
        SGlrTkFnWEVWZkkzaS8vRzVWM0dxRG8KLS0tIDhvalh2RlpRODIxTnNTVitBVjdp
        WHAwcUh1Y0NyMUtQZTUwbVZuYmVWbU0KO+Txu6gGUFW9ieuwtzJ+7HOdF5domk0l
        Nu2oQyuKF1mQ0LtNjx6AscGbgR89xcLDSEMH9VQdZM4rl1f5BDrnlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T00:36:40Z"
  mac: ENC[AES256_GCM,data:m4hF4DCrffwGMFyEljz7LN76TEciUr8fWdB5lXPqeVKmCi/DSgG08m/J8THet6etkeBim3KozQ2q/WHmsdY4v7JK5V3MmddoYz2STOY5t7G9eHp7f9IjbVM/WiZWbHfXpYqu9faw5YP15zZFrfJuCneJZm9t/7rKIAKlkh7oTv4=,iv:yUBHcPYBi+5MLfisZlT4S0zUX3KI7QmTmiiodiSKiec=,tag:pjQn+nuUBwpH6O6OD0zqyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
