apiVersion: v1
kind: Secret
metadata:
  name: mimir-secrets
stringData:
  secret-key: ENC[AES256_GCM,data:yEMmMAnH0Audtfxc2Drx3Q==,iv:wnE3qXoCNHWjOHEfZ3BK7njT4uZ8td/zB8V/MvRzUws=,tag:90AOyMW4lBUSPIaG2bjBNA==,type:str]
  access-key: ENC[AES256_GCM,data:lurI+/obvfG+9yTDhQ==,iv:+lGkyZ6uEU6ihkUkI2KqBRFbfDFibO6/B+udNS+YWcA=,tag:bH9NxKGQkR4BoFJak3fjoQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbnpCd0xkVjQrMVRUVG1v
        NVh6ZFkxTDNiSThkU3RSZUNNQUg3ZGhCalNBClFYUVhDRnMzM2RBbkxITmNzWWI2
        blZLb29rdUNhYWtYZjJTL09PSE84WUkKLS0tIFpDNkZJazZHVGlFY0RMc3A0ZzRH
        RDdkdEFXRmZpVzM0Rzd1aVdsTDVpdEkK7NVZJcFbBFxBwqNl4MyLGoazgF+Je/bm
        qjrDyjO5AD2NViMehXM8LUSFeKzAoGu++Egl4r0y6uX3ebqIDyoqdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:OEw6+mqQQ9T5ems9oONJ1NgtQhC2HHkIy9NSdSm8x/0smoq2k/9JX4cJpct0Nqu66hKkPN3tH+PdrdklilewL1nLkQJ+0UTY4CnFWjfiRHqE0PmjwVhzB7o961YieazHXk9UIUNuti7rCIREWkzF2Uh1f/c21TyKDBUuCN/XJnw=,iv:us7atT/NiLWoxbK+a0lQkLxfuai7ohcDtG9/BIchLPs=,tag:iyBMFnJ+81kNmAEX8lTYkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
