apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
stringData:
  DB_TYPE: ENC[AES256_GCM,data:4mPTycP2fotFjw==,iv:GtOL7K0Xtp/X1V6UdyD8sZEcez3lIqHR4O0N5BULIdo=,tag:Pchx6+8W/8lSyPl2Eygpng==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:Ogtl,iv:xUJJSCkXJpRxQLqpAlwliFcOW7W0cagNvwfim3pb0U0=,tag:YpqI2gzAVPEjeDXh+VMHOA==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:UUB36xckQ+KVQ5uFuusHpOeBeTHc,iv:MbLL8//uWBUz1KU16N+99f5il2G/717XHNZIxUALUlk=,tag:YUVsNL+4pghKrIhP0jDYcw==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:G7EQig==,iv:ABDk0GEQpSlpJbEjMDdNjH5LH4UPPsbK6PV+kfan/J8=,tag:XgZxIKnI+8X2DYXfjQiNAA==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:rDxY,iv:MpPl+Cy/dvwAQpbZTBa0a4vYR2KoROvKNh9IsYbMqOE=,tag:Nzmt6Rgrut6fCkPryNZPew==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:k/vuvlhPm+XJTKVZ7xo4ThTjhSHKMoW0JHZoG+ZKP9+JydGWoH8v5Y+ihbRUpxnacq70z4LzkwzMEZlEVIJUmw==,iv:FfypNU7mn7rhxZtpiqRP8nzPIa15nNnxZq10AFWGFug=,tag:vCPtWsk6zbQwPBI0p2Ehsw==,type:str]
  DB_POSTGRESDB_POOL_SIZE: ENC[AES256_GCM,data:jg==,iv:EKyyEZiAgOpNNV+yKlZ6wYp75Ws44FUvp1j0nJwOKEU=,tag:ns5sQtacmym6mgGNCZXIcw==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:d6wob13Ul0Lh5miKtfPyfsy6Ddo2ajLsT1W8RLA9hOpcZlfXONM54UziT15kc2t6T1tu8lQJ9B00nMbJPHA1Tw==,iv:DYTVTyhsU4W7a+5Q+HF2vpcSbzp4fgX4Nd8jcwFvASs=,tag:yaU6F/QDscVJojTzxDxPBQ==,type:str]
  N8N_EXTERNAL_STORAGE_S3_HOST: ENC[AES256_GCM,data:aKuxK+DTa6aTq4wCKcMNZ4eK,iv:QtI+dpOYX+cuCzBsvGnhd7uLPikKOJHoyr1M6DdUFIo=,tag:ZgAXgoq3b7KJ7yZ2O04n1w==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: ENC[AES256_GCM,data:G0Bm,iv:NUPN/alBVATC/uXrws/V5bWqPKOZdVI44/EJ9dUlFMU=,tag:rMVJNehCsecqXQsMFOTCXQ==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: ENC[AES256_GCM,data:dTLwBEOWeaIV,iv:T8x8k8LV/0gR0EnTVO6hkHNIF64L4ZDVOWCNjfqM298=,tag:5mBY+OxXmx7J5yYr6yDjrw==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:yoC5,iv:CoL03iWSr7y6h0aczBXfKE6ildKxeIvzDW5PhhoW6IQ=,tag:LXmIpkYOSLz/I+ZPRahM4w==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: ENC[AES256_GCM,data:fjhd2+58IS2D,iv:Ur7b2Tv2R7OXcU7Vy480JndRfgYJPq0QH6uY/o3BMv4=,tag:GHqoGbo1WZANIRT8kpp4GQ==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:tT1yBxT/heqC4MvR2Kin0Rq22yjangOPG4Jwyz+jDJ9ekcOPfxX6dL6OB9muXc65bBuniCwEs4jlUqGoKgna5w==,iv:Am1um7EsoXjuZZKWTYwespBpo2PxroG6fPtesT/37XQ=,tag:zdV3Xsh6VSpwy0oAItgpYw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:k3Or,iv:saekeNJDlY1C/IG60i2Xt6aOD3DYZVWCe2K0gjXqD6U=,tag:B3+qbXmiLVz20O7Kl+39Dg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8vZAmfkB1Px/RSQNaua8e0oyAn0W3f/mC5Fj9liBICOpXmqV0VZS,iv:WeXL7jNK8TwH4LL5aCTxaR8UWhfYN4v4SEa1kgxMIDs=,tag:GsH6KMwFRQa/3X98aa2A2g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VG7P,iv:kD+aTYRuC5NOSPSa82FqzziBf7juRobsVdlHP12CJZQ=,tag:0gqRZxuCIahCZQ+/oxvK8A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:goSuea/CozWVvaeEmNGjCD8lGxD7AWd1ZB03j/S7z3PkFb7INqJp5wWfC0sMzHXZ0WyRiX8JYLVvyAjzQwcx/A==,iv:TjsA/fuoZ471Ws286ZJhZ7Drm7aSqn7X5QKi/UDN/8g=,tag:ChhZX67X+0Djqyz+fViayA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:e8lwYeoAczym+ip9+HA=,iv:+Phlu9e7/5PTeAHcusqSEvgmG4kX3CvPilLKIeROi2Q=,tag:+kUx2is0L06I1Kt1fzHXkw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:xsjaf1LWflw=,iv:fRgEkmSwzYYzPGu96PhV7FGVjxzzi7hd2S3BPzlIIQI=,tag:a4ZFxLN2yIIiF6isUvztfw==,type:str]
  GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:Xc2w/ZVAObqgvE4q2RIIRfcMzkwPIIOQdi3RyWwY5/a0aP38dBr5r4NVzpA82qBX/6FifAWRyCGIE9+/zTeFwA==,iv:xYsCGDX0jHCDgLQzZSAL72zrWrJry1jpnvyCFYVpGaE=,tag:otUa5kRoxqtzc2rV/7qbaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbGUxejFHMUM2ekdKcWVp
        cm9ka0t1d0ZrakN1ZjRHekRLT0tLNHJIRmg4Cld0Z1Z2MzZLZGlJaFNveTI1dCts
        R1l3c1hUZC9xQjVYaVhzcFlvQ3dVTmcKLS0tIGl4eUlzNDhjSmR0TENRMXVDREtL
        U3FleGMyNVZaQ2lYQ0dEZTh5NVRSOUkKWt63lX2bE5suf6VyOIGcsbHJ432AIT6U
        JdT4sIFY9wBfeNaVVOAcgi/AWjN3zvzUJ0vg6GfLS8SCkvCDiVzyOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T13:50:21Z"
  mac: ENC[AES256_GCM,data:4GZSILuxaCGyUkMaVdhO7fQYXgsxm7ZGBx05O5JZifkS6DYaWL5MWZZkAyD6n/k8PmVUfZjep1KfzgDF3ZhDg931pfPKJ1KdowfCxSBgBIxh0M1AqKkP4g+c+QmWpQzRXg7JXAmqq/CHzpqaYGQmTdiI+yWDNwEMOPnrNeVgW9Q=,iv:e95bLVdchwQs2xsaPqKRYdR022V9qVtLKKtNmybNhA0=,tag:yoqru+9m/WsCSxNNANW/xg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
