---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: longhorn-secrets
      valuesKey: LONGHORN_INGRESS_HOST
      targetPath: ingress.host
  values:
    image:
      longhorn:
        engine:
          # -- Repository for the Longhorn Engine image.
          repository: longhornio/longhorn-engine
          # -- Tag for the Longhorn Engine image.
          tag: v1.8.x-head
        manager:
          # -- Repository for the Longhorn Manager image.
          repository: longhornio/longhorn-manager
          # -- Tag for the Longhorn Manager image.
          tag: v1.8.x-head
        ui:
          # -- Repository for the Longhorn UI image.
          repository: longhornio/longhorn-ui
          # -- Tag for the Longhorn UI image.
          tag: v1.8.x-head
        instanceManager:
          # -- Repository for the Longhorn Instance Manager image.
          repository: longhornio/longhorn-instance-manager
          # -- Tag for the Longhorn Instance Manager image.
          tag: v1.8.x-head
        shareManager:
          # -- Repository for the Longhorn Share Manager image.
          repository: longhornio/longhorn-share-manager
          # -- Tag for the Longhorn Share Manager image.
          tag: v1.8.x-head
        backingImageManager:
          # -- Repository for the Backing Image Manager image. When unspecified, Longhorn uses the default value.
          repository: longhornio/backing-image-manager
          # -- Tag for the Backing Image Manager image. When unspecified, Longhorn uses the default value.
          tag: v1.8.x-head
        supportBundleKit:
          # -- Repository for the Longhorn Support Bundle Manager image.
          repository: longhornio/support-bundle-kit
          # -- Tag for the Longhorn Support Bundle Manager image.
          tag: v0.0.52
      csi:
        attacher:
          # -- Repository for the CSI attacher image. When unspecified, Longhorn uses the default value.
          repository: longhornio/csi-attacher
          # -- Tag for the CSI attacher image. When unspecified, Longhorn uses the default value.
          tag: v4.8.1
        provisioner:
          # -- Repository for the CSI Provisioner image. When unspecified, Longhorn uses the default value.
          repository: longhornio/csi-provisioner
          # -- Tag for the CSI Provisioner image. When unspecified, Longhorn uses the default value.
          tag: v5.2.0
        nodeDriverRegistrar:
          # -- Repository for the CSI Node Driver Registrar image. When unspecified, Longhorn uses the default value.
          repository: longhornio/csi-node-driver-registrar
          # -- Tag for the CSI Node Driver Registrar image. When unspecified, Longhorn uses the default value.
          tag: v2.13.0
        resizer:
          # -- Repository for the CSI Resizer image. When unspecified, Longhorn uses the default value.
          repository: longhornio/csi-resizer
          # -- Tag for the CSI Resizer image. When unspecified, Longhorn uses the default value.
          tag: v1.13.2
        snapshotter:
          # -- Repository for the CSI Snapshotter image. When unspecified, Longhorn uses the default value.
          repository: longhornio/csi-snapshotter
          # -- Tag for the CSI Snapshotter image. When unspecified, Longhorn uses the default value.
          tag: v8.2.0
        livenessProbe:
          # -- Repository for the CSI liveness probe image. When unspecified, Longhorn uses the default value.
          repository: longhornio/livenessprobe
          # -- Tag for the CSI liveness probe image. When unspecified, Longhorn uses the default value.
          tag: v2.15.0
    longhornUI:
      replicas: 1
    annotations:
      reloader.stakater.com/auto: 'true'
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
    defaultSettings:
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
    defaultBackupStore:
      backupTarget: s3://longhorn@us-east-1/
      backupTargetCredentialSecret: longhorn-secrets
    longhornDriver:
      log:
        format: json
