apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secrets
type: Opaque
stringData:
  VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:AP57PVNs8J3Nr44IZ6YkghuA4RHJsSvUhOnYizLONhf38KRYY7gY/Bf9sp0HqcZtgPgdOWkWYkanq38Yly9VJA==,iv:lfOsZlgmBbIIjdoORO3NGOLXJ//6mVmjgxhAbTb2ygo=,tag:5zZ8FMgXYW7l4cotVXF99g==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:2tvNFkAlHbmQQKfNbvuqW5a/bTbIu3dyEGLW+jWS3tz5DeLj5JPW,iv:7TxPp75bY46syKEM+RL4uvtUlV9Sg8vHwLMnl8QQx5Y=,tag:QI0gQ2VetV0vYpddV+kYrg==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:1+yn2PH/qQ==,iv:+0gy/ylbvrn3xyo9Ko2WLHmh15OVFZMFPAcuFm8yKwE=,tag:NDWEDUO0hzbUk4LC099OuA==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:cmfytUOiwA==,iv:6GszK/9zxJS5twL4cAv/0sXi8g+e0dpP67SDn8dvMRI=,tag:xAGJg34ZZIeikg1foOTxVQ==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:Jz9EnfTPARJu1HgNLnt2SizvA3QZ35oawSh/iyVxy1vd0KStdKyCF6OKH9G/H23a,iv:JZQclvVtgSNZFU2VPXJ7D3i0YjjPV0V2ilT0KegzxWE=,tag:X7e5DqtwaRqWjX8pS3eikw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Pjb1T8GkrcqXrWldPntwV+FX5xB9vql5slbXaLMXnhhD6QzqZQTv,iv:jczqixPn2abLUYy5Vns9auYNVpuS3bmweiIqYwdv3IE=,tag:lcY4u824zPmYabPepDMH6g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4x3WB9f8SA==,iv:ulqsAd63cV5N2v9xa2hdyImv4Aa7nmCkD+8qy+h65TI=,tag:r9QzX0uG8qwcWXtnS5BQTw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:9JYNP2nhGw==,iv:c0TsZkvRy9IDkFS9VgGWlVo2vNnU0m1unJ2aThwuK9g=,tag:hKzYmb8BXflVqlNiEQDNdw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Nx83N562x0Iup35ZZ99KyKeazJOPINl9T9NYjoRIMYNJDG7uRDTwC/i3VqCVoJ0S,iv:qOyABwPpIsDhh94zB7wtBEzaMKS+t8fdWCK2XKKdb5o=,tag:xecmi+RJLhwC2XdLonZgzQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:lduRCBdqQMk=,iv:EoxKW4HPgdwFV6MfaFwdD5LBDhbRF3MJNvyOyTFdcTc=,tag:QOHCcSwvVIsmJINR8t/BJA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wTeGVIc+zU8CAkVaz0k=,iv:MjzHxMFbwQjLTXPy2L7HzeV/B3JdEph8Vb6DwhwWgzw=,tag:5qdc1sQksDk/PD4FASXDNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaUhBZitDaDF6Zk9aaHBl
        SU9kYkNGUUdUdC82WGtFV1pQeHkyc3dIQ0c0CnJzaFhYZUZjU2lMMk1sRmVXVjFM
        dzBwYnVzYzlJanV0UUd4OHhmUlhiZmMKLS0tIFZHRjlLVHVEUW9XcE5LWTMvV2NY
        S0huRUFCdTZDUUdSWEdFTzU3OGF0TW8KC/AkMJxE4tq2k2UwzYFwAheFNSKhwiON
        z/fLExEXA4CBiLrfoO9rtVPrTerc8MYZYN8LDfFZ2TokQsShxsjgUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T18:01:45Z"
  mac: ENC[AES256_GCM,data:fLELhuqdVqidsEipYpTOx9TAZWCtS6w+roshbQCVKxxxlCjVq5xEgVDWyvaiv2zkstCgjqNFPOpkvzCQgb3iMH0GQKXlPQYpclMnRug3CklZvvSVG9yY2q4PSK3RJuRfi1y9gqlSsOzkwKYu01ikFi1X2ehiksEF6iZfVo2azxY=,iv:tFsoorBN/gsZd+GBLiUASM0wKFsmjtD8vcjkDupzp1U=,tag:z3KhOF99XSWA4J44+LiA7w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
