apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secrets
type: Opaque
stringData:
  VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:kJCLmgiWlnobEb6/aMrrdPjL1kpSVSh3XKnpiTzJky1cN4e2JxHR/FJCZ89l51T5b/cxM5mBCq/d/1s1BapZ4Q==,iv:2xESvS4G3s2oLAKQ2yZjpuxtIVowPsTql1lgs/UIcLk=,tag:wc/nSLYa135j+wiBk7oY9Q==,type:str]
  VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:wnqTpEsAETv8Ma4hYzBemLbicBwrJA8zhaJ8SFkXfWhQjGeYBc4P,iv:Xx3urbGTWntTYT7Q26z1s6SGwCtIRQ40RytsO5c8w2o=,tag:Y/8q4m1RcDzsgAUG6bHhoA==,type:str]
  VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:+dc0fC+gBA==,iv:QDenmoOih68dkw1W9bMZUbK+guLyOoKML6m5insV514=,tag:k2VZoSvv8+jjfgppNdsC+w==,type:str]
  VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:EbWL1N59qA==,iv:7zLwwj3q3QQq85oChiT+DbEqq8VT6A8XtcegCPaBQOw=,tag:wUFOBwC/1ipreHnFLFna4g==,type:str]
  VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:s5rgF319Cwo7F8Q7AlB82TrVbA7j6/CVdQYX0bBhjN9pdlpFQiEgDpf7yTB8eXsQ,iv:nMbgfkICx3ZCLDRLpKjnSuSbO/5dMc5RZxCqh0KJShg=,tag:/gn1PMSM77V9EeDUbs1HUA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8RJuN50voX+17Yu7N6ticxCp27Pw/bCEeW68LdB/TI2q8vjkkskl,iv:Sm42cNSJtK8OOuY8aU7LdFmAiOLAa/8w6fxzp3qcq1w=,tag:DTv0VFoeXewEbwmx29PIug==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:x7Fr1DGRJQ==,iv:nVy6VsLikyOqshY7CTlHIpiD3pIwEMA1z70xP1FcwRg=,tag:0Qa/c48JjFF8BvKJQ5Gjkw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:mETS9nfYmw==,iv:KwLuG2pKjr1VEWkceaf6BlaGoMCvcVykglT00WTECfA=,tag:JIZTRaq3SjndIsML4lmrCg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FesqNmaHFFdVMbFqWoE/XcDVqBWZ8Is+/pBNWtv1/qFBA4/XlXhvESf7Cl3xJc8Q,iv:tEO5OkSYVSWGNjoQUdGodkzXtXl6BVs19hOlVvZPGdk=,tag:eHzlOd57Z9/4J9W772yVzA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:P7ZRpXn51nA=,iv:wCf+jLYGXINN69lUylnnbJZIo9rkM5Wa2LBkp+rv1nM=,tag:/E/SK1f7tE98TyzEiIqUnQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ytM8y2Al8y3h7EH4i2c=,iv:mXRVTIZxd7ejkR6VqF5rEqvu/Sv3EJTscYIQGoh3zd0=,tag:Vck5aF6Af2vu/1C7WFvn9w==,type:str]
  VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTID: ENC[AES256_GCM,data:YD9BB48I4RjI8bSuKLMcdFNXCJpe72ZsI7r5Y1LhGX3Mg33uZJeGiA==,iv:tLG3sFEG9xy1XXmamT+k/4rzyaJI3Bcpb/xdbfLi924=,tag:Hq2gpCohbc3xGQK3qERuEQ==,type:str]
  VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET: ENC[AES256_GCM,data:rSJlxmF+aGQlNuDHZxksbDklruePQrPcWXvL0ps3AHlB2iisJ8loyScWE8nQAhO9xinh7rK1EBJv3xugqEFADAVEj1vQAsYurxQ3y9D30JYEXVStA9rvd9784mhQrEMICQAbTn31+FgSeNc0w+kNhxVjA8dOX8LPUvlxlpdCYiA=,iv:mj4NXptDGdam156xSpLmmFpWojQq+8apg8UUb66MYNo=,tag:zD0D93GmQDuWvSaxgFmyJQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQWtQWVdtRjBjUFJqRmdq
        ZHorcFZHckVQVUdMcjQwR1FyRGN5N2RGUGtnCkRLOVRsVFpRVUNUM2xseVJ3NDJ6
        UXZSaUY0bU9FOUpnbXlpTnQ5ek1qTDgKLS0tIC9kR3A4bEY1Yng5QkJZMDk0RHRw
        dFpEckVwNlNndEFGVEg4cHVSU2JVcTAKJKyc6RqqvqBLufORNZXYxKaJ8M0t83MK
        KXfwSmZa4x8BjfpPVeBpDFP7I0AJ2gM60AsLhcUIrgBaJJ29v7Tdrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T12:55:20Z"
  mac: ENC[AES256_GCM,data:AtIMvTkLMLC9G2jHMEBrjXMOCoQEbowLg7QZ9ZBdbxI/VX7tg00tvAKiklmWTA86IVuJ9uPavB/vH3bcw+rTMn0+sj429Zz9dv4OFnbAsnTWknd4M5MCv7xeQHvnIBaBTzFOXMNCoGvdaHK9Bo01cKlRtQXnzqzzWcJdhf9cxkQ=,iv:VUCv/Lafi2RCuzA/m34ObvkVarie3wWgOKX23Q50xM4=,tag:Jil9iM91LhkDuwm9PD/NmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
