apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:hVkV6HdldX4=,iv:ja4dOam2/LFjcCWX7Wb1p4uRv924mCsdsTAqcAHLGJE=,tag:IBkk7dF3rmgwA7lPoxGuzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRVVWa0tadjY1bnFIenV5
        SkdObW5IYUpRcjhVZWlDTUtmZGhpT0RJbXdjCk5od2w5S0JCNXVnYkNTWGFYQkU3
        Q3VBTkh6T3BDbE9yZWxoKzVIOXNxOUEKLS0tIGZqbnI2RTQ2OHY0SHpEM3Z3R0Jy
        VEFUUndrK09hcUczNVZudzVMcWM3cVUK2s+zyQvOqweqmZGD+BdUSQtLujcamiZ3
        9D+KJhsy6ziDw3lWydVauKU3/xOgIE3u9XS9cPEGPVgbl5eRpZoBNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T17:01:40Z"
  mac: ENC[AES256_GCM,data:6FvbbHcStEysrYUtm7r4RwujQgkzPZoO8MiLtoSi+gZYm/ZHBohJpOX1EjguouM2BQ/3j9RwzQNdQ4/A5rOdiRtABHVdYrMFnLOZWxXoMkTreqwi2EFxEo86CSZdr1vsIqZeTC4i8pbYvyRTtB+Ys+vu8Veiq22hAODwP9xuO+Y=,iv:GYmxvzi9rZHpEJ6FOMdgpe9op/klimZPuJXA4whvqSw=,tag:MZTgkPGXe9SW+FWeR6nokA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-taskmaster-secret
stringData:
  PERPLEXITY_API_KEY: ENC[AES256_GCM,data:WlGa2+5081o=,iv:nr7TYVN8GrAymgcMl+wdRzChMP7eCQybxmu41LXSyj8=,tag:CTj67dN80gLFZ5LMJUWDvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRVVWa0tadjY1bnFIenV5
        SkdObW5IYUpRcjhVZWlDTUtmZGhpT0RJbXdjCk5od2w5S0JCNXVnYkNTWGFYQkU3
        Q3VBTkh6T3BDbE9yZWxoKzVIOXNxOUEKLS0tIGZqbnI2RTQ2OHY0SHpEM3Z3R0Jy
        VEFUUndrK09hcUczNVZudzVMcWM3cVUK2s+zyQvOqweqmZGD+BdUSQtLujcamiZ3
        9D+KJhsy6ziDw3lWydVauKU3/xOgIE3u9XS9cPEGPVgbl5eRpZoBNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T17:01:40Z"
  mac: ENC[AES256_GCM,data:6FvbbHcStEysrYUtm7r4RwujQgkzPZoO8MiLtoSi+gZYm/ZHBohJpOX1EjguouM2BQ/3j9RwzQNdQ4/A5rOdiRtABHVdYrMFnLOZWxXoMkTreqwi2EFxEo86CSZdr1vsIqZeTC4i8pbYvyRTtB+Ys+vu8Veiq22hAODwP9xuO+Y=,iv:GYmxvzi9rZHpEJ6FOMdgpe9op/klimZPuJXA4whvqSw=,tag:MZTgkPGXe9SW+FWeR6nokA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
