apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:tspbm10ZS7k=,iv:CZAWr6BKvQjNAkPzibNCDSbBYuvVhwt/ACbhdcmJcOc=,tag:UKNtAmPnAnPdnPDNtvH0nQ==,type:str]
  OMNIROUTE_API_KEY: ENC[AES256_GCM,data:eUH9Zh3yrZj9LRDUzs6+Tn13Ug6O3XaGpVDRbwP5zhelbjw=,iv:xU8xv2SKmHPC1SeyRcFuA39jR0GGOuuApWGyZ5+5Vk0=,tag:b3pci//SB10NKjhuXD6Vnw==,type:str]
  HINDSIGHT_API_TOKEN: ENC[AES256_GCM,data:RIQrnmOjr0xea+enX5my3CqnmNIw3w93h2leHkcsPjDso0Zu5AMPbKO5tTtcyqYqRimb4NLKcnyl+jYbNHc4xQ==,iv:euRDaijP1jMJYpNLuogV6On98J/A6RTEgFLpW6QjpSY=,tag:K/MAhgKCwZh2cI9fvGkQAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFJtejZnQ3hZQlFBSHRr
        SFNWUjFaWjF2bUwxTFVuSm0xKzd1c3BLbDMwClkxcmN1QktQUkV5T0cyTFZqb2Fr
        SEcydlo0VFVtMUVWczVuOVExV2d1aWcKLS0tIGE4L0JaV1AybkxUTkZNdW1YRFRo
        RnI4VHJRbUtIdWVSL3cxUW5pNFdkNXMKt2lbr2WnMprETyI/476hAe0Lzth7X2Tm
        0z16P1Zpq6Xl4RPDskJf486Off9yWZmLsorKcGW9kp+l50KLMZ30rw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T18:27:02Z"
  mac: ENC[AES256_GCM,data:4w56M5J30l2wKZKn4v9g1b6Hn16TfF/bUDemyIokcxexuVHq4MoUMMzH57zpfQ2D378ieWS3z4HofxPWR+SN8xctuu4IM+ORMSm1kSdhQM2b9NP7kOGE10W4pJ665oPYvQ++EQFz39jsVLscafsRzPLCAP1fOJocgyjUXYvbGZ4=,iv:vXF8x2RfT0DsgQ+J3KnFvQRvvNJQ+jG6CR18QL2iuuo=,tag:T7I9+j1G7YKM6NEo3iJ42Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-taskmaster-secret
stringData:
  PERPLEXITY_API_KEY: ENC[AES256_GCM,data:kjMLeD3pqcM=,iv:li5jU24U5l9lLcNJamLTsRRUoAVX5YqJnhyaFXi6xek=,tag:V1d082RnKm6G8dX9QZNPlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFJtejZnQ3hZQlFBSHRr
        SFNWUjFaWjF2bUwxTFVuSm0xKzd1c3BLbDMwClkxcmN1QktQUkV5T0cyTFZqb2Fr
        SEcydlo0VFVtMUVWczVuOVExV2d1aWcKLS0tIGE4L0JaV1AybkxUTkZNdW1YRFRo
        RnI4VHJRbUtIdWVSL3cxUW5pNFdkNXMKt2lbr2WnMprETyI/476hAe0Lzth7X2Tm
        0z16P1Zpq6Xl4RPDskJf486Off9yWZmLsorKcGW9kp+l50KLMZ30rw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T18:27:02Z"
  mac: ENC[AES256_GCM,data:4w56M5J30l2wKZKn4v9g1b6Hn16TfF/bUDemyIokcxexuVHq4MoUMMzH57zpfQ2D378ieWS3z4HofxPWR+SN8xctuu4IM+ORMSm1kSdhQM2b9NP7kOGE10W4pJ665oPYvQ++EQFz39jsVLscafsRzPLCAP1fOJocgyjUXYvbGZ4=,iv:vXF8x2RfT0DsgQ+J3KnFvQRvvNJQ+jG6CR18QL2iuuo=,tag:T7I9+j1G7YKM6NEo3iJ42Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
