apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:0OpZ2TFj26g=,iv:VuEWNKZRY20fyo/ghXsr7+NtoyHr3A8GRup/14Kiz+c=,tag:D/xIREfT9cDOnj8EOYSRcQ==,type:str]
  OMNIROUTE_API_KEY: ENC[AES256_GCM,data:9yl5rJB962fgx2HOtxMdfHQp528ALF8GJnXR81CTnKk/19Q=,iv:7gLpr4MLcyqdgnSYdI+vjf4Kk770qGQVPuNFtXpo92g=,tag:HbnUF+Wa6OVGMkdfptS21A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbUY1bTNFdGJ3OFdVM1o0
        UTdIcVB2YmZnOXB4OXZmZnNNMEN2Z1FBUjE4ClIzWkpzc2ZLMTRhaEE5VThodGNs
        TWpINElEU1dnbzNqTkFIaXVTTzVKUlkKLS0tIDNnaXZjc2ZrMTFqdUVZeVpWQm9j
        SmZ6UW1JVzlScjFLVWlWMUZqdUVWVEkKgPTLrOQ7ZsMy592QNBXGdJA48ezjP4gA
        ENEn9Ba1nV1h7nNXqICF9tcEMWYmDbJ6lXML7kDT1lP/3dHKlLjXTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T13:04:44Z"
  mac: ENC[AES256_GCM,data:WPvGlxhkmp6NQmSdd/FyA9FLW5gtS/uJSOXKZP/QcHx8nAuu4PEnWoKFrG2zLEaMyuWXO/vHvXUdwB0GJ2BzQicRTokxmzGEqu0HJKhRUXpaJHFM06kgvxr+TBzo6OjzrJiK/4EmyG5QYyLU3Eu8dn3M+gw6Z0BMSYGuGaSzeek=,iv:i2pm2GqmMcB7eR+1PMWBCdFWlDKsSlkeXSMquYSWvSc=,tag:oi49cYkE4FyjFnsQ/tnUbw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: holyclaude-taskmaster-secret
stringData:
  PERPLEXITY_API_KEY: ENC[AES256_GCM,data:MFhpP3yEw5I=,iv:cC2Y6lJm2DG2f9/x7VpJaqemzmNTQYZDwNmMve6A6QQ=,tag:o+S7KJ6vuYmgcC+90EXW+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbUY1bTNFdGJ3OFdVM1o0
        UTdIcVB2YmZnOXB4OXZmZnNNMEN2Z1FBUjE4ClIzWkpzc2ZLMTRhaEE5VThodGNs
        TWpINElEU1dnbzNqTkFIaXVTTzVKUlkKLS0tIDNnaXZjc2ZrMTFqdUVZeVpWQm9j
        SmZ6UW1JVzlScjFLVWlWMUZqdUVWVEkKgPTLrOQ7ZsMy592QNBXGdJA48ezjP4gA
        ENEn9Ba1nV1h7nNXqICF9tcEMWYmDbJ6lXML7kDT1lP/3dHKlLjXTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T13:04:44Z"
  mac: ENC[AES256_GCM,data:WPvGlxhkmp6NQmSdd/FyA9FLW5gtS/uJSOXKZP/QcHx8nAuu4PEnWoKFrG2zLEaMyuWXO/vHvXUdwB0GJ2BzQicRTokxmzGEqu0HJKhRUXpaJHFM06kgvxr+TBzo6OjzrJiK/4EmyG5QYyLU3Eu8dn3M+gw6Z0BMSYGuGaSzeek=,iv:i2pm2GqmMcB7eR+1PMWBCdFWlDKsSlkeXSMquYSWvSc=,tag:oi49cYkE4FyjFnsQ/tnUbw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
