apiVersion: v1
kind: Secret
metadata:
  name: oauth2proxy-secrets
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:P5eD1z4yqPpWaBumH8bKGf/Q44gsCtSWduCQfxk5Koki1YeD5kMRzBUGTNol7wQ+ao+cIyPuSmlPuhesl5UznMCLY04=,iv:o4D5kPDB1XPELyWuKHWGbAWd9ahaHUHroPhpRRBy6Fg=,tag:WIHwV7ydKuU/SukmIP6kwg==,type:comment]
  client-id: ENC[AES256_GCM,data:gPJmMNEguePXBARnjnhLHC5q0tpXcao6MenXQ9/L7x1DDPnlVrBx6xfex2MXp6Jyu+xcVm1rTgUIUNwszcmzQpN37iNcUfZ6,iv:ODie5Ll8Txr4UuBNhfXtNB2d3lLkGxZi0+r6d77L03k=,tag:6gQXVR90OIDSt8GmoDo6bQ==,type:str]
  client-secret: ENC[AES256_GCM,data:6ElnEWdvlHbo6Edx2CQyUrqnLZ6ZS72Ekrug4iJwOr41ZgM=,iv:2mh/fJCWGLGL0lVtuOCSTfpIo4szMCxMOIr6ebcJb3g=,tag:Cow0LOO2NjPZm9Cw3kzjEg==,type:str]
  #ENC[AES256_GCM,data:lGKqeJVFVtO072NJW1Zjl5Ce4ySTIzOIY4ibmNxjsoaYgWuoy4qQP6b0Y028Z2G9/ksx9527cnb53PNCZbsB,iv:eXALfbYFYwb5KRt7QduBI4BYL4fRIvnuOvJymODHgYI=,tag:8y5c6ZkbQEn7yj0fphMduA==,type:comment]
  cookie-secret: ENC[AES256_GCM,data:tvrrdef7hErzSscep+b9g3xDCqjtGkf3Jk5FG/e8P0XPtMYdXiDA2nHmWjQ=,iv:embFk0E6uPlZs05q+rT/Bg6zgS4bBsCyujo1s1IXACU=,tag:k3Py3V9JKF4Xly03v+04JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreWpyQzhvTkJZODJya0t0
        amJWZkhEbzNhYzEvU1BPNm1laHZyT1B3c3lNCmtiWnNoSnJhNGpKWVllNk1tWG5m
        THpLeWt6MnlSVTREK2I5RGJWbXhvbTAKLS0tIFRaTFFNa1kzb25KRlE4UmtBY1RR
        RVVBVVVJK3JEcmI3dTdnVjhFdlExd2MKpLqf22zty8ZihayyGgpd/F0DFPl8IduC
        KUbz1LpPKogBSRD588vPD4qO2/TpWvwdl4P4kzcU72P8SymCpjGsLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T12:55:20Z"
  mac: ENC[AES256_GCM,data:QWFXc3Sb14thoTL7qIL2V+YM9BQ8wthOgrkZtOsOqsROaSqCXl9d2JVj2sJ0CyHZAyTMtdvnLotNCf6CROhgAW/yrC2vrm+JPpMRTpvqGBlNn0tftL60VZJaHmltwef/lx5EtsKTFGoqwJodb7Z/G4KJkya4VLcon+gS8sx57/o=,iv:2E2nn5DVkqLLkshuZkIuL+iNcMYCtAyspzHVD9rXzZQ=,tag:pdZOEgDCmAo7ft/UPEsq+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
