# IMPORTANT: This file contains plaintext secrets.
# Before committing, encrypt with: task sops:encrypt-file file=kubernetes/apps/services/paperless/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
stringData:
  #ENC[AES256_GCM,data:0NFGraIFQXrdTTROSUqlMJKxSctCTlKy7IUruv24xGsdwe1UxNpaD8qR/JlKEvEJQ2fDy3VGOFh0U4I=,iv:/l2Tc+s7x0UipOgf9V/UPhS8XGYbCoS9if5nwQ7Gwsw=,tag:DcxZK/508Ac1nYaU7tMxRw==,type:comment]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:YtY7Ul2kQihFpq7kYxzJfE/ZY1icGVLxLnWIbKztfPvsD1YmfUpW3pq/gku4eExfAucSbfp1ndVwvZMXU6Iiz2LkfV8Jc66yhm8nG3LWKze9gs5MMLjio1Gp+PWRD49TkZPLfR/ni4sjGCe7oM5lQXrxKTZyilWNFbcU0Q==,iv:CIEzUt3O6ZxYJdkdaqmG48h7puSVX7+6xvtSX7xbU6Q=,tag:DGZSwe47nnS09tb/oYuZdA==,type:str]
  #ENC[AES256_GCM,data:cpWnsvNCv6QOtpf2KVfxCqgqi8BlacjxQ/jBg3sVv66mhiWSTvbnqH0XBOInjtpZWYYwmAhi2eKqkoVGY1KeLjRw6RwfxnqnvHG61Yw=,iv:ww5jDFvgpbOTSf4SoMdlDAsOgPffNYw4JvG0NAhwJQU=,tag:yzxyUuKjqGY5KKNUZEOcsg==,type:comment]
  PAPERLESS_DBHOST: ENC[AES256_GCM,data:wcZG/gLOLgh5Aos9H2owV9jk2zirZNabsmylHzGTf3/bbdGeH+EkSYw=,iv:DQYmvFK0Id5gyBhojtIymn0kpodAhPxuWSAYlxPCWdU=,tag:wE9FTt8i8jQKsi0uknZAFA==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:orGGgiPmvc5h,iv:7l/l7S7BCUhwiuf4e2OHzYOz64H89Oja2kLdJ+chM3o=,tag:Gmy0AmZSYou+XyE+CCB1SA==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:JrKRfExbiqSM,iv:GaBVm8DIlN03I9S3pCMd2W6tVPOHDMfY9mLAmUqxZ+E=,tag:d/S9i49sc1fVrkH5PPvJow==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:fxzuulooSVj5upeN7tvLAJNQHfQj3BKMDy0E3n5noBbsQmTozjBoamb3rrN8Mo518iFUD166Rhmt+4p7Roc0wg==,iv:qRbQLsyBGqqxAWpWXrACbewRTuVQVUAU2zMuGQLh67w=,tag:xht0sxanjrlpyr5Jyp//YA==,type:str]
  #ENC[AES256_GCM,data:e6HRd/x+3o8Tc8EiaggRBkzps5zc5l8VkN5BgoN60shlz3ehngLooZuPIlcxiZZx,iv:lnupRbK2XOdj77baib4wtQl9QN2VQsWIE4qpspGHt6g=,tag:v77ps1hoogH9XmJt/75ZSQ==,type:comment]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:tutBGZ4=,iv:fSHSe2y+ZmfBs2ZPdL/ocJZ2WQT0hxByUbHcgAO54zs=,tag:VEGrbJ+SOgoJsCcGaJM4jw==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:RUzbMpeCRRcd,iv:MqIxg0k0IWuU39uGduoN+rFcYvG5m5dVyZjkr75F5Bg=,tag:e2pAvMuVqHSsiA5/9swCWA==,type:str]
  #ENC[AES256_GCM,data:IXatGEZOUJk05vL7WUiQBgMvpVCv0NsvlokBCmiKYrctRA4N7WZl2arlyUA8brS5GVZvhdf7trqn8ptEuB2ZbZ4Un+980wk=,iv:rViO2yN6csYGpuy04mPH/gaZbEg/MUv3GHK9LROlBUw=,tag:deuqrclutwSpcD3EhOWgLw==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cDXimHif/dKoyS46XZNjNjstdsbJon5kVf5b9tpYT5pcO0hUDw5Fd8o=,iv:154+8p4H60E7QURH/xRIsJaivoQ2/V8qmYLPhSIx9yI=,tag:j6RhzckJaJzCPugDKfpCdQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:A5pGAj1KIPQ1,iv:Y4/80IkNzwe0ng1ANsDxQ50o3GHkl8eiumB0Ut+p0QY=,tag:7+oFwWnTYgX1Br5ICPgFKg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:S9/maw4yim0G,iv:xu1LwmeGqrdb2s9VKCDd6DVWZtj81Dw/Yvpdp93ACuE=,tag:sAIPI9rb+WinLF9fiKroAQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:j7nQWrRC8gvwvRBeS7AH3AH62f53Db5SS3tSw33b3f04FNZP5HrNjUNwFXWfG8faVudkyPiutw/uzR5ZmIY/GQ==,iv:s6cbKi9lvfiBpch9fZJwTF3lfoQ/UhzQnYY9px6lg4I=,tag:nNKSHISvD+tX5/JvqxyNBg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gdN6hL7Oa4U=,iv:oZnQIgo0UAKZ9pHfOHBJtHc18no2xYzueGpnsStHkxQ=,tag:J6qxb8FIFaqWMRPyhX5OoA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:N1Nq+f0Y3IUJeFZmy7k=,iv:CPVL0xzcGIOya1A9lFFCUnFShIaATOnW+XJO4UbP8es=,tag:Dw8aawaCidmchvQXpYKybg==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OFUwY0l4cG15NmdqRlor
        Q1U5N0x2eVRmR3Z5UWI3SmNYaVlLYVVxMkJ3CjgwY1ZrdEgrZ0RDV3BtbG5KM3VN
        eXFhUTdPOUMveUJjTitPUHZ2dWFZazgKLS0tIEFBclpUOHhVVVNxWnBPVExiYXdr
        UU40K215VENFZkFNUk92eWRmRE9EZVEKgPrWq1XBSqsv/Cg/xVYtGm0dgIKGj0YE
        FkmHT2EhgHJi+yNzqsCO/d0Uei2Xv81CI/MEuC2ZX0vjtjSAVbo0fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T00:29:14Z"
  mac: ENC[AES256_GCM,data:XnwY/+A0YynXfkUX2iBSpAZOmz2TMM7FJ9ATV1lfCn9LuO9/hDiKZyUZx1+sTnuc5rpui0Ig/gsvrgZv6DW1uYV1C2BQxtnZLBkscbwmEz/rIu1AS9MhreGuYMfqBaQlhD+s07O2b4MryttRdOTF30aWXhsHUhbvbMs+cTl3Y9A=,iv:+dk7pzdsr50wNLqeoGYGM/TWEnAlb1c7y6pE/vpMNa0=,tag:l/5+h2s8fx9iN3jWuxeDoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
