apiVersion: v1
kind: Secret
metadata:
  name: owui-pipelines-secrets
type: Opaque
stringData:
  #ENC[AES256_GCM,data:eFoG66Svw//CuAQo08Ayls6Rrr5Swrjlk7vb4AZrAKgbp54SCPLMiBIJW7N424ilMPHbzwE=,iv:fXgW0Kw6hvcIDdDad8+A7nJKVjysg50Yz+Msu3cpKT0=,tag:uokqVykZIz7q/TdSJF2ypw==,type:comment]
  #ENC[AES256_GCM,data:gPcw9mJSldfwkltJkVepn3K/aiE8m94SuQ19jR4W3W0wpqK4vYOSxOKrBIooJNf+i+kMLNvqyZ2mLSpLllapBUZEK1mTWA==,iv:ShH8+yS0RB92wfVA4OKEByPjakdFicq2SNNH/O+kmP8=,tag:ra1sPIfWHz/ibj0BsogMew==,type:comment]
  PIPELINES_API_KEY: ENC[AES256_GCM,data:/Ze/tMpu4Vjgp15FCaOICIIwF/GFuNtZBg==,iv:Onox7R6D7T2TcohGw9mYJtflmfGGS9ihTcB9TSblDGQ=,tag:rP9GFJSDhkESIUk4r87vuw==,type:str]
  #ENC[AES256_GCM,data:J2mvYUNIJ4OZoqBFhCKArWSP6lhno5ztQIFugkMe/amv4zb7hBfY6Fah51Y7rarCBJJdHdkgWBLPlh4J4WGQMPZHIA==,iv:lI7SbaWbeGxKxFhp7N9ZFtioEoLCk8ntQsH4fmUWAF8=,tag:ih2ZCWoufSXXRBWCGPKB6A==,type:comment]
  #ENC[AES256_GCM,data:hlZNX9q+lGgflwibKx3k9esGZCskG4dFQ2Rc20JeDxMsXW9rzQxmTvb0ZqsjdNAyC8tIGEALgWZpjfo=,iv:aJ/Wx3pbfhXnxvmCfEMvhO7BfFiFggvjKpxAOxmjOz4=,tag:GO3WhNWuRU3VTroeOCmA8g==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:FduyijquyQD2e2nZTdhnCpsVhl0VF5dG9anOpi266huln98dhBDNmqoM2Y/kpBxCJuwPXSvKUOlawSUlEqMRswD6JQ==,iv:odX+GUQgI5oaxUgTC3HCkXulwff3gYTNDtgkV8yMIt4=,tag:MKpgOSHVerTkvwNJBdGOvg==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:GRuKBQXkR8OPwJl/DUnSmHhW3t2U7w==,iv:HF0brpshrNuPi2EKpGLPrAlprpdUqySFvJj+7XrWwkw=,tag:fBgLBOEu+T51df8CkfJH+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc2E3azNEQ0x5TkphTzgv
        U2x6d3VtVk9haXJnSGVHME5xYnNSaVhXdERZCk8zWFJvQkJlV3dZUmhnWCtHaU42
        YXNOZS96MEg4cDhibjFseC83TERYOEEKLS0tIDBZdmNuenA3dE1Zd216WGdJUGNp
        WXZnSmtjMUVZcG1wQXdVc3ZVSEtFMzAKf+W83EwVCHIUqZvid+l0z8HGz+6/Qa1I
        0m9cBdsjURZ+vhz95ZOO/Abc0sYF3eFpEJxMZbmh2OxsFLOKUl3OgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T19:15:56Z"
  mac: ENC[AES256_GCM,data:mtTjxLsgQkA3qNwuUL44enbKcL3oU/mVGgyevgUI2PCz1hHl8pSgbuwTOh3jqG71pMwn+KTR1mbe7bsdBORGZsfpXVTDcAtRs8zNhuuwf5BOMmOEMwRaKKSFyluK/L+lgGUSfaaf5uxUADIbsR5g/pL1SV3IrguOBaFVvAdJiuY=,iv:E5a5EDlznxjILJekiViazXir2T3Lwn8t6Fw79L9Bf8A=,tag:IvkvgO5dcdu/6hYUVYY/BA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
