apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:pbQUQGa+PNLN68fV96bWS8SNdx2fPZM74oWvG21kPVI=,iv:HLQOAaUZgyNITlgjw2Lq4/23cXa8yBVdYYmGTVuGGWU=,tag:LMhNlsnJAK2PHSRbF2So4g==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b2Z3eTM0b0c0MzlqS0dZ
        MnlWYXBaZVdiM2RqMlNENExKQS96S3EwQ2lnCmwxelRvNzVINlFSc3BSYUlwRFg0
        b2hVTitqMy8xMmNTM0REZWM4eWtWS0kKLS0tIFBEQ1MyMnVXSU9MYzJ0TG9FajJZ
        UVB5alRPTVlpRkZhNGpSZ0dKSUpMeDQKwmsBQDXRk2hOWp2s/TlvG3HKTDCi4nyc
        dnUijJv9KxZ+r2d9jsK1QKvJYgaXZTG77mpD5GT1PSBh3v9pxsp+5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:9gEjQGfHnK4oRxT7MioKHtLi63fwwELXVO6On3waAU6gNUA6+i4Gy6FV+Sv/uHXIoibHRYcWKcMNNK14Scp3us/GfUWLgvJ1HL8qABxeuDo6h3IaktML23rdMYsST6+bxRdruRCIJzfCaYa4AGNXEmNmGx2K+QGZYLAN6SQgruc=,iv:AUZeOBIOlG3mB5YU+P85YpqnN5TKslEQU/644H20d48=,tag:J3Tk6SmWxsaTwZcxjeBszg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
