apiVersion: v1
kind: Secret
metadata:
  name: omniroute-secrets
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:umSBn156ALMIj0mlKBhTB3R5A9int6LC+LTJ6wYVdGlNpQO+u+lQkY+Seh93x2g4M9l2ksjV92me0pnmzicuew==,iv:FaBj/qPhyhJrTVS9DOHgfNIJkqSSLip8eIwvlqbphpQ=,tag:gpcBge6BjwwB0CAVJw+o7A==,type:str]
  API_KEY_SECRET: ENC[AES256_GCM,data:eHLzsJpJbpQ5jM0sYiMN7ZIFIDvHXDnG/Uc+/O27/2cAA7p1M2PUgpO3PcGj0xiHwFbKIjzcUsr9sIqagOwquA==,iv:93bgTPAnC+IMwrroma4to6zJ2TEPr/InKdNOtD3v55M=,tag:A0lvgPhVOCv/whnrOHDj2A==,type:str]
  INITIAL_PASSWORD: ENC[AES256_GCM,data:dR91W2Eu9FN9cSufm5Lsi+/2IJ9DggradXyNC5txrg==,iv:YMSZFA7aBW5SuB4TDS2JgQnaNR3Z8fHIJMc7ESKXutY=,tag:O22biuTG4YUNhFFJZLzJSA==,type:str]
  OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:/Uuvoxv0HLlTzp+ggXSYq4U6yGud297escEVF5wCKpg+ZlpjVCvXecZonD2GBpSX,iv:LHDnDOOyMEDSBkH+ceHM+VB5qnWn8CgOEZlhEcXJxAE=,tag:NOIXvsAHiC37vJDBAG7VSw==,type:str]
  OMNIROUTE_MGMT_TOKEN: ENC[AES256_GCM,data:Z824yNtqcQQRE4RHsHjlIW0NHiqJMRY2YPpxzlE8zTdEi1S8WEFwETtQwRwNcnFiZUYanA==,iv:JCrCxNG7fWhK1v3QUJC0IdbI876eDR2Z1n7aOi7XuSg=,tag:Y/Dx/Nm6aeAQ+qfFLOIzdg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:VKqNZiWRDmjcZJjHz2EfhL4LoEECl++sNHmJ5v3+FnOgl4XhJW4luKqWFFFR/QlhCy19JD/7muKD+/h0EQAo9XU70+6Hog79ZHb+DSPjATcIA558jJdonzVc,iv:R/kLH4LkuyvUIUOhbbmCBLlzIozmovb3A6rme6+Y7Co=,tag:qm/KdkEw9kDvVjA7X6Q0Og==,type:str]
  cliproxy-config.yaml: ENC[AES256_GCM,data:rAam2fyDXpVvaUWm7jSsF0YGgcSa5ySTQCBhF56PRytEQulnnW5OVchvSvchgcnc64pcOoPSWRcpnhJXAwpWz34Ec1ME+5LApnaurm89kDIumsyA1jA7D6MQOP0g9Pew6RqLSIrqMxIBwJW3NYObzeDcGCzZ2mPNf352yOzJyN1BYhddLW1vX5KGcA+Zxxn1OQm09XZ4m4FKhGHzkxvyPGOXyz6sH+GSsfDJBMFq4jrZLqYedroZqaQPxMNBPdbgx7x9/vrAxQWhuXjpALod02Vol+oxCkSymBWXZxS8u8uCUi1GAOHjWhcrluBpGMrNmT1tdYBPAFU5L/YAgSYWhPtola5wzvmYgwDGfO5pFRnORFrL33W5qO2v2maxMvAx0ttr80RvZ+aJY9vWloQUUKDxxZO/OH2bvDG+sd/1v61Ug27x5E7nMaGSuXvLD3g1RWtGVCIOvSmeyTIG1vfhDXO8bIKHQyu2eBBDzLk=,iv:Sg3l2cGRWoS4d0kXA3TG6jknYEAPQcwgJmTBEJPqi/s=,tag:Wm5yDhF3lKktrBGWOBAFww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWFNkWnRqM1h5YUd5c0NS
        U0JpZ09OWTJiN3NPRHBaT3dNV1BqbTFjVVdRCkd0YVhQU1lLeDRTcFZKR08xZFY1
        MjlxYldqQmU3bkdnNWhaejVUU1A1bm8KLS0tIGt1akRnb2tpZEpCdXRQLzJLVWF1
        WExZdUNreGRVNytRTnI1aitwdTRlUEEKjqZyJsKhb7mZ20VbU5urX2jTmvPhF6jA
        1LeTFj7Gihj9aYCtzUj7INs/iFx9BPn12ONCWp104sVLq3QmaUXfrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T00:11:54Z"
  mac: ENC[AES256_GCM,data:t0N+A3pGQemy7IzN+U3iGMkfqjzOqrY0ZOLKBLwmJEG2TMkwuyFefiA7Sl37R6DaSufeiI1xLIZrKTHhaCyw/CyZqWg0RJ2sVzifIDMkN+F+ic1SdBBL1h5oMiy7evRLw5iuHkg758JWuoWQfkpitDsyhh8Left5DZRpe4L4ukE=,iv:PAASXx1eZSV5vdn/zM8trkHscPtxrLbzViDenQCYtOM=,tag:0pCCifAEaU2urHQzdtxlBA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
