apiVersion: v1
kind: Secret
metadata:
  name: omniroute-secrets
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:B8JBS9CFFy21pryuUTLUSAkg+aUKyAv7PQR/Y9JkhvGEPpGGOBp4NoVi38kAKI0eG5e8KduQJX7nEvUpb4xkLg==,iv:5HvL7w1kTjDAQfdqCEZWiAuXkrILMsZXfsCYyAN1Njw=,tag:m/pOyAZKunLqs7zMLN7ZxA==,type:str]
  API_KEY_SECRET: ENC[AES256_GCM,data:PlsbXIpgqT5vbSILIE23xAGMLfgjPpcYwDnKLBMcURw9bZWgmAXdQlIaU/lGUxKF1tChleOF9vUA0wDuTbMsZQ==,iv:5Zm8ejqV4IJ6XwcxI3z9NeRTiyrr9nvOaqWhd1V4YRI=,tag:rPRzpCplzh8Eycqrm3j74Q==,type:str]
  INITIAL_PASSWORD: ENC[AES256_GCM,data:E06aGxlsJ4yGmfNNRXXSXeznQs8e+21Ltlvy4M8x9rQ=,iv:WHwQo9hXOB0/hyiCAg2nbBdLJJc4X/ltSgr4gQHGcZA=,tag:zQlv61kmj3dBMhWYQ17MfQ==,type:str]
  OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:8ToEtWjBQBBktq8FBye8FdZCYK+5i3cYbSmVllodgghPcm8ToXmLmxCJl7EslKxD,iv:nT69oKR1HK5WLP0dp2OKG4DSFLg1uH8OFOarHibP4JA=,tag:TAuC/pJpYLcZRHj21plMGQ==,type:str]
  OMNIROUTE_MGMT_TOKEN: ENC[AES256_GCM,data:JQ2hIgw43KY47tZ5ILok6VLDg9k1eBoGZfB4r4yjL0VIb+62aRzL8Az/Bto92rOSN3g4Lg==,iv:36BkthxWzgqL9UT9JhzpP2igSCHoeiS2h+qHiOpskTg=,tag:Yy6jsIuhIS1YYATR6ebx6g==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:Bne5gbRDbbgLcr6UwkSeh9dNlmXvgNRjiLavIcs8SrpJrt+5DiwBwn4F2OOKOgtYDAkrQu/6w1jR3Cao1sraPKUTpLSeSoMs3MdwwvKe+JklslJ+/0XBnS8r,iv:/NztuoSWw8Fe9pEK9PeEQydqTCi8Jjqks30KzA3IFzE=,tag:6WpYTX5d1XtJpvq5mIFRWA==,type:str]
  cliproxy-config.yaml: ENC[AES256_GCM,data:nHCxXYQZITv67aRN67MsuPS1ogn0qar12aMArqxO+5U4gRi6izUNEbby98ptgycfav7QSoOYWmZNe67pE6f7Qbpi1Hl837S4t7RVpmKz7T295EuCm+h20DftKVpDQrB0cmmkksY5mnRjsgOalMGudv+HKhv+VVQQUbXbAKfn17Ztb88iKXUQTBdeVafHDL2WuHTFTuvWYq/biD57jeM82t6GxF2Eb0JAJxxg3aFqYd9UZm7Zf2w1zkyzwjSNim/IijAAK6kguCl0zZNZgJI67CibKBDTIZ4Q1RTPhJpAcE3URBTFZaE5yjJzDcbm4paIbP1HBLm7CmsFfWfRAtsv0CN6mM3n8IopnprD38iATldINhHpIXA7fLgecR3syHBD9KrzFGqUHdBSXThBX2T0gUiZG0u3PH9B5wN9lw9mFGXeLs1d3aBd0UePht0cTQQ1p5fp5bFwSIoHGmqtAsY3UtG4VuMZIhuchbHvP4U=,iv:nj4wp3MphVy8jizQOFMLUuZ4+OyF8JIoRg3s5JW/FkU=,tag:Msx6QYo61Smk3FvoGKHqQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUkpJa2dBeWpUZXNLSGtn
        aUpSVW9xeEQweVh3eE0vc0l2VTVxMm42OGowCmpJNUVKWlNYbVdKc0orTUlmdWFs
        RmgyczgwYWR6UFgvWlJjNGMrMTI2ZlEKLS0tIHlTaXBzbXVvUEZGcVdRM1NoQ0tC
        cytkSWh2UCtIOEEvYjM1aEovekZmQXcKKXT0SRK+Zc94T5qh/MdccPq8pqvd7qiL
        jmgwD2U5SnGuM881n/F7k7Zy4shv+kibqtzixQyDgktORcQ3E+pjPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T12:51:36Z"
  mac: ENC[AES256_GCM,data:nnSEzepHPA9ov7vCtve2ECo/UxTwytXOcpMwUC3AuVOQ05HKFW8iGRlZGi4uycGS3hm+5kB5KLTn4Wsep7KTLqbHP3XOKMVMdE200l67eT9e0p2kThgijw/QVlq0VVE7tD24X0H1B5tmHGlpjNTsSceqoA0n06XT9IulAZdFxxs=,iv:45fU/vdtVvFDwKoXOwJ7Xfn9xiqXOfS36ajRifBpx4U=,tag:FFMnx5UedQiCjAceGgsIeA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
