apiVersion: v1
kind: Secret
metadata:
  name: omniroute-secrets
type: Opaque
stringData:
  #ENC[AES256_GCM,data:pZ+Sk2fhHX4KURalg0E4TCKZtuxaZNgGpJ8dU4WriWgnL0KGr/d/b0+1+ZAeQqLZo7ldg2IabSo+HClWDZc9ZdzijoOgtek=,iv:HHVAR286dNwW7OhtvxAwGPsQvye8MTGZU+kJhV8d+/k=,tag:AKzNHeoNTKZilhGJ0Dn4tA==,type:comment]
  #ENC[AES256_GCM,data:MAGbWzpSaXYV6pVyr5rcu0s5lTjC91R17IEQA79bAK1wd4IDJQsVeS5O4IjPtZdkXdBLHCBAbtovqe+l/wow0CQO,iv:tsLqIBdxyJb0QlP2Rl1Cz8Zc+jYpb3xoHjEv0RfjG9g=,tag:QUVh9EPTd2zCRCZJfl2bCQ==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:1+JHmnw31T9/xeE8Lq2CAiDvB5l/XtkNFwt9SXgHG3urHShsW8y0FN7Eua+qo7SeS7WJCDQCJT3oF10R5C5lMg==,iv:XW3MXbeFwJH4bIQ7wc7afg0eC0lbg5hTv884PFwODi4=,tag:iup3G+3chLcRa6NoEEHUog==,type:str]
  #ENC[AES256_GCM,data:zXP0sMlGlxMw0a2gU4XPzJPIVLNxW3DXfndQTvT+degfPI8qvgpRE9JmNmDQ6rTnRN1T1taF/wN6f2cN11sBsWmvW8U=,iv:ByOrLCKHo5tCof0nz+zgSdudfB2Rm9ikSBaFJhhmRFs=,tag:LfzCarO2Pb7t3jnDDLz0lQ==,type:comment]
  #ENC[AES256_GCM,data:ZK4IlA36NPAABNe626vETCmfoBTjU9w7o0CdZ7QEAiBQ++0ihxToEYntxLqE3IseSyuoqw==,iv:UbYPxCYtYwS60UgWJgBSGNmynbYIjdihKSH0T+FxFwY=,tag:MawO02ovENSd+VReKFxktA==,type:comment]
  API_KEY_SECRET: ENC[AES256_GCM,data:gjF6MLz626cAL5e9hSyQ30sQoudCN+16e4XzihezSoKDvFlCMs8e+kNQvgK+TjgAo2qo+JiAJLCsFgEGs3BYYA==,iv:A69YzTlfYUNdlI/UHnlc9yWGJv7M1AVS07RHBDKDj+Q=,tag:aX+Lu7UYbVPmL79yDYXw3g==,type:str]
  #ENC[AES256_GCM,data:9hOkkRHrG5uDuQnCRum8erL2Bcakr78C/WToH6fqE66Rk0RS0+zOgNe5Th+IYxv9ZqmvGTdmSKmKzcQnI0DgTkmqpYBDeg==,iv:gvfjOlbJNf4LF+4YKqOJ9xM7+hl9aVSTEygWvp6nFpo=,tag:rvg2o/1CefO/YwmlUORjEA==,type:comment]
  #ENC[AES256_GCM,data:PLOg8locIUcWC0xhUundWg90cR+bYDxRljt6+zSkqdy2MRVR3MwgTZ4tfy3WJ99p2xEkF5Wqyb6h7Tjq0w==,iv:32zmM3iuPMAd92U7O/GMDF5JthyUgWecml6c+61wQYw=,tag:u90foqHor/QsbhwOnftdkw==,type:comment]
  #ENC[AES256_GCM,data:NdIx0O7Wl9n8NcBPuw4cxEF1H9aubzzOLpFKIruMfTgvEo1bWddK0B/NSW0EUuq/a1gtws1cqNPeDmMECjVed9aQdnhx,iv:t/bwcRrWJ58pwYVK0lGAcaPpeToEEodajv11WcY9WP0=,tag:chwO16dPJV0QmVvk6MawbQ==,type:comment]
  #ENC[AES256_GCM,data:wHPJp7GZq93ZU8nCeFACF1dT7kSKkhXWyVuksQUuxtkAVyb27+yIHUL0TJOmJyPAG701,iv:IAmMQmDMlsNbTEJ55wccnzWq7UoBis8AHbp6qgRKdpg=,tag:vbJuOk/C01Z0C69yYb8Irg==,type:comment]
  INITIAL_PASSWORD: ENC[AES256_GCM,data:ueyEvxJQsdhYd6jftEGRmYNyGgOVw1f/,iv:KRAzjhXAi0Rxt8VDaO2x3QW250c8ksfKnLX7VyZS1t0=,tag:1V+YVhWlLoB2fQuiShlK2g==,type:str]
  #ENC[AES256_GCM,data:X2f/yYgw49Sp/DX4T7pzhY9EagM6UQyJIjVntcxmC8InbIX6Q5bhowaV19CwjbN0+IZgU9qx4GgX1On5iRpJ,iv:WXDQIoAzJuz5rkyfCb8ROE/42waLpxaJYll6X4ww80o=,tag:p5C8TlxSd7t0gOI4MCu/Wg==,type:comment]
  #ENC[AES256_GCM,data:NAvK9JpWUjnIb20RSumuuPreZ8k+9UhxKoDSy/dlfJHXspqQFkp/y9DX34M=,iv:EYflnPwSzGdv3w/ixB8ddUZSNvN9W0KMNJ/5YKWXMJs=,tag:YMPjbOP5S+kj1gEnTOjDmQ==,type:comment]
  OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:F8yRQHrgWMuHziuJ+ycZE8GQIkWp5c1+uXfyNbc1YPsDjCL7+8lfOrZ3MXYxGLa121J1tylE9IzhJVsjHKTS4g==,iv:qe7/2G4sWz4CMzDubdoLeB5yAXZp61kmbM2glKc4PIw=,tag:K9UXcUmwPbrTQfm3htTyKw==,type:str]
  #ENC[AES256_GCM,data:Kj0Cx8NT44FFUM/szI05kyKT2u5078iHHGULZ0ipjq05wSkwoVELAFGin9dUxB+TRrxS86vSmzPgYMHCPCngvbrQIw==,iv:9hXljTA9PnWmaXZIZdEynfRva2pwQWNkNiblX6awJ1c=,tag:y9bpVqVg23iNS42lwHQ9xw==,type:comment]
  #ENC[AES256_GCM,data:xWAZrKYXtOU8HHg9XtFMGzOpHOfYH/fluAq4J1p2vLVp3nu883Zdqh493976uE2W+Nvruo0g7GzceILbnkApyGMF3IZLLQ==,iv:6894kOrrIgfs6clSu/9I+MA3U3dEAMz4+C3vbXaHl3w=,tag:bllH9ff7KpQB422f6zll6Q==,type:comment]
  #ENC[AES256_GCM,data:FPJ8BhNF5AeTFzzRbPZnXusM3p9vjqShJbOQFKIF0E9atGrjx+rpSygIH4STA8Vmql5T9ANIYSmj86b60h3hzLwYlpDe8Q==,iv:f21fMM2LRUJW9OHclmibEx5ffu6kP+xfGp8WX1N2HJw=,tag:AlBg+PfRjJs/ik6el68Chg==,type:comment]
  REDIS_URL: ENC[AES256_GCM,data:EDtKURfvdkGRqYps9EVHRibvZ82+rP9ejEpk9SDQKMt2rlREm3YlsG0JPR8EAtCRgzu4M0i7JFRsLh1HVJ/crn3eeezdWSuT2iUCxXPwGZh79w2wDW4ZEjpA,iv:s98OP5bHyLPQKxRPlMreKbk75a0cqKb0y575x+T3FNU=,tag:uQcSE5DuOtC6RDXjOgxlBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMkVySWN6R3dUcEFua1Fh
        SCtobXVnTGpYeUJvSUZOUzRUREV4NEFURFVrCkRaN3FnYWNJbTY3Sm5XZ2NsQnNX
        MmZ6SDJxMDNiVVFBcTBGZEZNelorUHcKLS0tIFRvUjZRTU44Wk0rV1pOOUE2ZWZl
        cU9BR3FtTG45UWZxcmx3NzlrMU5RaEEKraTyByXIqadCnmr3Qrn7az9ZZo4Qiv0a
        J/Pl6rSQfgEjcrJ+RiPfv5zLmxcDGvCCnPT+bF+8SCdYclqrMv+Pyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T13:09:26Z"
  mac: ENC[AES256_GCM,data:glYUln04Mi5EPk43GRtm38RH3TYYVxxRWwjI6saWxUvAp1Y3xzAwpNO9x6EYLrZu57nIpCOLFk5mxHTioMxu1D6qi1y65Iz8uRQTlH2AxHufrB+3gX4RpTugvU4hzTzxi17RhZpCLMBR47FQMmP0HwQD8pQF6E8Vv6buLOr2MB8=,iv:2/KguJrLPZNLhAHTLsaCBNZSJ+H47uhvegAu3a8/WJ0=,tag:G8TdIcAPf8g8NVuqrneFTg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
