apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
stringData:
  OMNIROUTE_API_KEY: ENC[AES256_GCM,data:I7cVKd+/NqUrBMV7Qrtcom3fgrYL/L48f1RWEU6WzlR/V/A=,iv:jFAFtnvYicBq1sB6FgQrWv7rDQroN0pf1wrYItcFFzc=,tag:ivIKzflH8iNJNw8/GNJNqA==,type:str]
  VIKUNJA_API_TOKEN: ENC[AES256_GCM,data:VghmC4jg6LjTiAxgJ/6z7eXNC4fDISuqaAo/ZPDebad0YfH9HE/kjtUynQ==,iv:RODxxWZTLh+FqByT0Te92RR9pD40VpHcFEPQak4Tfio=,tag:x57a6iKXivT5NL9b2qd/Hg==,type:str]
  VIKUNJA_WEBHOOK_SECRET: ENC[AES256_GCM,data:Hizt1JuXxRatFiYA4l3HEBJidX8ibAnx5RRonu+KIbrQ7KDg25AxdtdlsXxG1pW9xNFD9G4hrJsZVeIpM8GTKw==,iv:Nd3INcjpK60xyPCKUvGUGFKRKWOF2m1REND5M1EjI5E=,tag:ulse2E5j8m0t+fPm7nlMiQ==,type:str]
  DB_TYPE: ENC[AES256_GCM,data:7gZdSNcaRxbzCg==,iv:64Rfg2UxGjdm203xkHkkFpqZbRhLEBhO5htHE332IFQ=,tag:+6jHf1gL7HsNjOg9u5hiPw==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:BEYr/L2dhj88HC1ZPiYDW+FyZnSOgPTeHjdCHcyAN7PVBg6/KxQp,iv:Jxd5BH42r+u05GKSE+xG/CKvlPZNE9/8zSSbuszF+7E=,tag:R1ln7UOErrfhN08iuuscSw==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:jPgb+w==,iv:WwjNOnE06Io/jDWAmhJc5VXHTsdERRaUK5yLG5wyGU8=,tag:iD02yK9wkrJhzBGtiOTz9g==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:QU9U,iv:L0Sn4lhm+RP0o8gArlfj1rZROU2lI5pgwnjLfeawbEU=,tag:GAtcpAQjFCAEv5GUfVcDog==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:dqib,iv:TcwHJUK7uq/0kjVw8bz0cqfAHwrFvi7u2dhy3rPD21s=,tag:AS1Pmr+y+Mn8h18wltao5w==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:0DEYImJkk6eVVMkKB+ZA11KNnxznMF6vsW+k41xAWaI=,iv:hwoxa/8mWB3Uy5teDzzZunZFrad2BViNKTFQFoclDV4=,tag:UFJbXJcw2LCSpWuJO++btA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:yLao4mNGMEXnhqYWrjva238+NNjvCw38wY1HNwdHmgrdJzGEmZpf,iv:KLwx4h8iDWyfU+wk9xl/FD/Tk6d0HdKd8FgBPXYtXX4=,tag:DPznleVBJU7ekkFluxzlpQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UUxp,iv:WDRa2GekBtS8UxMeNdyfagy48HFDClSRNMWGi4U6WKw=,tag:yeCxsadl5jFE0SN9lFHqvw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:n+ZO,iv:0U9v4SMKCSMNwVnUYP76N2KqeMQq93qB6+7MfhXapqU=,tag:ydmDPv97JJvtL6N0skNmYg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FHwXp7SGxeO9GRC5itW53h2GaHwJ3lCvNJaYzcwq1A8=,iv:ypjz7Bb80NqbfxRnD+dYi3f5+JSyjQTuAJd8Yq7FcxE=,tag:gciKd4VeO56+5/1mrxFgSQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:1KI8haH5B40=,iv:HO+XECr99bXPrMcGbvW3lefAWCbUGRYyt8xagWxfhPo=,tag:hliroQg78NcJAa5oXIGmvA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:u+5hUUg5rAq/PFSjIXY=,iv:fMRoNEJ4yhSeXjhwnll5dfQVf6w8SXSI6nsPtG1jhSs=,tag:q8ykapYU/OD0c8L10Y9rug==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:VTdInhz3Fz7yOeOLm1MH6yqECl9SZ8yQDDcC8tKJv2Q/X3t+1m7uvA5K6ZKiH2zMs4my1UuApStWooy5HHgsPw==,iv:r52BBarrJF3asj2w1TcyAft2UFthmebffyrOwOF/LA0=,tag:eiaCtsPwPxBhu0Wn9huc3A==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:/j/9n8IPoWHV0eFpLLEKVS/EJ4EGsz2KxWPukKJf0RFNRi9w+dtLwiWc7hlO1MrvO8QJ6MLD3gZUtMElp1P5Tw==,iv:NJagkbNSNv1DPKOwwajAknCCaOYVE561yGKCdoBjQ8s=,tag:jBRMrFRlsEMHaldMr9CzgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkclRrYTZLM1hDTWM2TnI0
        RmppSWw4ZzZxZTcwYlF4dXk2WDlKRmJFWFh3ClQvQ2lEelJremcxdzN1VWlEVWQw
        TlZPV3dseHdVQ0M3c0xKNjRGclNUUUUKLS0tIFdrK2hYOHM3MUt4TytpUjdZb3hI
        ZXlmeHM1alJDelNpRkxQdTdNU2FDZWsKDYqx7DcCFzNnt4yof9VxnJH1/SYjYtDt
        WEmbeGq91wDC0vdz3DFcmMaAoLqCILPT9mUadzrCQkEjakAnch6qrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T15:55:35Z"
  mac: ENC[AES256_GCM,data:Dx11dbeN0phE9irO+YyoNdrNizx5RVM0gDECbJTb4aSUDKBNnp7hGK29dUA7rshDo9HT03tgijlxURwDbNfrY4K8A/OnxFGsFfFY+HivSmu8YNoL0+0RKq5ehR6nUSQFH3t0rsYjiKTb+ozOtkq9Qa3wxfqV54wXX5reJvi5dc0=,iv:vw669xAk6WruGeEIcNuno4BCnrTxlRDSk2SJYyeCMkk=,tag:3NOJqg1k8SOVuF5QhOMglQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
