apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
stringData:
  DB_TYPE: ENC[AES256_GCM,data:g5Ev6lFvYgdZVg==,iv:lXtbDGlMUIBzgdMaYw+Xvp56XgKLZzLCk7Z3Qk6r5gU=,tag:YVhmFkUmPcaIFgHoMUdyWQ==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:RfSL,iv:6GP+Ja6dv6rMBsGz/Al5b7CCrL19i+yKJpng6kig1Ug=,tag:DDmae6KV7aBEd93ndL6AVg==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:q4Zkdo9J2qKIAQdjRgDsuE7YsKBkcas=,iv:/JvVBwPQ1Qbm54YrznbLIsQmbelyBhrJaH7Y4m9jrtc=,tag:FON4uyrMoDvQxQ6fCLBbCg==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:evkN0g==,iv:J32KYwxhVJDLGKI0DXbZvdqlKIZCB/5E6BKP5lzDqhU=,tag:7AnQiT+UCSw1XmnNlaQ1RQ==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:mFM7,iv:2fWXCoJ11vx3pzb3C4D3xfGJiCvfrvAjNrJO6HCTpD4=,tag:wk19v2QuPWHcLpcSGOhwvg==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:9d2OBBlK/UPZlN08D+hSFXW+zLO26w8tRVWpD0XCnzR8yHtzkTZsap4+hq2MPam6VLgsP+wHF/Wrr0yECPAHJA==,iv:hEQ8ErJ8w5TZU0R04TlO5Zpz2JCGELckvaC6ENxsgzU=,tag:Voi6/GW3RRuf8TRSeChr+A==,type:str]
  DB_POSTGRESDB_POOL_SIZE: ENC[AES256_GCM,data:Lw==,iv:MFJQRQE4e6AWWJB+bX6iuS3YZeB5JZU/2yu+aqYN5ZE=,tag:c2e/fDPANLJI4Qxf+oEmyA==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Osnf1P5Ld9MGDKctkDEKiO+/RvA37TU7gAydfARfhbiy5JicIVfE8RbabrFpi0ENs7CBTkOuBICQq0Y4YzPiTw==,iv:gpVW1TBMiyqzuvAARJFO7V04sIAy/fldknussxmPSSU=,tag:8KuCwsL2kjTMjINVIG2NDw==,type:str]
  N8N_EXTERNAL_STORAGE_S3_HOST: ENC[AES256_GCM,data:P7h2fvNPUDkMCkTS0ecMikmy,iv:TZPnMrUcKkQIZX2ui0ofqmmEAP8i4sAJOQZtDEkFn0g=,tag:LT4WV1uvV4/uALYdqk9zRA==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: ENC[AES256_GCM,data:JWaP,iv:d/aDARTQqRbpDK1VLEsHGN9HHnlzRUAY9ZDNYZ9tJxQ=,tag:bhKlxFQDcL5jzSPkkEZoIQ==,type:str]
  N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: ENC[AES256_GCM,data:DkXEEwN9L+oA,iv:6LjpgqrjdqmuKrWkDojDTmtwTSFML/pIpqSbH2Z1Irw=,tag:JYUjeVd1L9SAyKhfC0D22g==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:24sl,iv:T3bVMKk4JGsDnSV3bMg7oWN96++1/r/GorrHk1w6gCs=,tag:KeTTGm+kxhPXfDn0o1qVRw==,type:str]
  N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: ENC[AES256_GCM,data:BXV5Vf/lnadB,iv:CHFFDIvoLeNDQPD+7ZOclBo/oqr30BUJ+YKvWFArd1I=,tag:Jb0q/b28Eyme0YWfdud6JA==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:2dLJqIU+mllBsdanBoOTuytqSs60bpk3qLoN0QfBeS0qGBGbFcdbWxNaF/++w8AXzyzlI2nyRZUS7daG063Q+A==,iv:zPnQTNtgb1utam7giBuEE8rQGocCrJR9ctDNT8p7OcY=,tag:Ck9b734utnLLf8BKhkWoZw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:mAzt,iv:eoVtwBbcvypTvSdHME7M0LApMXJHQWRYlfNug0Vr5XU=,tag:Ks8yjNbfpIDHszJNSiFryA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fsAofz8MEwzT7p4aBCh99jSZU1c/uzZbWbb0ePhvzpWvAQppC8gqvb8=,iv:mezCVWEhBWJfp+jTjP7aWfaZstcUeR2nzisS1hXRkuA=,tag:GGYlDuoDL832WBHfRcUjGg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:k1ok,iv:bjhEzMReI8VHPDXWchmUobE/iWA7SfX2Sd4jZVh+Ad0=,tag:9tpskNuHBzogE659lVPhJA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:bTPFeEVSICks0IhInBvFfbKgY1QLOgAdqtTQxM3QiHaWGKyLL0BVCbzOAP+sy9bWZIOzg0fLad/obUKtEwoAbA==,iv:Te9mETMtDmt+sjgNE/Y01rV1B7+k0oVoguGFqWpwDmM=,tag:thsRESp2Xl5W8S2AGKy6lA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kmzUKplU6TUQkA6gj7E=,iv:xPfrnR7FuLRxDo/hef8KRFPWY/DL1Gp5mg5ARVn4Klo=,tag:SKQmic7JFNERzoylaTnj5g==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:IM2xbCC/Iyo=,iv:906y0vIuzkwIS7yLWk59CNWefWw4GwsNHEzD0OexMg8=,tag:DzNS9W7WdwITjsAJpkZNMw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYKzRVWWV5WS90ZFBOY0dp
        UHFWZXo4ZVQrMm1EUGFwTVVkcTJqTUNQenhRCnFXN0VaK2pQaDRkVVBxZzNWbnRW
        bkswU2xITWVhZW5BVFFTR1FjdWxseTgKLS0tIFh2S29FZzhzRjJkQjlBM3RRRWNU
        RU9QUlU5dlJWUFhxb0xWZGVmSitxWFUKkXkgnF7v0UttO6YVdmI7mvUQID9xueCd
        Pbk7fS00Ugog5P26ySM2Y+JJtIEFOfQvQU1fROwlqnSnzCIcetr7tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:1Sc1CyfwfPP55R/klLyLbcU3gMPj4RG/S5ielzVLHGIblpOmYrYl6WQAxPf9kC5YcScPNKI7CTBj8F0yZJzFw6hNOglw6bl8IXHkCzs2QbYUoIyRJ4cpAyd113DA3YjrQnZgswWXK/df7cmlWPuMzoO9RG29VSJXIO7u7IuAqUU=,iv:g0FDiwT3/T5DzZnsolOt0wVVqxk0qcxWewewx+ng2Mg=,tag:EDf1OnfkcxQJ0EbWnkiJjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
