apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
stringData:
  VIKUNJA_API_TOKEN: ENC[AES256_GCM,data:yGdburgQ+FzC5vX4ZCnSfoS/FSzWr/0j7oTfsxu46ZzEyi/hfRrCxl9fKw==,iv:aak9+iBDFU/SWP0adMrz3r6Ok8k40noEWc5X1kEZnhc=,tag:xqRc6oyfZOL3phsnGSlL3A==,type:str]
  VIKUNJA_WEBHOOK_SECRET: ENC[AES256_GCM,data:DnTxWhclsaBrrS4uGEFs1kfcIE1Z0yEbZKjOSgEnec2Z9qJpBOvVE1O+YkNYmYLRJHeslbMhOkKuWI4HPmi3Ag==,iv:ksL+0ycIZIAGarHrFAoc9TxmAG85QqofYzg8q+L6c/c=,tag:PfecsAmjZN6lS20mWvvUjA==,type:str]
  DB_TYPE: ENC[AES256_GCM,data:ExmA9npOrbe7NQ==,iv:sA9R1Klfup5I3NkMPaKP8pSv8qYC/no9OSlCxDi+hRg=,tag:Wk7yZLRpc3+ssHfbjPB4Qw==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:qJXW0vYEIG9Gn1Lqypxj0wdU/qKmtV3V1wJde0mh96tNWKOpMQ3F,iv:6cdAH4i/KDx/dkOKlIaC43apccRyxAUWbKWyPxUOmh4=,tag:+UPpO1h3D3MOfPOiIAOOzQ==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:jV84lg==,iv:Umz8bZx+y5I9qInhpNUGApsJp0Yn8U6tSZvc8NjDCZE=,tag:HLrakEtzGuK2lkBouCVGwg==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:j4Gy,iv:Lai9onT55HJCTVHwgL6Bbb2/yS53yET5Vf5EQTIF0oc=,tag:aGsAxGT0wTzH0nKBVD6wRw==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:j8Da,iv:tqzPo+UBXUCWUOS2A6VSSxLZ8gZ2afSBdeNuIdzspYs=,tag:y7NWxfXY8e+7uQKB6RW1UQ==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:jTKNvhw8jzbN6DV/WGeNSk9v4chLMohVVkp4UL/0QIw=,iv:2yEh8MsgShDV3RR9WXszr+LTXZH56aoEAFsxvk4/2/w=,tag:dQ00MgSNXRHHhz5mWhtTbQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:iH9ciRmUCAXZEbGXtuq5gTicGoyYb9rNvux8kvGrdaAJNMat359c,iv:FtXTuz411ArTJDrAA1Q1u2pGx36lkxPydBjInrsZXi0=,tag:KfD+vJhRvKrp7M8C0JvKSQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ac4u,iv:KoctpBMj6xNyaH+msL+KgCA9gpThEOyGZxs1c2vu9Mk=,tag:RpyazM4K+ptYY7Ucj12OEw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:+yi+,iv:fUbiP7ed2RydjgpA66lGdx3coWuiU9vKY/w5qA48fYM=,tag:U43BrQlUPIYEhh7PW5jxtw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Wl6HSGHr/0ROzmb4k1MrBC3BzueX0VSB/GC9/mZOu7o=,iv:SAwHUcSGpZYcEsrQd6of5sHLsKWUT5alllU4Xv6h0hw=,tag:e2mW4ZgZA6/iFjnjc2TnJA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gFznJfRPV28=,iv:ShSjXPvx/ooa0qhdFedgNDdeyEnc+50qzSd0TGVbrPs=,tag:DSjWeojCSeYw0quKraXhbQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yCh7VT+hO/7ZmLySOes=,iv:2bVCM+r1AkehXeRQTwGE3V/a5iiDUupaXsigG+Bld6c=,tag:tnPTHzfqFrHMq8Ntlj1PaQ==,type:str]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:C9qj5S3Sytx2PxPxrQVMjftVayqaQl7Z5Pf5iYGtzxdVxePatAbAhyLhT7EAZsrrtkMW6MtBa/q1/mEFNlr0og==,iv:Gt3HJYeCiKU+m7N5rNwtH6ZnPa99XwrjUL+ezmOFw/w=,tag:z1d+KzgofuRdS3muVHdSEA==,type:str]
  N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:lU0Ao5OYAjKUwHGB8ZmvLIF7kmfDQtx8sPBoSfPxH2b0sqd7AK2ZgzSAuMztPCUcoWM+B2Wk0nJXi92uvxVOTA==,iv:FVh5ce5A7uBdTGcTQqVJAS4aGW0Lgf/z6YfHcULMU8c=,tag:oVDhmav5IZrdbEBPHD8kiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVThZWFR3OC9BNEx6MitJ
        UzBTcTZkenJzK3EzQU43NUtMa0kzcVlZS0Z3CjFOTGZLalFWN3oxTDhyUWE5ampr
        eGpMdTBpOWV5NHd5cmE5aWlyd1MvWHMKLS0tIGZkM3dZQkpFQ0dzTW5TbTl3Y1I3
        TUppU213bnF2d213S1d2V2pudzZjN0EKeyCnQFDY0cF/W1bf8YvkQvE4VEPlZOX0
        +B38rO/RtQZ01Ihr4xJtaJAahADzM1nupVIn/YgsaXyWjyUBfSYL1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T15:53:28Z"
  mac: ENC[AES256_GCM,data:8YixqA9f8NdDLY8zqAQFT8vQCnPnGorGv6LwnGXXEtK2pdWzf5Vm5+dt75t/EBD5w56PAhd3PSO72ZwpaB5EgbznBMIE2dOMfKvKESdYJps2bAMfPojzN9Frc9yEl0kxgL1qwlG75UrGpqE5EDCJBYnWfHbxhmIaS/20tNs1f08=,iv:Px+b3cRz+DoAt94228Aku6ZNrWnmSlDvLEqMTNvyj6I=,tag:AVry2TzkMJ/uSDQZlvPiBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
