# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Bg2kOOhY9ED3I/mNYu8Wu8lQiq5p6B5mljeFlH4ADWOXFKge3xKcYw==,iv:HmO9J3pEz49w9lYsCpnC78WkjY+H1NZ5cJVicyIWNuw=,tag:T28z7u9D+xvZbo77xs4djQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQlFVNnlTQnJpT3VvbTE3
        VERyWGxSN3NuaUhsbnhnRWVFVDB0bUdwWnp3Cm11UkxOaURNMlVtdVNJUVp3aGZY
        VSt4bS9vRGVGUTVkZXRLRldpMDBLN2MKLS0tIEFkSkRFNnQ2blNscUp6Z2d6Wmh3
        K2k4VXJrcVQvMm51LzhwbVYzcFdicncKmmMvstxp8H30Tgcw9Kiatsmg2vZen5zn
        m82Yk7Coc6CtOsgOHTnxHrLHdOQJRY4pWAFD3drKES4kGCv8otilsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-23T13:18:04Z"
  mac: ENC[AES256_GCM,data:I1I/o35txwMmVXzhvdGZYPJYn173OK8G6pu4w1FIcOapdkWMJHNS5vp0d/H02/g2XWqz9thnTQY0MIEwr7s4uZuH1ZE7YtbaZ01XYVoJdAEL248Nmo+5R784KTyjiBi9liJp4GvGXBd9B6W422NnsjW1OYg9Z5hRM2WJM2Ig+C0=,iv:gEmu2XuScvH/pFGLhaBqoIc1DtLTHnhauHDIyY51GC4=,tag:WG8mMPbxsQsVwkNZlweo0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
