apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
stringData:
  SPACES_KEY: ENC[AES256_GCM,data:2Pj6Xft+wgLobA==,iv:HvpYw61qw9bNxDj5L5NCs3VSXktIX89YLsGMkTwM9lY=,tag:A0KjzWjKAUYq7LpSLWmolg==,type:str]
  SPACES_SECRET: ENC[AES256_GCM,data:5mMR0YVTOqTPAR6+BQ==,iv:1TQm9ighYavbHkNG3ykNy915dTNEVfQkCopbHJwvTp4=,tag:6Hsgq8XcbRBPQ3ZviMA/lA==,type:str]
  SPACES_ENDPOINT: ENC[AES256_GCM,data:7/57FTZ4ZTRcv81Ab5KDWXeZ,iv:n8SvR0GCIF0Hg36fNstZzinOfvICiS2WWPX4QRT9zL4=,tag:KdU81LdVI4uw81QYzEMN/w==,type:str]
  SPACES_BUCKET_NAME: ENC[AES256_GCM,data:DYz+Se019OPd/w==,iv:9ERGCfIp5nQdT21fZNYc8ri4cbywswY+EB0sfKBTvng=,tag:oE26+qtIgzqGvTEFrlofUQ==,type:str]
  SPACES_REGOIN: ENC[AES256_GCM,data:h9EGmlJy+FI+,iv:6OnBREybCVKE4NDeC1pdRxIfOqn8XBFH1fidLEvJKxI=,tag:BzJK9VFmtsyLQHnBzolvLQ==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:UEwCkDgzdpIBTF2CT2J5NjKxEY1s8EXa4k7PRuNYpmGEm8r09cKPLjcDi4Q=,iv:IA3i3t3NBzrz0nlz09TZqXbo9GDgTQ7gKlB7r1XeuzY=,tag:OM/4iWprQeuQWZY7olj2qA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:jYkoMezee8jK7EkD/diQY9el9KBnK3SqZrDUWpmpuaY6kgbODVg8X4FH8/D9Hd6pAPm+Cyz3FfiASlTYQNqzRgD5yemQg6Nka/A/mT70WCgyCPxYOO1nIMxABGjbfbWIszFEvIaUR6l5gIdD98M/Z85cHNu1UAYFjkFfVUNY,iv:mjYHXZ+AqqVTJYS3GVUq4vBQ48aSiZARH9fBhGXxjLU=,tag:xVashbG60BZ5J2tgLu0KjA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YMefzzzSLCKM4w==,iv:FIkGZb/SGztwxdBvdgApwGdjRI/uhXt15RzvXzsi0Ds=,tag:2wApGohfHv+CWMi/8/PPyA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:06Tue2uI/nKzdVaZ/lL96D/Fn9iRcuxsVrkrHmLvAVUVrPQb3yRP,iv:fxYMvcDAJ/cdBPreHWWbrC+JFSgqccu+bEa11Bvicfo=,tag:gsVYgO+24XeqNXxwu456ZA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:60cZu2w2Jve4Hw==,iv:D0hj1928Eq8hCD8NkNZ1sl+k82GtK06c1ZYjGP6YIDQ=,tag:5gzBfvOZIBp68RbMLTFlXA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LiM0gFCjNwErlf0tFNcWPeK0bGQ2Ok+QhFn9A5KMwMvNPhK0xRn4YrdjN2vcWHH0gD0e8gcf4CgxoXfazYypqA==,iv:+jN/mLv1/J3Ih8L3O3nbEKz1xZmEe1GM1470pTZ7mRs=,tag:OiAkEv4ZZs6f1onFL7NWLQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:kkwZ/nbDuL94QmINfNQ=,iv:0QgQRFrBXqcMm8XViLze/4XZAkn9/2U8m2IppiOORLg=,tag:peOKhmvzHkWKzXI/fMqEyw==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:+aL9YgKQ5dc=,iv:1P4Y1MaBBdk5Lt8ufeUgqAs30Ut//dX6tAuuwiEJX6Y=,tag:E3gWyrNtlpKOlKAMJtdlOQ==,type:str]
  AUTHENTIK_ISSUER: ENC[AES256_GCM,data:aZqGd4ltke837mo5N2jMtpJ/3vjs8NWCL+V63Qq9Q94pa1+NN3MvqAgBZnMq,iv:kg/VFQrlePrqaJRNXKpP0vO9PtoWr73FasiOxKNQnaI=,tag:TeD3zMIMJp+rMpV26QG6FA==,type:str]
  AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:WMFUX0o1OC9MKSnz2Rtaf3dtF3Joo1QNhD4BBr8ay5VjRXv3f3/52Q==,iv:lXzgq7cSa5GqZZQMkHhXYigr0dqnp++u44GmR5RXkto=,tag:sW3LDwmTBSNEsaKLW+4Lsg==,type:str]
  AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:gu4bktvIxNGetYDc3wqsYbJEFjXwYU7GvxAt6IDVg5TJdzHffR2NiH2CujbN5PQnm6cx5e+RDHL+f97RYwmDyNDBTiqUXdKhrRGnxVnthD+QtXscZqZYsm3CggFD6td/yERwHWjXqrzVNm79rXcBKEHcZ5Vd4kOqWEuCHB1bqFY=,iv:0ew2eFJkT5VMtaRjistk0VhK2bzRQNziUJ+1hjUy9fs=,tag:vaQ7qZLnDAs98YJW1Zw0rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbXNhS2MxZ3didGMxUVFI
        YndlaGxwNG13L1lhRnVpRUZQSVBJdUsyWFRzCm01LzhJM1l4YW5GNDEyOTFYaXBT
        TTh5TFN3Njg1NmlZdWpkQ1B0THFrcXcKLS0tIFcvNlduQk1ZRE9BbVh3VnBGZ2Qv
        U29OWTVBRTBVNkYwdXFJRnhXazRaZTAKZQwibtazPLiMXh9qwoxvXx2sGWEsqlJW
        WDOqy6QbT1RXpY35KWFiZx4duyuplCn+0u5+xc0kkUnwGS2J44t9cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T20:52:31Z"
  mac: ENC[AES256_GCM,data:OWBegiEyw9uaAXSTdYB6WC1mZc5V1vGdFHmgk425FDwWVPMZ0VZhEKCqMX82cb6zpdIveP0Ofc1mRyGgWSAZvDB0zNEAr6v7wXZwqyyeygsLnQUPOTibWN2lq64yI8DTm5XC4dpsGumbcEF08nQOdS/IoZT4cxgXkoyTDTOxU5s=,iv:sZiV0w04vtu84q3r0WKHzcXr9ljQk2YD+EAi8PI/U14=,tag:oIfk6srdY2Is1AAC1T5FrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
