apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
stringData:
  SPACES_KEY: ENC[AES256_GCM,data:dOnaXmjTybsRQQ==,iv:rksdavEjwmlbF9bgnizOsQ7NQO381j1gaByhbzMCJ0o=,tag:SibE/zn/K7xZQgGjHaZ4+Q==,type:str]
  SPACES_SECRET: ENC[AES256_GCM,data:d2yfbps4EUR8A9BDLw==,iv:irPaJDzzF8JZ7frbVKJriQ0CAVaIQF3pkRmKKZro13I=,tag:W5Bq2HCN9Fm1XF+3TEllXQ==,type:str]
  SPACES_ENDPOINT: ENC[AES256_GCM,data:7vYEYj566+czcRNgePZzmd/M,iv:osUaQmBR42YS7Igsnr/jAxteiqpoDqx+fqEsVExSlGQ=,tag:ghykY8kzxv9+asAsgEXGxQ==,type:str]
  SPACES_BUCKET_NAME: ENC[AES256_GCM,data:6AB5TEzlcOWYaQ==,iv:9yOb0l4QXAbVWyccR6BfALXU44go8zRrWlxui3tElkM=,tag:oPB6E9ueSmmp1bpk8+huKQ==,type:str]
  SPACES_REGOIN: ENC[AES256_GCM,data:WpoGY6vuYmU5,iv:Qy7HAYlOq3iIW2eR4tCEy/tqSZvsvap7LZCQJiUgYqc=,tag:pAIaF5VIJNPrsrSwCtN+uQ==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:lkrZw0x6MFAZyzQJLkULwZwW/1ym2Kuxwvt4Ob1A9i9rOu2ptiT2p2POK/g=,iv:5Ynjk/zqo+9Xjse48jYUJsWTD5eD0iJaoxRwLsGQQM0=,tag:gE9hWH/FaiSaf8iz9JwbiA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:Lw/9uaTQj4kGBvSb+wTyyqAhF/qsYnoQIlCgrsT8gs3w8CPK9/wBZp0mikcqMuyURCzBfg/bMYzGSdREmPya7NVPWRvDvu3cU92bv3L4BOvNqWP+RXk7KCGA15g394UUdbSnXdPJie1yEOZhp3NAhcIepiOZVQ7JtuCKRV81Hro=,iv:+WOfiKxjjm2wo3FdkuwneCtZgpmxB5+P4t4jA00cX50=,tag:0EStNtgwNvbw63Z6Ue77eQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YAZ8D74LbA7qlg==,iv:DmzJopn55Fx8TUsk3Z8pyVQ51x6HIAm5Ldrn56zDZZU=,tag:svoqilZEr2FuGYzMob5SuA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cHqviWYycaidoQq74ScO/OEeNw+fpqmxyXIgM3cPqEJl3WYyMEX8vCI=,iv:TN2vgBsJBJQcmNhMVBkwLIxy1XoWOG+57qJoOEQg7NA=,tag:3zAkBzL+StBQnd2wvj8/mg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Nsw0ff1YBtq6oA==,iv:fcgiid+DL2EbQBcIvZRB+quqkDiH8V8G4gMqJuT4Icg=,tag:mXTrSzTBn26SVrZ5LN4/Lw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Iu9RhEy0GALRz2QyRsfCz8mTjiQbfF6NLaZOClQWfuSWIkc6BxmwmOBEOtwSKCu3tQg1rw61kI9msaOprNMOOw==,iv:SLPoVOKZMEFk+tKVdWmmVQB0zvsxIG4hqCbPs4jnO1I=,tag:k/kaFKDKLxS8CA0FN0DeKA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:y96e3/gMGJgk7OVojXE=,iv:mvXHdwv36a8PI5WubTPdz+Edo/Ek/NATqoqDPTdRsl0=,tag:X5cdvUYGyevsTfLGB1aKDg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:i2NVAN8fbCQ=,iv:hY2CAFmhWws6uHiRxCnwwT0dRec+bV0/0N9iZQNNJaw=,tag:8b0KSbGi0tKcFe2O8IIW+g==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzNBUzl2a3VWb1Jmb3pQ
        Rm8vTTBtNnZFcCtWcVI1T25JWXhERXBNbUMwClRkZjI5cUtHb0RYckJERTNYM2RY
        MW40ZlZXWWpkSWdsRVdPcmg0L3pXNnMKLS0tIENpOSswYlc0RzNUTWMyZlkyeDds
        N0h4ZCtXQWNjRklpb2E3SnVjbjhxdmcKEOJHV1G2NE65AQRoShQK7hA4rXRM36yn
        iGdGVGv7kid5eKjYBh1HQPqh40QD0Ne6gUED9OutlCCj3MudpOlyXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:9FUPU7W4rJIfMzDqFfWYzF2G5c6W4HI03Ausf0v83s6c8IZPO7JadopH+rY5GC3+Zvc81Pc2EqGINBtI7oxLu5ZeA+W9kDhVFqflmg4yy8qZug/mG0cce64UsS6guqx3ckYe8xE5He5Cg87RVgMles+yRYyAgpTzWI0w3tK/ia4=,iv:GDH5qbzzRHqBY98jlEWY6lpbZ7QRC2XB/MT7FgvqnU8=,tag:iCbBNvbaO8pNGPQ1hTTnjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
