apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EGvjTc1a3A==,iv:gUtqnGDXbHcYENNFVSfck1Ii9M2XrCuHfMiFe8ji+VA=,tag:Y1d/9i0jVLOHBbKafkcGFw==,type:str]
  GLOBAL_SMTP_USERNAME: ENC[AES256_GCM,data:L/hr9+o9s0jgt1G6iZQ=,iv:At7mwMl4vbj/8bFoDh752tIIIS7l1H03hjzKNBuk0uI=,tag:eB2/y1B3GU+A/wiUHDoZQw==,type:str]
  GLOBAL_SMTP_PASSWORD: ENC[AES256_GCM,data:JvasyuJcFxez0TGPToUSgA==,iv:aESPDwbaoqzHGAtelyT/wt318T755ljOh0oNxMvPStE=,tag:dT9jWtW9r+AfR1+YCqlh6w==,type:str]
  GLOBAL_SMTP_PORT: ENC[AES256_GCM,data:FZdJ,iv:pzTNs0n9O0UG0VhmE/SvZ9T0JuGaDtQZ8cFznlZmP2s=,tag:W5ssaPn0A9hgoWICitaWJw==,type:str]
  GLOBAL_SMTP_HOST: ENC[AES256_GCM,data:JrdO9cSVlbwKHk3l00t7JIZw,iv:v+yESERx7ULzouaONCmhxcUR2mszZpCxJIDtbH9CFW4=,tag:2Gy+KDwUjWl0I4/R4nrFaw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS01oZm1BUTBqQmhaNGsw
        VURmK3M3elczbHN4V2QrL2d3Y0lUZUgxK253Ck1zejdRNjB5Q3FtNEZvYnorQVNS
        dWtDVWtONm5NcXowaGQ1L2Y1MVc1MmMKLS0tIHJhVkU0NGxDRzQ2enQ5NFlFSTlj
        N2pHNGMzbGNqR3ZGN3BLR09yajgvajAKKSHs0YaIy41SYg6CUbf+ES5UbxEG30/U
        PJxzSwJ0OaMeDfhxB06uGmlTzGewj4ccZ6gSWpMhj4Mtu2MpjF7c+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:Dl/LH13NyMwT3eAkcVoSroQmF7mygZDynto9trZKQtaaNhN0+X4/Lg5frIE+HAY2YLhKjRLutIAbJKtnhGzPEEnKKwHl1bajEfAi83lq9dj2+45gNcuxVeAw8as685NlXkFRyHqhH9dzaXdFhP/H4a1/cw3D8CwBDfq1jiUv6jY=,iv:Z+HIKoQmP7KS7VQNtO5PVDdJjun+505gLncHnMpYMP8=,tag:v+I1BWVCa6/AYM418eBHXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
