apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:vdjnEN07RUMe7pQcfABTZkZT/IJObOlRpQe8vJyxHSYfgFBxDP+NPv6BdCk2LHVRWpqTwKaH0747/30tBEiWy+A6P0mhdtH5DtA=,iv:Gt1xK17n+wMceu37CmBjeJgSBK9Ed0VfEG01ByMXQJU=,tag:Ktzoi8i8QfVs6Hi8Rb3t1w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVIrd2xPeUdURUtyOEox
        bVkvZVhLY1RoRDZLeHlSUzRJeFpKUXBLbjJZCjd5WUFPekQvdHpHKzRlM0JYQmVF
        dDdBVnhzOTFVVnh3L1dHVyt2YXNyUUkKLS0tIEN0clVjU1pDU0tyMVJmM0lTL1Vk
        L0hWYTBhZVFGNW1ucUhtU2RXT21MVEkKpEDLi3uG+EDeSrl3z9lnvr3+t+eXpNei
        bMmJ8YRuAs/TPlr7r3tnUXyuyy9HSn03aOxNvA2JToYAqHKtiDn+lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:VJ5xk2nH3Ry6EjMUlUqP/NZslWxMcpsC47xGO37CodUP3ly108WdL8g9lyD8NY0hSjQDPllpvZwxFklgYCMWx+N3hxgT5bJokekVfU3+KKxWGZ/vR1OxkTv2FCuVUiVjAW0ngnDSDxVJUM9MQzdkvGf7tA72FgpBf7z1A37uu18=,iv:BsRbLDyaQTlz28U5aFkgI0nBZxDwLgQqThx1DoMicaM=,tag:Bu4MQA+2MNdaffupduMfgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
