# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PrrizKp+bKV20wWgD6byzNbupCqE6jihLrWZzN3S1fOdWNyXfQlF2w==,iv:lT62avmZ0OmvrIVafj0zVBCm0s8fg4agzxhGM0ZHCyU=,tag:Gl9K93imyhu5/96jt8MDtA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcnRMNjhOb0Jpc1NKQkhp
        MEJUVThqLy9nRm9JOTR3U0dlSUd5VXpCVjJNCmtSNW0vNWJmWjVLWlJLRUl2U0Q5
        SlZmZjBMbHBoa1NuUUsxZHUvSFJYWjgKLS0tIEUxYTE2QWRjeFovTGllKzNYMm9h
        TnJveVlCU09kejlEQk1QUGJtUHlseEUKb4V6o3JOjohfDNW+LRZbj5q3vGu/YcBQ
        MJ/FhlvLGxNIobaA+0+UfhtDMVgPO1zm/tToteiiAOtGlmQBpJKDZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:TcJkbE5as/WBLcm/KXWwuTzN7/LTamv/0EQAbAyZAe7azg4RHD6ygr/2b8j0XTf/K8SbNrge0mg0QvLvwmL4iaWIjy808DSiKO2WBMyE3aQ33o7zrAzwa3tCyMZnAgtp4ATz4KtcWIB66J8VQwKSgEj6GkhF4ypqaug59I7+Guc=,iv:8KW/6AdASAwCm3i1wl5aCdFGQqyhfJWz7gzCnSnwxow=,tag:ZsLVTKa+RRdJ+b8wnfCVnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
