apiVersion: v1
kind: Secret
metadata:
  name: atuin-ai-server-secrets
stringData:
  #ENC[AES256_GCM,data:Gs4jRFVXGn47HPpruoTunWYbSj8WFBf5XGS+iWX3K9pzws7FosBqdqLusubrv17gYzFsMng3hlL6nQ==,iv:en2LJippb6U70zX0I2+SlIIF4MlcZPVsPWeIKJn5nCs=,tag:9Rj6uaRzGEvwmg8iUg+LtQ==,type:comment]
  #ENC[AES256_GCM,data:GZGRrBEeeDRfDt6zAiSdIpHYHxmYKzll75Qh+wuZJEty/W87PJ2l6wvQ+akq+KPz2XvP+BmLnBkz,iv:WdDDStgyn5OibK3GIG/UdwcWxK5Qf4OZIQ10ie9gIrY=,tag:6/3FVpWSLklVRHr1xU2RAA==,type:comment]
  CHAT_API_KEY: ENC[AES256_GCM,data:GF5ipzYPZ/1QiAvxdVj96paLq/njRiOm1A==,iv:SF7GvfPVYYtxRdtvHIp+LePTeRiZwZdf0EDh/wENOys=,tag:VKX6zcDvjpgYda3ITzVz2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaWdaR25CSVFvK2RZbWFW
        NkU2Rkw3b2g0R2VITzVoSVAzVVZkR2JaUm13ClV4RlhPUGwxb0I5cWZRcjBEWE1G
        Wnh5aHFjRjFTTFRoaUR6T21DUnl2KzgKLS0tIFVtam1SSFg5Y01sR25UTytEcEVR
        Z3ppUzM5bzBRTzFjRU9GRW9wbEo1dVkK/WCBRuEytES2QlyMnS8Xf0IpnXC3shVl
        lJA9Lb9u0zRNqLuwMSrlNOV8Zai7kjKMAIsv1gJ8UcgWOp2W4DpNKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T16:07:49Z"
  mac: ENC[AES256_GCM,data:t/mufhQ6TCYqI2cjCIRrLvvNRHNbx8EeURMRBtHaDgHw3GxrHaemCo72HnLr0RkS4fgCRSu3Lxr+NuOjzxNlUBpk02ccSnbqQO/39rygHRaGhQIqE0K/h980O3W3XcvQrOZcsVomykks9ot/PkN7DR9o1nVFC1rAy0fgdOgTT6w=,iv:x5VFuW8lh8H4iVllPimBF5CHITXVSEVZjcTcMpec2ak=,tag:WMvKVgqTEXrLLu6wN8drTQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
