apiVersion: v1
kind: Secret
metadata:
  name: atuin-ai-server-secrets
stringData:
  #ENC[AES256_GCM,data:fIvKVd88+3IPh1ouGuDovj/yx33HkQgsg0eJMAChoTSgy/ey75Ew1Wuti1koaTmJ6I/clo2s5d15vQ==,iv:IHfK44mzzojYbl+E98+UCsCsJZmu1RpOiR5MmVZtPoU=,tag:fcyes0/kWyBZxtVH0jyD1A==,type:comment]
  #ENC[AES256_GCM,data:6JNjb8eNh3oFDuQtrFHALHw8HzsmxzkM32VT4UIad+Cqvn+Eo7XZ5500RH15/xzS1cyfNB2ApeVc,iv:61kpZtsJhqZMYDQzhQFH05x+8fO8awhvHRGTULelouE=,tag:aC6i2yzH3AEcEffl1UXzDQ==,type:comment]
  CHAT_API_KEY: ENC[AES256_GCM,data:xdqIS7z50FU0rq0q8paqJQTPk/3OrOfiuQ==,iv:PR7z9tpwEk7ljbQ/N9SuHgHZSlZtVJzKA0Qcj6OQBZU=,tag:UBc9UONzm6l0idwlgS4x5Q==,type:str]
  #ENC[AES256_GCM,data:0hGN8V6bkGHbQ2nvaNhYiGrwxc4KNs2iXrr6cKnoIj+qdzzD6ludckVNTbLXhkPxWuqiz+QG6x5OR/EA7pEVs1U/JOzoCeE=,iv:LqV2g7dcCWpsBzcETnAwmGiBxFqsMghJ/wWFnyPvOpc=,tag:bbWv7Jlb+ne9RN9Qf/p/HA==,type:comment]
  #ENC[AES256_GCM,data:7TFCPyOwlLDD1daBpf3QzprdctulHHDfYR3Zabhs/X54GWjIUhLHEwc+3Q5EfO8AqcR1w8uvTZIBQg3TAX3aEWEChg8pkSA=,iv:r5e0onI0CTTutQxWCk5pNaMIsJkyASY9JBtu5gAH4dI=,tag:g+GcMNR3xbEB5o9oz+ldSQ==,type:comment]
  #ENC[AES256_GCM,data:/CqT07Ec1y4jc2TqQD1CkapwcfFPtOUB/vORpNcpSHpwgzJl6mhtY3rpqRy4ZPTKhTp2iYcezrcRYX1SPEla,iv:YeeJfmmmzQFMMg95/AJghPtK5vGmThp6z7TewArWwIw=,tag:NZ+GMEzOgSddPjHdKtqHew==,type:comment]
  AUTH_TOKEN: ENC[AES256_GCM,data:1reqjbYTGlWXuv7XE3E85GVbUi2e6ireISYN8GyGwEpqXHuuSn6AMg4XaA==,iv:njnTt4f+Opdu0VAK8FOQcyPWGFQXKfPNqVkFpcpraBY=,tag:s3cx+YnUnEDvjVWJpfn91A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYVJGZkQ2MzRJd3ZsZmU0
        QWEwbjhNU1dKblVhNlhKMnBaaXhpSExxY2pzCkdZYUlZVklsRWlFc3pDMERnYmpy
        ZnZEQ05vd0ppWllHVXZvWEtmUUY1YUkKLS0tIGpnakFaWUl0d09OT1MxS1IxeUJa
        L2UzZzlLbldZaCt4K2FCVWJZQnFUbmcK+T/0N3aQV/IWojHFo3ofSp9EEOxyl8pa
        ja9f4dtVYrxnaLi358SvYSjl+ySJE+6773SCcDPvUGcrT6jJn8YMUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T16:29:16Z"
  mac: ENC[AES256_GCM,data:RFxGo0aJGmtPDUZ1ERTPudalG/AOJHbHKGce7Vi8qqPOy24g6CnMLPprnBrs2W7ig+VfKSDjGVX6aZ1v0l0cYP2Jq7eqDv3aTL2PDAYjEPHcPp6KNdJBPlQiLSTwlcM+15m6z4CsWw9ZCuiq8DiW44RBtvXmVikXvcqljI1hO2Y=,iv:wQDvk/ImuDOKOegyeSGKYwxmB+kYB5oRbJSSEUwCYfY=,tag:KK7LCVKAKjmqbiqddrPOtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
