apiVersion: v1
kind: Secret
metadata:
  name: atuin-ai-server-secrets
stringData:
  #ENC[AES256_GCM,data:n/68LkAPZK/H992frmdjFFaQ0FMo7h2py+dpnDoC+eUqHkqtlh1km/1bYJmhKS6zlPaWmMaYgOwqqA==,iv:MIu1FIk7xiRw6ZQSG1WhOx/CLPA714+StxxVNeK/Kow=,tag:v39bEJiL+fErcTzX/ossFA==,type:comment]
  #ENC[AES256_GCM,data:5mwQKhpCc8z3yiIw6B1l5pfpWpG4Ybc2IFpjhW6v1r8IpLJJUIEsxbruOAnzXMi8owdbw7X8msVK,iv:KY7eJu1rrCG7ZYSw1K1c1IhnJsW4NwQA+MBgNufMmKM=,tag:Icea2qCx2Zh/KfopnTYpFg==,type:comment]
  CHAT_API_KEY: ENC[AES256_GCM,data:8rDCpOBHM1WYMuj3TrlzBBQFml4MoIIApRRzwdTJKH0CshU=,iv:NEh6xoEBn/VZ0FdldFYwPVC4DidGlrS58lz+m3xWZRg=,tag:eMVy2Z6Yd8ouRpeZGUgGIg==,type:str]
  #ENC[AES256_GCM,data:lkq1C11sAmxQwnRFfQE5W08iCqU50FXovXhJsJrqbEzs/sA7aN8fMdS0uBe6T8G1sY7kMQzoy04FuFkZSJtW2twmz0qmCTo=,iv:xTMJnyph6jqOB0Wo4YDS15QeOVmo6vMn358WFSIu7OE=,tag:eVKv1kaN4xBfq47qLYdRAw==,type:comment]
  #ENC[AES256_GCM,data:/q251qfIRqcDYXUk/uoYsneqNGJfQWbdjnhwqsNJ9eQk+uKlr3avL/aHFQbmd1gR6ewh6YcX508AW+lG3ofw2mjkC5HfMO4=,iv:HTvEoCICQEAvaETXXqXOOVAFdaYmOBgCfKOux7KGHM8=,tag:qS1sfvbfvn1+RbDU9n4pCA==,type:comment]
  #ENC[AES256_GCM,data:3lIoz9gYuxWdrk9TIaMgGh8bMkKzCXdrL/qfUZP91no9obQo9vwzH7H6HNnH2Bo9iBk1zi+SIxhZR4F8+RTD,iv:BQkzZ+KD8+gJLfyBjizjHS8k6Z3VLT/AB1oDKtfv/8Y=,tag:6KDHD76ff71JWXM/rOA4Cw==,type:comment]
  AUTH_TOKEN: ENC[AES256_GCM,data:xmLOA1z3tI1RxSZjPSg7eHVZuW9I23kpCVAdsmSXnRImsTdQdplbE6rrGQ==,iv:jUB0iW/JkKeFeu1v8CJckAY4KTdTVUBzc1nLjM7fF74=,tag:qTzc06CLGG+k5mkNNRQkOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dFFwZi9ib1dPcjVoeXRB
        Sy80QkZqSGFDT1NCRHZFa1I3aFBRRjBtT0JrCkFTZjd1K1JNVUMxK0hnOURQRUlw
        dTR3SG5rWkZNTWFvRk9OOUxhUDJKeFUKLS0tIFZ6bHU1czRXMkNuNUo4TzBMNkZl
        UjJUc25EZnpRVUxFRUdCckZzQllCS0EK39DuPXGRSaZOorCFDv5U8vn5q8RDdVAO
        B4r08i40lkPvfQ0hLXnyAfCAirdxqi52E1AcHmyRigGEbXhig9hcJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:25:28Z"
  mac: ENC[AES256_GCM,data:ZDGlhnpkmYTDY7RLo41FbS8kgnr1CQHLj/g+uAJBYSv8a+5FaYYk5LnU/CqdLQIswI8qiEDQQNTC4C5AVEd3OZ39RXlTJUng0t9MfNK8iGncUkWtZpawhrmMkFaqgnxhuUnyDlIGPIfwiERaUH2zw+C/oMaNZhxC3K/j8wm9eck=,iv:blwUi3vK7AhqSswFg7WMtVsnaJiSNZuzWbRTtrVcPrY=,tag:wjCFNq2DkrrQEo1nrnmbXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
