---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-operator-crds
  namespace: toolhive-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
      chart: toolhive-operator-crds
      # version: 0.0.7
      sourceRef:
        kind: HelmRepository
        name: toolhive-operator-crds
        namespace: flux-system
      interval: 5m
