apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
stringData:
  ATUIN_DB_NAME: ENC[AES256_GCM,data:S2knuso=,iv:jyZt1rrtyYzC37eTdMZzEssarCG4ElcV9M7vJj3Q4Fs=,tag:TezlJ0y2qTPq/XzCuRsfQw==,type:str]
  ATUIN_DB_USERNAME: ENC[AES256_GCM,data:E5Ukar8=,iv:mILbcOmfF7TI+Lp+N0qF6vQvcplk7SxGWyxw1pwhb0I=,tag:LM2fcOZ115y6dfHV3IRVOA==,type:str]
  ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:ki19gKd3JD9Chf22PM4SviaT97rKhBWFpitT6lM+uITzqIG2RGC+6HRX7k0rX5H3cZrJWnODaraESElLHQ70uw==,iv:xwANfiaMkstujnT/5rpxmP6mjsV8utw+0kPslHVOiW0=,tag:yueGauXi39YYMTsYHpmhyg==,type:str]
  ATUIN_DB_HOST: ENC[AES256_GCM,data:8k47odQUjuIsxQM7D2bDL4H/lQKxQ9zNa+kIigjgal+cxh6dnyJr,iv:rpgSE2Xusi5xtbhtIqjmyCdxjLBHlE6niYhjwPttdgA=,tag:+iGuY5ssOdl/PlPqLFJekA==,type:str]
  ATUIN_DB_PORT: ENC[AES256_GCM,data:8/8dfA==,iv:O2YD3hTcOcQw5SFxtt1c2MY9iGnPwNuCVHE+dmCM72A=,tag:5RXL3enVp8cvvZW+YfSzUA==,type:str]
  ATUIN_DB_URI: ENC[AES256_GCM,data:8m5+xGg7d4RAzSj9L+oFuCeRgOyST/9uC21AxU6u92qA2QWpudvEqdKWCMIZxFInQcPTFCcZYnYMWMweRzMBXvAkU+oQlNa364blWOE9JzQDSkR0QI00qcSDm3nxB4RypphPdzv8UB6IPmbcefTlGSJY5Qhk8kMUwpfuuUEgh9Fb3Mie,iv:J15masTLfmvpfdJoP5p7p/Z/mD9ylfpYwh8TadKKhfg=,tag:jsWQty9+LwNuRp2Vkl5Qcg==,type:str]
  RUST_LOG: ENC[AES256_GCM,data:n0HQe+tw7nfYwZ4sV1fo0Q4PL/aD1ig=,iv:n1SKDBAnAzUxK+PCA4pAyOLUZj1mz38iKXtkfbXEoFI=,tag:oo/6QcWHbmpiT1tvRiP14w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5NhBVOE=,iv:v96o01A1wMoaOf0zqibZIe5Eh76/vRIrc7Uz/gA3vcA=,tag:AGMhVoDJk2h9EFyhwdn8xg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2oLGKLBpojioMc8iEXLx0McSAGaJXHQfEuBitj5r9WXpYlj5vMoA,iv:lh/bTMS8Loc58B3Hv6NepuJTg82wiFZ3l6yTPyuHf7I=,tag:YwxBhQzAZg2T1DpD0ydDNQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:a/SjBL0=,iv:wQxSeaIWV6MqpfSs1iGZi6tE9pthjlrpTRdHGpyuulQ=,tag:Xo8VgcsElKx0DzF6SnW3lA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:b9d2p2AxSOA3PRP4VqCCCnwpGxm4+APB5BZHbsA7iOVlLT5RWwfSJ/DrlrCROhkR9XAQZ9c9zb8pw5v3rNpLFA==,iv:5LtetQHqQ9GuxBrL2jNvybfZdv3l+lRje2MtadDqv7k=,tag:a7EKFDO3225KsPjO/TwmeA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:fVCTE0xKfGWuVI9U5R4=,iv:dwMPDzYieBIYNhTXlGbtYuKzYRIbvf9DaQTTSZoCxsw=,tag:DiJQ5yMbRWNvbx9MCQqyEQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:vVCsGoBuUwE=,iv:Hj1VyB7nRd4j3sMXsdVCbYBYdjw+iBiDhVD55esEnQ8=,tag:LdEHIUm1SK18poIriOw3nA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb2FXNmpPWS9odG9rRWZk
        TDBHeTlsT0I1RE5oemhKL1VUT2NrK0hsQ2hZCkVueE1nTEdGWVo4UjlXU3Q3L01I
        QnpaaU82cDFwYnFDUkU0NHVOeVZzZGsKLS0tIENPM0ZlVzVaM29RQVdPRHFROWNn
        MCtNZEIrYVVPWUprZkl0bVRyRDdYSEUK2vpqDlWDV1B+EupviecND/dJeBrgyjf4
        59Hh19DeoheCDTyxUg6iyMurj1BCCxqWvqJT1MYD4iR+WtCDoHqS4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T14:21:28Z"
  mac: ENC[AES256_GCM,data:23tDClU0AZwnEvSjkqJhEa35TVxgdbIMRiWB8rJ3YF9jidKGlOd/6X90xAfIYxRUlj6YHlrivphtrdQGFoUb595/H5sPxDRXs/nDPSrOFC8FQegm9B0Gb3Nujds27rsR8cpyjeH40r+WljBGykT5sH3HzpniGLmDNs1u8tILUP0=,iv:dwNiYIjW0TXw9E/zL9HM/b2t0mw2mTBwKH6gECrvkRM=,tag:IQ1BXkJcHRIUwqo+i4D8fg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
