apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
stringData:
  ATUIN_DB_NAME: ENC[AES256_GCM,data:y6BiAgs=,iv:gYn5ka4qoDxacON+qSfm0+MykI8Y7EqwiOPk1g2IXB0=,tag:YH4OCf69A3R8K5ncFLwDHg==,type:str]
  ATUIN_DB_USERNAME: ENC[AES256_GCM,data:yatcWHs=,iv:O/ulQyt7coy2dbeJWEhj6zGQ/KH8tzI05nTygSR9HF4=,tag:88I/tXvCfi8KrSnn2FY2Dw==,type:str]
  ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:eerTgTdrqXJwPBrpyoyCv4kxZHrGWhXC4N4MKxK0UDXTXVK1dYLcH8BOMYzaNDTwVeSoA9p0eUQZXQEiqX9MVQ==,iv:PVPkIcCicjt+7KZ3rc2jwFNhNFTEx7qmYKROxcgd9A8=,tag:4Xm/q29v2RQH7F4oYJk6dA==,type:str]
  ATUIN_DB_HOST: ENC[AES256_GCM,data:xlsWGMPnOioXjwEFBBh+wmFU5BrnJFoo87qUnk/roRG3v7OYX2iMWEo=,iv:wHD7vKcwKP14AMfzPBlxv1ICi1N+Zwku+1x+CpArcBU=,tag:yBBMLeqNFo6rTARw1klkiQ==,type:str]
  ATUIN_DB_PORT: ENC[AES256_GCM,data:n8blRg==,iv:/6VojuGxmao+yfYngtIw/JPS43whRUxYerwSZI3SpvQ=,tag:A47PKrJy6/S8jMRYqNxkfg==,type:str]
  ATUIN_DB_URI: ENC[AES256_GCM,data:09DfvTanBSPnTpNT1hnSGJRv93n0nDSBQtp2Oi65QnthiZbldZmtY/IBzdR7GFbfqYg+6wKnz03aGGTO7MtLb/zN5rEWM8BCRblAtwBgar2meOSmpa4lAm4Fs0lVAXG3o79TovjdOt2KRiHq1vB3SBfyVXTCXRqAqC0vPoGloUvKOTnXl0Y=,iv:05egN20SDwGBeB1YfjVwdWMmqe0daK944defLSEAIy8=,tag:twy2G5SA5fMP5KXNqNDx+w==,type:str]
  RUST_LOG: ENC[AES256_GCM,data:gKjvlGpvBBlILvD8C/IMFTjisUihM3E=,iv:AeqxbQTC0OZl5PrXxhBK3DClfxf8lCPXVBVUSTHXmm4=,tag:LA63Mf2k8nIUwpDel1qdyw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:k87zSXk=,iv:9QCEvySRZRzi46K8oPaJHnmnKC2pdxkXVbRiA0XR40o=,tag:wB4bk7u9lwBwyPDpsVb1qA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nDwrP4IGcIxzTg/eA0igeAd3PQTGvasi6ckCfBEJ9Js6Jb1JoGtoabo=,iv:HR3siYTii6QV5XuIxY2bB/GDK2FzX1rNku9NJdyvvKs=,tag:2e9FxJMHgLRuheJE4uP+PA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:XXu6SiM=,iv:T56dvElnlZExsumXYWouHKco+kty5A8uZSp0Yb3ct0I=,tag:g0WRXPGNEU7xvLtfjpdiQQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:t6IaBouExk3WUbnURYj64Mt0fKlz00WuX1Aelg+b93YJMkgyRMbRygOfSRMdpmfmoj55TC9WrNwNPxoJq+lkbg==,iv:E6AwGY0iwoS62787f3LyUpmBGxvkEeUeEBRijEkE1T4=,tag:yZNX/7/mqW39E3v5hmpJTA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:eSCFPtOXw3Gssrgg0SQ=,iv:oe4jt0gctjGEDeFa6z0XiLyJKErduZVXpqMHCLTzpDo=,tag:jDzZ74RGyxzgj0MfBMFR/g==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gweohn09Msc=,iv:x0WEXgKnrJ2QC2R3vrM8+7wgrCbT44PAxvYCyuIGAkE=,tag:PNpD4eKNvRRELiqDRyeHdQ==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVElIN2lESCtTdGxWYWph
        WVNvU3VMc2szQU50QUFsdnBtdUVETUk3QUZNCmY2M2tQUDh6Mms3cC8reko2VEVr
        VVQ0NnpJQWFwNDIwUmxKREpwQVp4b0kKLS0tIEQ4Qm1jTlBLNGRpcTIvYWY1c1px
        cVdxeUZRdTRZNHcwQm43Z1NmdlF1YmsKgd5JZfdXK2209MDfgCoVaYGO3IoC9N1H
        BNKUO+i6/1schjJJ7SFT6o8c/E4FqbEcWyyWYgBhpzGyDdDknJk4Yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:hpgx98ABfoiC6jMayw9+IuEXpdJ8gJhpcCOteXbKIUk/B1Ilr22//dsR2u8S5bZic5enXuNOKNOIE3lMbMTmRp09z02WhLtK1qTwbCj/xKPFlhwKfp3OYg0GDVPjoJQBEUV+19rCRbYcDYZbfKPH/g+vJH//0OdWWV07KPRa9OM=,iv:jbaTD2eH1ABCXdjgNh5bfUonmWJnpf0mzsfzwjK93w8=,tag:sMXKVo/4QoakZxEJhGzSMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
