---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gitrepository.yaml
  - ./secret.sops.yaml
  - ./secret-holmesgpt.sops.yaml
  - ./networkpolicy-holmes.yaml
  - ./helmrelease.yaml
