apiVersion: v1
kind: Secret
metadata:
  name: argus-forwarder
stringData:
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:6O31P4yO+eCOK/35oDo9cv2zFx6pt7W3Sxhy8JmFzE+iZVgi2xNFsnlc34BbQs0oemJ2OPpN9xz4DPVXiT6/qzk248cQ6Lmg,iv:pBzTw0+3EpwRphRL9OgUHYwcuxsvFVkY2G35bKvx+Yc=,tag:i8VRdhGm79pbNNARnxg2dA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VkNJMUFmMkt1bHZBZEN6
        MGhkL3cyUDFLL0VXVllEVHRYSXZ5SlNoQ1djCm92eGtNQmlTK25GdUFmV0xnWDFx
        SXlCVXNRakYrQkN1VEk3V1RlM3Qvb28KLS0tIHZKU1JFQTkrVVZlOFBuMW9rYkdH
        cVJLK0F0dkRGbm5xUkVxbVQ2aEFJdkEK9YEWwC8W6AihxoQmO2mAyUAoSVCsQGuN
        9JO9NGg52CMGqHFQUklhHipAcSDHx6T+67PV18djfM1lB6AsZTjTDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T22:09:06Z"
  mac: ENC[AES256_GCM,data:e561ztNcNr3IHc2LKUXrZcdCZU1Bey17Ya1qV8p3I2Q6wR+1s4FsIxLg3NZANYe5FrQ2vX++MqnyDKOmHtv5+H/pIy21QdGH+9VuY7TvMwRYQfSvNuItpwbvjEy+9Zq3e6V+ZkK+R94wrOZDDqD8v2ywjr/UhZJmi/rGN5RomDs=,iv:Y7Y1Q1SFv/UaBr3LSNt79M41K2QTPCrXsWHY9e+7Jug=,tag:tLZ15c2Mpofo7nXfPNlzdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
