apiVersion: v1
kind: Secret
metadata:
  name: vikunja-mcp-secret
type: Opaque
stringData:
  VIKUNJA_API_TOKEN: ENC[AES256_GCM,data:Fo2tU1ub5PI4ZJDneXJQCyutNO39U95Kg5to3BULsTyBXyCELRa9KgIJRA==,iv:vbW5drOK2d3VWtsvwVwCsIN34aWBjVwSOHQcmWdgAi0=,tag:l35pUxnKn3xFVmZUpaeaRA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcXlkVlRLdGltRG9MalRz
        dWJvS0E5Ymk3cXk3SGtqMDVIVitVQmRSQTNJClc0YkNXVVNEeDVMY1lGZnk2NmRY
        ZCt6Zy9EZ1hGTDhhMGRLNVhIZkt2RTAKLS0tIFNYUmg0WEo2ZEhNL3BQMURwYnNj
        blI2enhIcC9ZcVc3ZEdrNWlzSmlNejAKNKJGKDbeIWRfSs5yxKwf6Rlx1GN4bYxx
        dbdG/sXsBkc3hqh+TkSVuGb31rnbE1wcmk1n1JAL6MQyt6RaDTeyFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T14:18:29Z"
  mac: ENC[AES256_GCM,data:96b5p07y7nvYrVIH3yWBk9zUeYXCpcrBOusatx7L4sTQBLXX8lifSzLel+Hi1PH15AvmVKZneJ3RdLyiiytWxpH3lE70nacqOHBIxVY9eM+ur55yQ9UnsSU19skW9JrOSdhhjWnie6n4cJIvc6bRtieBNK+YHZL/FFtVNfyLiZ0=,iv:0SLfrP0ijL8bqGjua4tCrahqhqlVkiscAjBEF2Fd6KM=,tag:gM6wFQq1QO678HYzPGJz+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-mcp-basic-auth
type: Opaque
stringData:
  users: ENC[AES256_GCM,data:xlG1qYDsPdjEdgjuCTT9UAgjjDGQjDHwJA9XkFpSciN6XqiFXZ1Csa4=,iv:0IYKHsdqmJWldTkiElW5WutZY9a5fyu9LAVGtNfXZJs=,tag:B0BLGUv28Np6g3nPDqJnPA==,type:str]
  username: ENC[AES256_GCM,data:unrD,iv:zgzIDb7vp2omGiLGK+B4pDm0qdQk2HnCR0XmpXoyzw8=,tag:07crYbccPJD5xrbxvhVlEw==,type:str]
  password: ENC[AES256_GCM,data:kX/uRyvcFs02BIdZ+jRunux5AY11Uy+90fFMyqJO1FK30tPYzsXuCzvMgrc4MM5L,iv:pa5owbylgilDqXifQ7tidYljxWCaC1sh4i+742lmCx0=,tag:Jun/aNQ8a5Gcjndei8nyCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcXlkVlRLdGltRG9MalRz
        dWJvS0E5Ymk3cXk3SGtqMDVIVitVQmRSQTNJClc0YkNXVVNEeDVMY1lGZnk2NmRY
        ZCt6Zy9EZ1hGTDhhMGRLNVhIZkt2RTAKLS0tIFNYUmg0WEo2ZEhNL3BQMURwYnNj
        blI2enhIcC9ZcVc3ZEdrNWlzSmlNejAKNKJGKDbeIWRfSs5yxKwf6Rlx1GN4bYxx
        dbdG/sXsBkc3hqh+TkSVuGb31rnbE1wcmk1n1JAL6MQyt6RaDTeyFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T14:18:29Z"
  mac: ENC[AES256_GCM,data:96b5p07y7nvYrVIH3yWBk9zUeYXCpcrBOusatx7L4sTQBLXX8lifSzLel+Hi1PH15AvmVKZneJ3RdLyiiytWxpH3lE70nacqOHBIxVY9eM+ur55yQ9UnsSU19skW9JrOSdhhjWnie6n4cJIvc6bRtieBNK+YHZL/FFtVNfyLiZ0=,iv:0SLfrP0ijL8bqGjua4tCrahqhqlVkiscAjBEF2Fd6KM=,tag:gM6wFQq1QO678HYzPGJz+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
