apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:7YFE8Ujud+QVFhcxPfaQ0Ik2ExTp/4eAfoY5Yt2/S/I1IgUVmwYzsxpRpvsN9X9bQYWJw+iNo/J13Rcy6cWKVw==,iv:caPbs13gC9/4dnRoIB1RMRsmu+uhTJynJsl1fZ5255A=,tag:dGT7xJcbY637aiCjJn2jCQ==,type:str]
  SALT: ENC[AES256_GCM,data:w7bq6t7xwTYuL6PlTmLDp38gBOJrDhhAUWOSKMwbK4ukI5WAe0aYoOG0hq1riFA4HH3gxKIHFL+wscFKr4Sugg==,iv:CgAtgIbWkaVs/dEtBK9bSk7MzjsfMsuXhDDdTU1L9vQ=,tag:DrZgBX+DQwsHT6bFvNkfmg==,type:str]
  LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:K1CiEzUmjNUnp5M23dhbZUpM,iv:pGo/lgd0R9xdgKhKgAqyZkOG3bk7RDpJcan0Rt9XePA=,tag:hQmou9XycTBKCy32kxygbA==,type:str]
  LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:YuDXkMQ3K+PAWdqck8vAOPFZ,iv:mFSA01dq+nIkX+97zZfc3T07/BLt8HSVPzLpW+GkLCU=,tag:qz4AG6jPmwudOthyegFBFA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Mn3k7nttL2pHUbQ19RP3OqqzIwVhmM/dd22KJ+mpxtCuvOz5fuzX,iv:sm+X7c5kTWyQH2F/mY1W+SW3C7JkNhEDXYCXc7vuuuQ=,tag:MiFb87jCI00vHEDEfiNf/A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9twvIxg2n4g=,iv:a4sxX5W+R5Q8PBxtN8BZPv8ewfFsShp0iwsvXz3rVXc=,tag:NZ5HXFahP4zWmIMoM9i/4g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:zW9K5LiRro8=,iv:E8uuh6Psix0A94dWGpeEDr2WtE+RAYhX5jncJnzvrBg=,tag:S+a/XSmIFzsfovaG8De9IA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:rPKwSzfpQCTQ3ulwakLuJjPdDCLO7ZdQJQmeFxDL4u0=,iv:TYKMd47VPlXcqX+yW/kVjIEYNbHvfzGly8KnBWH4QKI=,tag:a0LvBuuSZXUpvTA1hnOb7Q==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:eNmCLbkthE0=,iv:QWWzlYCOVxSdn/CA+klL8Hei9uImUqZjIvdb8lHBsec=,tag:IkSNRic4II/yzYIeF2wGsQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:O/NPjIubGrkjCrUdUkM=,iv:k3pQY6N8X2IWKPhBP8J9lE00zQBmocwuXtDhiBqqTaY=,tag:tzyYNOBznVPAkWWzvI0opw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:aDhIlJC+TRez6G2CvbUGEU2YFcVdMI5qNd5zvkrW4dB5IZqhFDG/P2zN5PnIGEpJuPSSAQZ9IFEmn2zn7Bw/eo+g1dZZDI2PYK6uSbyPbwjubhFf/nj01SgBTkudDVwp2ttydmmCkv2wu5Vd,iv:PgWdXmCrp8eU+WA7YveTjOGQqtL7tG7RQD8lTd8R1cc=,tag:PE81WJChFv9Hiy4QrvmLPQ==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:NJ/Z5JnfmuKz94Vlore/gmirte1d8ok7+adP8KQlS8t0fab+aOZhisGpAMhM4SawC4tmQ6UsM0rDIq2SdXFgdhMSVrG603TseaiSssfufu9LyKZQYSL86+jl,iv:UFshl/ed7ZuGnqi1AUjtD501Y2sHgAoYZELosZW8eyc=,tag:hRMkWIUV0G8rnqGmXPy5iQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbGJtRmxwa1F3MllxbnVT
        Q1ZidzA0ZUw3TVNPWjFTWEdtU2tneFJUc0VnCnI4Ym1MbjFJOU9CZ3BSdzBYSyt5
        a0xaV05FR0d4US9Hd0tnSnNFcU4yakEKLS0tIGo3bm5IQ2VOdzNZRHFlQncwVGhW
        N1QrYlFFK2JjelZtQTdNdFF0RnNUbUEKb0ME2YAz+m+7fc4pbIWvSORGg9OgiGhf
        MYfw3j5PzkiHwd+gXETAEP6/YpU6q7SNcd2pNf5QSOGTh9VX+eXGAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T18:54:28Z"
  mac: ENC[AES256_GCM,data:A/uzfH+Z2P/tw9UbQcL4fpXUuEGm8mb8T/GnUnLCMxZOYnkhsArQoxpziqw5vOM6j0I65r7ijxARBiNu8nH9xbxU9IJJYw2okyjxJ8dX8lG/S1JUJ7POj3i10eKXee8a7+jAocULKMeh2kYWTjVxsluRlSDQGgJKOmT53nLAhFY=,iv:+duVqwD81SX66iZIpvc1QQscYgx/UKqrcmaA1mAFONw=,tag:KKRiFKMF61EufrcXB/MKaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
