apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:3Bnmofr5wtPZm6azHhOB0tEpbyYIQjQToNANkqTVTZIndbvRHHr82AVO0bPgJG1MF9ZZwTmBRQQ9euoI3dmcWw==,iv:9f8wyN4VM2GuQLHlG57DOWPnZ4FmIGpx3BtQSkrC5Sk=,tag:olSfepwOJ9DkLHadILIhUA==,type:str]
  SALT: ENC[AES256_GCM,data:g3c7Uj9t1dIDXKP7TYyfyE0+vXMu6GKUxZAWXHogR+Tnm1QGzjJDGQLWrOaeEtJmaTlagNfQy73D8MDmS4Q4Bg==,iv:BOyppAck1FO1seeu5kQT2QmbaX0KUUrEQoRqai9yx3A=,tag:PDmONmvOAXel74z7BCzbgg==,type:str]
  CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:YgkoKxgkbtn71GksQxSTP4lgIoQQgKPjZphTlc5M188=,iv:MLjqBRZxQeu5JzstVqXLnmjGaVU2M1akigsKP5aR1tY=,tag:Mwda862RJLlyYfEiijKcLg==,type:str]
  LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:QTxNXqW1dtJyllFkhB89I5O3,iv:vL9+nI3A2Qn4VCXJFi7fyVHkf0XwXtITuXwhktQgkFY=,tag:EZ3FAu1fNq1nLsfcKzI7lg==,type:str]
  LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:nULtD0nhMBKc2BcpcSoBUgnk,iv:c4XRxhrApKtuDoYspkpknpjlNkUyhS+tq5alZs2lrhk=,tag:PUri28sbzFopH22IBzsRXw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2DzHLUpYkMoPaYxRmKmFLyPy9JXxhHEqUQqC0AZ7GQlqGp5XlBIm,iv:Yyqs3S9FGPUeOfC1Nqp+sRaCilHh8NRhAdmyDyrQyLA=,tag:+qIfwkVlN7DVHs9U9SKboQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:nvcFSv4SwvY=,iv:h7gRdy67gMZROdjOuppgC2fj3xFan2znlN54/iKmsug=,tag:4dS8YRMcTECv3Byx1Zf1dQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wujfOnTLoP8=,iv:wGqxNT5AY2DQtTaKm2NkspMAawOckVFQIRjGlcjR/OQ=,tag:TS4qWBDaqZTmkgfGQZoW1A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:9FBPA7oWYjEIiCDwTGiXHiu609yWHGOad1E5d0UBfsA=,iv:89nMOFkwGAMFc5IBVKL6QuwmgbWP3JrhSqhjjNQ1lx4=,tag:eP5EtXJWs1g4AtYOodHGRA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:W3I7e4mpHrw=,iv:gkw6p0LNqL3n6WHlVK5Yn01ZdoTCazeb7z67ljUCggQ=,tag:uADptTv3QPRBhJkJbVmW7g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:r/qX0i1S8Qh+GSNOfRE=,iv:oAx9Mr3MyJV36PrtwruZ+RzoB4n/kyWsclj80TxRu78=,tag:Qd6EntfKYgPhDHbGPJFKjg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:/Fo11pMwE45NX+xUA8kcgo2ORRd0h/rkq9tXRaAUrskqJIKAw5l1Xoan5kQSPGSM0/fFwG2G3/qQVAqDcp0WYKI1pTPUJNbvhMkYVd8/73SneY+RmDn1RcuAhUP2TxusCKmapxb+zQVpPLL9,iv:wWjIdQaTITmmhOVPx3hxxzX6Woqbo2as/mXI9GIcjgI=,tag:MvN/StJrbuymtx+OV6V6FA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:DdXodmohvzitzLFRy+9US7GeTgbGhGEjEOkzgqeXPHiGIaQlUwngvgnunWY2Upd/VeVZO6WiggLA07My0hmUSyn4bfKuKLQE2OgN+gr1p7vwG+62ga2e/qAR,iv:6VoeBtRYbh0nP1tMayIwjiPKksKP6z08MteuYw45634=,tag:1ytxC6iogsQRNCmXnu5Trg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSU9oQmwwV0swenZPUHZu
        UmRUdHlMdlBhMGNzY3ZiYjFXN09mQThMN2t3CmlBRzJ3MnAvNlY4VUh4eDNrNkw2
        K3IrT1U3MGc1SDUwSHJNMzJQMFE5azQKLS0tIDZoRUFGa2h6RVA3U2w3WEFQeUov
        bnppR3lXNnhOM2I4bEs0a1V3M0YwOUEKlDiW7CIufgFTaHfIG8ueXTntBpGG2L5D
        al3AQV83Zd4v3ByJ3m6J2a0/+JU06K74xIum5nSr2zygAv8y0VzRdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T20:16:16Z"
  mac: ENC[AES256_GCM,data:TvBTSqLaYZdgOFGIIq3KU+S9zlnY2aygwbokj4/LV+S4MDhYcbRcXq1ysStSL/DfhNX4PPCGoCmKNOalaXlWA6xoF5Q0w+7dPus0MYhxzCWmcfo2E66UO8/0q9ZFs6Z8u2vAdtBKc3SCnLi+OE0SN5OM+bqpQLTW6cqXf0aVADs=,iv:FdyBqOCbPKu6EyDhwUosr1cfhIYqSRPHCksbX1SxiBE=,tag:ipu+GawX/2GMKM99LnHCQw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
