apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:GOQcT/54hpWdISY5e2YxHYO1TgKWElH6shTm6ZTv3czqmo+Iq+LjzsUhQVU5A1nPNZLOBnHptyLgsWMdcaCGSA==,iv:/R86KP3MXzpjKHYEHxhC7mcHRNO1jiSsw7YgCwAz0fA=,tag:RCZFw2CdCf8nlBNbu60m6A==,type:str]
  SALT: ENC[AES256_GCM,data:z5cvi2XGxUC80pJBAmPGSsiAJSj81rJ/llaZgmN1srGZyKepb+egpMv1e+yVzuxLq41c5pcppz/suMfb/E5h6w==,iv:gDfAdDbpSzZchbxF4f0jyi9xdLXalPwZjeVndCpWF+A=,tag:A+y42cmfrDOqMJ0tEUF/ag==,type:str]
  CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:zYnPP3B02jmqyr5/1VIV+K9r9bcgo0qArRZLrqLPDLw=,iv:fzOJYGCfgOka1PttJ4qPSlq/dr+UyqD1cC+1lt5InZQ=,tag:9Fr0WUuPz2kmCzOVeoRWQw==,type:str]
  LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:Tgy9kwwgODQGMrkdqC2SITV+,iv:42Y58Tlv9ByVlOvB6hs2tdgYws3gVdWH8+xRlTTGPkQ=,tag:LPa05mkAn+y5pl62YjsFEg==,type:str]
  LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:JCkRvDzLBoNwY2I1BD1jIfWd,iv:X0dIWAYmmnJqgkKEUCj7i1Tq3yXPyL07WSZfpDCWgYw=,tag:naWQe4q/E75tyPSu+rpeDQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:g2l2DiTolDdx6nSAeS4FWaCNbjTbo5JgiP5VhVYHvsYbqhb+Z4jL,iv:OvKMk17KCe/qIzXNhvuwUdd2cWAE2mr7jwJjQdI1fdQ=,tag:/e7W3g/SGO/J9nxzfKkj3w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:p4azwcybA+c=,iv:A/Oc/VVLA9xkupkuS49dj4wBY5drSWUfQcGbI3raKzk=,tag:2iZquguDx2Mj7pGpS0rY8Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:P4Dt/MWrXXQ=,iv:SvHtAZ7GfGTonTV85t0Cbal0GR3QkQ9G3Isyn46Kqes=,tag:dzb+3xH/pQghWOqwgpLhkw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:lFDRoq/Eqb0iIVSHtD2d8aOqfIrAWLfy1LZZQnpd4Ak=,iv:vEF+7RqIASyjWO6tylJ6FcP858WORU6SIjBCuIL/ltc=,tag:X27LZg4dgfFWzxzeuq1tZQ==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:PffgXj8CdGg=,iv:E7T66YlHi90TDPRLN0LFmfXKhY0WfgGNyvwA3IXwlF8=,tag:X9ufMrwNXa3zA7keNNelBQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:89RFy9SEIvAbAIWzB98=,iv:ccAXW5uhQBF38Pj2DlE3/l5ELa8pnbLtrcwZr5rJZ0k=,tag:JIiGagDCbrvw8pp7bUJf5Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:SbbQfV1SK9iCulX9lmp82DvoR0OzfDBJcNWlA2lmPwRY6SLPYB6op4gzrcyYTMhcBWDD3v09a8Ct9JImKzIu4Xoh7Gn9kCS4ChltDCFi35jZzZWEn+01fpx66FITHj9Zn7R/Fg5uyDaMix/Y,iv:qQtJjj6AqEKn/741VVbBr1DRC8SJf+8LR5zu03MeP4g=,tag:6SOqpd3THxRoUz5ZK/e9sA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:FQUix9lUdom+UkqAk1hIJABZTIaE/e7RvAta5w2Sfyizp9WoTp4FGbytl1l8Mr8jkyETNQP2J/qHmCPKd1mj4UPmlAjoGjoBrPq5tGSVG00veqPWSnHWM9if,iv:/TJusuRn3DjMW2ys+dr871w7IDeWx2sbSnT1c0a80tU=,tag:Z5SEQqM4t/wNkONapk8e2A==,type:str]
  AUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:gndy/QtTC0t+3HNxlzHCbW5wp7EY2xDPpT4Si0gVZoM=,iv:N1r5L4KwK78Lh2qCb7xjtwlK4Xv4d6qUrH1PfwNw8HQ=,tag:Pzn0KXTKgE/bTnAeBUdV6Q==,type:str]
  AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:eHgvNOyn45kcR7SFcyifPBPlshZaoKXnzxtyUmTTByCDHJJP,iv:fZcFDcUp5FGqyxC/GYqNTNY0wCw7NIQgqElCQQg5ARQ=,tag:zSzYFIDEm59elHChMix2fA==,type:str]
  LANGFUSE_INIT_USER_PASSWORD: ENC[AES256_GCM,data:n8JM4E+d2XiO+R+8A/PKYlktPcmnJw5wHlSoY8/9Y4FLvbgXucF7eQ==,iv:01AgZ9ac6v0WzGogvKBL9q72oholHRdPgAWVAwOqQEI=,tag:MTC9VROBupWv1c5FW4OxIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eEQrWTVWOUJ3Z0lJN01i
        OUlabno0SXEyMmYyYUpJU3lKVTQvVStpM1UwCmw5MksveWxnMy9ORC9XNjIzRUlI
        c1RtdURQdmxjMzJyS2VEdGdzaExlOW8KLS0tIFpFOXdhbHptUDUralZ0djlaS2Zh
        ZldaVWpKMFl0dnlQU3FycVZmNS9kSmcKkB5nKvTryFmpN49W5Oh/J9ceXVkNF0Zp
        X0B279XfCjW205jXeenPNFqF3iiscK9NZZem4Kcv0glR7nbB7GDrsA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T13:45:18Z"
  mac: ENC[AES256_GCM,data:tlgRuVwLsSEeVAvZnpcIPB76937GUs21BKtj0lvBxtKtd1flT8eGSJejScmbnoIQcR1bDIZVQtD/GiuvU7fF1G9SBUhgFdOu43lhWZJjjhktHUTkAK0Qrx3H3FB7WktJJ2zsripuJPe4qAlo28d2HMIV+FzkBB6DTNOT5Kc7ZGg=,iv:st+U+1qSpZ3ISHyC6K6jaJaRADQqEFXWTouUcx3MfUs=,tag:7geHTdt5932F4OtN/W+5Uw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
