apiVersion: v1
kind: Secret
metadata:
  name: k8s-operator-oauth-secret
stringData:
  username: ENC[AES256_GCM,data:JzyobOfWq2u4jX8P+H7R6kA=,iv:UBpDgBfzLbpObnJe9eGSacAUtj6KfYbN5lX8eO+BIWA=,tag:0izvsspHigK+82lgu9jy5A==,type:str]
  credential: ENC[AES256_GCM,data:hIuJ392EgcUQ+peKllky0MHaGJik+qfpVraointpb0AIbRstNbpam9TLXF9Gl48yd6So9X+ljXAIcFhmJuMBQg==,iv:yF/RRkV108/WbUxnIsJrRd5AVlznGCsItGYMiWyToe0=,tag:EJ+0vOjffz012mQi8l56fw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNUhOQjloZDVjY2dFelhp
        ZFBsbXFDbmlRbWtXcWx6YXhNNUxHbCtsQ25jCmFrcHNINEpzSEJiTG9nWXNKTEt1
        aW1VYTVVQmcyUkxtL1c1YjFoTk9oVkUKLS0tIFVJQ2xjN1JMM0JCa28xNXdES2Zs
        aEM0UkhBcWs5cHBtYUVGbTlXbXJlcTgKfVyo1289e7OnGBzmrtTF71gYbgN5qBUP
        RmQKCBApqZ1lOE6u8h3Dj4FhI34xfUJNKzwHgMBdk4+eQ9f3Qe9DuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:SIdNpp0Sai6hCJP58QyQoYCEr8hsHa6rMqSLV2dXpJ1JJqSI7r/IsWLfK2yFMyIXRajCyP6OZaDi/V52Sybvp+F27cO/kGKmKJQBN3gi5LdF8vb1DSLl0NlvaIgIcyHsbPEoP5UO/JxI3uovPRNEtxNs3TAGPEPgk+fdnhiYqmo=,iv:Qbx7FaQ4atbxIMIjBVeXiiEIwiC00q4AlXQgNugAEwE=,tag:G5DJQxlMV8cNg13VH3UZjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
