apiVersion: v1
kind: Secret
metadata:
  name: mcpjungle-secrets
stringData:
  #ENC[AES256_GCM,data:SJCMKP2mM08JhCmFRY5/JFL1X1fCn7mVeF2fRjuuo9TTv8bQ6O0=,iv:xxYwIM/T6iFRkuFvYw/IgjhUdMlqu6FG0/mX02Zclp4=,tag:ijyS8v6eKssc0AiToPVJ4g==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EiOtVTU6Wf0/dU+ymSbgzYE9qZKU2TrnHIf5CbX9B5xqeX+TBEHi,iv:8F+Kdu7tb/X0hP7GjCrQ3Y2Loe1cfF1hxF2SrUfrL6k=,tag:j+kwfaBUIUFV5U6B5+i6Dw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:kBPOEzyyX6lH,iv:7oWiF5J2qRfvE7cSb08hpwFGmqVS5ea6HSQF1Zq+5uY=,tag:jTd3glniTtXi10sBqy6xRg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:2uJPsPWgJsUc,iv:cBZJO10kMSQ/rCrGGgMAIu4JT7X5N+vd2j0wGLtUahg=,tag:tSyLT2KfoB3Yy7Zgu2qM/w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ySdgw6sdpwVWARldKS8BO9xIxFHyJbnxQAcBZ5ndu8MZURUwlMxRF4tYisXq7g8cEWN2CUpuFYlW7z4ulvGBQg==,iv:ySW8EMDIcg1lNwhIKE8ADi26zHzVzcduCbxs8khdwYU=,tag:VpjJDl3nz6qvSNRV0Cgl8w==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:vaOP3QqV1YQ=,iv:qfZWdGFHjmkjDpGealutAMUQLfQcBU7Ba9J6QfE1zu8=,tag:bIPjQDni8oCqKs8zkkYUKA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:+9pSTIkE+7q1jP42r0w=,iv:QFkj2G8sA9N93y2jVItKt725meXsWmUiDCSkQXvLYxE=,tag:p92DDkgeRkd0m1l6DyPcNw==,type:str]
  #ENC[AES256_GCM,data:llf6M+MntIGuFLEVW0PDWNIDH6QcBa5aAQU1,iv:wXo1LQUoY0StKnAV4bGdnDFqMoDYBj13106NXsTYF4w=,tag:CkAh821wKcaUHrTyt/VVrw==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:yts5GraW40hLYU8I9dZT/DuGVt1d+2f05NeRyyhXa72WC9+uS47lnyopamUnU17q/EIObiIcJh+ILBKfOkRRv4FmlgkI+ZfxCljbc/Hg4n/qeBCVwI74dFD0/xnzI2udyF2FF5MxksbmYzqalZTPFm8522YlYbVkP9Lf2qEfRjKnVNdIbuklMYcGTA0=,iv:VY6hPKoAiEAtHl8iEDKiGt+YZC7lAl1cA0V1JLif0CA=,tag:mEvLMPJxSQrME1ZkJLIpqQ==,type:str]
  #ENC[AES256_GCM,data:G2tuDU57tR0wmKgXdJ1uAKAfht+1zIZquOWx8ZegLbLBdgtwuobhuH3kc5RqD/77AgtE/+hctlw=,iv:VQnW7z079ZAQMIQ55xkhkfvQeaBaSD4jNWjEga5cRIM=,tag:NfEzlujD7+kpuryqSznWNA==,type:comment]
  MCPJUNGLE_ADMIN_EMAIL: ENC[AES256_GCM,data:IAYyy6uxoJpvYvYdvE7O5AM=,iv:P1V+KRr86YMQ6tbipyWYouJUCD1uRGaFJAyRklYxSBQ=,tag:5Gw18/060BQxAmWFChNqeA==,type:str]
  MCPJUNGLE_ADMIN_PASSWORD: ENC[AES256_GCM,data:JhCjUHbz+64r,iv:2FR+Sh658u0J6vNO8j7NwZMun6eJXGMucIO6Xh8JlRY=,tag:Jub4C1eMxTWryrJ+IYs//w==,type:str]
  #ENC[AES256_GCM,data:46tLRH2A2Cwn99WX7Yl29hG4E8guFWVm6DHHNM9ZNQ==,iv:53SrW2KPQsGwvXqKRzWvWufahwBwMbysATj29XKO6vM=,tag:BwVvpZaFxPASFy1CZWMwag==,type:comment]
  MCPJUNGLE_API_KEY: ENC[AES256_GCM,data:K7rOIQP9ZmaOS6bXQR7kWdCVoBANLiU5CGqS8SZRokbGbmiRmRhwB4KyCbSvUa7sxa18RjqD4heOAW5/Rmq1YA==,iv:SWq+0SdelHoJhnQEddgdRyVAslYtfjZtdE2WQkwwu3I=,tag:85QjmwNmNvCE0s0mUv+0dQ==,type:str]
  #ENC[AES256_GCM,data:Ssgm6TKS1NRVb9c+IAP2a3avBD7YtaF9aT1Vtr9wMVr+Lug8Sw8Q6rpxaKIWQ3hBrkaeDmLGOA==,iv:ir7eX3xc9avIJCj6zJGLgHK2r14XIdI4QDc/RtsCnLM=,tag:BJYBuKYsKa9cQzgOivCUcg==,type:comment]
  EXA_API_KEY: ENC[AES256_GCM,data:abDABriE6G9JiK9B+9vkHx6j7RJHptxisnxZ330dpcbTVm1V,iv:ck4c8YQSCeVcnpeENzMdcVZJt0+G7Bd20LkhG8XqA4U=,tag:scxy7utHw9lBg2V1D33WkQ==,type:str]
  CONTEXT7_API_KEY: ENC[AES256_GCM,data:gkA9bhSnOqnADaraIvwtilTjf2gRIXM4QoCfBCHCV7dcHt7IN6wmCQevFg==,iv:CvWf3ilWd9ysBk6JOzkHB9QI331GGLV/TPR+w5NgSaY=,tag:jTb5/HrkLw7pMWDAk84XXg==,type:str]
  #ENC[AES256_GCM,data:e8gWSbVzr6Cekz4f8Op6Y8k/qPZwU2yG7ndXFCqMpWoyHRlJAOh6,iv:UuuoZXYIE8lAjHEll8d9FRmDJo40H529nV209RZJNj0=,tag:v9J3SQSkR5LNs7Vq2NpUnw==,type:comment]
  GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:DDfL571Xg8nwcaghBfgQzbtg7HH1l4ySGKNclP5fXgV9NfV9tNZL+TkZX2nXQu81oSqa8JM91hT1T4YcQrQHARb4bLOoA70hI78E8yKZJMX7eMbYNdUXZxjhco0M,iv:DBAEE/ISmOJX5pKub9doyVbdJbAjYjVomGxOV7OvG60=,tag:kbxtp4FU2o6LkzIy78XU2w==,type:str]
  #ENC[AES256_GCM,data:fKglUYfu+NrtEgxnEf1T5kCmgZVgi/oXoWCtgPSEd6nI57uCklIMFNJs4Qgf1ZuSQyo=,iv:oaz2+MqPM95rKbeUJFkyNiCw17xtf+/1zOsvnDEuJF0=,tag:qpDJbw5CqbQwCu02/laXcg==,type:comment]
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:ScqN30YX3Q6XbFmT3TQnAGmg7d6ripxeCPLuKpUcPbqokjtjcG+RFmI9HRwPgcZIX2QjI8k=,iv:5XvPv2wb5onMwROhfWrMWWS2GBlb2trBdpNGVQf8Gqw=,tag:RTHQ6wbxUN1MCLGb/Iw7Ww==,type:str]
  PERPLEXITY_API_KEY: ENC[AES256_GCM,data:ZkNBfXdLK3PxZVgxeRoaw44BAzDsXeWaTeAsiGKe59LxCPp5edi9v9lh03EE8e8RecpEtMM=,iv:Ifoe1L13oTQV7ik67o0wnimAvXLqT+cwstOhwhG/cZA=,tag:zYistZ95EVKcziK2pP/dXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa2FTNkZGNDdoNHdmaVlN
        eFczSkdWSnc1c25jOCtsRHBwTmhCZmhJZUVrClhvb3A5SVJmQkVsTDFJWTlVMHpj
        RVQ5N2pPNXZISVNpMnZkMkE5UTlqOEkKLS0tIGluRCtHUUVRT25ld2FYSmJYNFVk
        QTFkZGNYOXpYcHNqRFhIOWFyUlBmK1UK/AkFLl1Zj2SmzvMKwxCEydhkQ+UunFNe
        2WSqL03n9Nkw85cjy//bdKfgBnllWchDL5VAo+nBLhUtRi3DsPvemQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-08T19:13:36Z"
  mac: ENC[AES256_GCM,data:kPbwfu17eofdcOeEhwIcJXcRrMg16hmKusD5MsHiD7MiPx1JGheXMTzvu1MX9COgWjCiybDBYryOewI723qHLjcv7pRMoAVA+N9rigpKTtyCqEYuJOcTKPs/3NpXlMvzaYYE6RvIVN1M2t6qua9tn8TxqTBp0uo40lnunaOEsK0=,iv:2fK396px3yLB4pV8PNTH9OhxMxsvPNuYN1gn93druO4=,tag:RzgcOKEr7nVlJnF/mPlo5Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
