---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./amd-device-metrics-exporter.yaml
  - ./amd-gpu.yaml

  - ./cloudnative-pg.yaml
  - ./cloudflare.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./k8tz.yaml
  - ./nfs-external-provisioner.yaml
  - ./netdata.yaml
  - ./traefik.yaml
