---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./certificate.yaml
  # renovate: datasource=github-releases depName=traefik/traefik
  - https://raw.githubusercontent.com/traefik/traefik/v3.7.3/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml
  - ./middleware/
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./grafanadashboard.yaml
