apiVersion: v1
kind: Secret
metadata:
  name: agent-canvas-secrets
stringData:
  #ENC[AES256_GCM,data:AU+1wUc124zfS4D6y52kWRakPvnwvo7AaQRaD3LM8vgi5DMZh7/wHjvlupiUI6dg5RI+Qm1dA4ZRtGiieW+LShkIYw==,iv:0UgvPc1xwSnB1EGWK/nQDrH2XoqSxu8j4u6A6TXWVmc=,tag:ZBqro3Wbml2xMe8bORfvNA==,type:comment]
  #ENC[AES256_GCM,data:i02hXknHnLC81TJDGxkLAVgfyhqKQ8J+9jwy5r66AWy/kbDd0bVyNGNSMATNBRXyASrsZcMDq7LL/6zNjK6g,iv:9UBYbiqCxO0/ehsCV+loat/T/8bf8MdIRNT7gIbf2fo=,tag:ucCr+ZN0XxrZfAT++pt7sQ==,type:comment]
  #ENC[AES256_GCM,data:2x1lWSmXulHXmM333TtFtm4Z2aIBjPfRM1eruyRPE1Bp7D5kbannuIoylxwalPhDTT3s1Mog67GQ,iv:uOahPRqmtiBOlX2HGfEka1LfRddxdDxBHTepeT7pArM=,tag:NSYT3WT24qYq/dFy/DnCyQ==,type:comment]
  llm-api-key: ENC[AES256_GCM,data:cmqDHqToxBoJyHQJ1Ms5PzCxzCvaEOj3OX1NRynRSlStCbg=,iv:+YVIi2EhGvjKLwRJvHmyEQY5xIR/lj8BZxs19a6I5HQ=,tag:2Z7XskSL8NVaXLjYBiWU7w==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUGdBNzZONW9QbXVkVTRu
        aVZHWDhXYW9sekM1aGRtR2lFWjMycXU3MzBJCmlXNnA2UFVkdGpaMHFZUWRPT1cx
        bXMzT2g1ektnS2VPVG1tSTJHMnp5cmMKLS0tIGE4YnVORllyREcrb1FYQ1VaNmFQ
        TSsvbEJaN2dmb1J2T28xc1lyN3NmTW8KQvshbBinqZf9h/TJk6Tbzj26/wORWD5q
        OLA5zuTy0pX4sHsKIkPiQkwi8CrkldV3x2SQtNYUYo1796xfxLIsJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T14:41:54Z"
  mac: ENC[AES256_GCM,data:gpE1gm9nikSFCITILGjwX6nxq65Nf+YGbGoTgV1DpbOQ4aYqWrHhgyX4Wo4I3eYwajnuIx9uiQmk2Xtac6moDcFwRTwr5yRhAbdPrZ7S82ge4/8NYfmKQCTERp0nYizemOew5g001k2EBdlKjGAWursnU81E/lT2xR73Cq9rDCc=,iv:DR0Zh8l+M+q68LKqdOkVQe4sJuMHF2Y7K3NQYGwIz1w=,tag:lIlzpK4vhyYqq3VPCjVnbA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
