---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app proton-bridge
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      proton-bridge:
        containers:
          app:
            image:
              repository: shenxn/protonmail-bridge
              tag: 3.19.0-build
            env:
              TZ: America/New_York
            args: ['init']
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          smtp:
            primary: true
            port: 25
          imap:
            primary: false
            port: 143
          # metrics:
          #   port: *metricsPort
    # serviceMonitor:
    #   app:
    #     serviceName: *app
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s
    persistence:
      root:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteOnce
      localtime:
        enabled: true
        type: hostPath
        hostPath: /etc/localtime
