---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app proton-bridge
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      proton-bridge:
        replicas: 1
        containers:
          app:
            command: ['/bin/bash', '-c', 'sleep 1h']
            image:
              repository: ghcr.io/j0sh3rs/protonmail-bridge-docker
              tag: 3.21.1
            env:
              TZ: America/New_York
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsNonRoot: false
    service:
      app:
        controller: *app
        ports:
          smtp:
            primary: true
            port: 25
            targetPort: 1025
          imap:
            primary: false
            port: 143
            targetPort: 1143
    persistence:
      root:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteMany
        globalMounts:
          - path: /root
      localtime:
        enabled: true
        type: hostPath
        hostPath: /etc/localtime
