apiVersion: v1
kind: Secret
metadata:
  name: longhorn-secrets
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A5sAaxwAN2E=,iv:7CkwiHDnj908x+ZvDUIw/QJXS54kupC3Q8c9IEoLzGE=,tag:b/PbyeFk49qv6jHZq4zquw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:z3VONroS2HyLZU0=,iv:bhuJJfxs2Eso4/rcxVc2s37j4VsZviTEuSirbj8QFDI=,tag:YWBa+3uFtZbRlIsg7WLtOQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:1wRTARK3zq/H9uSeicE/qkvx,iv:dxDyerT4vN5DU1NUyOwxXbRsUNMd75uybq3vP0FY9i8=,tag:zlWakdXGzDyaPLPFdbsj0g==,type:str]
  LONGHORN_INGRESS_HOST: ENC[AES256_GCM,data:dp4ZdG12Bo7+uOZztcMWgA==,iv:qxOit1n+ht3xfFeX+tG271rCwVmua8Utw8kw9Ef7cnY=,tag:xW42iE9kOncudnIrleCBTA==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dGVGZDBISTB2QzRyT05E
        V3dmcEFQZUZQZG5PdEtLQmRlVEtmQS9FQm53CmpkMlR0TlBzRFFCYmErTFp3YmV4
        ek85RGc0aXlvVDB6eUVoS09lb0FzL1EKLS0tIDN0cXprbHYxdUlKOXBkbVNZYUNy
        ZWVqRGtrQzdjSFNDRDRzblZYa2QyTlEKJzyAndgfmPutgavpwzhKQHr9cIHdV++Z
        GSIoPurdM4eVpofkUpR4Cs1VZRZ14ftJEG1jWo/ISGqjHT+3g+Mx1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:5JgU8J85DbThuuvRiemZw/aw6nvtQtWmOJ5weP5GbgUu8HTFavJcyalsLQFAP+xykB5nMvWLa5ANsMzHEtP5LoF8270mD2Mx4tym2iYk6W17n1ZeFDFpe9accLplDElGuTgmFkEKbfuDcIpRpydH8DzznPzz0g1srxn/lgfmQHQ=,iv:nWBN9L9xWiU1Axe8maodSnLvywxoWhXrmG4JBAKF8zM=,tag:XRKRvaUxmkeMg7BkDT5ATw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
