apiVersion: v1
kind: Secret
metadata:
  name: goose-runner-secrets
  namespace: ai
stringData:
  #ENC[AES256_GCM,data:pcJoGWw58uLGPq0aA1n4PSlbvI/fIel6up01GzD6mRF1EGHNr0RzSerwygiIX7s4NyKYuPtV3TzaXQtwkRlLNzXUUvE=,iv:c24iYgbI05pXBmXYcIHDvS7OhtXQa/bdqfVp3iUCoZE=,tag:CF3w5kWF4iUOjewUWSULsg==,type:comment]
  #ENC[AES256_GCM,data:yZtZyZwiRMbMMgGhkB/tY1iT8ZPIuM58hZqp0vxmku9GwBuCjK7xGmIyLXAFMcIW1dghiWFz+53JJ5E=,iv:qBOEZxsQpAHALv7HlSB0Qc2NrqNIWJM2u0MoVmoz4Mw=,tag:zFVaW1dXzVClc4n2N8GQrQ==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:f29dWtcLEEdzmve8lT8af2FxEtOWGWiRU9smC2oAMUk8iZzfkqfdIOaagUIWp5QarcdrcOL2GfbFFMWgm3BAc632sw==,iv:U+vZmIp46azINkIdFLWMTb28kRp4Kh2GExXzKacQd38=,tag:qVTa3/un9jVzeKdc0QjnOA==,type:str]
  #ENC[AES256_GCM,data:TK5k3PYmSZ24foFmIgzawZsEpGQaiSyMIJPfSkTOxOXFrjSJ8DZcqDQSQYGBj0zWmFOdhtSVgF39o00ndEuO3tYY2UPhvd6wZw==,iv:bSJ3ig46YJ4BOQl7+F3qD/uBeNpTi0LCKbXr1mI4QBA=,tag:C8SP8JRlommtN8CzxTYM/Q==,type:comment]
  GITHUB_TOKEN: ENC[AES256_GCM,data:MhLk+7GQIbsuCfzwMv8Ak6n53B7I9xJKFvJJsdWgsrPbZDdWCd3NlQD3gvk29ey752j6uguqXQ4r52w3Nn+oRKvf9OOxyP9mCf871qao7RFCNxvWhAUhJpvUgeB4,iv:X92WCLMnP+7Od+ikUxmb+l16YfZtPGkFsryFu4sI8Bc=,tag:9Oglsms7WpIXqwTzZKQ89Q==,type:str]
  #ENC[AES256_GCM,data:0lbqPnyl1qSax7susbCLF6qN7JL2BHueSauaIsTGS+oPjNQ4uRNnhyjBfrcSVnIXlJUBUoIAEh9X7Ht6XtH7W54U3A==,iv:6uxTbgjILdpDoAE1179hxtfcc3xZQ4tpWNBfqfY2aUU=,tag:zg2Zmf1Tpib80mXL0jLJMQ==,type:comment]
  LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:XyHnrvjv+nFpiLpEXIqC1+cS75vFyMqItu64V7FPqCMavnj3o+WN/VPM,iv:Zyt9DTEpMAgMR2B4HfsjvTOnYrNF8Sk0Fo+Vra8lq68=,tag:NnO39+8fNwhq5/raL4j81Q==,type:str]
  LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:kq/+13POg67GJzrXGYlMtiA3JJgJgH8Ah0eKu3q1VrXGgsKNl8j0/pDb,iv:BxpVdKkLmucHpMlC3UODjmBHrNrs3wl/0F/FEhGD+wg=,tag:9cSdBS0kCUbmj4xbfrcxcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZk40OXhjNWY4bHZ1VG5X
        TnNhZ2swMElaM2hJOGNNcjl0SXh5RTlDeERNCmg3YW1LdlRsdVVhTWsrQ3ZaVGRj
        UGFrWmR1MlU1dkU4UWJKK0hZQ0dUcDgKLS0tIEYvUjlpYjF4NHhlSlpSUlBBdE51
        S3dCVVBSTTBid1hjQWVCa0I4U2xsZkUKAi0A6zOqKwT9Es+cIriLPwPGQCIjczLB
        oLBmDcbLKpjhRc8xP7vt2kJOfl8TbcSUnE99KHvKG6gqGH45YEx8Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T15:28:53Z"
  mac: ENC[AES256_GCM,data:oljZiNCRS6MeTSeajRLMkQ2AvLb0uzD/htMLUtEbps5acew54fCyRou6TsaosQyssErC/lMuL3bsu4PlPVn8ERgZjjSWgcWuGNV0758gIZfKbVXszmmc9r1gcSbGlj069BPjUUoGiqJfah8pEdO17HT0vjZvEjGaQRRXVjW4NFE=,iv:ZzLyolRDq164YmXML1UCk7lj+6sx/J1LSY18zPgfPq8=,tag:79swwS6sBRp2+ruYGHZhfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
