apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  chart:
    spec:
      chart: amd-gpu
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: kube-system
  interval: 10m0s
  values:
    nfd:
      enabled: true
    labeller:
      enabled: true
