apiVersion: v1
kind: Secret
metadata:
  name: longhorn-secrets
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ORO9c8qCMDc=,iv:Sb0S3k/pTVmsIZfOz/ma8fX89HWa6+Ljg4ISZPzCri0=,tag:Yc0gs+ZC6flL8FqreWwAOA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:elAaYBA6kcigc4Y=,iv:NFX/+tJraDihH+eg0RNFLuAyGQU5/aNzrX8UGscAUwo=,tag:UaVlj+JOJuayvOPinyu1iA==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:tlt8dLK+PKTvh8x3y/aXbuup,iv:OoLryJlSt5d3zPteH/LY9/v1tLul2aB+wG1PE279GWo=,tag:UramJz9FvtMjWbOn3gYpgg==,type:str]
  LONGHORN_INGRESS_HOST: ENC[AES256_GCM,data:p2EywjkUVK3LuxJbVMUfGA==,iv:3owWkwB3BNsTk/hLpLIM0M+FkX9t/U3kYPb40ipoQ/w=,tag:3jOPdaoEKzE4yU41v8LtDw==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV243SmZDVnoxQWVVdXdt
        NzBNRnNHbS8weW1VZzBLTGNzcVMzeVdOODNrCmluc001UHRzdFkwdEhNb25xTHZz
        RGpyKzVZRjJDMXByb09BanR1UkY0SWcKLS0tIFFiakF6TmdjdGFNZkVUNDJqb2xk
        UEIrZDFHT3lsNmlDUTFzTGhINlBHTEUKvu2EWSz1C2Vk7CDQJzc/HIxtSeOnyZfA
        YwBC0Yeor3Bb6fQ/lSIib7MgCkagJVJXQwouu0GxxyS1aeDuNNqF2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:ej7E+3CEZ5RvRlkVfiX2KcowBO1aOoPjWT8NgOm7M7x3WbHtzb3TiihEgnxqGuSNm9BR1S491uMzfb78yYohJoBiYV5g8dBBuayeT6qWCuZWSoz9IVI7uN+IYwELKcjWskhItAp0kkxwuq3uzXIyRdBvrqRDrHiFBLt1MaeU25Y=,iv:CIKMnAnq552yUh2dbAQXntGoNIZxdejq8VO8tFWAN4Y=,tag:Yib6GC4ksV6OASxQTeUHow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
