# IMPORTANT: This file contains plaintext secrets.
# Before committing, encrypt with: task sops:encrypt-file file=kubernetes/apps/services/open-webui/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
stringData:
  #ENC[AES256_GCM,data:Ugxk9Og0cRbf4o0rycMkAZOmibKZl4EEdodYS828RLOCKduX,iv:tXFK6VB82HHDxpYhgTrnAskWF1DXHyqlU3dXgjHwpSk=,tag:Nuptkm/5tGWfKz/8YxcStw==,type:comment]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:63K+bN7n0SXIWVvlkesMQI/WObpOzIxfrWlJe3Mau0nhbfpqP+Fe1AywbGLZHd/5k5npq552JIgWYEoOEE3bow==,iv:CVYFz70Dv81KcmKPA2wE5qu8Qzb8BMtgLB6WOtQzqUc=,tag:07rg5nKbcCOaDkefhfho6w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZmZFTTlCbnY0aS92SUlP
        TTFuZnhmdjBKdGYrMVZ6MkxQemxrSGFTQkJnCkJtck41am9OQVR1RVY3QXgzdWpW
        VnBCL3lYa1BMS1NzcXVZTU1Td1NOWFUKLS0tIExveVkrcTdXOXV1TFA5QnNOR29u
        eE9oQkJUM0VKNmZITUxMaHVkRFFmTU0KfOu1ldst8hUdruxNLgH0jd5MYN+2AX/w
        aKuSsSv1o0+8ld/0dt1NyU/hgEFf8nsZmdYZZCdaoeOYrHeWVhQTYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:45:38Z"
  mac: ENC[AES256_GCM,data:00QjgriRAlg1dxO8uQ43mU/+/8G/csyr2grWtozuqDRx399EtNF6j0npTYCkZA3MziCz7du6KAIZJNHOVMK/tPJWtVcJqa6mUfFwZSIJ+PScCw0+NAJ7dwl6dWfBgjlAEwvKs3i39uFhCJpY1KfPmeqMmMPCDV5Kje+mJvJcvLk=,iv:DY/9yQxRf7qjMonLWtZ6hgqnrVsYBEHtYC7vGLRr044=,tag:BM3vGt2EpHLPmI6TujTkqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
