# IMPORTANT: This file contains plaintext secrets.
# Before committing, encrypt with: task sops:encrypt-file file=kubernetes/apps/services/open-webui/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
stringData:
  #ENC[AES256_GCM,data:MfyrhEwhA7Agxt0UGJt0rmZEzDVyRmpuZmHPszHc6VyPUplp,iv:2/gvoMi9roAKOzkG5eeG9HigJy8GRZb5gzUYmTPrdD4=,tag:vDEpWQOB1uxWTsmT4Q900g==,type:comment]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:pQL6bfQD0uqwXcdJiCcSHAuHqqD8gnQRM8Digrfe9eDfnSgi6tUCrricsQZFkVqGKutp7WekaX+/oqXMhC3tmQ==,iv:s10jd1Mxg4i8W5QoWPY9AzpkT/PjE6rJ2CK0ehOeEyA=,tag:XSuzHuZupaJllMiJaMdM7w==,type:str]
sops:
  age:
    - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcEpFU3NLUGRnbS9sZW9R
        NzdZMWRVUWY2ZHV2dDN3cVVsV3NIUE01ZkM4ClhrVFVzc0d3cCtBc093c2dSODFF
        V2lYak9SMW1yYlJZOGZMZldjUTdFT3cKLS0tIGp6R2RlTmFlazBQQ1UrUVR6T3pD
        bFFvaDQ2VDNvNGsrMFF4S2J1enV3cFEKZD6hni2oYLUTkmfpGgimLprGHm2V/TrL
        jfLZJnM8KZdWFazJQIFXozU1IHs1xA0ccn/rWUc1dsSrrCOVMJYdZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T00:11:52Z"
  mac: ENC[AES256_GCM,data:SdKplBrtPegRkqY3iBR+hQRU+0NUrXSoiIXwg8EAkSZaapRSgjuulwTzdEHoVnazQuhC6beN2XMReLNPapd8HL9sEwf6/LCKy/oKLpDax8Ip78mXcvmqAeVcGUoK1qHw3azvJ0uaUkcgNzP2aig+5nY2pwh89PDJj1Rb5fWKcRE=,iv:y2k/tugZSq5J7vl8iQV9UqZF9uzoU6KWz1HWXwtcxrE=,tag:O9Q95mxA/UF0eGKFjrmx+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
