apiVersion: v1
kind: Secret
metadata:
  name: cognee-secrets
stringData:
  #ENC[AES256_GCM,data:I0yqec6AW3Fv1FIP+cY2BoZU0PQ+8bK7CLRv421/3AFzYRgfbs8=,iv:KH7USgffHN9KOhBDm7ye1Z+u7vB0h34dbPh1Vstp5Xs=,tag:ZGAoCsMgdBbe69Vc/z5MZA==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SyGGHYnuROvhOAFfqjW2d2CmJF7ACyvUI9fFz2rDkXga5RVBzX8D,iv:EEZzDMRTlULKkVKuJuW6jW6MLMhYhKtNhsgRA39/Zr4=,tag:qQBBLX5wkbzI7VVgpqSMKg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YZrYZCZe,iv:2eobxsut+yl9hjwGWgDtFKx6bEINFQLZEs9iZXwN7SU=,tag:rBfj/KReOUSxzWIqpbugkQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:xnMv32dJ,iv:CQwGDA2HDCZH1YaUr+WvCbrir/pBLbhZoMcy3M4WmOU=,tag:Ha+G50OJqgApHZLqtz/gZA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sB95AnlmxKQ74ywFz2uhqjOvW4HcioT2P6JkH48kGwUzzqBjO7guaq6YrbJnnjfzTwA2c/Mp/Cd62J1rC8Rdhg==,iv:DZozN3AlLmFCMZI6hQIXIfPHQ7mh0oZ6SNf/pW+YKww=,tag:kV6Zjs7eWcmC+BHaR9ScIg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:7yK8xERDu80=,iv:s+ETyp3AQcImbb2cK0e4jHJowUE3ZvnbCXl2rn6Dyvo=,tag:nGTVFI9GdRinkH9yYHyXGw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:axnYC47mvLXU/Rr2l0E=,iv:BAWFnwwSRi+6LJ62sggJAP0BHQGjXasb0VQogs0XEks=,tag:hYm3It3gxLDPpO6x675S4Q==,type:str]
  #ENC[AES256_GCM,data:ITdg8meA9rhcIfJzyEkr1k6ZrhnPbTlxUhduQJYhQx8zXm9h,iv:L+O6xMgg/45oXV44C8l6uJc+x7ckNhBMBxqiDI5gTkA=,tag:kI9HAoU0v29tkp74pMZlvA==,type:comment]
  DB_USERNAME: ENC[AES256_GCM,data:Y0Chfq6s,iv:CsyfAcV1LFjBhhz4rmvnYZ1SMPhZCvchw9uq74GIvwI=,tag:Gsb6rj1R6WVao/csbnPJTg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:iH6+1w/zhPcsVFFEa23TrqYbPyy/pnCwVMDUUUqtnWELEXY5t/qNjmADNdn2v8mhE0zXttr1xHqGNSBpu7WgDA==,iv:zr+6XHRT0VVJKE4tP7JidrpOInGdNs2sJGvSR4etSKE=,tag:eQ+tmgbHCKeJWALRwIbw9g==,type:str]
  #ENC[AES256_GCM,data:YaS5YAqBcmcu1DUy9p2/Z8AIK+HOY2JT9wW3ddT2HHivkIAhPT9q23+KKTtRPpjsQvsuV2yNsePfC7bxGLR1,iv:nxVUcriblchG8eiucRc+0XpLAB9oJM0KOz8Z5VyEvZI=,tag:tlZWiyUux9wrb2INTDngHw==,type:comment]
  #ENC[AES256_GCM,data:l8JcH8hR6ngXK6Fn/8ileirC0ToTsobkz0Hpu/ErnPIZLpuHTj2Z24BhUNcUTDpwg31bZrDFhIsokc8IIIrXCGXnog==,iv:8on2V28P6G635TOiBHrI2Q0P4ZpOE/113hmRu+Wmv/4=,tag:ud9IbFJJqe2P4Jp8bjMfqw==,type:comment]
  LLM_API_KEY: ENC[AES256_GCM,data:rRv54ZoIX8pzLLsvJkgz9HV8l3EM8prwEQ==,iv:1exnoRMgDpG8QUqF81I1yl6YKy+HU7ZdPeDjUZyT0hA=,tag:btc1D6HTPxGsQa0KDec0Yw==,type:str]
  EMBEDDING_API_KEY: ENC[AES256_GCM,data:sJ++VnacBWT+UFso3PjVeBwu9/7O5r3IBg==,iv:ds0FTrdBd3cY2WiRIZ7u97wECQhe9J+LWRthB3nmLo4=,tag:BOqkxD7kGfeLbwAvRU89Dw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd3AyaHgrWmpjNnFxeHl0
        RlA2Sk15OWRIRC9LOFMvcEZrT3drM0lsckJFCkYrMXFlWXVteHdkMEY1SEpaWVVv
        QWtPanphUy9jd1Z4clovR09NWHkvNm8KLS0tIERLSEhXNEdUdS9EMDlqOFRKNHp2
        NFFKVTZTdzg5by84QXdaT0ZyQTRHRDQKsxCDTeKU850Pe3Vt3zub2CEai8+AHoFZ
        PR6yjvyp2XXtNpW//prxxRpf/5QKR4lc7zH1oHRatGs5A1gqyIy+fA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T21:54:30Z"
  mac: ENC[AES256_GCM,data:Dg6IfWJXOIslih8LaJbJQxvwO/Bu0TuF/y9FJgm0C84cM496kHSNFs6pV4kJN0jLsvNgYUFsCcufyUOuez8BC+bm394qQgM+vDkHFcAHtJ6CKOZ6C7HFROXegTL9MM0y5Qvqu2aEO4kLON4SEBFF+2ZmyzE6VVwAodN8S3gJlkY=,iv:vv5R2usEXI5BIBlaZxXJ5dStTJScpZWR4jlGuUtspH0=,tag:SpBP66zr0le+Y7RuimP2aw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
