apiVersion: v1
kind: Secret
metadata:
  name: qdrant-auth
  namespace: databases
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:6/LYyIx4l5qTjpSyetYeXZgbjbU4elwlrWH8/Uzr5ik/c27diMLsaBUKxFw=,iv:ML08GkyNtFBSCEc9Y9+uybfyJkTkIGAnMnsSDcb8G40=,tag:p2J+GqZ6ug/iirTa9a3xYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUnRreDFyZndsWkFCNjBS
        amVLK28wQytwT0EvWFJsVHNUK1h5VVYyendFCmlZbUhOeUljZ1pta1FMTjloaHJG
        cHZia0pYZHhnY2tuUERRbUNTMFJlM1kKLS0tIGJpSWtSSnFrL1dpeURkbUNobGdu
        YmNiSEhySEx6MzZvODY2NmZTSWVJMHcK5GVrG++9/L0VVj5ri7/7RlEDPIkg8y9r
        YboAflkXqj2l2dPIxGrvS89SUWzSuyIrS34REjq50g0EeQwJ7/vrTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T15:53:29Z"
  mac: ENC[AES256_GCM,data:c07hIKFG+ZXm67XJvMA3YR9hKZx9bsHUFyJiaQCTRMTHLfp5vf93+4H0dhLYcKUF8urdEN+CtM5AOqoVIuSuykJtPhXGiMBNf0IeNz6fb6S2SIBg8SnvY+s0LACB3uuyTybp8My8V1uS2kk3pHhPn3Yet71r+03cxFeNI6NJBVw=,iv:XMRy9NpgbF6gLBwp7NhJ1AZAQpOhLNHyT+LHgTsAr14=,tag:l7I0N/F9hZqNxsOEqkk6wQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
