apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  CLICKHOUSE_USER: ENC[AES256_GCM,data:RA+h0G/DNNg=,iv:yWpUEb9bvbccLvclpRX6IXRFCYXfNF9DWB3u0XgxX3o=,tag:55RanXLZw0K3qRNNI2e4xA==,type:str]
  CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:8QEcTrQwfxftz2rV5Prm7cHIKe2CaZYIbvicehVFA+A=,iv:njRQZACslp7swB4+XpHPtANwSnkQBalEzOMwTgOQtJs=,tag:eciDPGsT0JBEUVLYLqHXfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWTNoc0VDQ05BRG5vKzVw
        QW1uOG5xTUdGSXhDU0JEK2JnakNjejhGaEFFClNhMm9KYXVVaEZUZHJTNHJFTUtz
        K1V5VHkrTUxvblMvU3RKc3ViZ0ZQK2sKLS0tIGVmRWtrZDlMb0dPOTk4ZS83UHRP
        Z3NVTmtnS3NvbE12cnUxa0lickY3TjQKXAGOrWaZnN0DFAqfGeYmlguVI39IpCZG
        RLul76cZwTJ0BYUhpHdDXII5T5oGafVUTHtcK5gAEFt6z/14Vtbs3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T22:13:35Z"
  mac: ENC[AES256_GCM,data:yYbVoK2bcpRFbihhoFQRaCrmM/iXWHc4/oo2qo2n/RRf2Yl6QmoOjDY8HKGIthhaItYJStz+DNwjIQLJ+5H/6+1NDdT0RPat88SbHDbKorDOelwJTc0fuYG8BNwvnjDP0S0NKzAqxErxq3veJL+PcsdpjrzVW2Z7lwA1VVW9ulc=,iv:aTYFj8eU6COgDDK+Ezd+2RpKPA+aKh1A6Vs4aExvh5c=,tag:A45m11kw2tAwuaaJASJwUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
