apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  CLICKHOUSE_ADMIN_PASSWORD: ENC[AES256_GCM,data:KUxydTuowD07Hkylan5ktlYhVGntRVeJpzWoKMUfn6s=,iv:0XGMJUBimVqXgcpAIYlrAG5mJZrFy3tUiEVcp0Dm0tQ=,tag:FKBaqrWqvAmhzGljiyMplA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZWQ4RHA2R0lvUUh1RFNy
        NGxWd0JNcm00ci9QSFVlT2RReWpTN0s3VXk0CjdDRCs4bWx1aWdiNTNVYWprMUJt
        cytmZDVZNW5hWDlPMFZRdHpwNTMvNUkKLS0tIER0YS8zQ0p4eVpmcVNTeXkwdWI0
        Rm12SGNXSHZzSmdzSzk4VFNBemRVVTAK1vyq/iNz/gpM3rgTDG4u1/Pyv6ZUt230
        ApnSmvLHNjv5M863uCh6o0kOPPZ6a0U4ME6onEULr8bK9IB3d0h4kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T20:32:15Z"
  mac: ENC[AES256_GCM,data:iq++HcizARXxye0J2Myz9npAmlbjiYskpVJu8IY/pcvarAOErKCxz7EA9999h/u7z4CQnAVvEbIaGmaapHMHtbpgnzT2V+NgJ/mwd2tKz/6mnjQvKiGiFj3lHZD+pDTi45Pr6A476/1fRXultEOqKXdJLdEyi8Lfs8W88bOFyS4=,iv:e9qvAvaMT4kFPVsu2b+nxyyK6noEetXnps9mL78pO9c=,tag:B9T50Btc0UPmnecpRG62Ag==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
