---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/traefik.io/ingressrouteudp_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: victoria-logs-syslog-udp
  namespace: monitoring
spec:
  entryPoints:
    - syslog-udp
  routes:
    - services:
        - name: victoria-logs-server
          port: 514
