apiVersion: v1
kind: Secret
metadata:
  name: hindsight-db-creds
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
# Password MUST match postgres-password in
# kubernetes/apps/ai/hindsight/app/secret.sops.yaml. Rotate both together.
stringData:
  username: ENC[AES256_GCM,data:7cQDwZLyR1fu,iv:2DsFkkZfBqP6OyYoQnDY7jbqgfdJHFPK7chod/LT910=,tag:Y7/jvF39Cb4QUfCO2HVHYA==,type:str]
  password: ENC[AES256_GCM,data:8tz2szuYaTU5U7Z8OYUTkCSW7KmNo1ld8k/8cv/ryluJqfoRRwwB3pECbGq350hP,iv:8+odnAaa2hgKkOuChjB/ndvrxWcVlUo/np7KFYsSA94=,tag:gI2g/fjGHmyD5BqKztf5tA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEJHWHpxVjhGWml0dmdu
        dlZoQlluS0wzbytDNW1zZEZ6L3UyMk1nOWhVCkF0QVpERzhLOERSZS9sUm5tSVhG
        RkFTV1V0ZE94VEswSmpqd1IrcndzWEEKLS0tIE1ISWVEbXo1NEpUeTFhVGx2cTZM
        WSs0eEVjSW1HWERIeXdlMTA3VXdkRGsKhlt8sGKSm4uXhzESyr1aFAJVJJYUouYD
        DQltBT3sdlxIVnpVAlvGq0uX2Hjll66oCj8wD3A93rfe3KrsKY8bZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T17:10:47Z"
  mac: ENC[AES256_GCM,data:s0tKu3X4geWDX/WGXwUaaBN/FMegq2A+A1Btr3tAWiU3gP44u9ZjvZissT4WhrRjZgrphzbCXu6I/FpGGVAJdI02xmdAbo9lIh8Dpln2yB/G7V03ORD65SPrlKn2qOg73O4Vg6tBSteCBtVW1OdzuqLySmxlYai3Lr4k2LwX91o=,iv:Y7F+cSQEfTx2NjsjK1VFgT5hd4eJYapJbUdUvwsl/7o=,tag:KTVW9VNpWFPQIIwNmIv/8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
