apiVersion: v1
kind: Secret
metadata:
  name: holmesgpt-db-creds
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:6gpODNTc+2fYyROb,iv:wMKpzFCs6X1DGtszOfQVeksYGCYYGVlKQfLTU1e1UGQ=,tag:i/75/tNMvrH/1iCUdL0SiQ==,type:str]
  password: ENC[AES256_GCM,data:FlA0g6t+msUTtMi4ckofYFCtJQnbqTxUBFavUY3LVAM=,iv:JtbLkRYZcNrACekSVmtJjYioGgQZaXI7D+yKZgK+hHc=,tag:sh4OWpOhYVc3x08VYvYXTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSHlGT2t1WXVlTG5JWDls
        WG5aUy9USzllSVh6a3NXaXk1NUFVTzZwUlJrCklodnFVWnlTbjhwL3JRL3lheWx4
        QkkyUCtPZHBKeERyZ2VueDFYL3BnK00KLS0tIENvWHJQc0RIU2NORk5ZVmVYanZO
        dmNhZXRnOXJNdHhQUU9UaUNyV2ZMeWsK4htIhZx6/0beO0OJk+pS982jvc5ePmCV
        UAAD9bFDlZ4nBwb3ft23DAFahKaSuo+urltegt8p3RJC28X/bAZ4Jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T17:33:28Z"
  mac: ENC[AES256_GCM,data:iDYKTna7PiNmnQAA6qSVpF++NWtZwtNtiTLYAruG2irD293UX6Fwa6z9cG+h7lsT5Fk5UZp5RO2util4thTRfbXWXVR0s/3lpuJhgc8SHLAlLiwPfl35Brz2ugvAOWb4mtj1TMOVM0hLi2Z/bB9HEJMNbwP7VfWlTCffP7a6i+I=,iv:Rt9X0KCkF9HaJoqIxaQPVUMyatnwptaIp3pET8vlVPs=,tag:Kts+ReyYSChcYQNdRGJRmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
