---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./imagecatalog.yaml
  - ./cluster.yaml
  - ./service-aliases.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  - ./grafanadashboard.yaml
  - ./tcproute.yaml
  - ./dnsendpoint.yaml
