apiVersion: v1
kind: Secret
metadata:
  name: opencode-secrets
type: Opaque
stringData:
  LITELLM_API_KEY: ENC[AES256_GCM,data:3tj+BjaDADoCnoPCkeNyleKUC22IuJ5Q+w==,iv:ZcWBJeAiCxpr5kso7VbyNWxBn1x/e4H1vBFMdYjHVaM=,tag:mhglLXh446Iy4NrUf50zYg==,type:str]
  OMNIROUTE_API_KEY: ENC[AES256_GCM,data:p1R+WsluJfyFwk0rL/OhXSAMqqN+H3THrVunAewxQ5i5uEg=,iv:99nRXKGmLh8Xp9MOPp4DMcutCMF8KzctNTDnhofeD9c=,tag:o1XnI9sd5KktRIGgDOaRtg==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:j1Qa+EAAuq70m4OmXSgA9BYvGKH5V8zCR+bsvTqhGqbtO5wT/HZkmdtgiHKo7M0xHxHzZrDfQ7doW6UNK5WC9NV7FXjbtfiUeK2fIhnDZ0mAT4ipx2LabvASHNe+,iv:PplBGQm4PvdqyjvULIJlHStyCuPo4GR/U5HEZkAxqUM=,tag:b+xpxESVNWTK27twlIeiOQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd05PTEZlbEtjcGZBUjRp
        RUd1eU5aU0pxbGduZVh4TTZHeUY2anNQRWlJCit0ZXZ0YlVZR3I3Z3lYdVY0V3d4
        S1NDSHJCeUxoZHBBUzZtS2t4Zm9xRzQKLS0tIDRjOUZzRldROXNsMmlsSWpiVHhs
        TVFvWEcwWkttTWtEd1h2eUZWMERLVGcKxmZCB538gxfMzPxzWgq7z9qoJbOfG+z0
        9jJrpL1+CyrrILnZI8OF4ilXOIAyvGrpDNxGgESgxhNS8vbJPQgwSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:35:12Z"
  mac: ENC[AES256_GCM,data:UCYHv10kTqrMdCXqYpGqXatGoa+YsK1T/9l58nfow0o/TzZTgDkZRTbGi0CjoecaDhb/WY/wiVdx7LkhlSSsSmtwJOfnFchaTbq67JTpIf7hpUOqjDGu5c0GB7Lm0EZowqMkKXzN0Vs4qTmhXa8cYWg2MYSqOo5v8xBJMsmgjBs=,iv:6DApYY8QV3rv7o8NP0/jZ/8YkDtKYv0kGaIZsLGjxog=,tag:WQ6RUOOtX5PwHXGQE26szA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
