apiVersion: v1
kind: Secret
metadata:
  name: opencode-secrets
type: Opaque
stringData:
  LITELLM_API_KEY: ENC[AES256_GCM,data:MGA4xg7gghG/D1Fj5T5vUbQa6cTgMLkQNw==,iv:WpX7nTcPNwoYPlhAc9MsHSL03W6xUdfGLcnQPzOHO4k=,tag:mZXwnRSByLRIPoDg06T3MA==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:MOW8ZBRvQMM5fpgbWOQIaxtyYMklfbEDA34vTweB6SLcQ5xxHbKHPU/ugEQp0HwhJvGQhqpJlRn84z2Iq8wNlKnT0X3gcvbfVlxDouExOjeXuzSRwblC7GpJOJc9,iv:YEE8VFEpouSWy+gWQBsU5ck+MIibluFvWyJ0UXwC8zM=,tag:PjpP9WyvQmRVw4cARKHhIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWVIxeXpKdWFmZVhWTUx5
        UXFCNG5HSjk0WThPUFdOSE5GOEhUQ3puYlVrCndZWmJwd090YW1YZjliOWl0NzhZ
        ME5PQzZDOHdBY2xmRTQwTkJ2MG5BOEkKLS0tIEtKck5FdnNOMUltdEpiQkVWUXdl
        bE9hSzRZSm8vTWNmWEJHSFo5RVlDVGMKDD8pTvXbWNiwUAYvUkyzT7MI6l1X8IPj
        iWq0F/dtRMDd+fJBJ3dWReRmda1FcyCuR6bSXwAbWST09WXbHDybIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T15:38:00Z"
  mac: ENC[AES256_GCM,data:Uvh0ixqL8ewokoDQEUhZQPoCOskx9zF9NC/2sKdMCthG7RpUkD5q9hOFNqi+OOR3E4+Rj+GGDU0shBzqTJUEg+bmOkEMgmSoXcR4/jNRFHTDqBheOddjSEMvju/YBSyMO9nJfZODT7mENTzKZjDR1uVJPKTs2V/IiM+TJebFwhM=,iv:SyXTheLIqQb2qwmxeAjkuxEOvXqsy1Mf8RT6gemyNKQ=,tag:p9k8Ki4qzcwjDeTNR5SmrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
