apiVersion: v1
kind: Secret
metadata:
  name: opencode-secrets
type: Opaque
stringData:
  LITELLM_API_KEY: ENC[AES256_GCM,data:35FRmsDo7HfgW4JLbEJR3wdEuQqdkZk/7w==,iv:jMocV0aIRB2C8/x8aZSkY4UTBVyQY/QAUplyO+OhcFU=,tag:m/+GhmYXGju+EVzHa2tJbw==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:mtBoz22LZlKMiJnVjEHmGpdNXIxMiyAPr2Y+kf3pkxWuC/5DGPya2gJ/JHsgyjOOcDTdQHY06aGUm2PEppxyZoVe+TL7W4A01/Ytkpjx6LTpKEiQ+cf3p9/AFsZf,iv:kU/qK+eUBtwUA5eeUmYb++k+2L9YXTaKxDLNWNxBeZc=,tag:yIK4dbbzDS929OcR1trAiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ1NKSjRPanRVVnFWSFFE
        M0VaODZWWjNCdHE4ajNtZU1VZU1pMVFEcmpzCkxqRGQ5Zm8wdVhMNngrSlN5bE9u
        a3dRZ2hoVERKUlh0UnpubzV2RExya3cKLS0tIEMzNnFZV25BOGhuVW9vblAxZTVK
        aEdhZlpFOWlKZ0lRd1ZOM3JPblRPQjgKTDwquj9D2n4l7ewyESGpStDLUUI/AO4e
        3LL57Ig2C2M7+cpI7IthZKRA1XaMpYwELTwOQMDklQdd7z7SGORDvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T14:59:45Z"
  mac: ENC[AES256_GCM,data:MJL1C0iTFjBXyMuytyhbnSNKk2bU+GmxlVcksexZWIHqyvuwPWrWcWWwkav4P6sL65N2dQQHI5Goh/t0la/3CRSnNX+pVR1BdO28oK/uehEnHMjJddLv7ibVN1k12CUNkAP1t8/ptopid5/mTcZjkhbp1n4nGSN/slZNBhQt+lU=,iv:5IkLgxYhCDKB2rXD3aFs1K+zmskbZjyGOAZ+hj5U29s=,tag:mIIOZ4uScLgEdLNrXYO1vw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
