apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:87R2KrccnVAISm6ewOMkDIKULcFPQwqbP6w+jT0DiUn0ot/JP+b7h4NMpYviFAILA7Tt86y2h0gerDHbmzPIfg==,iv:zz64dNULPrhkGQdtJlfo0oCwWjP5eCUnUXnzs6tvCq8=,tag:ZfcA2nSTtZ3yjggwcoHd/Q==,type:str]
  MEM0_API_KEY: ENC[AES256_GCM,data:lwCmqMxLdeep5gxN+Ct/yEAvpukR5b9aReWAc+Hdw8+nydlrDztAGXQXFhezfH+GTRymf8h+R7UxvK4kQE/MIg==,iv:t/WOP7On1AUBb+B8wG/1YKk08fY7jqllZpZT502nihw=,tag:TzymvgaCEf9gPVDWhqaM4g==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:/RsiiLmNL2Je8Ic+NG9kxsVaYzOfuAef2w==,iv:dqO3ePsQI2aB3VH0phsVLOzJ7GZhiv0fiohh1prpycA=,tag:WiFG5XqT0V8BRSrrKj7sPg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQVdQK3FRWnJHdXE2bjNG
        eDg4aHY0T3FUcENBb3Z1b1M4MUpNVW9NSlNFCkhSUDVVS21VSVNoRlJPdHJBRm0y
        eFIycUIyYXNvOU1ESXRtTTFXVi9CdFkKLS0tIGdSdXVqREFzN1lqb3RPZ3JrekVH
        OHh4VThBa3pMZ1Z0c2tLS2Iwd0pvYzAKWXYUyeEt8bV0NaP0WrN2bTeMQ/RY61ci
        7QXrOJbZxOMbCikQOqCcOhznr02OkGbr7sz58+w/3uw956w6hb6LCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T19:17:01Z"
  mac: ENC[AES256_GCM,data:Hd/WmBAXoYxRDNt+scJeVYhz7wGLRK+u3BwlDKjt8cjgs+jRwhFtAYHyrapBmu+DbFpZkaXWBVTqZ5MrS5HMA+m0BB9IINW6mJgMtdVbdwCmun6E0/jhBL7BPMfYFhcZHGf6KkX5flIfs+2AZZOvzx/u3r7Ye9vmI2rcS40Bad4=,iv:nNlezLBBDdUbuAkDCFyC/1zcD4kTBuDiz057SL2Nvs8=,tag:LYg11b7ZzxZ+C77EZmKwfQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
