# IMPORTANT: This file contains plaintext secrets.
# Before committing, encrypt with: task sops:encrypt-file file=kubernetes/apps/services/open-webui/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
stringData:
  #ENC[AES256_GCM,data:zrzrP6sf9Bo28u/DLARx2hGp3kQEa9IwYN6ez6g8A4xDAIoV,iv:PEafJlbgAnxEIgxQO5LlJeX6eIDUvecjnrg5sUHbraA=,tag:jjVJo8ycZhAFTBOzrGYxcg==,type:comment]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:eLJfb0Aig8p3QdQOlNP76O+ddaG+/vMz4EVsVRdjoyCXs3JV1GGnrZOjqy5S3sbj8fUnHAS7GDfXV3aObOLxew==,iv:tKsjStJAgdeiuo2SsxldLXo+7wYtpsJ4MKqPuy7Jvdo=,tag:1Oo0ig/jdqkJUZGCTa62Nw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbW04YlJwby9FTTVyb2RC
        aXY1Y0k4ZVh2dnFUT0JhVjNiTktnR3Iyc0FVCndEdEJobUlWWERNNDd3d210UU51
        MktzQlorU2hHVmsvUVptSk5kdlE3NnMKLS0tIFJ4cXBRUkYyNEkxTGkzY2s4aXFP
        Zk5BVUNJcUhQRER5cXMyYkJQM00rRW8KNzvfJGlF6NWm3MDb/crzCr7FRIjcQVbV
        rdglnsI+Ir126CGtvm0uHXmyeLXnBNzi3WArDCn0kYBo1ulGq4Wr0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T21:41:23Z"
  mac: ENC[AES256_GCM,data:pUtwS8LY5SgRQc23Sv95Wuyiv2qvrEhph54PUFG9QsO92G6UzxuCIfkUGxTwWwmAiMpxy0ni8PwCOwPiFFXA3KhlfEOV1rvkldqWJGIlsy/Qz1MKHoUktoM4aJf4erb7mKGw8EeNKK5gCtjs/IJl/JHF3LBv7b9Zow6zlpyGkJs=,iv:6JOr7i1VEzUxyCcaw134Z/Vzq1hZso8pCVSEHNNgut8=,tag:tOkkYLDRHK+qx8EdVFd9EQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
