# IMPORTANT: This file contains plaintext secrets.
# Before committing, encrypt with: task sops:encrypt-file file=kubernetes/apps/services/open-webui/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
stringData:
  #ENC[AES256_GCM,data:R4/AtcxBYmb87aFPXP1EQs7+MzqZZuxyqrbgI2CmmzY2M4PT,iv:l6HiESKXX2PcvTHeyBCBkev21/o/oh5x3FDmEd0whJI=,tag:lCGvVBVYqc6vSPvz7kyfmg==,type:comment]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:20wUf8InOXGLzM5AQJQ2jx9MrylMBqLvMRpOT08SMJGDQd/TGb7jX5Cu1PwG3tM9bx09DzGWwDmb90MUsa4/2Q==,iv:4w6p5g3cIyOobqRB3mp8WnfXs79yhi1ITEX/gz1cG+Y=,tag:DKPwaI7OrhVwcIag+/Qnkw==,type:str]
  MEM0_API_KEY: ENC[AES256_GCM,data:IkLWT47hZM3V4dFOOE4T6qHE3sFOp833iYc543ucejq51k5vSFF5ceTMwAEwt2tQtUkXdntiR4ZUGYNDuc2HaA==,iv:AeKQczr51T7LZE54InaT98O/UAewdHiXhw3/xrxaOrc=,tag:CXQkYeXa6q+UysDyXDdu3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteUUwRGdxUFo2bjdFMzN0
        Q1cvSjNSakNxNzY1YnFlc21mRFlFS0JxVlhrCk9JYjNHTlh3SGxtY1NBOEdsMG90
        RVJEVUF3Y2I2UFdXN0VJN0VVQmFFTlkKLS0tIEVQbkttOEZyQTNjaEkwbmErWXhQ
        MnQ2TGE5T1RWVjlVeU94bjVnZzdORlkK/iIPtc41VU7LgkwViwhsBKSmfE3v4IEq
        HGcfs9z/uvWU81wUoxJBB/NatpvPuUjqZ3NVPIdJ53ziZcBYzOU4yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T18:57:41Z"
  mac: ENC[AES256_GCM,data:fcT0lA3dSwJA3cwT8eY6Eezd4uPj2b+JgGf1+3qX4qLHlMzpnNEpCXIBXS6N9Iuog8kF0yWX6+pWkPwUlgUEy9tlPORZV2nqJFxxpRYUMrVtfk5eIFR0ZRj+MAtGXybARyZpXf3qlcTDIhqKc/3K+gCV0DcddU5ryR/+mGrh8Os=,iv:QGhYW1Zd3Jf5IJtvqUrrRiz5rriDLFVI/lb2fYLrbxs=,tag:DUywOZgfHqBxeUUKT5Z9rQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
