apiVersion: v1
kind: Secret
metadata:
  name: holmesgpt-secrets
stringData:
  GRAFANA_API_KEY: ENC[AES256_GCM,data:AioY77YMyWFO3ik4JOR7O+Zibz5vtYMBuv83xHJvjOASpe44mLEaaav+ADpz+Q==,iv:gnotU+LCsLFVmDdEHS24V1pBG9bjTzyLaAPxRYp1ZEA=,tag:EELNocKIYGnuwfQfF/coHA==,type:str]
  POSTGRES_CONNECTION_URL: ENC[AES256_GCM,data:ggv3rkLehiRpJr8Wa8dX3yo+lHX3nMwhaf/tbraQziMspM7rNyHRkw71C5bXStyBBV4jwJZpQESsfhuo6ee7Ms84IJ/fAUrTxCQO9nf4AEqHBb3L8YNlRCRbpC37XU9eTomBJqmfpsk5HO5XsvLsPigq,iv:L14GiDf1DoohYD/inBy0zGahft5576uFM0WTZOJkdKo=,tag:QoaCL+FrazHDZd1hiShbHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqazJxV2wzTzY4b3Q3aFh5
        aklNNEZ4aVROSU94QVRvQUUwclU2UGlJYTFZCm5wcisrcTJKT21NKzhML1hQWkhE
        R25oS21zUHVjT3BsVTVVZ29EOW43TWcKLS0tIDA0Q3IyNlNVM3Y1eExoZjdZNE9m
        MWFZMk1hb0lUeFBBSmZFMUhlcVd6QzgKOshYGQ59RSCY2TX6YA8+xzfoQPMUzUSM
        7Y49oiV5z0TEoLAzGCmMzjvsVSSkpSgusRVxQITUiGYP2juCChypGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-15T17:33:20Z"
  mac: ENC[AES256_GCM,data:aRzhG5r9q2mJct4bcA158KBnyMa9kBrThXq1P0a7VDzJkmBvRkISDuBuxeiKKrb8/GNKpRBXckwkPPRlwBZLwYAuh392mPshYF0xqkotDIYbSQzTaQNGvyqHlWRc6b4T/ianeC1s/gRdKXe+T2ckcEr+cVYUVxeVKG6hCLrKdwQ=,iv:wfxLSMA8vBaTP6HlqoQk7wZxmeKDQHaShpINWAGRwR0=,tag:ChNxIQlt15CWWCC6dRjUIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
